== Chapter III.

[.chapter-subtitle--blurb]
1784

[.chapter-synopsis]
* Credentials for England
* Embarcation
* Anecdotes of Samuel Emlen, George Dillwyn, etc.
* Letter from Capt. Truxton
* Reaches Liverpool, London
* Christiana Hustler joins her
* Letter to Hannah Cathrall
* Establishment of Women`'s Yearly Meeting
* Extract from a Curious Letter.

Having long felt an engagement to make a religious visit beyond the Atlantic,
a certificate was granted her by Philadelphia Monthly Meeting for the Northern District,
on the 27th of 1st mo., 1784,
addressed "`To our friends and brethren in Great Britain and elsewhere in Europe.`"
In this document, her friends say, "`We find our minds nearly united to her,
in Christian fellowship and sympathy,--she being one whose
life and conversation becomes our Christian profession,
and her ministry sound and edifying.`"
This certificate was signed by 112 Friends, only one of whom, a woman Friend,
aged nearly 90 years, a former pupil of Rebecca Jones, is now living.
An endorsement from the Quarterly Meeting held the 2nd of the Second month,
expressed "`a prevailing sense of near union and sympathy with
our beloved sister in her religious exercise,
under which she has secretly laboured several years,
which lately reviving with increasing weight, she hath now solidly communicated to us.`"
The following certificate was granted by the Select Yearly Meeting,
held by adjournments from the 27th of 3rd month, to the 30th of the same, inclusive.

[.embedded-content-document.testimony]
--

[.blurb.centered]
To our Brethren and Sisters in Great Britain, Ireland, and elsewhere in Europe.

[.salutation]
Dear Friends:

We salute you in a thankful sense of the continued love of Christ,
through the efficacy whereof faithful servants are drawn forth to labour in his Church;
and commend unto you Rebecca Jones, our much esteemed sister, who has,
with the approbation of the Monthly and Quarterly Meetings,
as expressed in their certificate,
now spread before us an exercise that has for some years attended her mind,
religiously to visit you, which has brought a solemn weight over this assembly,
uniting us with her concern,
and giving us an evidence of duty to resign her to the Lord`'s
will and guidance in her procedure on this weighty undertaking.
Greatly desiring that the protecting providence
of the Almighty may preserve her by sea and land,
and that by humbly continuing under his holy anointing,
she may be daily qualified to perform the work whereunto he appoints her,
to the honour of Truth, her own peace, and the comfort of the faithful among you,
to whose tender sympathy and Christian fellowship we affectionately recommend her,
and remain your loving friends.

[.signed-section-signature]
+++[+++Signed by 130 Friends.]

--

These testimonials, given forth by the church,
are well calculated to introduce her to the
confidence of those who cannot recall her memory;
whilst those who knew her, and in whose hearts an indelible memorial lives, may perhaps,
in the perusal of them,
find themselves in the midst of thronging remembrances of the palmy days of our Society.
May such Friends, the venerable relics of the race

"`Who danced our infancy upon their knee,`" be favoured with a Pisgah view of the day,
when He, whose presidency was then so eminently felt,
shall restore judges and counsellors,
and qualify his servants to build again the waste places.

From the diary of Katharine Howell we extract the following passages:

"`4th mo.
20th, 1784.--Went down to see my valued friend, Rebecca Jones, before her departure.
A great number of friends came, and we had a favoured time.
Rebecca Jones and William Savery spoke excellently.`"

"`21st.--Mary Smith took a seat with my husband and self,
and left the city with the intention of accompanying our beloved friends to the ship.
Phebe Pemberton, Mary Pleasants, Rebecca Jones and Hannah Cathrall, Thomas Ross,
John Parrish, wife, and sister Patience Marshall, and Mary Compton,
joined us at the ferry; S. Smith, Mehetabel Jenkins, David Bacon and daughter,
Joseph Jenks and wife, having crossed before us.
Mary Armitt, Elizabeth Foulke, Anne and Susanna Diliwyn, Rumford Dawes, and Nancy Emlen,
soon overtook us on our arrival at Chester, where we dined,
and where we found Margaret Haines and son, and Sally Greenleaf.
Richard Vaux and Elizabeth Roberts, Samuel Elam and Hester Fisher, came in soon after,
and James Bringhurst drove Samuel Emlen and John Cox.
H+++.+++ Drinker and son, and Samuel Emlen, Jr., came on horseback,
and I believe we had been there more than an hour, when George Dillwyn and wife,
Margaret Morris and son, Henry Hull and Patty Moore, driven by Richard Wells, arrived.
Reached Wilmington after 5 o`'clock, and were taken by our kind neighbour, Rumford Dawes,
to his brother Harvey`'s, where a good cup of tea proved grateful to many.
At 0 o`'clock there was an evening meeting appointed.

"`First day, 7th mo.
25th.--We crossed the ferry about 8, A. M., after a very pleasant ride to New Castle,
had a sitting with our dear friends in a public house,
after which there was liberty given, and a meeting held in the Courthouse.
After dinner we took an affectionate leave of each other,
and our friends went on board of the ship Commerce, Captain Truxton, about 4 o`'clock.`"

Relative to her embarkation, we find the following note in Rebecca Jones`'s sea journal:

"`Embarked at Newcastle on board the ship Commerce, Capt.
Thomas Truxton, commander, the 25th of the 4th mo., 1784,
in company with my valued friends, Thomas Ross,^
footnote:[The following incident respecting Thomas Ross, was mentioned in my hearing,
long after his death, by a friend who was personally acquainted with him.
While his mind was under exercise with the prospect of a visit to Europe,
but before he had given up to the service, he was one day thrown from his horse,
and his foot being fixed in the stirrup, he was dragged some distance,
probably a very short one, in that perilous situation.
His mind recurring to this engagement, as one from which he was improperly shrinking,
he breathed forth a petition:
"`Lord spare my life and I`'ll go;`" when some of the fixtures giving way,
he was instantly released.--Editor of Friends`' Review.]
Samuel Emlen and son Samuel, George and Sarah Dillwyn, and Mehetabel Jenkins,
all intending for Great Britain.`"
She also preserved the names of the cabin and steerage passengers,
ship`'s hands and common men, her interest extending to all ranks and conditions of men,
desiring the welfare of all, and being more than willing to be made helpful to any.

Succeeding this catalogue of names, we find the following passage:

"`Having for many years had a prospect of duty to pay a
religious visit to Friends in Great Britain,
under which my heart was often bowed within me,
secretly desiring that if it was indeed the Lord`'s requiring,
my will might be brought into a perfect state of resignation to his holy will;
at length my mind was fully given up,
trusting in a gracious promise which I was favoured with from
the source of all true blessedness and comfort,
with this charge, '`Look not out, and all things necessary shall be furnished.`'
In the regular precious order of truth, I laid the same before my dear friends,
who in sympathy and unity therewith, signified their concurrence in the Monthly,
Quarterly, and General Spring Meetings.
And though I was favoured as it passed from stage to stage,
so that my mind was preserved entirely clear of doubting, yet it was my constant desire,
(the which I each time told my friends feelingly,)
'`that the Divine will only might be done.`'
The before-named friends, under the like exercise, being all set at liberty,
and the aforesaid ship offering, we felt easy to take our passage therein,
in a humble depending frame of mind, believing that if it was the Lord`'s will,
we might reach the next Yearly Meeting at London.`"

An incident connected with their embarkation is worthy of recital,
as illustrative of the benefit which the true disciple may receive
from an entire dependence upon the all-sufficient Teacher.
Two ships were in readiness to sail for London.
One was a large merchant vessel; the other, a smaller one,
had been built for a privateer, and was especially adapted for fast sailing.
Rebecca and her associates in the proposed voyage, visited the two ships,
to decide between them; and went first on board the larger one,
which had been preferred by many of their friends.
They seated themselves in the cabin,
and Samuel Emlen first broke the silence by saying "`Death and darkness!`"
A similar feeling of uneasiness in reference to
this vessel pervaded the minds of the others.
On taking their seats in the smaller ship, a clear evidence was vouchsafed them,
that it would be right for them to take their
passages in her--which they did accordingly,
and in due time the reader will have occasion to remember that
there is a "`Wisdom profitable to direct,`" which was
remarkably confirmed in the experience of our friends.

The next day after they found themselves out at sea,
their rough Captain (subsequently Commodore Truxton,)
opened a locker and threw in a pack of cards,
saying "`lie there--you`'ll see daylight no more--in compliment to these Friends.`"
And at the table he took up his glass of beer, saying,
"`Here`'s hoping that we friends may reach London timely for the Yearly Meeting!`"--which,
it will be remembered, had been their desire,
though from the shortness of the time it was not confidently expected for them.

After clearing the capes of Delaware and discharging the Pilot,
Truxton joined our friends in the cabin,
and having obtained their assent to some pertinent remarks upon the
mutual benefit which persons confined within such narrow limits would
derive from making themselves agreeable to each other,
he observed that there was one thing they could do which would very much displease him.
They of course desired to be apprised of his meaning.
"`It is,`" said he,
"`for you to know that there is anything in my
power which will contribute to your comfort,
and not to ask for it.`"

The kind disposition thus indicated, was continued by him through the voyage,
and his high estimate of the qualities of Rebecca Jones was frequently evinced.
As an illustration of this we may be allowed to quote a rather extravagant speech
which he made at a London Coffee House soon after their arrival in speaking of her
to his brother captains and merchants--"`that he had brought over an American
Quaker lady who possessed more sense than both Houses of Parliament.`"

One day Rebecca Jones going upon deck,
saw George Dillwyn seated in pensive mood upon the chicken coop (which on
shipboard is ordinarily fitted for a seat.) He said to her,
"`Rebecca, canst thou keep a secret?`"
To which she replied,
that she was not in the habit of prying into other people`'s secrets,
but that she could keep them when entrusted to her.
"`Well, then,`" said he, "`I think we shall see land next First day.`"
They were soon joined by all their companions except Thomas Ross,
who was confined in his cabin (as will hereafter appear) by a hurt.
Rebecca Jones remembering the lonely situation of the latter, went to sit with him.
He accosted her in the same words, querying if she could keep a secret;
to which she repeated her former reply.
He then expressed the same prospect, that they should see land next First day.
On First day morning (5th mo.
22d, 1784,) George rose very early, and,
standing on the quarter deck with his arms folded behind him,
he called out with a firm voice, "`land ahead!`"
The Captain being still in his berth, hastened up in alarm,
and asked who had called "`land ahead.`"
George, calmly retaining his position, in a few minutes repeated his call.
The captain immediately ordered to the mast-head a man who was noted for distant sight,
to keep a look out.
When after the lapse of ten or fifteen minutes, no sign of land could be discovered,
the Captain sharply rebuked George Dillwyn for the false alarm, which might, he said,
have led to serious consequences.
George stood unmoved, and called, in a firm tone, and louder than before, "`land ahead!`"
The puzzled Captain ordered the lead to be thrown, but, before this could be done,
the sentinel called out, "`ahoy, land ahead!`"
The lead was then thrown, and, in reference to it,
the compiler turning for confirmation to Captain Truxton`'s sea journal,
finds the following note:

[.offset]
"`Sunday, 23d May.
At six o`'clock sounded,
got 42 fathoms water--shells and rotten brown stones--at seven
made the land--lake it for the start--bearing E. N. E.;
nine leagues distant.
Latitude observed 49° 45`' North.`"

Rebecca preserved some of the shells and sand taken at this place,
a portion of which is still kept.

We will anticipate the course of the narrative to say,
that they landed at Gravesend on Sixth day, the 28th of Fifth month,
after a passage of thirty days, reaching London about four o`'clock P.M.;
this being the day prior to the select Yearly Meeting.
Two weeks afterwards, the ship to which their attention had first been turned,
was towed in, on her beam ends, the keel being out of the water,
the ballast and whole cargo having shifted in a
storm so that they were unable to right her.
They had taken a different course from the one pursued by the "`Commerce,`"
and experienced danger and distress,
so that all hope of reaching their port at one time vanished.
A female passenger afterwards gave Rebecca Jones a moving account of their passage,
and mentioned that when,
(every light in the cabin being out,) the water made
its way in the cabin and into the state room,
she lay in her berth expecting death as inevitable,
and reached down her hand to feel the water as it rose;
and that while her soul`'s concerns were uppermost,
and her heart was engaged in fervent prayer,
the only temporal desire she allowed herself to cherish, was,
that she might not struggle long in the water.

We now insert some extracts from her own notes of the voyage.

"`We left Philadelphia, Fourth month 24th; upwards of sixty Friends with us.
Dined at Chester, then proceed to Wilmington; had a meeting, which was large,
and favoured with confirming evidence that the Lord is good to those that fear him,
to the souls of those who in sincerity seek and serve him.

25th. First day.--Proceeded to Newcastle where the ship lay;
had a meeting in the Courthouse with the inhabitants, to satisfaction;
after which we dined, and after an affectionate leave of our dear friends,
went in a yawl to the ship, which was ready for our reception.
Our dear friends S. Hopkins, Samuel Smith, John Parrish, wife and son,
S+++.+++ Pleasants and wife, Phebe Pemberton, Ann Dillwyn,^
footnote:[Afterwards wife of John Cox.]
and Ann Emlen, Jr., accompanied us on board, about four o`'clock,
where we felt easy and resigned,
trusting in that gracious Providence who is able
to protect and preserve us by sea and by land.
After adjusting our little conveniences, etc, we retired to rest,
which was much interrupted.
However, I got some sleep,
and felt refreshed and comforted in the hope that the Lord was with us.

26th. Second day.--About seven A. M., the wind having sprung up, and fair,
we reached the capes, which is near 100 miles, by one o`'clock, P. M.,
when the ship hove to for the Pilot, who left us about two o`'clock.

28th. Fourth day.--Extremely sick.
G+++.+++ M. and self taking little nourishment, yet quiet in spirit, looking to the Lord.

29th. Fifth day--Had a poor night; high wind kept us rolling about.
Three of our hogs washed overboard,
and several poultry drowned--but the dead lights having been put up in the afternoon,
the cabin was mostly dry.
As I lay rolling about, the sea being very rough, my mind was turned toward the Lord,
and this petition revived with life and sweetness: "`Let not the water-flood overflow me,
neither let the deep swallow me up.`"
And my trust and confidence were renewed in the all-sufficient Helper of his people.
This day we passed through the gulf stream of Florida,
and left Cape Henry to the windward.

30th. Sixth day.--George Dillwyn, M. J., and myself continue very sick,
but the weather clearing up, and a pretty good breeze from W. and shifting to N. W.,
we ran along finely.
I came upon deck about one P. M., and was revived with the air,
and took a little nourishment--so I sat on the floor of the deck to
make this memorandum--retired to rest under a humbling sense of the
Lord`'s continued care and regard towards his poor servants,
who have left all to follow his leadings.

5th. mo.
1st. Seventh day.--Very sick--yet quiet in mind--trusting in the Lord.

2nd. First day.--Our Captain having been informed last evening that we
thought it right for our little band to retire and wait upon the Lord,
under the persuasion of his providential care,
and in acknowledgment of our dependence upon him for a blessing, he readily consented,
and appeared willing the steerage passengers might have the privilege of sitting with us,
if they chose it.
But the wind springing up freshly, and increasing with rain, we sat down alone.
Melting goodness was near our spirits.
Thomas Ross, and Samuel Emlen, had some encouraging hints,
and we were comforted as well as bowed together in spirit.
The Lord`'s great name be praised!

3rd, 4th, and 5th.--The wind being fair, we sailed from eight to ten knots.
We came in sight of the banks of Newfoundland.

6th. Fifth day.--A calm, and a pleasing calm of soul.
May gratitude be the covering of my spirit,
under a renewed sense of the deep obligations I am under to the great Shepherd of Israel,
who has not only favoured my poor soul with the knowledge of his will respecting me, but,
oh! blessed be his power,
has furnished with strength sufficient hitherto to comply with his heavenly requirings.
And I feel at this instant renewed desires,
that I may be kept humbly dependent on Him alone, who is strength in weakness,
and riches in poverty.
Hitherto all the company in the cabin have conducted in great harmony,
each being willing to assist the other in little kindnesses, and our mutual friend,
nurse, and helper, Sarah Dillwyn, has been particularly attentive to our various wants.
I esteem myself under great obligations to her; may her labour be acceptable,
and rewarded by the great Master,
who has promised that they who give a '`cup of cold water in the name of a disciple,
shall receive a disciple`'s reward.`'
And in the course of this voyage; Wm. Ludlam (one of the passengers--an obliging,
sensible, well-behaved man) having a stone bruise on his heel, and Samuel Emlen,
and Thomas Ross, having, by the motion of the ship, slipped and hurt themselves,
Sarah Dillwyn has had to dress and tend the wounds of them all.

I was favoured with a quiet good night, more so than any previous,
and was in my sleep in company with my dear friends at Philadelphia,
in the enjoyment of sweet unity and fellowship, especially my dear Hannah Cathrall,
for whose welfare is my soul anxiously solicitous, that she, with myself,
may be kept near the Lord,
waiting steadily on him for help and direction in the mot needful time,
and that we may be supported, encouraged, and helped, under the present trial,
and stand so unreservedly dedicated to the Lord`'s will and requirings,
that the hands of our arms may be made strong for labour in the heavenly vineyard,
in the day time.

8th. Seventh day.--Had a good night.
Awoke about midnight,
in the enjoyment of divine love and sweetness on my heart in a superior
degree--lying peacefully with my mind turned towards Him who has,
I do believe, required this sacrifice at my hands,
and whom I do acknowledge worthy to be served, honoured and obeyed, now and forever.
In the morning sea-sickness came on again, that George Dillwyn,
M+++.+++ J. and myself were renewedly tried.

A small bird called a curlew plover, supposed to come from the banks of Newfoundland,
lit on one of the ship`'s yards, was taken by one of the hands,
and brought into the cabin.
It is about the size of a pigeon, with a small bill like a snipe.
It being a stranger, and, to us Americans, a curiosity,
our captain has ordered a box for its accommodation,
Sarah Dillwyn wishing to carry it to England.
My mind was this evening poor, but quiet.
Retired early to bed.

9th. First day morning.--Awoke refreshed, both in body and spirit.
Sick for a short space, but, getting better, was favoured to sit in the cabin,
where a meeting was held, the Captain, cabin passengers, most of the steerage passengers,
and as many of the seamen as could be spared from working the ship, attended,
and behaved well.
It was a solid, good opportunity, and, I trust,
was owned by the Great Commander of the sea.
Sarah Grubb D., Samuel Emlen and M. J.,
each appeared lively in the exercise of their gifts.
A light head wind.

10th. Second day.--Awoke with these expressions, "`Confide in his mercy,
and adore his '`power`" Was sick at first rising, but grew better.
Spent great part of this day upon deck, in sweet fellowship with our little band.
Little wind, and that ahead.

11th. Third day.--Less sick today.
A fine wind.
In the evening, my mind was drawn into secret retirement,
in which my soul was bowed in humble prostration and worship to the God of my life,
who hath done great things for me, a poor, unworthy creature.
Rain in the night, with thunder and lightning.

12th. Fourth day.--Could have slept this morning, but felt much sympathy with M. J.,
knowing by experience how dispirited they feel who are very sea sick.
I called the steward, and gave orders for some gruel, which was salutary,
and she seemed better after it.
Our worthy friend, Thomas Ross, this day, by a lee lurch of the ship, fell in the cabin,
and wounded one of his legs badly, which was timely attended to.
It was a favour that he was not more hurt.
I retired to rest under a thankful sense of Divine mercy,
and fresh breathings of soul after the renewal of love and favour.

13th. Fifth day.--Awoke sweetly refreshed; arose humbled in a view of my own weakness.
Felt drooping this day, but quiet in mind.

14th. Sixth day.--Better this morning.
Admired the kindness of Divine Providence towards us in
this our floating inclosure on the great deep.
Blessed be His great name whose care is over his poor servants,
fulfilling his gracious promise, who hath said, "`I will not fail thee,
nor forsake thee.`"
We had a sweet, refreshing season this morning in our cabin,
select from the other passengers, which is an additional favour.
It appears, from the Captain`'s account, that, by 12 o`'clock this day, we have,
in 24 hours, sailed 228 miles.
He, with William L. and R. Ely, etc., are preparing fishing tackle to catch mackerel.

May our rejoicing be in fear,
depending only on the divine protecting arm of the Almighty,
without whose permission not a hair of our heads will be allowed to perish.

15th. Seventh day.--A fine fair wind, and such pleasant weather,
that our Captain tells us that we might go to sea for 20 years,
and not have such another day, for our ship is steady enough to sew and write pleasantly,
though going so rapidly, that in the last 24 hours we have sailed 240 miles.

16th. First day.--The wind unfavourable.
I was not so well today.
We sat down quietly in the morning,
but had not so general an opportunity as on last First day.
Spent the latter part of this day alone in our state room,
my heart being turned towards the Lord,
and my confidence renewed in his sufficiency and strength,
for the fully supplying of our various needs.

17th. Second day.--Rose refreshed in body, yet low in mind, though not discouraged:
much desiring to be rightly directed in my future movements,
particularly in the place suitable for me to take up my abode
whilst in the great city towards which we are approaching;
and that I may be kept humble,
little and low in that simplicity which my heart has
been long convinced is designed for my safety,
and has ever been the prelude of true peace.
Oh that wisdom and knowledge may be the stability of our times!
Then may we hope the Divine strength will be our salvation and rejoicing.

To this note is appended, in the hand writing of George Dillwyn, these words: "`Amen,
saith George Dillwyn.`"

The following instance of the signal care of Divine Providence is worthy of record.
Samuel Emlen, Jr.,
had just moved from his seat directly under the sky-light in the cabin,
when one of the sheep on deck fell through the glass into the cabin.
Without doubt, if Samuel had been in the spot where he had been sitting, without his hat,
the particles of glass, with the weight of the falling animal on his bare head,
must have greatly wounded him, if not taken his life.
May a grateful sense of the distinguished Mercy,
be so impressive on his young and tender mind, as to excite this query in sincerity,
"`What shall I render to thee, oh Lord, for all thy benefits?`"

18th. First day.--Not so well this day.
Still under an exercise on my own account, that the Lord, my alone Helper,
may condescend to favour me with the distinct knowledge of his will,
that I may not determine in the uncertainty, nor mistake his counsel.
Spoke a brig from Amsterdam, bound to New York.

19th. Fourth day.--The wind favourable.
Several of us employed in writing,
hoping for an opportunity to convey some intelligence
to our dear friends whom we have left behind,
towards whom my mind has been often turned in near affection and for whose
preservation and stability in righteousness have my prayers ascended as for my own.
It looks probable we may reach the Yearly Meeting of London,
where I expect fresh exercise, and oh! may I be kept humble and low with the pure seed;
though in a state of deep suffering.
Last evening I had some serious conversation with our Captain,
during which he was attentive and solid;
at the conclusion of which he acknowledged my kind intentions,
and said he believed I was concerned for his and
others`' good--and behaved affectionately.

21st. Sixth day.--Awoke with these expressions:
"`He will be a strength to the poor--a strength to the needy in his distress,
a covert from the storm,
when the blast of the terrible ones is as a storm against the wall.`"
Spent much of this day in inward retirement, humbly trusting in the Lord, my sure,
unfailing friend, to whom I desire to look in simplicity, as a little child,
for further direction and help,
knowing '`it is not in man who walketh to direct his own steps.`'

23rd. First day.--Held our Meeting this day in the cabin.
It was a favoured, comfortable season.`"

On this day ('`the 23rd) the Captain, who had conceived a high respect for our friend,
which he afterward repeatedly evinced, presented her with a copy of his sea journal,
in his own writing, with the following letter written upon the first page.

[.embedded-content-document.letter]
--

[.letter-heading]
To Rebecca Jones

[.signed-section-context-open]
"`On board the Commerce, in the English Channel, May 23rd, 1784.

[.salutation]
"`Madam,

Our passage, in all probability, being now nearly at an end,
give me leave to present you a copy of my journal,
which contains all the observations that were essentially necessary
for our guide and direction across the Atlantic Ocean;
which, with the help of Divine Providence, we have passed over,
without the smallest accident whatever; and have, thanks be to Heaven,
arrived on our desired coast, where I hope, in a few days, to see you safely landed,
and to congratulate thereon.
For it is with heartfelt pleasure and satisfaction to myself, that I can with truth say,
that I never had so instructive and pleasing a female companion at sea as yourself.
And in short, I cannot say less for all the rest of the Friends.

"`This small token of my esteem I present you,
that yon may at any future time refresh your memory with the different
occurrences that have turned up from time to time during the passage,
respecting the ship, winds and weather.

"`That you may enjoy your health,
and be the instrument of enlightening the minds of many in this
eastern world (as I am satisfied that is your errand,) and return
safely back to your connections and friends in America,
rewarded by heaven for your labours, is the sincere wish of your friend,

[.signed-section-signature]
Thomas Truxton.`"

--

The Journal thus commences:

"`A Journal, by God`'s permission, on board the ship Commerce, from Philadelphia to London.
Commencing April the 26th, 1784, and kept by Thomas Truxton, Commander of said ship.`"

24th. Second day.--As we were advancing up the British Channel,
and although delighted with the fine prospect of the land, of White Rocks, Isle of Wight,
etc., (George Dillwyn and self being on deck and counting the shipping around us,
30 in all, which was a feast to the eye,) yet my mind was low, stripped and fearful,
lest I should not keep near enough to that Power
which alone has preserved and can preserve,
under and through all the dispensations of his Providence, to his own praise.
May I be favoured not only to get deep enough,
but to keep deep and humble with the pure seed,
in mine own bosom and the bosoms of the faithful amongst whom my lot may be cast.

28th. Sixth day.--Being favoured to reach Gravesend early this morning,
we prepared to go on shore, which we did.
Our Captain left the ship first, in order to prepare a dinner and carriages for us,
and had all ready when we arrived.
Having dined, we started, our Captain with Thomas Ross and Samuel Emlen, jr.,
in one post chaise, Samuel Emlen, sen., and M. J., in another,
and George Dillwyn and wife and myself, in a third, and reached London about 4 o`'clock.
During the ride up, though there was much to entertain the eye and delight the senses,
yet my heart was humbled and bowed in contrition,
under a sense of the Lord`'s goodness and mercy,
in having conducted a poor handmaiden over the mighty ocean in safety, and above all,
in the sustaining sense of his power and presence, which had attended me,
to bear up in the time of conflict and exercise.
For all which my heart is prostrate before Him,
and returns the feeble attribute of thanksgiving and praise for all his mercies:
acknowledging that He is worthy now and forever more.
Amen.`"

Before her departure from Philadelphia, Arthur Howell, in bidding her adieu,
placed in her hand a sealed note to be read at sea; which contained a short, but full,
expression of his sympathy and unity with her in her prospect,
and concluded with quoting from Isaiah 49:
23--"`Kings shall be thy nursing fathers and queens thy nursing mothers.`"
She afterwards mentioned that on first meeting with Christiana Hustler,
(who was her first companion in England,
and travelled much with her,) at Joseph Gurney Bevan`'s,
the passage occurred to her--"`Kings shall be thy
nursing fathers and queens thy nursing mothers.`"
Although their home was together, at the house of Joseph Gurney Bevan,
nothing passed between them during the time of Yearly Meeting,
relative to their being associated;
but when John and Christiana Hustler were preparing to return to their home in Yorkshire,
Christiana told her husband that she believed he would have to return alone--that
she was not acquainted with Rebecca Jones`' views relative to a companion,
but she felt very much bound to her, and felt that she must make an offer of: herself.
Being encouraged to attend to her feelings, she went to R. J.`'s room,
where they had a conference,
which resulted in a mutual conviction that they were designed
to be banded together as companions in religious exercise.
In a letter written immediately after her arrival in London, she says,
"`Christiana Hustler is in her person very much like my Hannah Cathrall;
about 50 years of age, has a lively gift in the ministry--an agreeable nice,
very nice person, and indeed in general, the English women make a very neat appearance,
and carry their age remarkably well.`"

On 5th day, 6 mo.
3rd, she writes to Hannah Cathrall,

"`As I know thou art fond of particular accounts, I have risen early before the family.
My mind is turned towards thee, expecting to be so engaged when I leave this City,
that I may not write so much: though I intend to omit no opportunity.
I spent the evening before last with Catherine Phillips,
and she with her husband supped with us the last evening.
I have already informed thee, she looks much as when with us.
Her husband appears an elderly person, is a sensible man, and agreeable.

Joseph Gurney Bevan, my kind landlord, is a solid friend, and his wife a lively,
agreeable, very nice woman.
She does a little in our way.
He is an apothecary.
They have no children.
They are very kind and attentive to us, and I believe it right we are here.
John Eliot, with whom Thomas Ross, R. N., S. Emlen, S. N., and many others lodge,
is a solid substantial Friend, and his wife a fine person.
She made me think of her mother, M. Weston.
They lived in a spacious complete house.
William Dillwyn lives elegantly.
His wife very much like Ruth Richardson.

Lydia Hawkesworth, whom I shall call Catherine Phillips`' Aid de.
Camp, is a fine, agreeable person.
And Esther Tuke is a sort of Princess.
Samuel Neale looks much as he used to, only a little older.
In a large company he said to me, "`Thou and I are sisters.`"--I replied,
"`Why not brethren?`"
upon which he discovered his blunder, and many smiles ensued.

There is (however low things are in this nation, respecting the discipline) a living,
deep, clear ministry; and remarkably so on the women`'s side.
Dear Catherine Phillips labours indefatigably;
seldom does she sit a meeting through in silence;
and in many of them has exceeded any time I remember her in America.
She is greatly improved in humility, tenderness and sympathy.
She has shown much love to us poor little Americans,
and has told me she does not expect to be continued much longer in mutability.
Hannah Wigham is a solid, agreeable friend.
Also, Martha Routh, Mary Proud, and Mary Prior,--these are all from Yorkshire,
and lively ministers.
Thou wouldst love them all as I do.
Alice Rigg, an enterprising skillful work-woman, is from the same place.
She plead nobly before the men`'s meeting.
Mary Leaver looks much as she did; enquired kindly after Friends in America.
She and E. Gibson desired love to thee.

It appears that prior to this time,
the queries were not answered by the Women`'s Yearly Meeting of London.
Thirty-one years previous,
a proposition was made for the establishment of a regular Women`'s Yearly Meeting.
Tho`' united with by many friends, it was then postponed,
as was also the case when revived some years afterward; one friend remarking,
I see it but not now--I behold it but not nigh.`"
A communication from Rebecca Jones, enforcing the propriety of it,
had such place as to induce the action which is recorded in
the following minute of Women`'s Yearly Meeting,
bearing date the 5th of Sixth month, 1784.

"`It coming weightily under the consideration of this Meeting,
the great loss it sustains for want of its being
regularly constituted a Meeting for Discipline,
the following Friends are desired to lay the concern before our men Friends now sitting,
and bring in a report to our next adjournment,--viz: Esther Tuke, Elizabeth Gibson,
Alice Rigg, Christiana Hustler, Mercy Ransom, Martha Routh, Tabitha Middleton,
Susannah Row, and Sarah Corbyn,
in which service the company of the women
Friends from America would be truly acceptable.`"
footnote:[The ministering Friends from America in attendance at this meeting,
were Robert Valentine, William Matthews, Nicholas Waln, Samuel Emlen, Thomas Ross,
George Dillwyn, Rebecca Wright, Patience Brayton, Mehetabel Jenkins, and Rebecca Jones.
There were several other messengers from America at that time in Great Britain,
who were not at the Yearly Meeting.]

This dignified deputation, leaving their own meeting still in session,
proceeded to that of the men, some of whom were unprepared for the proposition.
A part of the discussion which ensued,
is too familiar to our readers to need insertion here.
One Friend expressed the sentiment that it would
be preposterous to have a body with two heads,
to which Rebecca Jones responded that there was
but one Head to the body which is the church,
and that in Christ Jesus male and female are one.
A note in Hannah Cathrall`'s hand, says:
"`My Rebecca Jones informs me that Alice Rigg plead nobly in the men`'s meeting,
and Martha Routh silenced David Barclay.
I perceive by a letter to J. P., he surrendered very unwillingly.`"

This deliberation resulted in the issuing of an epistle
setting forth the rise and use of the Discipline,
and encouraging women Friends to attend to their share of it.
In alluding to this measure, Catharine Phillips remarks: "`As mothers of children,
and mistresses of families, they have an extensive service to attend to,
and ought to be concerned, so to discipline their families,
as to be able to answer the several queries relative to their situation.`"

Samuel Neale, in reference to the proposition as opened by these women friends,
says:--"`The evidence of Truth strongly impressed the minds of
those present with a sense of their concern being right,
and Friends concurred so heartily with them,`' that a minute
was made to that purpose at the next sitting of the meeting;
and a copy of the said minute was handed to the women
friends by a deputation from the men`'s meeting.
Robert Valentine, William Tuke and I were the deputies.
We had a good time among them, and left them in sweet peace.`"

The following is the minute of the men`'s meeting in the case,
bearing the same date with the women`'s minute.

"`This meeting,
after a solid and deliberate consideration of the proposition
brought in from the Meeting of Women Friends,
held annually in this city,
agrees that the said Meeting be at liberty to correspond in
writing with the Quarterly Meetings of Women Friends;
to receive accounts from them, and issue such advice, as in the wisdom of Truth,
from time to time, may appear necessary, and conducive to their mutual edification.
For this purpose it will be expedient that the said meeting be a meeting of record,
and be denominated the Yearly Meeting of Women Friends, held in London;
yet such meeting is not to be so far considered a meeting of Discipline,
as to make rules, nor yet alter the present queries,
without the concurrence of this meeting.`"

Our readers will be amused with an extract from
a letter written the 10th of the same month,
by one of those who dissented from the above conclusion,
but who evinced commendable candour, in admitting that he had been actuated by prejudice,
and that he had received a salutary lesson of condescension.

After bearing his testimony to the value of the "`instrumental help,`" and
expressing his sentiment that the Yearly Meeting had been "`much favoured
every way,`" he adds--"`The most remarkable occurrence this time was,
that the women have obtained a point which they have long thirsted after--that is,
a Yearly Meeting, regularly established by representatives from the Quarterly meetings.
So thou may, at some future meeting, be a member of this female Parliament, who,
if they take it into their heads, may recollect that they may,
like Solomon`'s crown be placed above the head (as told the audience at a wedding.)

I was no favourer of this measure,
well knowing that Power is a dangerous tool in some hands, who,
if one gives them an inch, may take an ell.
And so strong was my prejudice against it, that,
though most of the solid part of the men (and all the women to
be sure) seemed to favour it under a right influence,
yet I felt it not.
Thus I have however obtained a teachable lesson of the strength and danger of prejudice,
as well as to learn condescension to such as are entitled to it:--for
to set my own judgment and feeling in opposition to my superior,
would be a presumption that I should not pardon myself for.
