== Chapter V.

[.chapter-subtitle--blurb]
1785--1788.

[.chapter-synopsis]
* Gives up for Ireland
* Various letters
* Lands at Dublin where she visits families
* Message from Captain Truxton
* Family visits, at Ballitore and Calleds.
* Remarkable anecdote of George Dillwyn
* Sarah Grubb arrives
* Visits families at Lisburn
* Completes her labours in Ireland and returns to England
* Sickness, death and funeral of Thomas Ross
* Labors in Wales
* Family visit at York and at Leeds
* Certificate of Ireland Half Year`'s Meeting
* Attends London Yearly Meeting
* W. Mathews`' testimony of the growth in her gift
* Illness of Christiana Hustler and of Sarah Grubb
* Visits families at Sheffield, Warnsworth, and High Wycombe
* Hannah Cathrall`'s integrity in returning 50 pounds
* Certificate of London Yearly Meeting
* Concern on account of Africans
* Attends London Yearly Meeting
* Preparations to embark
* Parting scenes
* Tabular notes.

Her proposed mission to Ireland, closing from her view,
Rebecca Jones made preparation for going into Sussex,
and she esteemed it a favour that her friend, Deborah Townsend,
obtained on the 31st the consent of Peel Monthly Meeting, to accompany her.
Sixth month 2nd, she makes this brief note--"`At Plough Court, in great distress,
gave up for Ireland.`"
And on the morning of the 3rd, she writes, that after a night of deep distress,
this prospect so clearly opened, and everything else so closed up,
that her full resignation became absolutely necessary.
"`I have, therefore,`" she says, "`yielded to it, as the path for me to pursue,
in order to obtain that peace which no substitute, no contrivance of the creature,
no human exertion can procure, because it is reserved for obedience only.
The great lesson of self abasement and mortification has been singularly renewed to me,
from which, through the Divine blessing,
I hope to derive lasting instruction and benefit.`"
On the same day she writes to Christiana Hustler--"`Pray for me,
that I may not be left to run at uncertainty,
for I am likely to be led in paths that I have not known.
I should be glad thou wouldst encourage dear Sarah Grubb to move forward.
Her Robert, I expect, will accompany her over the water.
Let her know that my heart is nearly united to her.
I now feel, in this sudden movement, the force of the expression--"`Ye are not your own.`"
But if I may in any sort be acknowledged by Him, it matters not,
whether or not I am owned by Abraham`'s descendants,
or acknowledged by the nominal lifeless professors of Israel;
those who are not doing the works of Abraham nor of the wrestling seed.
Feeling thee in the precious heavenly fellowship to be of the seed,
I freely open my heart to thee; thou knowest I love thee,
and wish thee all "`joy and peace in believing,`" that thou art one of the
tried chosen number who will not be forsaken by Him unto the end,
and in whom he will yet show forth his praise.
Lift up thy head in hope,
and trust in Him who is able to help thee over and through all--yea, He will do it.`"

On the 4th of Sixth month, with her "`face turned toward the land she had feared,
and without any certainty of a companion,`" she took her departure for Liverpool, where,
on the 13th they embarked on board the Earl of Charlemont packet for Dublin,
and landed at Rogerson`'s quay.
Here, on the 20th, they commenced a family visit,
which was completed on the 14th of Seventh month, comprising "`in all 115 sittings,
in which, though deeply exercising, at times Truth prevailed, and we enjoyed peace,
and only +++_______+++ and +++_______+++ refused a visit from us.

"`I have been,`" she says, "`without a woman friend, except Sarah Dillwyn,
who just went to keep me in countenance; yet the Lord hath been my helper,
and I have abundant cause to bless his name,
and to rejoice (however strange it may appear to some) that I came when I did.
I have been a feeling witness of his great mercy,
and love manifested towards this people; they received us joyfully;
and though we have been exercised in much plain dealing,
yet the influence of best love has been felt; and though all are not alike sensible,
yet many feeling minds, have, I trust, been encouraged and quickened in right prospects.
I never knew Samuel Emlen more favoured.`"

A letter from Capt.
Truxton to Samuel Emlen, received at this time, says--

[.embedded-content-document.letter]
--

"`Present my best compliments to Rebecca Jones, and to that worthy old favourite of mine,
Thomas Ross.
May God of his infinite mercy and goodness, continue his blessing towards you all;
and after you are satisfied in your own minds that you have done your
duty towards Him and towards your brethren in this eastern world,
that He may be pleased to conduct you to your families, relations and friends in safety,
is my sincere wish and prayer.`"

--

The following lines addressed to her by Sarah Grubb, and dated Seventh month 1st,
have reference to the engagement just noticed:
"`My mind sympathizes with thee and thy companions in your exercising engagement.
It is a work in which, comparatively speaking, the weather changes many times in the day.
Sometimes the clouds hang so low as even to
baptize the inhabitants of that climate in them,
from whence there is so blessed a connection with the great ocean of wisdom and strength,
as to extend the baptism thereto.
Here we find our spiritual Moses, through whose Almighty power the clouds break,
the earth is refreshed with celestial rain, and the Sun of righteousness breaks forth.
Then they who delight in his precious influence revive
in vigour and press forward with new alacrity of soul.
Thus may your spirits be supported to persevere in the Lord`'s work,
and to do valiantly in restoring the ancient path of purity,
simplicity and dedication of heart.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to James Pemberton.

[.signed-section-context-open]
Dublin, 6th mo. 29th, 1785.

[.salutation]
Esteemed Friend,

Thy truly acceptable salutations of the 23d of Second month,
and 13th of last month, came duly; the first received at London, the other yesterday,
and both were occasions of comfort and encouragement to my drooping mind:
having had many conflicts and exercises,
through all which the Lord has been merciful beyond what I have even dared to expect,
and among other favours received, having had the wing of a valuable,
experienced mother cast over me, in my beloved fellow-labourer, Christiana Hustler,
is not one of the least.
We have in many depths (few heights) with increasing love and truest
unity been exercised together for the space of twelve months,
and found it a close trial to separate at London the week after the
Yearly Meeting, when she returned home with her husband.
And now that I am like to be favoured with the company of Sarah Grubb,
a daughter of William Tuke, (who, after their Quarterly Meeting,
the latter end of this month,
intends crossing from England,) I view it as an additional provision by kind Providence,
which renews the obligation on me, to be still more humble and devoted in his service.
I thought it was rather confirming to my mind that thou
shouldst even think of my coming into this nation,
which I did not give up to without great fear and much exercise of mind.
I left London the 4th instant, and took a few meetings in the way,
in company with my dear friends Samuel Emlen and son, George Dillwyn and wife;
got to Liverpool the 11th, and on the 13th in the packet,
(a brig,) from thence crossed the water hither, landing the 16th,
not without sea sickness, as usual, but resigned and quiet in mind.

And now I am engaged (till my companion comes)
in going with George Dillwyn and Samuel Emlen,
from family to family in this city;
but whether Samuel will make a thorough visit of the kind, is not known;
George Dillwyn will hardly, and I hope soon to be released;
but thou knowest Samuel Emlen is much led in this line, and is peculiarly gifted for it.
He is at times weak and discouraged;
but on the whole I do not think him in a much
more enfeebled state than when in Philadelphia.

It was cause of great joy to meet thy dear brother John at London,
and the more so to find him so easy and cheerful in spirit,
as well as that he appears improved every way, except that he is and does look older.
Whether he will cross from Scotland, whither he has gone with Father Ross,
(as Captain Truxton used to call him,) into this nation again, is a matter, I believe,
not fully settled in his own mind.
But I trust he will be wisely and safely directed.

I note thy brotherly desire on my account with
thankfulness to Him who is so rich in mercy,
and boundless in compassion still,
that he is pleased to require no mighty works at my feeble hands,
so that he should condescend to accept my little labours of love in his cause,
is humblingly marvellous in my eyes,
and must be so to others in whose hearts a place has been found for so poor a creature.

Thou wilt doubtless hear from different hands how and where our American friends are.
I can only say, I believe they are all well; and I trust in the Master`'s appointment;
as well as that they are much in the acceptance of Friends where they travel.
I may inform thee there is a large body of Friends in this city.
Their meeting, when fully gathered, is in number, I think, equal to ours at the Bank,
and no ministering Friend belonging to it but one woman Friend,
who has a small testimony.
Many of them appear hopeful, especially among the younger and middle rank.
My landlord and his wife, Joseph and Jane Williams, are steady, valuable Friends.

Please give my love to thy wife and children, to H. Pemberton,
(bid her be still resigned and patient on dear John`'s account;
he is in good hands and prosperous,) to thy kinsfolk,
and to other dear friends in thy freedom.
`'Tis cause of humble thankfulness that I still maintain
a place in the minds of my dear friends at home.
May their prayers with mine ascend for renewed help and preservation.

Thy brother John has left a sweet savour behind him in this land,
and so have all the other Friends who have been here;
and oh that I may be kept from doing any harm, for I do very little good,
except `'tis secretly, yet I don`'t murmur, but am content.
Thy account of dear William Savery and D. Offley, is comfortable.
May they be preserved through all.
My love to them.
Tell D. Offley his letter came safe, and was acceptable.
I should like to hear from my friends often, but I feel my own unworthiness,
and knowing that others must know it, I forbear asking.

And now, desiring that I may not be forgotten, in this dark corner,
by those who have my welfare and the welfare of the great and good cause at heart,
which is increasingly dear to me, though a feeble servant, who can do little,
very little, for its advancement, I conclude, and remain thy affectionate friend,

[.signed-section-signature]
Rebecca Jones

--

[.embedded-content-document.letter]
--

[.letter-heading]
To H. Drinker and Wife, and M. Sandwith

[.signed-section-context-open]
Dublin, 6th mo. 30th, 1785

[.salutation]
Much esteemed Friends and old kind neighbours, H. D. and wife,
and M. Sandwith,

I don`'t forget my former acquaintance, but often,
(among many others) think of you and yours with continued desires for your preservation,
every way,
that as you with me have been made experimental witnesses of
the care and kindness of our merciful Creator,
many ways vouchsafed, we may neither distrust his continued mercy,
nor withhold from him his due,
even the surrender of ourselves and all with which he has blessed us, into his holy hand,
suffering him to have his own way and work in and upon us in time,
and finally lay down our heads in peace, in a happy and joyous eternity.

H+++.+++ D.`'s few lines of Third month 12th, accompanying G. Churchman`'s,
were truly acceptable, and more than I expected,
considering how many are his engagements, which, I understand, are not lessened.
Should a suitable opportunity offer,
I should like my dear love given to A. James and his precious
wife and their children--I have sympathized with them all--to
your connections--to your kinsfolk the Jarvises,
neighbours Walns, Hartshornes, Howells, and to other dear friends in your freedom.

Dear Samuel Emlen and son, George Dillwyn and wife, with myself,
left London the 4th inst., embarked from Liverpool the 13th,
and landed here the 16th. Samuel Emlen, whose service is great in families,
with George Dillwyn, found their way opened to a visit in that line here, and,
as a feeble link in the chain, I have been united with them.
We have been engaged about ten days,
and there being as large a number as I think there is in our Bank Meeting,
the weather very trying in this crowded city, and some of the band weakly,
we don`'t take above six in a day, so that if the whole is gone through,
it will take me at least three weeks more to complete it.
But Samuel Emlen often talks of going back to England, and taking ship from thence home,
which, I apprehend, he will in a short time.
He is, as usual, often poorly and discouraged; at other times better and cheerful,
but strong in his Master`'s service, and is, with George Dillwyn, greatly owned therein.
Indeed, it seems a day of precious visitation to Friends here.

Our friends from America are, I believe, all well in different parts of England,
and dear John Pemberton has left an open door in the minds of Friends and others here;
so have the other Friends who have visited this nation.
May their honest labours be blest!

--

"`Seventh month 25th, 1785.--Richard Shackleton and wife, George Dillwyn and myself,
engaged in a family visit to friends at Ballitore, and Catleds.
Began at Abraham Shackleton`'s school, amongst about fifty boys,
mostly not members of our Society.
This was a time of great favour.`"

During this visit, which, by a subsequent note, we learn,
consisted of sixteen different sittings,
Rebecca Jones was introduced into much discouragement.
Her friend Sarah Grubb having arranged to meet her at Dublin,
found herself detained to attend the Monthly Meeting at Warrington,
and a meeting at Liverpool.
She at length embarked in the Havre packet, and had a tedious and distressing voyage.
Being compelled to put in at the Isle of Man, she was detained there two nights;
their provisions were entirely exhausted.
Rebecca had received letters addressed to Sarah since her embarcation,
and also tidings that she had actually sailed.
Hence she was in great distress of mind, and brought very low;
ready to conclude that if through her means so dignified an
instrument should have been lost to the church,
she must be under a delusion, and her mission a mistaken one.
On their way from Richard Shackleton`'s,
(accompanied by his wife,) to visit some friends in the country,
Rebecca Jones was riding in much mental depression.
George Dillwyn being on horseback,
rode up to the side of the carriage and said--"`Be comforted, Rebecca,
Sarah is safe on __terra firma__.`"
When they had reached the house to which they were bound,
Rebecca Jones found a Bible in the window, and opening it,
her eyes rested on 1 Kings 17:24. She said--"`George,
art thou willing to be tried by this?`"
He replied, after a solemn pause,
"`I am!`" and she read aloud--"`Now by this I know that thou art a man of God,
and that the word of the Lord in thy mouth is truth.`"
It had been their design to remain that night in the country,
but in consequence of George Dillwyn`'s firm impression, they returned toward Ballitore.
Whilst they were on their way, in the dark of evening, they met an Irish car,
bringing Sarah Grubb, who having landed, was hastening to join them.

Sarah Grubb says--"`In a few days we set forward together, viz,: George Dillwyn,
Rebecca Jones, and myself; our prospects comfortably corresponding one with another,
we cheerfully concurred therewith to travel in company.`"
On the 4th of Eighth month,
returning to their lodgings after a little mission to Christians Town,
they had a solemn sitting with the family from whom they were about to part,
on which occasion R. J. was enabled (as Sarah Grubb expresses)
"`in awful supplication to breathe for continued support,
and preservation in the path of obedience, which,`" she adds,
"`comfortably contented our spirits together.`"

Next day they set forward, leaving Sarah Dillwyn at Richard Shackleton`'s.

On the 1st of Eighth Month, she writes from Baltimore to Joseph Williams,
who was her kind host at Dublin,

[.embedded-content-document.letter]
--

"`I am yet a very poor creature, but hope to be content,
and to feel the reward of peace in reviewing my labours in your city.
May the professors of truth in that place be
favoured so to submit to the divine visitation,
that the scales will fall from their eyes,
and they see for themselves the necessity there is for many to come away '`from Lebanon,
from the top of Amana, from Shenir and Hermon, from the mountains of the Leopards,
and from the Lion`'s den;`' that so our Heavenly Father may delight to dwell among them,
even as He did among their forefathers,
as they come into the experience of the fulfilling of his
gracious declaration,--'`This people have I formed for myself;
they shall show forth my praise.`'`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Christiana Hustler

[.signed-section-context-open]
Grange, near Charlmont, 6th mo. 13th, 1785.

[.salutation]
Dearly Beloved Friend,

So it is, whether we have anything worth communicating or not,
when we are brought near to them we love,
and feel in the precious covenant of life and heavenly fellowship,
we cannot forbear saluting each other; and this is so much my case,
that I am obliged to take up the cross to the disposition I feel,
or should run thee to much unprofitable expense.
I wrote thee from Ballitore; since then we (that is, George Dillwyn, my companion,
and self,) have taken the meetings at Rathangan, Timahoe, Edenderry, Old Castle,
Coothill, and Castleshane; to the four last,
the inhabitants had an invitation on George Dillwyn`'s concern, and they were held,
I hope, to some profit, the people behaving well; and Friends being desired,
at the breaking up, to keep their seats, afforded me an opportunity for some relief.
We had a very large satisfactory opportunity at a newly settled town called Prosperous,
a few miles from Timahoe,
(no Friends residing there,) which was held in
the chamber of a large unfinished building.

Came to Joseph Nicholson`'s last evening,
feeling our minds more inclined hither than to Dungamson,
and are comforted in the company of his grandfather, J. Morton, who,
though labouring under an asthma, is "`an Israelite indeed.`"
Several young people here appear hopeful; after tomorrow we may move toward Tobberhead.
We have had rainy weather mostly since leaving Ballitore,
so that I am more reconciled to the old post chaise,
which George Dillwyn and Samuel Emlen strongly urged my accepting.
My limbs are better: but I am still a very poor affair,
and don`'t know what will become of me in this journey;
for I feel very little more than resignation; and that, methinks,
I hear thee say is a favour; I join thee; because, whether I live through it or not,
it keeps me quiet, so that I don`'t look far before me, but just live from day to day,
and that more by faith than by sight.
And in some of these, my baptized moments,
thou art brought so preciously near to my soul,
that the enjoyment of the unity of thy spirit, is indeed a brook by the way,
wherewith I am refreshed and encouraged still to trust in that good
hand who has thus inclined thy heart towards a younger tried sister;
and who will, I do believe,
suffer thee and me to be tried no further than He will enable us to bear up under,
if we retain our confidence in him to the end; cast, therefore, my dear friend,
thy care upon him, for he careth for his depending children; and though,
in his unsearchable wisdom, He feeds with the bread of affliction,
and dispenses the waters of bitterness, oh,
they are measured in the hollow of his holy hand,
and in that unerring wisdom are given us,
for the more full effecting of His inscrutable designs,
and our perfect sanctification thereby.
I know not why thou shouldst be so constantly present with me;
I sometimes think and believe thou art in near sympathy with my tried situation;
at other times, that, perhaps, we are again to be united in service; and again,
if thou shouldst have thy commission extended to America,
and we in the Master`'s appointment, cross the great Atlantic together,
it would be cause of humble rejoicing to more than myself;
but let the cause be what it may, or ever so latent,
the sensation is so sweetly comfortable! `'tis as a seal upon my spirit,
that thou art under the special notice and regard of the heavenly Shepherd,
whose voice is sweet, and countenance comely as ever, and will "`put His own forth,
go before them, and give unto them eternal life;
and none shall be able to pluck them out of his holy hand,`" nor any thing past, present,
or to come, separate them from his love and favour!

I have letters from home as late as 20th of 6th month.
All well.
They have not yet heard that "`my mistress is taken from my head.`"
When they do, they will bemoan me, as I do my own situation,
yet am thankful for dear Sarah Grubb`'s company, who is a valuable, steady, kind friend,
and has been much favoured in her service.
I love her, and wish she may receive no damage through me.

Now to Him that is able to keep us through all that may be permitted to attend,
and to present us faultless before the throne of His glory with exceeding joy,
I commit and commend thee, with my own soul,
and remain with undiminished love and well-wishing, thy poor fellow pilgrim.

[.signed-section-signature]
Rebecca Jones

--

On the 25th of 8th month, our friends attended the Monthly Meeting at Lisburn.
Sarah Grubb says,
"`My dear companions were silently baptized under a
concern to visit the families of Friends in that place,
though the time did not appear to be then come.`"
After visiting various other places, they returned to Lisburn, and, 9th month 2nd,
commenced the visit which occupied about a week;
"`the Minister of ministers being near,`" as Sarah Grubb remarks,
"`to hand forth in the needful time (often after long suffering
silence,) suitable instruction and consolation to the visited.`"
Shortly after this they found peace in the performance of a family visit at Timahoe.
Having been very generally through the meetings in Ulster,
they had several very large and satisfactory meetings at
different places among other professors there and on the way,
particularly Ballinacree, Ballymena, Charlemont, Rathforland, Prosperous, Rathangan,
Edenderry, and Tullamore.
Referring to these places,
she writes to John Pemberton--"`An opening is made for us through thy dedication,
and many, both Friends and others, remember thee with love and esteem.`"

At Moate they met with Zachariah Dicks, from North Carolina.
"`I expected,`" says, Rebecca Jones, "`George Dillwyn and he would have united,
but when companions are rightly yoked, great care should be exercised,
lest a separation do harm;
and though I stood freely resigned to the thought of our being left, two poor females,
to struggle alone, yet George did not see his way clearly to join Zachariah Dicks,
and we parted from him in love and tenderness.^
footnote:[George Dillwyn continued with them through their visits in Ireland.]
After a week spent in Dublin, under great discouragement, she writes from Limerick,
10th month 10th,
to John Pemberton--"`I need not tell thee how low the state of things is in this land.
The scarcity of living ministers fully evinces it,
as well as the deep feeling sense which has attended our minds;
yet there is room to hope that some young people will,
if not turned aside by the many stumbling blocks, be brought forward in the Lord`'s time.
I feel for thee, dear John, in the tried exercising path in which thou art led,
but as often as I look towards thee,
the passage occurs-- '`He that soweth plenteously shall reap abundance;`' and
I trust the sweet enriching crop of divine peace will be thine at last.
But as for me, I need the prayers of my friends,
for I am of no service only that I am daily led in the way of the cross,
and wish to be obedient, but have little strength.
I am humbled with the kindness of friends to so nothing a creature!`"

Her services in Ireland were extensive,
and from the testimony of her companion and others,
it is evident that she gave full proof of her ministry,
and was in numerous instances made helpful to her fellow probationers.
Having taken at Dublin their passage in a collier, bound to Whitehaven,
they were detained by contrary winds.
Sarah Grubb says, "`We found it safe to look around us,
that if any little service was omitted if might then be performed.
Standing in the resignation, and not being detained of ourselves,
divers opportunities for public and private labour unexpectedly opened,
generally tending to invite the ignorant,
and to encourage the sincere and drooping minds,
to a faith in the sufficiency of the gift of God in themselves,
for the sanctification of the soul,
and the necessary supply of every spiritual enjoyment,
and qualification acceptably to worship, which must now, as formerly,
be sought for in the beauty of holiness and in newness of life.
We stayed over another First day,
when my companions George Dillwyn and Rebecca Jones were
enabled to bring up living stones of memorial to the sealing,
I trust, of their testimony on the spirits of many;
and my cup of affectionate fellowship seemed to overflow in secret.
The next day a gale rose in our favour, which we thankfully accepted,
and were gently wafted over by it in twenty-five hours.`"

On the 20th of Twelfth month,
our friends (including George Dillwyn and wife,) landed in England,
and on the 27th she thus writes to her valued friend, Joseph Williams of Dublin.

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Joseph Williams.

[.signed-section-context-open]
Leeds, 12th mo. 27th, 1785

[.salutation]
Dear Joseph,

George Dillwyn having undertaken
to announce our safe arrival at Whitehaven,
in gratitude and thankfulness to the great Preserver of men,
it was less necessary for me to write at that time;
yet feeling increasing affection to thee, thy family, and other dear friends in Dublin,
I thought it would not be unacceptable, to hear again from us,
and how we are at present circumstanced.
We stayed meeting at Whitehaven, and went to Gray southern that afternoon,
where George Dillwyn finding his way open for a visit to Cumberland, dropped anchor.
Sally will stay in the neighbourhood until the Quarterly Meeting for that county,
which is to be held at Wigton, the latter end of this week;
after which I know not how they may be disposed, as George Dillwyn like myself,
sees but little at a time.
We parted, under a persuasion that it was the right time and place to leave them.
My dear companion Sarah Grubb and myself,
proceeded in a post chaise by Kendal and Settle, to this place, taking Wray,
Bentham and Settle Meetings in our way, and arrived here last evening.
The weather has proved very cold, and during the last two days much snow fell.

On taking a view of my late travels and small services in your nation,
though I do find abundant space to write, unprofitable servant,
yet I feel the evidence of peace, in a full persuasion that I went, continued,
and returned, in the right time; and trust,
the remembrance of the Lord`'s mercy and goodness, as witnessed by our little band,
and felt to be extended towards a living, though small,
remnant in different parts of your country, will follow me all the days of my life.
I feel that thou and thy beloved valuable wife, with others,
will be as epistles in our hearts, as we in yours,
under the sweet influences of that love which many waters cannot quench.
May you, dear friends, stand wholly resigned to His all-wise direction,
whose fatherly care and protection are, and will be over you and yours,
while the race begun is continued in.
And finally I ardently breathe for you as for myself,
may we be found in our lots in the end of days.

I hear that one of the Society from Congenies, in France,
has come to London to consult with Friends, and has brought with him a long epistle,
signed by about five hundred persons,
giving a very full account of his people and their present condition;
that though he has been a warrior, he appears to be a solid, sincere-hearted,
thinking man, and that he proposes staying awhile to acquire the English language.

[.signed-section-signature]
Rebecca Jones

--

The following is extracted from a letter from J. Pemberton to Rebecca Jones:

[.embedded-content-document.letter]
--

"`It appears there are in two places in our land,
convincements similar to that in France, one about 150 miles from Danby,
on the borders of Canada.
A man who had been an officer in the army, grew dissatisfied and uneasy in his mind,
retired home, and got into the quiet, and sat down with his family,
retiring inward to wait upon God; this drew the attention of some of his neighbours,
who came and sat down with them,
but did not know there was any people whatever that
held the same principle they were led to embrace,
until some who had been in the army,
and got some knowledge of Friends and their principles, called them Quakers;
they then sought to be informed respecting us, and meeting with Robert Barclay`'s apology,
rejoiced to find there was a people who professed this inward principle;
their number is about 12 families who have embraced this doctrine.
The other settlement is up the North river, on the west side of it,
the number not mentioned.`"

--

At the opening of the year 1786, we find by a note,
that she was enabled to look forward with the eye of
faith toward the end of her pilgrimage through time,
with something of a living hope that, "`all remembrance of the necessary proving seasons,
will be lost in Divine fruition, everlasting and eternal.`"
The notes relative to the early part of this year,
afford little material for our present purpose,
whilst they clearly indicate industry in her religious engagements.

First month,
6th.--"`My Hannah Cathrall writes me--'`Society concerns have greatly increased.
Our Monthly Meeting (North Meeting, Philadelphia,) has become very large;
but I may truly adopt the Prophet`'s language, '`Our joy is not multiplied.`'
She laments the ungathered, airy situation of many of the youth,
and the unskillfulness of some Friends who have undertaken to nurse some of the
precious lambs who have been immediately called by the heavenly shepherd`'s voice.
She is, upon the whole, in a bemoaning, sorrowing situation, on account of divers,
yet strong in faith, on account of her poor Rebecca Jones, at which I marvel greatly.`"

2nd Mo. 3rd She notes--"`Thomas Ross said to me, Dear Becky,
I am waiting for the messenger.
Oh he will be a welcome messenger to me.
Give my dear love to Hannah Cathrall, to H. Pemberton,
and to all my dear friends in Philadelphia.
I have heard that several are coming forward and growing in the truth,
and I rejoice in it.
Tell them so.
Oh, I hope that he who has been with me in six troubles will not leave me in the seventh,
but will grant me patience till my change comes, which will be a glorious change to me.
Dear John Pemberton,
I have believed that thou wilt be set at liberty
to go home after the next Yearly Meeting:
and I once hoped to be thy company--but that is over,
and I shall finish my course here.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Henry Drinker, (written At Robert Grubb`'s.)

[.signed-section-context-open]
Foston, near York, 2nd mo. 8th, 1786.

[.salutation]
Much esteemed friend,

I have abundant cause to
be more humbly thankful to the Father of mercies,
than any other of thy correspondents--not only
for the innumerable favours heretofore received,
among which the enjoyment of a living union and sensible
fellowship with the members of the church militant,
is far from being the least in my view.
And thy cordial brotherly salutation of the 4th of Twelfth month last,
which met me here under an exercise of both faith and patience,
is an occasion of renewed gratitude.
Thy several kind and brotherly queries were replied to by the silent tear,
which afresh flows on taking up my pen;
and often has this been my experience on looking toward thee and thine,
with some other dear friends in our native city of Philadelphia, where,
may the presence of Him who so marvellously sustained
us through a fight of afflictions that are past,
be mercifully witnessed to preside in meetings, families, and the minds of individuals,
and by his own saving power, keep and preserve my soul with yours in a state of humility,
watchfulness, and dedication, to the end of the painful race.
As no impossibilities are required,
I have been for several weeks with my beloved friends Christiana Hustler and Sarah Grubb,
in turn, using some medicines which have had a reviving effect,
and have had an opportunity of frequently visiting our beloved aged friend, Thomas Ross,
who is drawing gradually to "`the house appointed for all living,`" with an
unshaken evidence (which he often expresses,) that "`there is a place of rest,
prepared for him.`"
He was much revived by thy letter to him,
and often mentions great nearness to friends in Philadelphia.
His disorder being in part dropsical,
one of his legs has burst and discharged considerably,
which has afforded him some relief, but we have no hope of his recovery.
Our dear friend, John Pemberton, is with him at the house of Lindley Murray,
one mile from the city of York, which will, I trust, prove recruiting to J. P.,
as his arduous labours have not afforded him much time for rest.
He looks well, but considerably older.

I observe with concern that bodily weakness is thy attendant: it has often been so,
and it has not checked thy best and most worthy pursuits.
Let us then, dear Henry, take courage,
in hope that "`all things shall work together for good,`" as we retain our
integrity and follow on to know His blessed will concerning us,
whose will is the sanctification of the obedient mind.
My pen can do but little towards setting forth the excellency of his lovingkindness,
but my soul even now worships with prostration,
and daily craves ability acceptably to adore his unspeakable,
unmerited and matchless mercy and goodness me-ward;
that he should at all condescend to notice,
strengthen and engage one of the least in the family to
proclaim his goodness and call unto others to come,
taste, and see for themselves, that he is good.

I am pleased with thy account of the Friends from hence.
May they be furnished with divine strength and wisdom proportioned to their need;
and that dear N. Waln is so favoured, is comfortable.
The situation in which thou describes dear Samuel Emlen to be, was much his,
when in Ireland: we often mingled our tears.
I had a hope he would get safe home, but I regretted his hasty escape;^
footnote:[It may not be inappropriate here to insert an extract from
a subsequent letter from H. Drinker to Samuel Neale,
dated Third month 10th, 1788: "`Our valued friend, Samuel Emlen,
hath visited our dwelling twice this day.
He is, as thou must have known him, often feeble in body,
but continues to be a vessel chosen and appointed to preach the gospel in the
authority thereof--frequently animated and strengthened to the admiration of many.
Ever since his last return from your land,
he appears at times much bowed under a sense of too hasty escape,
and an apprehension that he must give up to
visit some parts of Great Britain once more.`"]
and though I do not wish to add to his uneasiness about it,
yet I am still of the same mind,
that if he had extended his visit in Ireland to the northern parts of this nation,
his bundle of sheaves would have been increased.
My dear love is to him and his, and to the other friends above named;
though I did expect he would have written to me, yet I know I don`'t merit his notice,
and therefore wish to be content.
But thou mayest tell him his visit will not soon be forgotten by his Friends in Dublin.

Our (i.e. George and Sarah Dillwyn, my companion Sarah Grubb and self) leaving Ireland,
etc., I expect, will be mentioned to thee by others since which, as before said,
I have been attending a little to the body, and engaged a little among Friends at Leeds,
and a few meetings in this county, and if no engagement at York prevents,
I hope in a week or two to move towards Cheshire, etc.,
where I may probably be detained till the next Yearly Meeting.
After which, whether I may be favoured with leave to return home or not,
some of our number, I expect, will.
But as I remain a poor, weak, short-sighted creature,
and George Dillwyn says it is best not to strain our eyes in the dark,
I crave that I may be kept in that resignation in which
I left my native land--with an attentive ear,
that when the sound of the trumpet is '`Return,`'
it may with the same certainty and confidence be followed,
as when the command was heard to '`Go Forth.`'
But the continued feeling of unprofitable servant so accompanies all my movements,
that I am at times ready to fear on my own account, though my fellow servants,
I am sensible, are greatly favoured in their steppings.
All of whom, I believe, are well, and in acceptance and love amongst Friends.
And thou mayest tell N. Waln and R. Valentine,
their labours will long be remembered by many.
Robert Grubb and wife, join me in love to them.

Malton, Second month 10th.--(At David Priestman`'s). I forbore closing this,
thinking I might have something to add respecting dear Thomas Ross, but find,
by a few lines received this morning from William Tuke,
that I have only the account of his growing gradually weaker: and being easier,
they have a hope that he may pass the little time that he is continued,
with less bodily pain, though he is not likely to continue many days.
I have also a letter from our dear friend George Dillwyn, dated the 6th inst., at Kendal,
where he, with his wife, were in usual health.
He is going into the dales of Yorkshire--mentions
Patience Brayton as being there and well.
I have also tidings of dear J. Pemberton`'s continued health,
and that he is not easy to leave Thomas Ross.

With the salutation of love, I can feelingly subscribe myself thy sincere and obliged,
though poor, friend,

[.signed-section-signature]
Rebecca Jones.

--

Rebecca Jones and John Pemberton were detained awhile in the neighbourhood of York,
awaiting the release of their aged honourable friend, Thomas Ross.
He quietly "`ceased to be mortal`" on the 13th of Second month, 1786,
at the house of Lindley Murray, about a mile from that city;
and was interred on the 16th in Friends`' burying ground at York
beside the body of his countryman and friend John Woolman,
"`agreeably,`" says Rebecca Jones, "`to the good old man`'s desire.`"
The time of his funeral was a favoured season,
Rebecca Jones preached with remarkable unction at the grave,
as did George Dillwyn at the meetinghouse:
a large audience being collected on the occasion.
On the 15th she writes--"`Dear J. Pemberton`'s tried path has claimed my sympathy,
but he is so admirably supported, both body and mind,
that I am therefrom encouraged to believe that all is now and will be finally well.
George Dillwyn has sometimes made a comparison between some of us and John Pemberton,
that we are as fishing with a crooked pin and thread,
while John is casting his net into the sea.
Oh that his labours may successfully gather many to the heavenly Shepherd.
In Ireland, Friends and others love to speak of him, and also of our deceased friend,
Thomas Ross.
Indeed, they have seemed to labour more abundantly than us all.`"

On the 20th of Second month, in connection with George Dillwyn and Esther Tuke,
she commenced a family visit to Friends of York:
and on the 6th of Third month with George Dillwyn and
Christiana Hustler she began a similar service at Leeds,
which latter comprised fifty-nine sittings, ending on the 22d,
with three satisfactory meetings--one with disowned persons--one with those in a tender,
seeking state, who, though not members,
attended Friends`' Meetings--and one with fifty scholars and their teachers.
The latter two, as also the Meeting on the ensuing Fifth day,
are spoken of as crowning seasons, and an adequate reward for their painful labours.

A note from Sarah Grubb, received at this time, says, "`Let me bid you go boldly on,
and believe that your judgment and your work is hid in the holy treasury.`"

Writing from Stockport, on the 6th of Fourth month, to Esther Tuke,
(who was stepmother to Sarah Grubb,) after acknowledging the favour
of "`the living loan from your family,`" she thus continues:

[.embedded-content-document.letter]
--

"`Now that my back is turned upon Yorkshire, I cannot say,
notwithstanding I have had close and deep baptisms to pass through,
what dear N. Waln uttered when he had quit your borders, except this, which,
I may say with thankfulness,
that I have been enabled to keep from complaining to mortals, and, as dear S. F. advised,
have desired "`no confidant but Eternal Help`"--which help I
have been made sensible is near the true seed there,
and will I believe be more signally displayed for its support and preservation,
even when it may be more signally sought after and implored.
I love Yorkshire--many friends in it are near to my very life.
I have had to believe that under the precious, however painful,
operation of the holy fan and fire,
some of the present rising generation there will be preserved,
and in the right time show themselves to Israel,
equipped with the holy armour on the right hand and on the left.
And I also do fully believe that a time is approaching when a discrimination
will be made between the worshippers only in the outward court,
and the deeply exercised suppliants in the inner Temple.
Of which number, may you, my dear fellow travellers, both parents and children,
be happily found.`"

--

Being joined by Sarah Grubb, they visited Wales and the western counties.
This journey was rendered arduous by the ruggedness of the country,
the road partly being "`over the tops of very high mountains:`"
and the scenery impressed her as "`amazing and awful.`"
She speaks of meeting with honest-hearted friends in Wales, "`well worth visiting,
and more in the simplicity than most other places.
Great openness also among others many of whom understand our language,
and gladly accept invitations to attend our Meetings.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Joseph Williams.

[.signed-section-context-open]
Bradford, Yorkshire, 3rd mo. 25th, 1786.

[.salutation]
Dear Joseph,

Thou wilt probably be surprised to hear that I am still in this country;
and I assure thee that my detention has been as
unexpected to myself as to any of my dear friends;
yet having an humble hope that I have been in my right place,
thou knowest it matters little where that may be.

Thy brotherly salutation of last month reached me at York,
and was truly comfortable to my poor mind.
Having just attended the funeral of dear Thomas Ross,
I had an opening into some mortifying labour before me, to which,
when our worthy brother George Dillwyn came (who arrived in
time to attend Thomas Ross`'s interment) I soon yielded.
He joined dear Esther Tuke with me in a family visit there,
and I may say that I was thankful in believing
that George also was in the way of his duty;
for besides his weighty and acceptable service in the divers meetings we there attended,
one of which, with the inhabitants, was at the request of dear J. Pemberton,
he was much favoured in the visit.
After this service was completed, we came on together to Leeds,
where a concern of like kind came over me,
and he united with my dear friend Christiana Hustler and myself in a family visit there,
which was evidently owned by the putting forth and leading of the heavenly Shepherd.
We finished on Fifth day last, having visited about eighty families.
From thence we came here, attended the Monthly Meeting, which is large,
and expect to stay their Meeting tomorrow,
and to have a public meeting in the evening with the town`'s people.
The Quarterly Meeting being held next week at York,
I suspect I cannot avoid going thither,
after which I shall again hope for a release from the North.
Thou mayest judge by this how my way is hedged in,
and feel a little for me in my situation.

John Pemberton writes me from Whitley on the 20th, that he was visiting families,
and having public meetings thereaway.
William Matthews, by a letter this day from him,
has been held prisoner during the winter in London,
where he has had many large satisfactory meetings with
religious professors not of our Society.
At the time of writing he was at Hertford,
laid by with a rheumatic complaint in his head and face, and was low in every way.
He says that dear Catherine Phillips is in a declining state of health;
that Ann Jessop had been in Cornwall, and gets along finely,
and that he hears our dear Z. Dicks is mending.
P+++.+++ Brayton has gone towards Cumberland, and M. Jenkins is in Westmoreland.
I suppose she with George Dillwyn will attend the Quarterly Meeting,
held in about three weeks at Blackburn, in Lancashire; where dear Sally Dillwyn,
whose abode has been for some time at Kendal, will meet her husband,
and probably proceed with him to London.
Dear Sarah Grubb is to join me after the Quarterly Meeting,
and if her patience is sufficient, may perhaps set me down in London,
where I shall be rejoiced to see thee and thy dear wife--and
many others of my dear friends of your nation,
whom I love, and wish well, here and everlastingly.

I am obliged by thy sundry pieces of intelligence,
and hope thou wilt continue thy truly agreeable and profitable correspondence,
for I can assure thee I am the same poor thing as when under thy roof.

Farewell, dear Joseph, and be not of a doubtful mind;
for faithful is He who has called us into His service;
and I do believe He will not leave us destitute of His mercy
and care while we follow Him in the way of His requiring.
Though He may suffer us to be deeply tried, as in the depths of the wilderness,
yet He will make way for His dependent suppliant ones where there appears to be no way.
He hath promised that "`The needy shall not always be forgotten:
the expectation of the poor shall not perish forever.`"

[.signed-section-closing]
I am, with unfeigned regard, thy affectionate friend,

[.signed-section-signature]
Rebecca Jones.

--

From the residence of her valued friend Dorothy Owen,^
footnote:[Dorothy Owen was a lively minister,
of whom Rebecca Jones often spoke with great affection.
She used to walk from her residence in Wales to the Yearly Meeting in London.
In a letter to Rebecca Jones in 1789 she thus speaks of her family:
"`My mother`'s name was Lowry: she was daughter of Evan Ellis.
His place of abode was called Cevercruyn.
She was of the family of Gwanes.
One of the sons of her grandfather, Griffith Ellis, went to your parts.
His name was Tudor Ellis.
My father, Rowland Owen, was of the Tythn Ygarreg family.`"]
at Tythn Ygarreg, she writes, Fourth month, 26th, to John Pemberton:
"`We came by way of Ackworth, where my dear Christiana Hustler, receiving a hurt,
I went home with her into Lancashire, and so into Cheshire and Shropshire,
taking the Meetings in those parts.
After Shrewsbury my prospect was turned into this principality.
I have been two days coming hither over a rough road and mountainous country.
Had a comfortable meeting here this day, and,
though divers of the Friends cannot understand English, it was a tendering time.
Friends from other places met us here, because we cannot get to them on wheels.
After taking Eskirgoch, Llanidloes, Pales, Almally, Leominster, and Pontypool,
we are to be at Cardiff, where their Yearly Meeting is held this year.
North Wales being then gone through, we may, should the prospect continue,
visit South Wales before the Yearly Meeting in London.
Thus I am led in a way that I know not--but desire to be content and thankful,
acknowledging that the Lord has been my help and
support beyond all expectation or desert in me.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Christiana Hustler.

[.signed-section-context-open]
Llanidloes, 29th of 7th mo., 1786.

[.salutation]
My Dear Friend,

I wrote thee a few hasty lines from an inn at Welchpool,
to inform thee of my coming into this principality,
and to entreat thee to let me hear from thee.
And now being a little at leisure, in a kind friend`'s small cabin,
though in the chimney corner, with very little light, on my lap, and a book for a table,
have begun this, which may perhaps be finished some future day,
and some time reach thy quiet prison--from whence I do believe "`the
prisoner of hope will go forth,`" and that with songs of joy and rejoicing,
in the Lord`'s time, which must be patiently waited for.

We had a precious meeting at Tythn Ygarreg; many who could not understand us,
were feelingly sensible of the spreading of Divine love over us.
At Eskirgoch, in the midst of high hills and great barren mountains,
to the house where old Jno.
Goodwin lived and died, came many not of our Society several miles on foot,
and were solid and attentive.
The Welch people are an industrious, hardy, plain people,
and there are a few precious Friends worth visiting.
I have a secret hope that there will be a revival in Wales, in His time,
who doth all things well and wisely.
The roads are in general sound and hard;
but we were comparatively like a ship on the ocean, continually ascending or descending,
and the steeps very great, with a deep precipice at the side for miles together;
so that yesterday morning a very high wind taking us on the tops of the mountains,
the probability of being overturned was very alarming.
We had an honest Welchman with us, who carefully led us in the steepest; and one hill,
a mile in length, I walked down, which was great doings for me,
a poor cripple--so that I have daily need still to say, "`What shall I render to thee,
O Lord, for all thy benefits?`"
We got here last evening much fatigued, and though a small house, a very little bed,
and holes on all sides to let in light and air,
with plenty of company to keep off the lethargy,
sensible of the kindness of our friends`' disposition,
we were thankful for past preservation and present
favour--and are to stay here till Second day morning.

Pales, in Radnorshire, 5th mo.
2nd. We have got thus far safely.
Yesterday and today is held the Quarterly Meeting at Philadelphia;
my mind has been much with them: dost thou think that I shall ever sit with them again?
Whether I ever do or not, there is a precious number there,
to whom my soul desires to be united now and forever.
As we have a bit of leisure this afternoon, though the wind is high and cold,
having had both snow and hail in showers, these two days,
I would gladly undertake a walk of a couple of miles to make thee a visit,
if it could be done; but, as it cannot be personally, feel my spirit, my precious,
in that which is unchangeable; and accept the tenderest salutation I am capable of,
with my desire that grace, mercy and peace may be multiplied to thee,
that thou mayest "`Lift up thy head in hope`"--for Infinite
Mercy does not forget "`the kindness of thy youth,
the love of thine espousals "`--and hath promised,
"`I will not fail thee nor forsake thee.`"
The present sensation is sweet--under it I renewedly
feel an increase of Gospel union with thee,
and drop my pen, in a reverent hope that "`darkness will be made light before thee,
and crooked things straight,`" through His love who is
bringing "`the blind by a way that they know not,
and leading them in paths which they have not known.`"

7th.--Being got as far as Leominster, I now conclude, as the post goes from hence.
For these two or three days past, much rain falling, has made the roads deep and trying,
especially in Herefordshire, the soil being clay;
but we have made out as well as we could.
Tomorrow, it is probable, we shall set off, having fifty miles to Pontypool,
where the Quarterly Meeting is to be held on
First and Second days--and next day to Cardiff,
where, oh! if it were possible to meet thee,
it would be almost too much joy for me to behave decently under,
considering where we have been, and how I have fared every way; but,
hush! my faithful monitor reminds me how little I deserve; so,
complaints of every kind aside, I wish to be more thankful.

William Young, at whose house we are,
tells me his sister Catharine Phillips is to be this week at Bristol,
where she has been advised to come, and L. Hawkesworth with her,
who is almost worn down with attending her;
and that Catherine Phillips is in a very declining and doubtful way,
not at all likely to attend the Yearly Meeting there much less get to London.

--

"`Nathan Dearman,`" she notes,
"`presented me with a walking stick made of the trunk of an oak tree dugout of a morass,
at a depth of 10 feet, near Thorne, and supposed to have lain there since the flood.
Many such have been found, all pointing towards the west.
The morass contains many thousands of acres, the surface of which, nearly 10 feet deep,
is turf for fuel;
and below it are often found large Fir as well as Oak trees--some of which
have been used for timbers in houses built upwards of 100 years ago,
and are still sound and good.
Where the turf has been removed, the ground is in many places cultivated.`"

The following certificate was issued by the Half Year`'s Meeting for Ireland,
held in Dublin, 5th mo.
7th, 1786.

[.embedded-content-document.testimony]
--

"`Our esteemed friend, Rebecca Jones,
having paid a religious visit in the work of the
ministry to the meetings of Friends in this nation,
and in some instances to the families;
and apprehending herself clear of further service in that way amongst us,
by a friend requested our certificate.
These may inform you that her labours of love in the gospel were truly acceptable,
her ministry being sound and edifying,
and her life and conversation consistent therewith.
And we esteem it a gracious mark of Divine regard still extended to us,
by the servants and messengers being thus sent to labour amongst us.
May the great Master continue to strengthen and furnish her for every good word and work,
which he may yet call for at her hands in the further course of her service in Europe;
and when this is finished conduct her in safety to her habitation and friends,
with the incomes of his sweet peace as a reward for faithfully
giving up to labour in his vineyard.`"

[.signed-section-signature]
Signed by 144 Friends.

--

After the close of London Yearly Meeting, Rebecca Jones, in writing to John Pemberton,
gives a beautiful instance of the tenderness with which the assembled
church could enter into sympathy with a tribulated servant,
traveling in the bonds of the gospel.
"`Though thou didst not fully commission me,`" she says,
"`to apply for a certificate for thee,
yet I felt a freedom to tell Friends at the select meeting, thy wish,
the expression of which brought a solemnity over the minds of many,
and led to the expression of their near sympathy with
thee in thy deep and singular exercises.
E+++.+++ T., E. H., and J. A.,
severally informed the meeting that they had been eye-witnesses of thy dedication,
and that they believed that thy services had been of
great use in spreading the knowledge of our principles.
The meeting desired me to convey to thee by letter the
expression of their tender sympathy and concern,
hoping that thou mightest be favoured with a release from the
very exercising path in which thou hast been led.`"

In the epistle of this year from the Womens`' Yearly Meeting of London,
to the corresponding body of Philadelphia,
the services of the women Friends from America are thus acknowledged.

"`It has been strengthening in this large assembly to
have the company of our beloved sisters from America,
their united concern and fervent labours for the furtherance of the Lord`'s work, will,
we trust, be blessed to us.`"

She not seeing her way to request a returning certificate,
was left at liberty to obtain one (if released before
next Yearly Meeting,) from the Morning Meeting.
She proceeded, accompanied still by Sarah Grubb, to visit the Western Counties, being,
as she expresses, "`made willing to go down into the imprisoned state of the seed,
and in deep baptisms with and for it, to feel the supporting hand of Divine goodness.`"

On the 21st of Seventh month, she writes thus to Joseph Williams:

[.embedded-content-document.letter]
--

"`I have had a low and weary travel since we left London.
We passed through Hampshire and some other counties on our way hither,
where we have found the state of the church low indeed,
as in the wilderness,--meetings very small,
and very little of that living exercise by which our
ancient friends had near access to the living fountain,
drawing refreshment therefrom, through the precious current of light, life and salvation.
Yet we have found a few true Jews, who are mourning on account of the desolation,
and these have been encouraged to step forward under all-wise direction,
in the work of repairing and rebuilding the walls: and divers among the youth,
appear under lively, tender impressions, but they have few, skillful nurses,
or safe waymarks, among those who ought to lead on in wisdom and firmness.
They have been advised to look to the Holy Head for preservation and strength,
and I do hope that some of them will stand their ground,
and in the appointed season advance to the praise of him who
hath visited their minds with the dayspring from on high,
and called them out of darkness into his marvellous light.

We are now drawing towards "`Land`'s End,`" and expect to return by Minehead, Bristol, etc.
My way at present is quite shut up from any immediate prospect of home;
I hope I may be kept in patience the Lord`'s time, yet confess,
the thought of my dear friends leaving me behind is very discouraging.
The country near the sea is so hilly we cannot be very expeditious.

I conclude with desires that thou and I may persevere
in faithfulness through all our buffetings,
tossings and afflictions, so that we may be favoured with a safe landing at last,
on that peaceful shore where all sorrow will cease, and temptations will have an end,
and where our wearied spirits will be forever at rest.`"

--

Penryn, Seventh month 28th, she writes to Hannah Pemberton:

[.embedded-content-document.letter]
--

"`I suppose thou art a little cheered in hope of
seeing thy beloved husband before another year.
But, though he has a certificate for returning, I would not have thee be too anxious,
but, continuing in the patience,
be thankful that thou art not exposed to the same necessity to expose
thyself to the many jeopardies he and others have been in,
for the sake of that peace, which, when obtained, is beyond every other enjoyment.
Tell Samuel Emlen, that if he should be sent hither again,
I shall be careful to write to him quite as often as he has done to me since his escape.
Farewell, dear Hannah;
mayest thou in the Lord`'s time be favoured with the company of thy dear husband in peace,
and, when these few fleeting moments are over,
be received by the beloved of souls into that peace which is pure and eternal; which,
on my own account, I often desire,
finding nothing here worth desiring to be continued for,
except that the suffering of the present day may work a
far more exceeding and eternal weight of glory at last.`"

--

In recording, after the lapse of more than half a century,
these aspirations after a better, an enduring and an undefiled inheritance,
the mind is brought in a degree to realize the deep meaning of the phrase,
"`these few fleeting moments`" (though our friend had yet a score of
years to tarry for the coming of her Beloved) and to rejoice,
now that the lives of these valiants of Israel are as a tale that is told,
in the assurance that they are in the fulness of bliss, having received,
beyond all that they could ask or think, the end of their faith,
even the salvation of their souls, being gathered with the just of all generations,
and beholding their Redeemer face to face,
and the glory which he had with the Father before the worlds were made.

Pursuing her journey with her valued Sarah Grubb, she notes respecting her,
a growth in her gift,
and an increased weight and clearness in the Discipline of the Church.
Her mind being turned, with strong, natural longings towards her native land,
she admired that her way for returning did not open,
and W. Matthews being constrained to let the ship in which he had hoped to take passage,
sail from Bristol without him,
he was in company with our pilgrims at a number of meetings.
Being deeply grieved in spirit at seeing how many were minding their own things,
and how few coming forward as they ought, the query was often raised, "`Lord,
what wilt thou do for thy great name`'s sake?`"
connected with the petition that the Lord of the vineyard would "`raise up,
qualify and strengthen other labourers, successfully to search the camp,
that so every accursed thing being removed and judged down,
some of the little ones may arise and do valiantly.`"

"`Why,`" she writes to a friend,
"`shouldst thou be ready to lay down thy arms and retreat from the field?
It is a noble cause we have embarked in,
and there is no doubt of victory if we humbly and industriously follow our holy Captain,
seeing it is decreed that He and his followers shall have the victory.
It is a time of suffering, and I look for little else.
Can we expect to reign where the Master does not reign?
Let us then be content with the necessary portion of suffering assigned us,
and not increase it by wishing to be any thing but what He
would have us be,--because without Him we cannot be at all.`"

William Matthews having found it his place (being stopped from
returning to America) to join himself to the Yearly Meeting
committee in visiting Quarterly and Monthly Meetings;
thus refers (Twelfth Month 10th) to the services of his pilgrim sister.
"`In most of the visits we had the company of our beloved sister, Rebecca Jones,
who was eminently furnished, not only with gospel love and authority,
but also with wisdom to point out, in our conferences with those we visited,
the way whereby the waste places might be rebuilt.
She has shown herself a work-woman, that needeth not to be ashamed,
rightly dividing the word.
I may say her company and fellowship have been a
strength to me whenever our lot has been cast together;
and her growth in her gift greatly increaseth,
through her honest dedication of heart to her Master`'s service.`"

Sarah Grubb left Rebecca Jones at the Circular Meeting at Gloucester,
yielding her place as companion to Christiana Hustler.
In the Eleventh Month this valued partner was taken dangerously ill,
so that they were laid by a week at Dudley, and several weeks at Sheffield.
In the prospect of Christiana Hustler being likely to be unfit for Winter traveling,
Rebecca Jones says, "`I shall be like a lonely sparrow,
for there are very few that have so feeling a mind,
and such real worth as this meek disciple.`"
At another time she says, "`It has pleased the Lord to knit us,
as were the souls of Jonathan and David.`"
In this place, (as previously at Leeds, Birmingham,
and other places,) she found great peace in having select meetings with apprentices,
female servants, "`and those who work day`'s labour.`"
She had also one with parents and heads of families.

After a time of painful exercise at the Quarterly Meeting at Leeds,
she left her invalid companion, Christiana Hustler at Undercliff, under great trial,
neither feeling at liberty to separate from the other.
Joined by Sarah Grubb, she tore herself from Christiana Hustler,
essaying to accompany H. Stevenson to Bristol.
But passing to Sheffield and Chesterfield, the prospect towards Bristol clouded,
and her distress greatly increased.
Taking counsel from the unerring source, her mind was favoured with a calm,
and a former prospect of a family visit revived.
Attending the Monthly Meeting at Warnsworth, First month 6th, 1787, Esther Brady,
of Thorne, opened a like concern, greatly to Rebecca`'s strength and confirmation,
and on the 8th the visit was commenced at Sheffield by the trio, Rebecca Jones,
Sarah Grubb,
and E. B. After sixty-six sittings this visit closed on the 26th. During
this service she expressed herself "`deeply concerned for the blessed cause,
lest, in this time of trial she should dishonour it:`" and writing to John Pemberton,
she says, "`I have been ready to think I might finish my course in Yorkshire,
and be laid near dear John Woolman and Thomas Ross.
Who is so poor as the Lord`'s servant, or blind as his messenger, etc.
Very soon after this her companion, Sarah Grubb, was taken alarmingly ill,
and remained so for some time.
Second Month 5th, Sarah Grubbdictated the following message: "`Say to Rebecca,
my affection for her is unspeakable:
also that in this affliction I have been sorely athirst for the purest enjoyments.
As the hunted hart panteth after the water brook, so have I after the living fountain:
but my beloved has been a well shut up, a fountain sealed.`"

And on the 19th, being again able to lake the pen, she wrote to Rebecca Jones,
"`The extension of infinite compassion is marvellous in my eyes.
The hand of Omnipotence invisibly supported in the time of greatest proving and conflict,
when, as Jonah said, '`I went down to the bottom of the mountains,
the earth with her bars covered me, yea, and the sorrows of death compassed me about.`'
But for this support I had irrecoverably sunk under the sense of gloomy desertion.
But I have thankfully to commemorate, that the accuser,
and even that condemnation which I must have acknowledged my due,
were mercifully restrained.`"
We find that on the 26th of Second Month,
Rebecca Jones commenced a family visit at Warnsworth,
(consisting of 38 sittings,) accompanied by Christiana Hustler,
Eliza Hoyland and Philip Mayden.
The work, she testifies, was singularly owned with good--and an open door set before them.
Fourth Month 8th, she commenced a visit to the families at High Wycombe.
After this she appears to have been engaged about the neighbourhood of London,
in great bodily infirmity.
Croydon Meeting being much on her mind,
she was enabled to administer at that place close warning,
and also consolation and encouragement.
After this meeting she was taken ill with fever and acute pain, from which,
being a little recovered, she was removed to London in time to attend the Yearly Meeting.
The following letter was written about this time.

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to David Sutton.

[.salutation]
Dear Friend,

Our dear friend, Hannah Cathrall, of Philadelphia, was a few years ago,
presented by her relation, James King, with the sum of fifty pounds,
understanding that she had suffered through the trials
which were permitted to prevail in America.
And she, being informed of the deplorable state of his affairs,
was uneasy to retain this sum, which he, through intended kindness, had given her;
having a tender regard for the reputation of our religious Society,
and to manifest that uprightness which the principle we profess leads into,
she has requested that this money might be returned to the assignee,
and that the creditors may be informed thereof.

Our said friend is rather in low circumstances,
but this did not prevail upon her to retain this money,
which I have ordered into thy hands, and desire thee to pay.

[.signed-section-closing]
I am, etc.,

[.signed-section-signature]
Rebecca Jones

--

The money above referred to, being offered to one of James King`'s assignees,
he refused to accept it, till the committee of the creditors should meet.
Several of the committee being informed that a bill for
the amount was ready for their acceptance,
they said in surprise that it was such an instance of
integrity and uprightness as they had never known,
that "`it reflected unspeakable honour to the Society of Friends,`"
and that they thought the creditors would not take it.
We find, at a subsequent date, the last sentiment repeated; but,
whether the money was at length accepted, the compiler has not been able to ascertain.

To Joseph Williams, she writes:

[.embedded-content-document.letter]
--

"`I sometimes remember the precious bedewing seasons
thou and I were favoured with together when in Ireland;
and I humbly pray, according to my small measure, that these may often be renewed to us,
when separated in body still farther than at present;
and that thou may not be discouraged nor faint in thy mind,
because of the great insensibility in which so many of our fellow members are centred,
but that we may run with patience the race set before us,
so as to obtain the glorious crown of Eternal Life which is at the end thereof.
Let us keep this animatingly in view, and endure hardness as good soldiers;
remembering that the Lamb and his followers will have the Victory,
however the latter may be tried from within and without.`"

--

The following certificate was granted to her by the London Yearly Meeting,
although she notes that she had no prospect of a time for returning to her home.

From our Yearly Meeting of Ministers and Elders,
held in London by adjournment from the 26th of the Fifth month,
to the 4th of the Sixth month inclusive, 1787;
to the Monthly Meeting of Friends in Philadelphia for the Northern District,
the Quarterly Meeting of the said city,
and General Meeting of Ministers and Elders for Pennsylvania and New Jersey:

[.embedded-content-document.testimony]
--

[.salutation]
Dear Friends,

Our beloved friend, Rebecca Jones,
having in a weighty and solid manner informed us that she apprehends her religious
service and labour among Friends in this nation is so nearly completed,
as that she may be likely to return before our next Yearly Meeting,
and proposed to this meeting`'s consideration the granting her of our certificate;
these may, therefore,
inform you that in the course of her gospel
labours in visiting the churches in these parts,
she hath endeavoured faithfully to discharge the trust committed to her;
and in the exercise of her gift,
hath been favoured with renewed ability to
labour to the comfort and edification of Friends,
and hath been particularly serviceable in the promotion of our Christian Discipline;
her conduct and deportment having been becoming her station in the Church.
And this meeting, after weighty and mature deliberation,
leaves her at liberty to return to her native country, if the Lord permit,
when she may have finished the remaining part of her service.
And, in the conclusion of this, her arduous engagement,
we hope she will be favoured with the evidence of peace and divine consolation.

We salute you in the love and fellowship of the gospel, and remain your friends,
brethren and sisters.

[.signed-section-signature]
(Signed by 204 Friends.)

--

About this time, she had in London eight meetings, exclusively for servants,
apprentices and poor labourers.
The whole number thus visited was 500,
"`many of them evidently under the notice of the great Master of us all.`"

Sixth month 2nd,
she writes from London to Joseph Williams,

[.embedded-content-document.letter]
--

"`I have
esteemed it among the Lord`'s mercies and favours,
that I have been enabled to sit most of the meetings,
and have thankfully rejoiced with my dear friends in
the renewed sense of the heavenly Father`'s love,
which has eminently attended this solemn assembly in its various sittings.
More Friends have come up from the different counties
and places than have been known for many years.

With solid satisfaction,
I may inform thee that the newly established Women`'s Yearly Meeting here,
increases in weight and experience; their deliberations have been profitable and solemn,
and I am strong in the faith,
that men Friends will not have cause to repent their
indulgence to their sisters in this and other instances.
Very pleasant has been the sight and company of so many of my friends from your nation;
and they have had their use and service in the general muster.
I hope it will be not only an easy, but a desirable thing in future,
for surely the wages will be adequate to the toil.`"

--

From Plough Court, 7th mo.
25th, 1787, she writes to

[.embedded-content-document.letter]
--

[.salutation]
John Pemberton:

"`About half an hour ago, dear Patience Brayton, etc., left us,
taking an affectionate leave of dear Christiana Hustler, and poor me;
I have striven for leave to go with them, but, it not being granted,
I am desirous of obtaining strength to stand fully
resigned to whatever may be permitted to attend.
But this has been a bitter cup indeed.
Our dear friends seem all sweet and easy.
They go at 6 o`'clock tomorrow morning to Gravesend, to be on board at 11.`"

--

Christiana Hustler continuing with her,
after the Yearly Meeting they were engaged in extensive and arduous service.
Rebecca Jones, testifies concerning her,
that she was eminently favoured in the exercise of her gift,
"`though she does not take the lead as I would have her.`"

They parted for a season about the middle of Ninth month.
E+++.+++ Hoyland accompanying Rebecca Jones, in a pretty extensive range,
and then yielding her place to L. Hawkesworth.
Our pilgrim was not only, in the companions of her journeys,
blessed with a signal realization of Arthur Howell`'s prospect for her at her embarkation,
that Queens should be her nursing mothers;
but striking coincidences in the mode of her being thus furnished,
evinced that these helpers were provided for her in the care of Him who put her forth.
Sarah R. Grubb, in referring to a prospect, which was unexpectedly realized afterwards,
of joining her, for a short space, in a particular service,
thus instructively speaks of the authority needful even
to act as helpers to others in these solemn engagements.
"`I am more and more convinced, that if we are right, we are not at our own disposal,
and that even the most plausible inclinations are not in general to be followed,
without they are accompanied with some little sense of
Divine bidding to render them profitable and safe.
The protecting providence of the Father of mercies, is, indeed,
repeatedly manifested to those whose care is cast upon him,
and whose blindness is that which is peculiar to his messenger.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Christiana Hustler

[.signed-section-context-open]
Brecknock in Wales, 11 mo. 8th 1787.

My last to thee from Worcester informed of my intention to move with my dear
friend L. H. and John Dearman into this principality.--Know then,
my precious, that we left Worcester last 2nd day morning in our own chaise,
but found the road so exceedingly bad by the rains, that had fallen,
by then we got to Bromyard, that from thence we took a chaise to Leominster,
and stayed over Third day there, having a meeting with them,
which tended to my relief.--On 4th day, as the weather continued unsettled,
the badness of the roads, the season of the year, and the worn down state of poor Jack,
(who had enough to do in dragging us to Broomyard,) were considerations
inducing us to believe it might be best to leave our conveyance at L. to be
forwarded to us at some suitable place on our return,
and go in hired carriages at least as far as to Haverford west,
and round to Swansea and Neath.--Accordingly, having our friend W. Young with us,
we left L. about eight o`'clock yesterday morning,
had some showers in the way to a town called Hay, which is twenty-four miles,
dined there, and came fifteen miles from thence to this place, where at a good Inn,
we have lodged and breakfasted.
But my mind was, on awaking this morning, brought under a very close exercise,
which upon keeping to myself as long as I could,
has at length issued in a belief that the resignation
of my own will is required even in Wales,
and on mentioning to the company the prospect of a meeting here,
they have readily closed with it, and having procured the Town Hall,
notice is now spreading for its being held at eleven o`'clock.

Landilavour the 9th.--The meeting yesterday was small,
yet I hope the great and good cause did not suffer.
It proved the most steadily heavy day`'s rain that I remember in all my travels,
yet we went in the afternoon about eleven miles to Trecastle, where we lodged.
The wind was so exceedingly high that I was kept awake great part of the night,
not only by the tempest,
but in considering that we were now in a very mountainous part of the country,
and no Friend within twenty miles,
and moreover that I had been the cause of my three
companions leaving their comfortable quiet homes,
exposed every day in rain, etc., that we were altogether at expense in our journey, etc.,
(a variety of such fears and doubtings as thou art no stranger to in me.) So
that my mind for a time whilst my dear L. Hawkesworth slept beside me,
very much resembled the tempest of the night--yet towards morning,
being enabled to make my humble appeal to Him who knows the integrity of my heart,
that I had given up to what I did believe was required of me,
and that I had nothing in view besides an honest discharge of duty;
it pleased my great gracious and alone helper, to quiet every disturbing apprehension,
and favour with the lifting up of the light of his blessed countenance,
even as He in His unutterable mercy had often
condescended to do in many a "`needful time of trouble.`"
Under the humbling sense whereof I fell asleep, and in the morning resolved to go forward.

Haverford west,
(12th,) at John Lewis`'s. Since writing the foregoing we have had steady and heavy rain,
yet we have been favoured through the Lord`'s mercy to
get on to the far end of our journey in Wales,
and are better in health than could be expected.
We had a public meeting at Llandilo, there being only four Friends there--from thence,
going round to avoid the water which by abundant
rain had rendered going one way dangerous,
we reached Carmarthenen the largest town we have been in.
Here there is a Meetinghouse belonging to Friends.
We held a large and satisfactory meeting on 1st day morning,
after which (though the people expected another
in the afternoon) we proceeded to St. Clare,
and hoping we might have a dry evening; changed our chaise,
and about forty set off for Narberth, which was thirteen miles further.
There we were obliged to take four horses,
or we could not ascend the mountain at five miles distance.
Before we sent back the two fore horses a violent heavy rain came on,
and it grew so very dark,
that by the time we had got within four miles of Narberth we could
not see either horses or driver--poor I. D. soaking wet behind us,
not daring to pass the chaise, lest he should be lost in the storm.
(W. Young parted with us at C. and hoped to get home in three days.)

Thou may judge of my situation,
what a tossed state I was in! but after a sore conflict of spirit,
I almost fancied myself on the wide ocean--remembering that, in passing over that,
the "`Lord on high (to his poor servants) was greater than the noise of many
waters;`"--and so I was helped into the quiet harbor of resignation,
in which I was mercifully preserved through this close trial.
We lodged at Narberth and next morning,
having only ten miles hither,--we got in about twelve o`'clock, and, to our surprise,
as well as mutual comfort, met dear M. Ridgway and companion,
who were also very low and discouraged,
having been here waiting about two weeks for fair wind to return home,
and failed reaching their Half Years Meeting.
I am now under renewed anxiety about poor William Young, an old man,
and alone in such inclement weather returning--so that my precious friend
cannot help sympathizing with me,--and the more so when I tell thee,
I am in great concern about returning:--the roads are so bad, and still it rains.
But then I consider that if I had not been accommodated in a
close carriage it would have been impossible to have proceeded,
yea, I doubt whether our Jack will be equal to the load again; and yet,
when the great expense attending the present mode of traveling comes into view,
I am ready to sink and call all in question--thus I unbosom myself to
thy feeling mind!--I have endeavoured to stand open--yea,
have desired through the several stages of our journey, liberty to turn about,
and wished for a discharge from the prospect;--but
though I have by night and by day thus laboured,
have not obtained it,
and therefore hope to cast my care upon Him whose wisdom is
unsearchable and his ways are past finding out.

Among other damage done by the late gale last 5th day night, a Captain Blackburn,
who has a wife at Whitby, supped here in the evening,
and with four of his hands went in a boat towards his ship lying at a distance, was,
with three of the men, drowned, by the boat overturning just as he had got near the ship,
and the fourth person, is deprived of his reason through the shock;
being saved by his foot somehow fastening to something in the boat,
so that when she turned up again, he turned with her,
this affecting circumstance has made deep impression on the minds of Friends here,
as they valued the captain, and he had just before left their company.

Tomorrow is the Week Day Meeting here, where there are only about five or six families,
and no more Friends till we get to Swansea and Neath.
From thence I expect we shall proceed by Pontypool, Monmouth, etc., into Gloucestershire,
so that thou will hardly hear from me again till we get into England,
where I shall rejoice to meet thy salutation.
Salute me to all thy kind family--accept my endeared love,
and hold thyself in readiness to come to London and see the last "`of
the child;`" pray for my preservation--pity all my weakness,
and believe me to be thine in the precious bond of Gospel unity though thy poor tried,

[.signed-section-signature]
Rebecca Jones

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Joseph Williams.

[.signed-section-context-open]
Undercliffe, 1st mo. 4th, 1783.

[.salutation]
Beloved Friend Joseph Williams,

Thou mayst perhaps
wonder to find my letter dated from this place,
and truly, it is marvellous to myself also, that having been, as I apprehended,
fully clear of the North, I should again be directed hither, experiencing as a truth,
that "`the wind bloweth where it listeth.`"

Having just returned from a visit to Friends in South Wales,
and expecting to go pretty directly to London,
I felt a strong draught to the Quarterly Meeting held at Leeds last week,
and being enabled to reach it timely,
have been made humbly thankful in believing I was in my place there, and thou knowest,
if this sense does but attend the mind, it matters little where we are.
Mayest thou, dear Joseph, of whom, with thy beloved wife and children,
I have of late often thought,
having now been favoured to feel thy proper place in the family,
be encouraged to fill it with dignity and firmness, and become,
under the renewal of holy anointing, "`a workman that needeth not to be ashamed.`"

I have been for some time expecting a line from thee,
but I know my own littleness and unworthiness,
and am therefore willing just to remind thee, that I was once thy guest,
and don`'t forget thine and thy dear wife`'s kindness to me whilst with you.

It is likely thou hast accounts directly from J. Pemberton, who is yet in Scotland;
and from George Dillwyn, who has been mostly in London since the Yearly Meeting.

[.signed-section-closing]
I am, with dear love to thy household, thy assured affectionate friend,

[.signed-section-signature]
Rebecca Jones

--

The next day writing to John Pemberton, she says:

[.embedded-content-document.letter]
--

"`I believe I shall spend some time in London this winter,
where dear George Dillwyn is still a prisoner; I trust a '`prisoner of hope.`'
Whether he will be at liberty to return with me, I cannot tell,
and I desire to leave all to Him who has not failed to be gracious to us poor Americans;
and who, I do believe, will not fail nor forsake thee.
A concern seems spreading on account of the poor Africans.
Many small and well written tracts have been published and dispersed,
tending to set forth the injustice and iniquity of that trade,
and the newspapers have continual strokes at it,
so that I hope something will be done to put a stop to the diabolical business.
The town of Manchester have formed a committee, and passed many resolutions,
and they are opening subscriptions there and at York, and some other places,
to forward the good design.
I hope, my dear friend, thou wilt not forget me when it is well with thee.
Thou knowest not how many difficulties and discouragements I wade under,
and the greatest fear of all is,
that I shall dishonour the great and good cause
which is indeed dearer to me than life itself.
May the good hand be with thee in all thy goings, and crown thy labours with peace,
whatever becomes of thy poor unworthy friend and tried little sister.`"

--

About this time she became fixed in the prospect of
being at liberty to return to America in the spring,
though she began to doubt whether she could with an
easy mind depart before the Yearly Meeting of London,
which would commence on the 11th of fifth month.
Being solicitous to accomplish all the work required at her hand,
she used much diligence,
even going from meeting to meeting when the
state of her health seemed to forbid the effort.
She was much interested in the efforts which now became
prevalent for the abolition of the slave trade,
yet she was careful to guard Friends,
in the modes of expression adopted in petitions addressed to the great ones of the earth,
that in all respects a pure testimony might be exalted.
This true Christian circumspection was not made a cloak for indifference,
her interest in the "`good cause`" being in various ways evinced.

Reaching London the 4th of Second month,
she sat (mostly in silence) the meetings for
worship and discipline as they came in course,
and noticing-with much satisfaction an advancement
among women Friends in the work of the discipline.

Third month 10th, she writes, "`I am now a prisoner in London,
yet peaceful in my allotment, going almost daily to meetings,
but not blowing my horn in them all.
Our dear friends Robert and Sarah Grubb, and Mary Dudley, produced this day,
to the Second day morning meeting, their certificates,
given by Friends in Ireland for visiting London, France and Germany,
and our brother George Dillwyn revived his concern.
The meeting freely concurred with them all, expressed near sympathy,
and agreed to furnish them with certificates from hence.
It was a solid time.`"
"`Shortly after this,`" she says, "`I am waiting in the patience,
as an unprofitable servant ought, for clear direction,
and then shall not hesitate about going with the first likely opportunity.`"

The second sitting of the Select Yearly Meeting, held Fifth month 12th,
Rebecca Jones mentioned to Friends, the cause of her detention among them,
and at the next sitting, (the 15th,) a cordial endorsement,
(signed by William Tuke as Clerk,) was made upon her certificate,
setting forth that her additional services had been to the comfort
and satisfaction of Friends where her lot had been cast,
and desiring for her, in her return, "`the evidence and reward of true peace.`"

After the Yearly Meeting, attended by Christiana Hustler,
she found herself still engaged,
so that she could not with a peaceful mind take passage for Philadelphia.
She went to Norwich, partly to visit John Pemberton, to whom she was closely united,
and with whom she kept up a frequent correspondence.
She writes to him from London, Seventh month 1st, "`I have hastened to the city,
after a large, and I trust good meeting at Haddeston this day,
in order to go on board the Pigou tomorrow, with some friends, that if this appears,
on waiting for right counsel, to be the right time and ship,
I may be accommodated with a good berth.
I have the prospect of Ann Warder, and Susan Dillwyn`'s company,
(Ann takes two of her children and a servant,) etc., etc.
Now, notwithstanding I told thee at Norwich,
that I should fear going in the same ship with thee,
unless thou felt thyself clear to return, yet if.
having had some time to deliberate and feel for the mind of thy great Master therein,
thou art easy to come and take passage also,
I then shall have fresh cause for humble thankfulness to Him
who has so marvellously sustained us both to the present time.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Sally Hustler.

[.signed-section-context-open]
Carshalton, 8th of 7th mo. 1788.

[.salutation]
My Dear Sally Hustler,

As the time of my departure from this country seems to draw nigh,
and as thou (with the other branches of my worthy friends J. and Christiana
Hustler`'s family,) hast often been the object of my tender solicitude,
I feel disposed (as we have a day`'s quiet rest here,)
to give thee one more testimony thereof in this way.
Though it may probably be my last from this shore, yet I shall,
if favoured to reach my own country, be gratified,
and rejoice in often interchanging these allowable tokens of mutual affection,
and hope to be punctual in my remitances for every one that I shall be indulged with,
by any one of the inhabitants of that hospitable retreat called Undercliffe,
where I have been often received, kindly cared for, and tenderly treated,
far beyond my deserts.
Can I then forget those who have, through the precious efficacy of Divine love,
been made so near to my best life,
the connections of a faithful yokefellow and companion in the arduous service,
through which I have been carried to my humbling admiration,
in this land;--an helpmate specially provided by kind Providence himself?--can I
forget those who have been part of the hundred fold promised in the gospel,
to those who have forsaken all in obedience to divine commandment?
surely no: herein "`my heart shall not reproach me while I live.`"

Well my dear Sally, I do also hope and desire that the resignation of thy worthy father,
the condescension and dedication of thy dear mother, thy sisterly kindness,
and the works of love received from the whole family,
will both be accepted and amply rewarded by Him,
who declared that the giving even of a "`cup of cold water`" to one of the least,
should obtain a disciple`'s reward.
Mayest thou, therefore, become more and more the object of Divine care,
and by an unreserved surrender of thy all into his blessed hand,
be strengthened in full obedience to all His requirings, that so with increasing years,
thou mayest happily experience increasing fitness to come up
honourably in that line of service in the Lord`'s family,
which, after having undergone the necessary preparations therefor,
His wisdom may assign thee, and thus know His blessed will to be to thy devoted,
willing mind, "`thy meat and thy drink.`"
This is my fervent breathing on thy account, to almighty goodness,
who has been rich in kindness to thy soul, and has often made thy tender mind,
under the bedewings of His love,
as "`a well watered garden,`" wherein He has graciously sown the seed of eternal life,
which, if full room is allowed, and it is suitably cherished,
will spring up with increase, to the praise of His ever adorable name,
and thy enriching comfort both here and forever.

I hardly know how to bid the last farewell! but as I apprehend it will be so,
shall conclude in the fresh feeling of dear love,
craving to be had in all your remembrance, and being thy truly, affectionate friend,
conclude such, and bid thee endearedly, Farewell in the Lord,

[.signed-section-signature]
Rebecca Jones

--

As the time of her departure from England approached,
many and touching were the evidences of that Christian friendship and
true unity of spirit which cannot be weakened by separation,
though it adds solemnity to those partings which, so far as time is concerned,
are likely to be final.
Many a farewell scene was crowned with supplication and benediction, and,
on these occasions, the holy presence which had gone forth with her,
was thankfully felt and acknowledged.
The 10th of Eighth month, the last First-day before her embarkment,
was to her and her associates, "`a day of favour.`"
At Grace-church Street meeting, in the morning, she took for her text the words of David,
"`Give unto the Lord, oh ye mighty, give unto the Lord glory and strength;
give unto the Lord the glory due unto his name;
worship the Lord in the beauty of holiness.`"
At Devonshire house in the afternoon, she notes having an exercising time.
At 6 o`'clock in the evening she had a meeting with men and women servants.

It has been already remarked, that she was curiously minute in some of her tabular notes.
From these we find that from the time of her embarkation in
the "`Commerce,`" to that of her arrival in her native land,
she had travelled twenty thousand four hundred and ninety one miles;
had attended one thousand five hundred and seventy eight Meetings,
two hundred and seventy five of which were those held for discipline, and in which,
as her friends in Great Britain officially testified, she was particularly serviceable.
She also notes having had meetings with Friends
in the stations of servants and apprentices,
and labouring poor Friends,
to the number of one thousand one hundred and twenty individuals.
At a time of mortal extremity five years subsequently,
this last named service afforded her a peaceful retrospect.
"`Blessed is he that considereth the poor--the
Lord shall remember him in time of trouble.`"

On the 13th of Eighth month,
the whole company of cabin passengers who were to cross the ocean in the Pigou,
together with various friends, dined at Plough Court, with Rebecca Jones`'s noble host,
Joseph Gurney Bevan, after which they went to Gravesend.

In some of her notes, made during the voyage and given in the next chapter,
will be found interesting references to her embarkation,
and to her final parting with the friends who attended her on ship board:
especially with her beloved Christiana Hustler; who was her first companion in England,
and the last to part from her,
after the performance of every service which the most tender affection could suggest;
and respecting whom Rebecca Jones repeatedly said in after years,
"`I have loved her as my own soul.`" As a parting token, Christiana Hustler,
when about to be let down in a chair to the boat,
took off her cloak and threw it upon her friend--when they immediately separated,
with emotions too deep for utterance, beyond the last farewell.

"`But was it such?
It was!
Where they are gone Adieus and farewells are a sound unknown.`"
