== Chapter VI.

[.chapter-subtitle--blurb]
1788.

[.chapter-synopsis]
* Return Voyage
* Letters written on Board the Pigou
* Lands at Salem
* Attends Woodbury Meeting, and proceeds to Philadelphia.

Went on board the Pigou, the 13th of Eighth month, 1788, at Gravesend,
about 7 o`'clock in the evening of the 4th day of the week,
accompanied by Joseph G. and Mary Bevan, George and Sarah Dillwyn,
my dear companion Christiana Hustler, Mary Crowley, Thomas Crowley, John Townsend, Jr.,
Richard Phillips, Anthony Wilson Birkbeck, Thomas Jefferies, etc.
Had a comfortable season at the Inn previous to leaving Gravesend;
and with the above Friends on board the ship, before my fellow passengers came,
we witnessed Divine goodness renewed to us.
About 11 o`'clock came William Dillwyn and wife, and divers other Friends.
+++[+++Here follows a list of all on board, commencing with the captain, William Sutton.]

Passengers in the Cabin.--William Poyntnell, George Russell, Rebecca Jones, Ann Warder,
her son John and daughter Mary, her servant, Sarah Stewart, and Susanna Dillwyn.

Stayed up till late, in order to adjust some things in my berth, (which,
through the Captain`'s kindness, proved a large airy one,) and,
as the wind was fair to carry us into the Downs, I got some sleep, but was sea sick,
yet I felt easy in mind, and, parting with my dear companion, Christiana Hustler,
who had been to me part of the hundred fold promised in the gospel, and my kind landlord,
Joseph Gurney Bevan, and his wife, and many others,
under the precious influence of the Father`'s love,
the sense thereof remained so very comfortable, that I was enriched thereby.

14th. Our pilot left us about 2 o`'clock, and the wind being contrary, we lay at anchor,
so that by the tossing of the ship I w,:s at times unfit for any thing but lying in bed.
Yet a boat coming to us from Deal, I wrote to my friends Jospeh Gurney and Mary Bevan,
to dear L. H., and to my beloved Christiana Hustler.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
On board the Pigou, 16th of 8t.h month, 1788, 1 o`'clock, P. M.--

[.salutation]
My dearly beloved companion, Christiana Hustler,

Here sitting on a hencoop,
after a day and night`'s sickness, by reason of head wind,
which keeps us at anchor just in sight of Deal,
not knowing how long we may have to wait for a
change of wind to carry us through the Downs,
and thinking that, may be, some Friend may come and give a peep at us,
from Dover or elsewhere--though hardly able to hold up my head,
I have got ink and paper in one hand, holding it on my knee,
while I salute my precious Chrissy once more before we lose sight of the British shore.
Feeling the same holy cementing influence,
by which we have been in the Master`'s appointment united,
and now under the same direction separated, I dare not distrust His continued mercy,
nor that He will fail His poor handmaidens.
My heart and eyes now fill in thus saluting thee.
Mayest thou be helped to think of thy poor Rebecca Jones, now in her narrowed inclosure,
and pray for her preservation in all things.
Thou knowest I am a poor creature.
I suppose thou art now on thy way some miles from London, and dear M. C. with thee.
I hope she will feel satisfaction in waiting upon a meek, humble disciple,
who has long accompanied a lesser disciple with whom
she has united in the great Master`'s service,
and that she will be instructed by thy company and conversation,
even as I often have been.
I am so sick, that I cannot say all to thee and thy family that is in my heart.
Let it suffice, my precious, that I feel thy spirit near, as in the days that are past,
and what is more to be prized,
I feel the Ancient of Days is near to us both now we are separated.
Lift up thine head in hope, that thy condescension to the poor servant,
out of still greater love to thy blessed Master, is accepted by Him,
who did by His in-speaking voice say to my soul,
when it was lifted up within me on thine and my account at Walden, "`Lo!
I am with you always, even unto the end of the world.`"

Look towards me with sisterly kindness,
for my whole heart salutes thee in the bonds of the gospel,
believing the pure union will not be dissolved by time or distance.
I am thy ever loving, grateful, though very sick companion.

[.signed-section-signature]
Rebecca Jones

--

17th. Being the First of the week,
I told my female companions that I should think
it fight for us to hold a meeting in the cabin,
to which they agreed, and leave being had of the Captain,
I mentioned our intention to two men who were our fellow passengers, viz:
William Poyntnell, of Philadelphia, and George Russell, of Birmingham, withal saying,
if they were free to give us their company it would be acceptable, but if not,
we should take no exceptions.
Accordingly, the whole of our company in the cabin, also our captain and chief mate,
sat down together in the cabin,
where condescending goodness was pleased to own
our first little meeting in our narrow inclosure.
My mouth was also opened in a short testimony to his goodness,
believing we were under his Providential care.
The men before alluded; were very, serious,
and they were very civil and attentive to us on the voyage.

18th, Second day.
About 3 o`'clock hoisted anchor, and got through the Downs well.
What a mercy that my mind should be kept in perfect peace,
while the poor body is so distressed with sickness,
and the ship in a continual agitation and tossing.
Oh! my soul, trust thou in the Lord,
who by his in-speaking voice said on my going on board this ship, "`Fear not,
for I am with thee, be not dismayed, for I am thy God.`"

20th, Fourth day.
Made but little way.
Passed Beachy Head.
I was led to consider that having, according to the best of my ability,
waited for and desired the Lord`'s blessed direction as to the time when,
and the ship in which to embark home,
and this detention in the channel being in the ordering of that gracious
Being to whose requirings I had endeavoured to stand faithful,
was comforted in believing that I was under his mercy and protection,
so that I was hereby kept from murmuring,
gave up the idea of reaching the Yearly Meeting, and resigned my whole body,
soul and spirit, to him who knows best what is best for his poor creatures.

21st, Fifth day.
Awoke this morning in a quiet, sweet frame of mind,
feeling my dear friends and late companions Christiana Hustler
and L. Hawkesworth brought near to my spirit in the precious
bond of love and light in which we had often rejoiced together.
Also, found the cord of love very attractive to my beloved companion Hannah Cathrall,
which was like a brook by the way, even in this my watery peregrination.
Oh thou gracious Being,
be pleased for thy great name`'s sake to keep us near to thyself and to each other,
to the end of our time in this world, and whatever thou mayest see meet to deprive me of,
or suffer me to be tried with, take not thy Holy Spirit and blessed protection from me,
I humbly pray thee.

22d, Sixth day.
Had a very sleepless, tossing night,
so that I could scarce keep from falling out of my bed, by reason of a high head wind,
occasioning a great swell in the sea.
My mind was, however,
mercifully preserved in a steady reliance upon that gracious Being who of
old time was declared to be "`mightier than the noise of many waters.`"
I did not rise till near noon; was much tried with sea sickness,
so that I was not able to move from my chair but with assistance, which Captain Sutton,
John Cillett the mate, and our men in the cabin were all very willing to render.
A+++.+++ Warder also was in a like situation.
Before I arose, my dear Christiana Hustler came sweetly into view,
believing her to be nearly if not quite arrived at her own habitation, where,
amongst her amiable family, she will be joyfully received;
where I have at different times spent some weeks,
and where I shall often be the subject of their agreeable conversation,
and have the sympathy and prayers of the Friends with whom (next to
my beloved Hannah Cathrall) I have been most nearly connected in the
Father`'s love of any in this world.
May I be sensible enough of the favour, and may the aforesaid two dear friends, and,
next to them, my beloved fellow labourer Sarah Grubb, and my other dear, kind,
and benevolent companion, L. Hawkesworth, with my own soul,
be kept under the precious influence of that love and
life which covered our spirits when together,
and united us in travels, visiting the churches,
and in baptisms and sufferings for the Lord`'s sake;
that nothing may be allowed to separate us from one another in him who went with us,
a light and leader, our "`Ebenezer,`" for ever worthy to be followed and obeyed.
My mind is more exercised on account of dear L. H., whom I left in London,
in a declining state of health, and under much discouragement.

Yes, it was a near thing to take my last leave of one who
had been so tender and hind beyond expression to me,
from the time of my first landing, and rendered me many kind offices to the last.
When I took from her the parting embrace, and our tears mingled together, she said,
"`My dear, may the Lord`'s blessing go with thee, yes,
he will be with thee unto the end.`"
This was the day before I left London, when she gave me a small parcel,
with directions that I should not open it till I got home, on which was written,
"`A few specimens for the hand of dear Rebecca Jones.`"
Oh, it was like rending a part of my life to part with her,
and with my ever dear Christiana Hustler,
which last was oil board the Pigou to which she accompanied me, stayed near three hours,
helped make my bed and adjust divers things in my berth,
and was the last woman let down into the boat, by a chair fixed on ropes.
We wept upon each others neck, and repeatedly embraced;
our feelings were too exquisite to admit of a single word more than the
mutual "`farewell,`" and then with difficulty we separated from each other,
she to the boat for Gravesend, and I, to my berth to feel my bereaved situation,
which was more than supplied by the incomes of the Lord`'s goodness,
whose loving kindness is better than all other enjoyments, yea, than even life itself.
And my hope was revived in that salvation,
which has been so richly manifested towards me and the worthy
companion with whom Almighty Goodness has been pleased to favour me,
in all our travels through England, Ireland, Scotland and Wales.
To him, therefore, the Holy Shepherd of Israel, be all praise and glory given,
now and for ever, saith my soul.

23d. Seventh-day.
Had a comfortable night`'s sleep, for which I was thankful;
also that I was not so sick through the day as usual when at sea,
so that I spent great part of it on deck, the weather being fine,
though the wind was still against us, we not having got farther than Plymouth,
which seemed trying both to our captain (who is of a kind,
quiet disposition,) and to our fellow passengers.
But I dare not murmur,
believing that the mighty Ruler of the seas knows best
what is best for all his depending children.
This night I laid down my head in a degree of faith that the Lord was near to us.

24th. First-day.
Rose humble and grateful, for the favour of another quiet night, and,
feeling more able than usual, got into the cabin to breakfast.
At 10 o`'clock we sat down and held our little meeting as before,
under some sense of the Lord`'s presence with us,
and I had to mention some things concerning inward and spiritual worship,
which seemed to gain both the attention and assent of the captain and men passengers.
When the meeting broke up they withdrew, and then we settled again, (viz: A. Warder,
S+++.+++ Dillwyn,
the children and myself,) and a word of counsel and encouragement was given me,
for my dear female fellow passengers, which had an affecting tendency.

25th. Second-day.
Was quite peaceful in mind.
Our whole cabin company behaved with great civility.
Susanna Dillwyn very sweet and agreeable in her behaviour and conversation,
so that the detention for want of fair wind,
was not so trying as it would otherwise have been.
About tea time a fair wind gradually sprung up.
We got quite out of the channel, and clear of Scilly Islands.

26th. Third-day.
The wind continuing fair,
we got on at the rate of about nine knots an hour till towards evening,
when the rain ceased and the wind grew slack again.
Retired to bed under a sense of divine care, and,
having awoke in the morning with "`Whom have I in Heaven but thee,
or in all the earth in comparison with thee,`" it was a good day to me.
Blessed be the Lord!

27th. Fourth-day.
Awoke this morning less sick, but did not rise till after breakfast,
finding myself less able to move about than in my former voyage,
by reason of stiffness in my joints, etc.
The weather was exceedingly fine, so that my fellow passengers were upon deck,
which I also tried, but finding it too cold, I descended,
and employed my time in working, reading, and writing.
By staying below, I had a time of deep inward retirement before the Lord,
and enjoyed the unity of His blessed Spirit,
both with my near and dear friends whom I have left in England,
and increasingly so with my dear friends in America, whom,
if it be the Lord`'s blessed will,
I hope to see in a few weeks in my beloved native city of Philadelphia.
Which comfort (though I anticipate it with pleasure) will, I expect,
be greatly alloyed by the many painful circumstances that will occur;
for the hearing of which my mind had for some time been preparing,
by a continual sense of sadness, in apprehension, that does attend,
both by day and by night.
Oh, thou most merciful Being, who, for purposes best known to thyself,
hast been pleased to enlist me under thy holy banner of love and life, and hast,
by a further display of thine Almighty Power,
measurably enabled me to fight against the power of darkness;
against spiritual wickedness in high places; grant, I humbly pray thee,
for the sake of thy blessed cause, which I have endeavoured, through holy help from thee,
to advocate,
(not for any desert in me,) that nothing present or to come may be allowed
to separate me from the sensible and comfortable enjoyment of thy love,
shed abroad in my heart, nor from the precious unity of the spirit, in the bond of peace,
with thy little gathered flock and family the world over.

30th. Seventh-day.
Spent the day chiefly in reading.
I have often admired not only the kindness of our captain, but the quiet, civil,
and sober conduct of the whole crew,
among whom scarcely an indecent or unsavoury word was heard.
This, with the harmony subsisting in the cabin, the singing of a sweet bird in it,
and the innocent prattle of A. Warder`'s children, made time pass on more agreeably.
But my being less sick than in the former voyage,
and (what is the greatest of all favours) believing
heavenly protection and goodness were near us,
often clothed my mind with a sense of gratitude to the great Preserver of men, who is,
both by sea and land, to his depending children, a God near at hand,
a present help in every needful time, to whom be high and endless praises given,
because he is good, and his mercy endureth forever.

31st. First day.--At ten o`'clock held our little meeting, composed as before: in which,
feeling the spirit of prayer and supplication, my heart was poured forth to the Almighty,
that He might be pleased to bless our little company,
and to reveal Himself to every soul on board the ship,
and favour them with the knowledge of His pure will,
giving them hearts to fear Him and to love His holy law written therein.
After meeting, A. Warder, S. Dillwyn,
and myself by turns read many chapters in the Scriptures.
"`Oh that men would praise the Lord for His goodness,
and for his wonderful works to the children of men!`"

Ninth month 3rd. Fourth day.--Awoke this morning refreshed in body,
and thankful for the favour of a quiet night.
A gale suddenly came on, and heavy rain, with squalls, which, though fair,
tossed us much about: during which my mind was inwardly retired to the Lord,
in humble secret intercession,
that for His mercies`' sake and the sake of His blessed cause,
He would be pleased to look down upon us, and preserve us over the mighty deep:
when the assurance which was given me on my first coming on
board with my dear friends to feel after right direction,
was comfortably renewed, viz: "`Fear not for I am with thee,
be not dismayed for I am thy God.`"
In about an hour and a half the sun broke out,
and the wind becoming more steady we went on pleasantly.
Oh, the unspeakable loving kindness of the great I Am!
My mind this day was variously, and, I hope, not unprofitably engaged,
taking a retrospective view of my steppings, in the arduous service in which,
during the four years I have been separated from my native land, I have been steadily,
and, I trust, honestly engaged.
The consideration whereof, deeply bowed and contrited my mind,
and qualified me afresh to admire,
worship and adore that Power which has been experienced by me, a poor weak instrument;
and excited a renewal of my confidence in the continued mercy of the Almighty,
also raising living desires and fervent breathings and cries to Him, that I may be,
through the blessed assistance of His Holy Spirit,
enabled to walk with care and circumspection, on my return to my own country, and,
to the end of this painful pilgrimage,
be clothed with the garments of unfeigned humility, gratitude and fear.

And now,
under a precious sense of the Lord having in
early life plucked me as a brand out of the fire,
made me sensible of the multitude of my sins,
which for His mercies`' sake He was pleased to forgive,
and to blot them out as a thick cloud; by the spirit of deep and sore judgment,
and the spirit of burning,
to cleanse and purify my soul from the pollution of sin and iniquity,
and for purposes best known to Himself, to commission me, a poor unworthy creature,
to testify to His goodness and the sufficiency of His mighty power:
has been with me hitherto by sea and by land, provided me with suitable companions,
and every necessary and agreeable accommodation, and favoured me, from time to time,
with fresh and sure direction as I have waited
for it;--my soul is prostrate in great awfulness.
I acknowledge myself worse than "`an unprofitable servant`"--
and can set up my "`Ebenezer`" and helped me!`"
Blessed be Thy great name, for ever and ever, Amen! say, with gratitude and thanksgiving,
"`Hitherto thou, Lord, hast

And now, in the prospect of my returning to my beloved friends and native country,
without a home of my own, nor certainty of what place will be allotted me,
there is at times the source of great anxiety.
Yet I dare not distrust the care of the heavenly Shepherd, who both knows what I want,
and how to supply with all needful things.
If Thou, Lord, then wilt but condescend to be with me in the way that I go,
give me bread to eat, and raiment to put on,
and bring me again to my own country in peace; Thou shalt indeed be my God, and I will,
according to the measure of light and strength afforded, for ever serve and follow Thee.

[verse]
____
"`My life, if Thou preserve my life,
Thy sacrifice shall be,
And death, if death shall be my doom,
Shall join my soul to Thee!`"
____

The remembrance of an honest, upright-hearted remnant in the island of Great Britain,
to whom I have been made near in the fellowship of the Gospel of Peace,
and in the frequent soul-solacing seasons which we have enjoyed
together under the covering of Divine Love;--the travail of soul I
have witnessed on account of the dearly beloved youth,
in the sense of the heavenly visitation being powerfully renewed to them,
(divers of whom are preparing for service in the Lord`'s house);--and
the strong desire that I feel on account of my three fellow labourers,
George Dillwyn, J. Pemberton, and James Thornton,
whom I have left behind in the same field in which I have faithfully
laboured;--have fully taken possession of my thoughts this morning.
And a humble hope has been renewed, that some good fruits, in the Lord`'s time,
will be produced by all the labours and pains that have been immediately and
instrumentally bestowed upon these parts of the vineyard,
and that the honest labourers will have their reward,
and the gain and praise of all be given to the great heavenly Workman,
who is now and for ever worthy.

All the night it was at times squally, so that we were, I trust,
properly thoughtful in the cabin:
my mind being often lifted up in secret intercession to the Most High.

5th. Sixth day.--I went upon deck and stayed about two hours:
when our captain told me we had now made full one-third of our passage.
May not only my poor soul, but all the souls in this ship,
be fully sensible of the favour conferred,
and endeavour to walk more worthy of its continuance.
When on deck I took an opportunity with S. L.,
a young woman who is passenger in the steerage, where there is no other female,
and where amongst four men passengers,
and all the skip`'s crew (making twenty-two,) she is very much exposed.
I endeavoured to strengthen her mind in behaving
with such a degree of propriety among them,
that nothing may be unpleasantly remembered by her after she has gone on shore--
advising her that when she cannot becomingly and consistently converse with them,
she had better remain quite silent if she cannot withdraw.
I also inquired into her stock of clothing, with a view of supplying her if necessary.
With all which she appeared much affected.
I felt much for her, as she appears to be a sober girl, and in a tried situation.
May she be preserved!

7th. First day.--Rose early this morning; much refreshed, and thankful therefor.
At 10 o`'clock we held our little meeting, and, though it was a low season,
yet I was glad that I was able to say that the Lord was near to us,
and that we kept up our meeting every First day,
having the company of the captain and all the cabin passengers.
After meeting the captain went up to take his observations--we stayed below, and each,
by turns, read in the Bible.

11th. Fifth day.--My mind was comforted in believing that in the right and
best time we shall be favoured to reach my native land and beloved city,
when, though I expect to meet with renewed and manifold exercises and trials,
oh! that I may be kept in the hour of temptation, by the favour of my gracious Shepherd,
that so nothing may be able to pluck me out of His holy hand in time and in eternity!
Amen!

12th. Sixth day.--Rose this morning quiet and thankful in spirit,
breathing for preservation to my Almighty Helper and sure Friend.
A dead calm.

13th. Seventh day.--Awoke refreshed and humbly thankful,
but found my berth more uncomfortably warm than I had known it before.
On deck found the awning up--all hands on deck--some mending the sails,
some repairing the rigging,
and the chief mate preparing hooks and lines for fishing off Newfoundland Banks,
towards which we seem approaching.

14th. First day.--On consulting together, we concluded,
that with such incessant motion and tossing of the ship,
we could not sit safely and hold our meeting at the usual time, so postponed it,
in hope that we might sit down in the afternoon.
But the same difficulty attending, and A. W. and myself being poorly,
we were engaged reading most of the day.
S+++.+++ Dillwyn, while A. W. lay down, came and read to me.
I was pleased and helped with her innocent company.

15th. Second day.--Was sea-sick in the morning, as were my two female companions.
But having a fair wind, which carried us without much motion five and six knots,
we all grew better, and were able after breakfast to do a little sewing and writing.
Walked awhile on deck, but soon retired to the cabin, rinding the sun very hot.
I was awaked in the night by a heavy gale, with lightning,
which prevented my getting any more sleep; yet, as I lay,
my mind was inwardly retired to the Lord,
and breathing to Him for preservation every way, for His blessed cause`'s sake.

16th, Third day.
The wind increased--had several heavy squalls, and the sea ran very high,
so that the waves seemed like mountains rolling around us.
One wave, while A. Warder was on deck, was so near breaking over the ship,
that they were quite alarmed, and we esteemed it a great mercy that it did not reach us.
This gave the ship such a lee lurch that a large table, with our breakfast tray,
which was on it, and S. Dillwyn`'s box of minerals, which was under it,
all well cleated and lashed, broke loose, and was driven with violence to leeward,
where A. W.`'s dear little children had just been sitting,
and removed but a few minutes before it happened.
What a signal display of Divine care over innocent children!
When their mother came down, and saw and heard the circumstance,
she sat down and wept in humble thankfulness--and well she might--for
had they been in the way they must have been hurt badly,
if not killed.
Our captain informed us that we had passed the banks of Newfoundland,
and that he believed we were crossing the Gulf Stream.
During the course of this day, I was often led to examine myself,
whether in any sort I was the cause of this distress;
to look back upon my former travels, and to consider whether it might not be,
in some sort, preparatory to my arrival in my native country,
and to keep me watchful and careful while on board.
And, under all these considerations,
as I sat holding both with hands and feet to keep on my seat,
those comfortable expressions arose in my mind, "`Behold, God is my salvation,
I will trust and not be afraid, for the Lord Jehovah is my strength and my song.
He also is become my salvation:
therefore with joy shall ye draw water together out of the wells of salvation.`"
This, with the enriching assurance given me on my first coming on board of the ship,
"`Fear not,`" etc.,
together with the prospect which my dear friends Christiana Hustler and M.
Prior had at the same time--that we should get safe to our desired port--
tended to settle my poor mind in humble trust in Almighty goodness and mercy,
through the present, and whatever trials might in future attend.
Went to bed about 11 o`'clock, and was enabled to commit myself, body, soul and spirit,
into the hands of my "`faithful Creator,`" desiring his gracious protection for myself,
my dear friends in the cabin, and all the ship`'s company.
After which I soon fell asleep, had a good and comfortable night,
and awoke refreshed every way.
Blessed be my sure and unfailing Friend!

17th. Fourth-day.--I retired under some apprehension of a tossing night,
and slept till about 2 o`'clock, when I was awakened by great noise on deck,
and the three usual stamps of the men, calling "`All hands ahoy!--reef and topsails!`"
The wind being high and the ship labouring hard, this at first a little alarmed me,
and raised the humble prayer,
"`Lord have mercy on us!`"--when presently A. Warder came to my berth,
and sat by me two hours: in which time it rained heavily, with some lightning,
and the wind, in squalls, very high.
After another heavy squall the ship was put about, by which I was turned to leeward,
and was in less danger of pitching out of my bed.

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Esther Tuke.

[.signed-section-context-open]
On board the Pigou, on the great Atlantic, Latitude 40° 42`' 9th mo. 20th, 1788.

[.salutation]
Dearly beloved Friend,

Being often favoured, whilst floating on the mighty ocean,
to feel near unity of spirit with such dear friends in the
land whence (with my natural "`life for a prey,`" and a degree
of that peace which exceeds description,) I have now escaped,
with whom I have enjoyed sweet fellowship, and who are still near to my best life;
and thou, among others, having been pleasantly brought into view this morning,
I have sat down in order to give thee some account of thy poor feeble

I have given up all thought of reaching our Yearly Meeting,
so that if more is given me than I expect,
I shall give it a place among the many marvellous displays of Almighty goodness,
of which I have been a thankful, grateful witness.
But not this mighty deep, nor length of time, will, I trust,
ever erase from my remembrance an honest, faithful-hearted remnant,
a tender visited seed, a highly favoured people in that nation,
whom everlasting loving kindness has so signally cared for,
and at whose hands He is now looking for fruits adequate to his abundant care over them.
May the upright, affectionate, disinterested labours of the poor servants,
who have been sent amongst you, be in some degree promotive of this great end.
May the hands of the faithful among you be made strong to the
removing of every obstruction in the way of advancement.

May the dear youth who have been enamoured with the
brightness of the Divine power arising in their hearts,
"`keep humbly their solemn feasts, and faithfully perform all their vows.`"
May the "`north,`" through the softening influence of holy animating love and life,
be prevailed upon during the day of offered mercy to "`give up,`" and
the "`south,`" in a state of faithful obedience to the Divine will,
"`keep nothing back,`" is my humble prayer.
Then will your light go forth with encouraging brightness,
and the clothing of Divine salvation, on all the different classes in the family,
be conspicuously clear "`as a lamp that burneth.`"
Nor shall I be, I humbly hope,
deprived of the enjoyment of the bond of christian fellowship with
those who meet at the approaching annual solemnity in Philadelphia,
and at your Quarterly one held about the same time; but,
by the great and good Remembrancer, may I, in this my watery peregrination,
be raised as an epistle in your hearts,
and feel the efficacy of the fervent prayer of the righteous,
with whom I pray that I may now and forever be united.
I know I am an "`unprofitable servant,`" and yet can appeal to
the great Master in a degree of childlike simplicity,
that I have endeavoured to do that which was required as a duty at my hands:
and for the encouragement of other poor weaklings I have to testify
to the goodness of that hand which "`put forth:`" it has gone before,
made crooked things straight, and cast up a way,
even when and where to my view there has appeared no way.
So that now, though I am going to my own country and people, with no spoil taken,
yet am I returning with that acknowledgment made by the
early publishers of the gospel in reply to the query,
"`Lacked ye anything?`"
and can, with reverence of soul, say, "`Nothing, Lord.`"
I know that it will be still necessary for me to feel after
and dwell deeply with the heavenly gift on my return;
and oh, that under its blessed influence, I may be favoured with patience, lest,
for want of this profitable virtue, I should lose the things which have,
through holy help, been wrought,
and so miss of that consummate reward with which we are
not fully entrusted until the end of the painful race.
May this, dear Esther,
be thine and my gladdening experience when this short fight of affliction is over,
is my fervent prayer.

I shall be much disappointed if I do not frequently
hear from the houses of York and Holdgate.
To all of them is my dear love, and to my other dear friends in your country, as if named.
Thou knowest who they are: they are too numerous for insertion,
but not too many "`in order one by one to rise`" in my affectionate remembrance.
When you do write, mention how "`the lilies flourish,
and the pomegranates bud and blossom,`" and whether "`the
garden of nuts`" has furnished any more ripe fruits for the
King`'s table--with whatever is interesting to thee:
for it will be so to me, because we are (dare I presume) soldiers in the same army,
consequently entitled to hear of the several movements therein.

[.signed-section-signature]
Rebecca Jones

--

20th. Seventh-day.
Awoke afreshed, and with an easy mind.
But soon found, on getting up, that the wind blew fresh and quite contrary,
which was a fresh trial of faith and patience, when,
on considering.a little what should be the cause,
and why we have such an unfavourable prospect,
my mind was silenced from enquiry by a secret persuasion that it was all for the best,
though not for the present seen to be so.
Whereupon I again resigned to the thought of not reaching our Yearly Meeting, which,
had it been, or should it be the Lord`'s blessed will we should do,
would have been a comfortable circumstance.
But as I have often been fully convinced that our Almighty Shepherd
knows best what is best for his poor sheep and dependent children,
may his holy will be done in all things, saith my soul.
Our captain spoke a sloop this morning from Grenada, out 15 days, bound for Newfoundland,
and upon comparing the ship`'s reckoning,
it appeared that we were not by three degrees as forward in our passage as we expected.
This was unpleasing tidings to our company,
who had fixed the 7th of next month for gating to Philadelphia.
In the evening the wind lowered, and it again grew calm,
so that we retired early and soon went to sleep, trusting in the Lord.

21st. First-day.
About 5 o`'clock, the wind for the first time was on our stern.
It blew fresh, and rained heavily.
I rose early, in hopes that we might hold our little meeting,
and once more in the cabin together wait upon the Lord.
But the wind so increased that we kept our seats with some difficulty.
The dead lights were all put in, and candles brought into the cabin.
I, however, sat down in quiet about an hour, with my mind inwardly turned to the Lord,
who is worthy to be waited upon at all times.
The ship was the whole day in a perpetual roll, from side to side,
and a day of the most heavy and steady wind, our captain said, that he ever remembered,
so that the poor men were wet to the skin, and we could not stir at all out of the cabin.
We went, through the day, at the rate of 8 and 9 knots.
The great motion, rolling, and thumping of the waves was alarming at first,
but our Captain told us we were crossing the gulf stream,
so that if the wind had taken us ahead instead of astern,
or had it been quite calm as before, we should have been in a much worse situation.
This, and his further information that this wind in
Delaware bay would inevitably run us ashore,
humbled and deeply affected my mind, leading to the renewed inquiry,
"`What shall I render to the Lord,`" etc.
A+++.+++ W., having dreamed of her husband,
pleased herself with the thoughts of getting to Philadelphia in a few days more.
But having always found that I fared best when I
was most fully resigned to the Lord`'s will,
and having been favoured to come to this desirable attainment,
I did not dare to flatter myself with so agreeable a circumstance,
though fully persuaded that all things are possible with our gracious Creator.

22d. Second-day.
Our company seemed highly pleased with hopes of soon getting on shore; but,
on divers accounts, my rejoicing is in fear.
Oh, thou great Preserver of men,
condescend to fortify my mind with a reverent
trust in thy goodness and providential care,
and clothe me with humility and watchfulness on my first meeting my beloved friends,
and to the end of my time in this uncertain, fallacious and wicked world,
for thy mercies sake.

In the evening the wind shifted, and by 2 o`'clock the wind again shifted,
and blew a heavy gale directly against us.
Captain Sutton ordered all sails made snug, and lay too about twelve hours,
during all which time the dead lights were in, and the ship laboured so much,
and the sea was so high, that it made the most awful and gloomy appearance I ever beheld.
Dear A. W., and I, not being able to keep safely in bed, sat up till day light.
W+++.+++ P., being much alarmed, sat up with us all night.^
footnote:[Sarah R. Grubb, writing to Rebecca Jones, says--"`If I am not mistaken,
since thy leaving London,
thou hast had thy portion of awful sensations on the mighty waters.
My heart was so almost continually with thee, and so affected sometimes,
as to amount to painful conflict,
so that I could hardly conclude that it originated merely in those natural,
affectionate feelings, which a separation from one so beloved occasioned.`"]

23d. Third-day.
The wind much lowered, though the sea ran very high,
and it was dangerous moving from our seats.
I stayed in my berth, and, as in the night,
my mind was often engaged in humble intercession to the Almighty for our preservation,
and that he would be pleased, for His great name`'s sake, to have mercy upon us,
and influence our Captain with wisdom, and his men with strength in so perilous a time.
About 8 o`'clock, P. M., it was nearly calm,
and I was told that it was likely to remain so.

24th. Fourth-day.
After a good night`'s rest, I arose refreshed and thankful for the favour.
This day makes just six weeks since we came on board.
Light wind, but fair.
About 11 o`'clock we espied a sail, which proved to be a schooner--Juno--from New York,
laden with corn, and bound to Teneriffe.
She had been out about a week--had met with a gale of wind last First day,
when we were going before it at the rate of ten knots.
Had been under the necessity of throwing overboard 60 bushels,
and cutting in two her long boat,
one-half of which she threw overboard to lighten the ship.
Her captain desired Capt.
Sutton to take a letter for him, and, to bring it to us,
they immediately launched a small skiff with one of their hands, who, with two oars,
made his way very dexterously over the waves, and brought the letter,
returning safe again.
This was a pleasing circumstance to all our company,
who were with one consent gathered to the larboard side to look at fellow men floating,
like ourselves, on the watery element.
But as I stood looking on, and considering how we had been preserved in that very gale,
by which they had been distressed, my heart overflowed with gratitude and thanksgiving,
and mine eyes with tears,
and the more so when I adverted to what might have been
the consequence had we been in the bay at the time.
The sense of the Lord`'s protecting goodness extorted
from me this expression in the hearing of all,
"`Thanks be to Him who is forever worthy.`"
This sense continued sweetly the covering of my spirit through the day.
We made some preparation towards going on shore
when it shall please the Lord so to favour us,
which, when granted, will, I trust, sink me in the deepest gratitude, fear,
obedience and love to mine Almighty Helper and Protector, all the days of my life.
In the afternoon we were easy and pleasant on deck,
and in the evening came down to writing.
My heart felt peaceful and humble, which, I pray,
may be continued to me till landing on my native shore, and forever, Amen!
Through the night I had not a wink of sleep, yet my mind was tranquil and easy.

+++[+++For several days they were subjected to storms and consequent discomfort.]

Ninth month 28th. First day.--After a good night,
awoke with the remembrance of its being the time of our Yearly Meeting in Philadelphia,
where many worthy and dear friends are collected, and where,
had it been the Lord`'s good pleasure, I should have rejoiced among them.
But as it is so ordered,
I desire to be content in the enjoyment of that blessed fellowship of
spirit which cannot be quenched by the mighty waters between us,
and is the solid rejoicing of the heavenly minded family everywhere.
After breakfast, I informed the captain of a wish which I felt,
that if he had no objection,
an invitation might be given to the steerage passengers and to the sailors,
to sit with us at our little meeting.
He readily consented, and sent the steward to give them all notice.
We sat down at ten o`'clock.
Some of those invited, came and behaved soberly,
and my heart was enlarged in gospel affection towards them, and under the influence,
I trust, of the spirit of true prayer, was enabled to intercede for our preservation,
and for redemption from all iniquity.
Oh, that the request may, in adorable mercy,
be granted! was much affected in the meeting, and appeared solid and thoughtful after it.
Our captain sounded and found no bottom.

29th,
Second day.--May I be favoured with patience and
resignation in the present trying allotment,
thus detained from assembling with my dear friends in Philadelphia,
at their Yearly Meeting, because All-perfect wisdom knows best what is best for us.

30th, Third day.--Still an unfavourable prospect.
Our captain found bottom in fifty fathoms water; on hearing which,
divers of our company appeared very much elated, even to an ecstasy;
but my mind felt very much restricted from appearing outwardly to rejoice.
Soon after, the wind sprang up so fair, that we ran into five fathoms.
Upon this, our captain, who is prudently careful, stood to the southward.
The wind increased to a strong breeze from the N. E., so that towards evening,
we lightened sail, and about six o`'clock, spied land ahead at about six leagues distance.
All things then laid snug, we lay at the mercy of the wind and waves,
which were under the direction of the Most High, till morning.

10th month 1st, Fourth day.--Wind still the same, and the sea running very high.
About eleven o`'clock we espied a pilot coming towards us, who proved to be Harry Fisher,
a skillful man.
On his coming on board, our captain and all the ship`'s company seemed relieved.
He told me that he was last week in Philadelphia,
and that I was expected to the great meeting there.
He brought us a few apples and peaches, which S. D. and I particularly enjoyed.
Oh, how my soul worshipped in deepest prostration, and craved to be kept little, low,
and humble in going amongst my dear friends, under the present mercy,
which is indeed marvellous in my eyes.
Blessed and forever magnified, be the name of the Most High,
from this time forth and forever more!

Last night I was comforted in remembering that last Sixth day night,
which was a time of sore exercise in a storm of wind, thunder, and rain,
I was assured this would be the last storm;
and that we should safely get to Philadelphia before the Yearly Meeting ended.
So that I had no creaturely fears to contend with.
But my health feels too much impaired to promise myself much enjoyment for a time,
and having no fixed home to go to, feels discouraging;
but I dare no more distrust Divine care, now nor forever.

Rain came on in the evening, and it was very dark,
so that we were truly glad we had got to a safe anchorage within the cape,
as the wind blew fresh against us.--Dropped anchor at eight o`'clock, below Bombayhook,
and in the cabin afterwards our captain and pilot spent the rest of the evening with us,
the latter giving some accounts of Philadelphia.

2nd, Fifth day.--A head wind,
our ship could get no farther than within five miles of Salem,
and being assured that unless the wind changed, we could not get up till first day,
and being desirous of reaching the Yearly Meeting before it ended,
I concluded to go with our company on shore.
So our kind captain ordered the ship`'s yawl to be launched, and sent four of his men,
who, with the pilot,
(after the latter had taken a respectful leave of all on board,) took us on shore,
to the house of a Friend named Clement Hall,
who took us in his wagon to John Redman`'s in Salem, where we lodged,
and found the family all very kind.

On Sixth day, the 3rd instant, Rebecca Jones notes--"`We rose early,
and two wagons having been provided, having Emmor Baily and Elgar Brown for drivers,
we got on well and safely to Woodbury,
just as Friends were going to their week-day meeting;
whereupon I felt a draught on my mind to meet with them,
and left my companions to their liberty.
They not being inclined to go, I went alone.`"

Our pilgrims, halting at Woodbury, noticed a few Friends going to meeting,
and anxious as they all were to reach Philadelphia,
Rebecca Jones could not feel at liberty to pass the first
meeting of Friends after her arrival without attending it.
Her companions left a vehicle and driver for her, and proceeded.
Owing to the attendance at Yearly Meeting,
the number of Friends assembled was of course small,
and she was only recognized by one person present, Margery, wife of Samuel Mickle.
Having relieved her mind, and after sitting a short time, feeling easy to do so,
she informed Friends that she wished to attend
the closing sittings of the Yearly Meeting,
and desired that the meeting might not be disturbed by her quietly withdrawing.
The Friend already referred to, followed her out.
Her carriage soon overtook the one containing her friends, and, saluting them,
she passed on before.
They crossed the Delaware in company,
no time having been lost by her attending Woodbury Meeting.

"`We arrived,`" she writes to S. Alexander, "`on the 3rd,
just two days before the close of our Yearly Meeting,
(after a passage of seven weeks from Gravesend,
but only thirty-six days from land to land,) so that I had the
satisfaction of seeing my dear friends generally from the country,
and truly our joy was mutual:
and in the assembly of the Lord`'s people to give Him thanks for his mercies.`"
