== Chapter VII.

[.chapter-subtitle--blurb]
1788 to 1790.

[.chapter-synopsis]
* Attends closing sittings of Yearly Meeting and returns her certificates
* Diary letter to J. P.
* Letter from Sarah Grubb
* Present from pupils of Clonmell school
* Parts with Hannah Cathrall and takes lodgings with James Goram
* Letter to J. Williams
* Visits the Yearly Meetings on Long Island and on Rhode Island
* Letter to Dr. Cathrall and to other Friends
* Sickness
* Journey to Maryland.

"`On the first sight of my native city,`" she says, "`my heart was so affected,
that I seemed near fainting; but, after relieving myself with many tears,
I felt deeply humble and thankful,
under a sense of marvellous preservation every way experienced;
but more particularly so on the mighty deep, as the Harmony, Capt.
Willett, who sailed with us from the Downs,
came into port about the same time in a wrecked condition,
from a storm which we were favoured only to feel in part.
We landed at the old ferry,`" (this was about one o'clock,) "`from whence,
taking leave of my company, I went to Johns Hopkins', where I dined,
and dismissed a letter to H. Pemberton to let her and
my Hannah Cathrall know that I was landed.
Samuel Emlen came in his chaise and sent me in it to Richard Humphreys,
where my Hannah Cathrall met me.
We were deeply affected on seeing each other,
and together blessed the Lord for his abundant goodness and •mercy.
I was shocked in looking at her,
and thought her every way more altered than any other person.
At three o'clock went to the Women's Meeting,
where a general solemnity soon overspread us,
and I was engaged publicly to return thanks to my great and gracious Helper, Preserver,
and Everlasting Friend, the Lord Almighty, who is worthy to be served, feared and obeyed,
for ever and ever.`"

Her arrival was known to few Friends till her appearance at the afternoon sitting.
Soon after the meeting was settled, Rebecca appeared impressively in supplication,
and the remarkable covering of solemnity was long remembered by those who were present.
"`Before the meeting broke up,`" she notes, "`I went up to John Pemberton's,
to avoid being stopped by the crowd of Friends who were glad to see me again,
and in the evening several came to see me.
I was much fatigued with this day's labour, but got some quiet good sleep.`"

Next morning in the Select meeting,
she returned the certificate granted to her by that meeting in the 3rd month, 1784,
with endorsements from the Yearly Meeting held in London in the years 1787 and 1788,
and from the Half Year's Meeting for Ireland, Fifth month 9th, 1786.

Her diary thus proceeds:

4th, Seventh day.--Rose refreshed,
and with a mind deeply bowed in gratitude to the great Preserver of men.
At eight o'clock went to the last sitting of the Select Yearly Meeting,
where I returned my certificate which they had given me,
and also delivered those given me from Ireland and England.
And though I had not much to say for myself,
I was enabled openly to declare that not only was the
promise made to the early disciples when sent forth,
mercifully fulfilled to me in every part, so that I could say on my return as they did,
that I had lacked nothing,
but that the reward of Peace was more than adequate to all the endeavour I
had been enabled to use for the promotion of the one great and good cause.
After this meeting concluded, I went to that for business among Women Friends,
which was large and solid.
Dined with many friends at John Pemberton's, and before bed time,
had an opportunity of seeing many of my dear friends who called there.

5th, First day.--This being the first First day after my landing,
I chose to go to the Bank Meeting, that being the one to which I had always belonged.
I attended both morning and afternoon, and sat in silence.
Dined at Henry Drinker's; drank tea at William Compton's, and having much pain,
did not go to the evening meeting;
but after sitting an hour at Daniel Drinker's with G. and H. Churchman,
went to my lodgings.

6th, Second day.--Was at the second day Morning Meeting; dined at James Pemberton's,
and there, and in the evening, finished divers letters begun on board the Pigou,
and sent them by +++_______+++ the going to Cork.

Various letters commenced on ship-board, were finished on her arrival.
In a postscript to one addressed to John Pemberton, she says, (10th mo.,
6th,) "`I can't help wishing it may be thy lot to return in the Pigou,
when it shall please our great Master to set thee at liberty--till when,
may patience and holy stability be thy covering and girdle,
that so thou mayest return with a clear evidence
of having "`finished the work`" assigned thee,
and in the right time.
Which I can say with humble thankfulness, is in some degree my experience,
though I am sensible I have-not been fitted for great things,
and am "`an unprofitable servant.`"
The reward of Peace is more than adequate to the
exercise I have undergone for the sake thereof.
So, dear friend,
be encouraged through all to look to that good hand which has hitherto supported us,
and is able to keep us to the end.
I am now quietly sealed in thy front parlour, with thy beloved wife,
who is about as well as common, and received me very kindly into her house,
though she appeared not a little disappointed at not receiving thee
also--yet she bears it with becoming patience and resignation.

We arrived at Philadelphia last Sixth day, the 3rd inst.,
timely for the afternoon meeting for business.
Next morning at the Select Meeting had my certificates read,
and at the concluding Women's Meeting afterwards.
So that I was at three meetings with my beloved friends, who were all, with me,
mutually glad in seeing each other,
under the humbling sense of the Lord's goodness in many ways extended to me, a poor,
unworthy creature.
An eminent display whereof we witnessed in a hard gale,
a few days before we reached the land; which, though it did our ship no damage,
was very heavy upon the Harmony, Captain Willitt, who left the Downs with us,
and arrived in a shattered condition soon after us--having
carried away her mizzen mast and quarter galleries,
washed away her caboose, with two men in it, several of her live stock, etc.,
and lay four hours on her beam ends, without her dead lights in.
Which, when I heard, oh,
how my heart was humbled within me in a grateful sense of Divine preservation over us,
for which I hope to be forever thankful.

I see great alteration in people and things,
many look more than four and a half years older,
and my dear Hannah Cathrall is one of the number.
We have not yet got a house, but hope we shall soon.
But thy dear wife wishes us to be content with this.

May the God and Father of all our mercies, who has thus favoured me to return in peace,
be with thee in the way in which thou goest, and in the appointed season,
restore thee to thy beloved wife and near connexions.`"

After her return to her native land,
she accepted the hospitality of her friend Hannah Pemberton, until Tenth month 22d, when,
having obtained a house, she, with her former companion II. Cathrall, removed to it.
We find her domestic accounts and business records interspersed with memoranda,
from which occasional extracts will be given.

"`Tenth month 9th. 5th day.
At meeting.--Warner Mifflin, and Ann Emlen, married.
More in the simplicity, and with less parade than I have ever seen on the like occasion.
I fear they will not have many followers in this city.

12th.--First day.
Was at Bank Meeting twice, and in the evening at Market-street.

13th.--Second day morning meeting.
Samuel Smith opened a concern for England

27th.--Second day.
At the select meeting, dined and drank tea at John Warder's, where also dined Capt.
Sutton, George Russell, W. Poyntell,
and Susanna Dillwyn--all my fellow passengers in the Pigou.

28th.--Third day.
Monthly meeting at Bank.
Rebecca Jones appeared.
I gave in certificates to both meetings.
S+++.+++ Harrison appeared in supplication.
Samuel Emlen came into women's meeting.

11th mo.
1st.--Seventh day.
At two meetings in the great meeting house, in both silent.

3rd.--Second day.
Our Quarterly Meeting.
Delivered my certificates in both men's and women's meeting.
Adjourned at 5 o'clock, a good time.

9th--First day.
At Bank meeting, twice in silence.
In the evening kneeled.

10th--Second day.
Was at the select meeting.
Mentioned the black people's having leave of
their masters in a morning for attending meeting.

Eleventh month 14th,
she was comforted beyond expression by the reception of
a letter from her beloved Sarah R. Grubb,
the following extract from which will meet a response
in the hearts of those of our readers who,
being amid the conflicts of time, preserved in "`the bond of peace,`" feel that they,
like these precious sisters,
"`stand together in the unity,`"--having in themselves the
evidence that they have "`passed from death unto life.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Sarah Grubb to Rebecca Jones.

"`I do indeed join thee in the grateful tribute of
thanksgiving and praise to our ever-living Helper,
who, blessed be his name has done, and will, my soul is renewedly and firmly persuaded,
continue to do for thee, great things; wherein his own eternal name will be exalted,
and thy acceptance with him stand for ever.
Ah my precious friend, these truly are great things;
not works of righteousness which the creature itself can do--
no--his mercy and his truth are marvellous in our eyes,
and that effectual washing,
that fiery baptism of spirit which prepares instruments to convert sinners unto Him.
I congratulate thee, as my spirit did in my last,
which was written before I heard of thy safe arrival in Philadelphia,
from whence thy rejoicing salutation of 10th month 6th.
reached my hands a little before meeting time last Fifth-day.
It almost unfitted me for going,
because my mind had been exceedingly tried about thee for a little while,
both by night and day, towards the latter part of thy passage.
But this meeting proved a salutary opportunity for me,
under the assistance then afforded, to centre down to the Root which bears the branches,
whose direction is as various as every point in the
compass;--and yet they have all the same origin,
where they meet together, and flourish through the efficacy of the one liberal source.
There is a prospect now, that the salutation of my heart will be wafted to thee,
and meet thy acceptance, in the renewings of that love which,
I humbly trust no vicissitudes or future dispensations will ever be suffered to diminish.

I value it as a gift from the hand which is full of blessings,
and wish to honour it as such.
The affectionate part in us fabricates a strong resemblance of gospel fellowship, but,
had we no stronger cement than it affords, we could not stand together in the unity,
through many of those storms and combats with which the Christian traveller meets,
from within and from without.

--

Our readers are supposed to be aware that the writer of the foregoing letter,
had removed to Ireland, and taken charge of Clonmell school.
The following inscription was worked with
beautiful neatness on a sampler by the scholars,
under her inspection,
and sent to America as a memento of their close friendship and gospel unity.
Rebecca Jones had it framed and hung in her chamber.
Rebecca Jones having spent about a week in Clonmell school,
the pupils had become much attached to her,
so that the offering was one of affection on their part,
and not merely as made to their teacher's friend.

[.centered.emphasized]
Clonmell-School
to Rebecca Jones of Philadelphia;
On her return from a long and arduous visit to the Churches of the
People called Quakers in Europe; sendeth greeting.
After a frequent and sympathetic conflict
with this her endeared friend,
and instructive companion;
SARAH R. GRUBB, rejoices in HOPE,
that by the POWER OF OMNIPOTENCE,
and in the Covenant Of Love And Life,
She is now restored to the bosom of the Church
in AMERICA,
and to the precious society of
her most beloved and constant friend,
in the Tribulation And Consolation of True Gospel,
Hannah Cathhall.
Eleventh Month, 1788.

Shortly after this, in an open conference between Rebecca Jones and Hannah Cathrall,
as regarded their future mode of living,
the latter announced the insufficiency of her
health for resuming the charge of the school.
etc. "`My mind,`" says Rebecca Jones, "`was much sunk in the prospect of our separation,
and my not being able to work for my living as I used to do,
nor having enough to bear me out without labour.
So we retired for the night with heavy hearts.`"
We may anticipate, by noting that Rebecca Jones took lodgings with James Goram, No. 3,
Watkins' Alley, on the 1st of the ensuing Fourth month,
Hannah Cathrall removing to the house of her brother.
Rebecca Jones, under that date,
notes her desire for preservation under the close trial of being thus separated.
I rested poorly, yet was quiet in spirit, believing that I had no hand in our separation,
and desiring patiently to wait the event.`"

Writing 11 mo.
18th. to Samuel Alexander of Needham,
having related the incidents of the voyage and
their preservation from damage in the storm,
in which the Harmony which "`could not have been
far distant,`" was shattered and almost wrecked,
she says,

[.embedded-content-document.letter]
--

"`For this extraordinary circumstance together with the innumerable, unmerited mercies,
in which I have been made a sharer, both in your country and my own,
my soul worships in the deepest prostration before the throne of boundless goodness;
adopts the humble inquiry, 'What shall I render unto thee, oh Lord, for all thy benefits?
and desires to walk in gratitude and humility all the days of my life.`"

--

After giving information on various points, she thus concludes:--

[.embedded-content-document.letter]
--

"`Thy kind epistle which reached me before I embarked,
I esteem as a fresh proof of thy brotherly remembrance,
and that thou art desirous of pursuing the one thing needful.
May thy labour be crowned with success,
and thy resignation to the despicable epithet of fool,
introduce thee worthily among those wise who are 'to shine as the
brightness of the firmament,' and as 'the stars for ever and ever.'
When I look towards the honest hearted living members in your land,
I rejoice in feeling the current of precious unity flow even from this,
and am still fervently engaged in spirit for the restoration of all the dispersed,
scattered, and captivated children through the various tribes in our Israel.
May the Most High hasten the day in which this great and good work will be effected,
to the praise of his own adorable Name and Power, and that without instrumental help.

It was a great thing to part with my beloved
friend and precious companion Christiana Hustler,
yet it was made more easy than we could have expected,--and so have other
hard things thro' the virtue of that love and life without the sensible
enjoyment of which there is nothing worth desiring to live for.
Farewell dear Samuel--"`hold fast that which
thou hast received--let no man take thy crown.`"

[.signed-section-closing]
I remain in christian sympathy thy assured friend,

[.signed-section-signature]
Rebecca Jones

--

In accordance with the noble determination of Saul of Tarsus
that he would "`make his ministry without charge,`" and "`with
his own hands minister to his wants,`"--our friend,
not finding it expedient to resume her school, commenced a shop,
which was kept in her parlor, (the articles being deposited in closets and drawers,
so as to be entirely out of sight.) She imported gloves, shawls, kerchiefs,
some articles of dry goods and trimmings, and various articles,
costly and of superior quality,
many of which could be obtained no where else in Philadelphia.
In the selection and importation,
she received the willing aid of her friends on both sides of the Atlantic;
and thus her business which was never allowed to
interfere with her religious duties and engagements,
was made to her the means of "`providing things honest in the sight of all men.`"

"`Twelfth month 27th. Sixth day.--Was at Philadelphia Monthly Meeting.
Job Scott and Daniel Aldrich had the chief service.
It was a good meeting.
At its close I had a short opportunity with Warner Mifflin,
and desired him to let patience have its perfect work.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Joseph Williams.

[.signed-section-context-open]
Philadelphia, 12th mo. 16th, 1788.

[.salutation]
Dear friend Joseph Williams,

Before this reaches thee, thou wilt have heard,
that through the tender mercies of the Most High, I am safely arrived in this,
my native city, which I was favoured to reach two days before our Yearly Meeting ended;
thereby having an opportunity of seeing my beloved
friends from different parts of the country.
They received me cordially,
and we were helped together to set up our "`Ebenezer`" with
thanksgiving and praise to our Almighty Helper and everlasting Friend.
My beloved companion, Hannah Cathrall, was almost overset on my approach to her.
I was favoured with a good passage on the whole; a very kind captain, and good company.
But what calls for the deepest thankfulness, is,
that even whilst we were much tossed with a tempest, about a week before we arrived,
my mind was preserved under the calming influences of soul-solacing peace,
under which I met my dear friends, and, through boundless mercy,
it has been the covering of my spirit by day and by night since.

And now, my care and desire is,
that I may be preserved from lavishing away the precious sheaf,
which has been vouchsafed me as a reward: a reward far beyond my deserts,
and more than adequate to my feeble endeavours in your land and in Great Britain.
Moreover,
my heart breathes after an increase of ability to "`walk humbly with my God,`" who
hath so marvellously condescended to my weak and low estate,
having been "`a very present help in every needful time,`" and
having accepted the dedication of my heart in my late services,
and who is now and forever worthy to receive the praise of His own works!
May the honest and disinterested labours of love, which have, of later time,
been bestowed by the Lord's messengers upon the different parts of his vineyard,
be productive of fruits, answerable to His gracious design!
May the living members of the church in your land increase in the holy increase of God!
May the careless and lukewarm professors be quickened and made alive in the daytime,
and repent and do their first works!
May the camp be cleansed from the accursed thing! that so
Israel may no more turn backward in the day of battle.
And mayest thou, dear Joseph, improve thy time and thy talent faithfully,
and with my poor soul, witness the answer of "`well done!`" at last.

I feel near sympathy with thee, whilst writing;
I know the humble diffidence of thy spirit; but be honest, be vigilant, I beseech thee;
then, the greater the cross, the weightier will thy crown be!
Salute, for me, dear E. Pike; I think of her as a mother in Israel,
worthy of double honour.
Let thy dear wife and children know I remember them with a heart replenished with love,
and fervent desire for their welfare in time and in eternity.

Do write to me soon,
and let me hear if the "`lilies grow and the pomegranates flourish "`in your nation.

I am entering into a larger field of sorrow and exercise in my own land, where,
though I find a faithful, upright-hearted number,
there are multitudes of a different description amongst the professors of truth,
some of whom, will assuredly be "`corrected by their own folly,
and be rep.roved by their own backslidings,`" sooner or later.

In reviewing the past, with Friends in your Island and Great Britain,
I feel the precious unity of the one everlasting covenant, in which I can in spirit,
though absent in body, salute, sympathize,
and rejoice with the true born children of our Heavenly Father, and say,
"`Fear not little flock, it is your Father's good pleasure to give you the Kingdom!`"
Amongst these thou my dear friend,
with thy faithful partner hast often been brought nearly into view,
feeling tenderly solicitous for your welfare in every way; and I trust,
though finally separated in this state of existence, we may, through boundless goodness,
meet at last where we can unite in the ceaseless song,
"`Great and marvellous are thy works, Lord God Almighty; just and true are thy ways,
thou King of Saints!`"   month, 1789, to their Friends in Philadelphia.
"`We rejoice,`" say they, "`in the extension of Divine favour vouchsafed to you,
our beloved sisters, in your annual assembly, and that our endeared friend Rebecca Jones,
with other gospel messengers who lately visited this land,
were conducted in the aboundings of peace, to their native country.
We are now favoured with the company of our beloved friends John Pemberton,
James Thornton, and George Dillwyn, with his valuable wife,
whose services and gospel labours have been truly acceptable to Friends and others,
where their lot has been cast.`"

[.signed-section-closing]
Thy assured, obliged, and affectionate friend,

[.signed-section-signature]
Rebecca Jones

--

"`1789. Fifth month 4th.--Was at our Quarterly Meeting,
where I mentioned an exercise for going to the
Yearly Meeting of Flushing and Rhode Island.
Friends gave leave for mentioning my concern to the Monthly Meeting.`"

On the 2nd of Sixth month, a certificate was granted by her Monthly Meeting,
signed by sixty-four Friends, in conformity with the prospect above noted.
Fifth month 20th, she writes:

"`About this time, I suppose Friends will be going towards the Yearly Meeting of London,
where, if I had the wings of a dove, I should be tempted to join the solemn assembly;
but as this is altogether impossible, in body, I am thankful in believing,
I shall in spirit be wafted there, to join the intercession with a faithful number,
to the Father of mercies, for His continued help, preservation,
and guidance in the weighty service of that meeting.`"

It is interesting in this connection,
to observe the reciprocation of feeling on the part of her transatlantic
sisters in the assembly to which her mind was thus turned,
as expressed in the Epistle addressed by the Women's Yearly Meeting of London, Sixth

Of this journey to New England,
neither her notes nor her numerous letters (two excepted) have been discovered.
Hence we can give the reader no connected details.
An endorsement upon her certificate signed on behalf of New England Yearly Meeting,
states that "`her Gospel labours, exemplary conduct and conversation,
have been much to our edification and comfort.`"
And a very full minute, of similar purport,
records her attendance at Sandwich Quarterly Meeting at Nantucket,
the 30th of Sixth and 1st of 7th months.
She had a meeting with a few Indians and Negroes on this Island, forty-five in number,
also one with six hundred young females,
and one with about four hundred young men and lads.
"`Our Friends,`" she says, "`were very industrious in spreading the notice,
and seemed well satisfied with them all.
I have great cause to be humbly thankful that I
gave up to the pointings of the great Master,
and that he was pleased for his own Name's sake, to vouchsafe a portion of best help.`"

This service appears for a long time to have been in anticipation,
as in a letter to Christiana Hustler, dated 5th of Tenth month, she says:
"`I have taken part of a house in a valuable family, where I am well contented,
but I do not expect to be allowed long to enjoy my pleasing retirement.
New England and Long Island rise full in my view.
Thou mayst recollect that I used to tell thee those parts were yet to be visited.
Well, I serve a gracious Master, who provided all things necessary in my late journey,
and I still trust in his providential care.`"

Third month, 1789.--Her young friend, Dr. Isaac Cathrall,
(to whose skill and remarkable assiduity and tender attention, she was,
some years subsequently, as will be seen, indebted, under Providence,
for her life,) being about to sail for the East Indies,
she addressed to him an affectionate epistle.
"`I wish to suggest by these few lines,`" she writes,
"`the warm and tender desire of my heart for thee, that, as thou hast hitherto been,
through the tender care of the Most High (which is the arm of
salvation) preserved from falling into temptation to gross evils;
and as thou art no stranger to the principle of Divine Grace,
thou mayst now stand upon thy guard,
and acquit thyself with such a degree of uprightness and conformity to thy profession,
to the sincere desire of thy well wishing friends,
and to thy own solid and better judgment, as that, on a serious retrospection,
thy own heart may not reproach thee as long as thou livest.
Be especially careful of thy company both on shipboard and on shore.
If thou beginnest right, it will be more easy for thee to keep so.
To find thou dost so will give me real satisfaction.
My heart loves thee, and my best wishes attend thee.
Mayst thou be favoured with a desire after retirement--(on first days
thou mayst find it in thy berth) and know that power near thee which
is greater than 'the noise of many waters,
yea than the mighty waves of the sea.'
Believe me when I say that if thou seekest the Lord he will be found of thee,
and will do more for thee than all things without him.`"

8th Mo. 25th.--She attended Quarterly Meeting at Haddonfield, and was largely engaged,
exhorting friends to beat their plowshares into swords,
and their pruning hooks into spears,
and to make war in righteousness:--thus seeking to arouse those who,
in the spirit of this world,
were taking their rest and laying up their treasure in sublunary things.
D+++.+++ Offley followed in supplication.

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Joseph Williams.

[.signed-section-context-open]
Philadelphia, 10th mo. 21st, 1783.

[.salutation]
Beloved Joseph,

Yesterday about noon arrived our dear Mary Ridgway and Jane Watson,
after an easy passage without a storm, though longer than some others,
(I think ten weeks.) I had been, by a hurt received from a fall, and an epidemic cold,
confined for seventeen days mostly to my chamber,
and had that morning just made out to crawl to our meeting,
but on hearing of their arrival,
and John Pemberton (at whose house they quarter)
sending his carriage for my dear H. Cathrall and self,
we went to see them, and truly our joy and greeting were mutual.
They were calm, cheerful, and very well.
O, that they may be as kindly cared for, every way,
and helped along as I was in your land, is my desire.
I often think you have set us in America a good and noble example,
in your provision for such poor pilgrims,
and I do hope Friends here will not be deficient
towards these worthy handmaids of the Lord.
 
Thy last, dated 9th of Seventh month, hints the low, deserted state of thy mind,
like a pelican in the wilderness, and striving to wear thy sackcloth covered, etc.
Yet I felt, whilst reading thy bemoanings, my mind meet thee in thy tried steppings,
and hail thee as a fellow probationer, with affectionate breathings,
that our confidence may not be allowed to fail us in Him who hath said,
"`I will not fail thee nor forsake thee.`"
I do not marvel that thou and I are more deeply plunged than some others;
we are jealous of ourselves, and it is good to be so; and we are, I humbly hope,
jealous of that honour, which at times we desire may be advanced over all,
however we may be thereby abased and humbled.
Ah, dear Joseph,
there is plenty of company when the triumphant song of hosannah is uttered! but alas,
very few, who are willing to visit and abide at Calvary!
Flesh and blood does not like it, it wants a more pleasant way.
But let us keep near to him in whom we have believed,
and be willing to visit his precious seed, though it be in prison and to death;
for to those who herein are faithful, the promise is,
"`I will give thee a crown of life.`"

And still, Ireland is visited and revisited by the servants!
May the labour bestowed be productive of some profitable increase.
I am glad my dear friend Samuel Smith is thy guest; I hope he will experience,
as I did under thy roof, that the Son of Peace dwells there;
thou mayest interrogate him as thou pleasest respecting me and my present situation.
I note thy sundry intelligence,
and am obliged by thy continuing willing to give me a
hint of matters and things interesting amongst you.

Our dear friends who have lately visited your land are, I believe, all well,
except W. Matthews, who seems in declining health.
Samuel Emlen moving about as usual,
and sometimes grumbling at himself for coming home so soon.

--

In the 12th month of this year she was severely ill.
During her confinement the precious reward of true peace was mercifully continued to her,
and her mind was stayed upon her never failing Friend,
with desires for increased purification and fitness for the exchange
of the "`earthly house`" for the building "`not made with hands,
eternal in the heavens.

To Christiana Hustler she writes:

[.embedded-content-document.]
--

[.signed-section-context-open]
3rd mo. 10th, 1790.

"`We have had the company of the female Hibernians`" (Mary Ridgway
and Jane Watson)  "`in this city since their arrival (except a small
excursion for a few days to Burlington).
They labour faithfully and zealously for our good, in public, and privately.
They have finished an arduous and acceptable visit to the families of
the middle Monthly Meeting (about three hundred) and are nearly thro'
a like visit to Pine street Monthly Meeting.
This they expect to complete by the general
spring meeting (the last 1st day in this Month).
Their services among us, (particularly in our large first day evening meetings,
composed often of more than two thousand people) are very acceptable.

Dear Mary Ridgeway is a great example as well as a great minister,
and her faithful armour bearer Jane Watson keeps her close company.
May this renewed visitation be blessed to us!
May we rightly prize it and improve under it! else there is room to fear,
that it will be an addition to that weight of condemnation
which too many of the professors of Truth are already under.
These dear women have been divers times at my habitation,
and appear pleased with my visits to them,
which are as frequent as my health and engagements will allow,
they being near half a mile from my house.
Mary Ridgeway wishes to have me with them at least every first day.

I was last Second day in our Morning Meeting,
so dipped into sympathy with our two brethren now in England,
especially our dear George Dillwyn, that I told friends how I felt,
and that I did believe the language of their spirits was unto us, as formerly uttered,
"`Brethren pray for us, that the word of the Lord may have free course, and be glorified,
even as it is with you.`"
It had a baptizing effect on the meeting, and several, after it broke up,
said they had also been in like manner in company with those two friends.

John Pemberton is now with Samuel Emlen and others waiting on
Congress on behalf of the oppressed Africans.`"

--

In a letter to Mary, wife of Joseph Gurney Bevan, dated 4th month 15th,
after referring to her frequent indisposition during the late winter,
which frequently confined her for weeks at a time, she says,

[.embedded-content-document.letter]
--

"`I am often with you in spirit,
and strong in desire that you may encourage each other to do all the good you can,
while your faculties are continued bright and lively.
I feel mine on the decay,
and am secretly comforted in believing that I was divinely helped to discharge,
in the right time, the very heavy debt to your land, under which I had long waded.
To the Lord alone be the praise!
His time, dear M., is the only right time.
I frequently see thy cousin Samuel Powell Griffitts.
He is in good repute here, both as a physician and as a member of our society.`"

--

A visit which she paid to Maryland, of which no particulars are preserved,
is believed to have been performed in the Spring or early in the summer of this year.
The summer was chiefly filled up in attending meetings near Philadelphia,
as she found herself drawn forth,
different friends alternately taking her in their carriages.
At one of these meetings, on the 30th of 0th month,
she was largely engaged in enforcing the duty of
frequently reading the holy Scriptures in families,
and also of supplying poor friends with them.
This concern, she was, on suitable occasions,
engaged to impress upon her fellow probationers.
And surely those who believe in the Divine origin of the sacred volume,
and that its contents are given by "`the only wise God,`" for our instruction,
should be careful not to be deterred by indolence, by the cares of life,
or by any subtle presentation of the Tempter,
from a diligent and frequent perusal thereof.

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Esther Tuke.

[.signed-section-context-open]
Philadelphia., 10th month 30th, 1790.

My soul bows in deep abasement,
in consideration of the little fruit as yet brought forth in my vineyard,
in return to that gracious Being, who, to magnify his own praise,
hath done marvellously for me, a poor, unworthy creature.
My bodily health is confirmed; he hath made ample provision for this tabernacle; yea,
he hath condescended to make up every deficiency for his mercies' sake!
What then shall, or can I render.
Nothing have I of my own!
AH is of and from his own inexhaustible source,
who hath determined that "`no flesh shall glory in his presence.`"

Thou hast, doubtless, heard that I have shaken my hands from the gain of school-keeping;
though, by the way, I may tell thee, my present gain is not so delicious,
nor do I feel so every way complete, as when my uncontrolled sway was love,
among my numerous tribe of varied dispositions, circumstances, and ages.
But as I cannot be ground over again,
nor renew my youthful sight and other requisites for the service,
I endeavour after contentment in my present situation,
and hope that I shall wind up my accounts as to worldly matters,
without even the shadow of bankruptcy.
If my more solemn and important account prove as fairly stated and as fully clear,
then shall I, in an advancing awful hour, have nothing to do but to die.
Oh, may this, my dear friend, be our joyous condition at last,
(whatever shall attend us in time,) is the breathing cry of my whole heart!
On this ground, I feel thy spirit meets me.
I rejoice in thy company, even now, 3000 miles distant.
Hail, fellow traveller, then!
We are near the journey's end;
and we have nothing to rely upon but boundless mercy and unfailing goodness,
of which we have often been made joint partakers,
and which will never be withheld from us,
if we patiently continue under the holy harness,
and cleave steadfastly to the law and to the testimony.

I am glad thou wast enabled to attend your late Yearly Meeting.
I thought I felt thee and our dear Christiana Hustler, there,
united like old standard bearers; for, I may tell thee, that however desirous I might be,
at many other times, to keep mind and body together,
I am not able to do it at the time of your general assembly.
My spirit wings its flight--I see you collectively in
Devonshire House--I run to Plough Court,
Bartholomew Close, Duke street, Lamb's Conduit street, and other places,--and salute,
first one, and then another, of those whom I dearly love.
I am refreshed with these ideal excursions,
and have a sentiment of my own about such visits, which is strengthened by thy saying,
that I was "`much in thy remembrance.`"
Thy account of that meeting is very descriptive of our late annual solemnity, where,
to our comfort, we had dear Mary Ridgway and Jane Watson.
These brave soldiers are greatly beloved and honoured,
both by the Master and by their fellow servants.
Soon after the meeting, they went, with dear J. Pemberton, Samuel Emlen, etc.,
into Maryland.

I am pleased to find that you are likely to have
a more convenient house for the Yearly Meeting,
and that thou lovest my faithful brother, S. Smith.
I hope he will visit both my nest at York and at Underclifle,
else I shall call him to account.
I shall not be sorry to hear that he is obliged to visit the sprouting seed in Scotland.
Tell him so with my love.

Dear George and Sarah Dillwyn, and Robert and Sarah Grubb, wrote to me from Amsterdam,
to my comfort.
Surely their sheaves will be very large, for they do not "`sow sparingly.`"

--
