== Chapter VIII.

[.chapter-subtitle--blurb]
1791.

[.chapter-synopsis]
* Decease of John Hustler and of Sarah R. Grubb.
* Letters
* Visits Long Island, etc.

1st Mo. 27th, 1791.
She thus notices the decease of John Hustler.--"`I feel near
sympathy with my dear companion and sweet-fellow traveller,
Christiana Hustler, on hearing of the departure of her beloved husband.
He was a man of great talents, much tender sensibility, and of a noble spirit.
He will be missed by the public--by the church--and by his own amiable family.
We pass away, one after another, experiencing the verity of the Divine decree,
'`they shall perish`'. May we who are suffered to survive a little longer,
obtain through our love and obedience to the Holy Shepherd, that enriching confidence,
which will enable us to say, But Thou Remainest.`'
And when we pass through "`the valley of the shadow of
death,`" if favoured to feel Him near us,
we shall '`fear no evil;`' but having been guided by His counsel,
be received into His glory.`"

On the same day, in a letter to Christiana Hustler, after expression of tender sympathy,
she adds--"`Thou knowest, my dear C. from whence soul sustaining help is derived.
Thou hast often been permitted to draw near to it,
and thou art fully acquainted with its healing virtue.
Mayst thou now, under this close conflict, for thy own sake,
and for the sake of thy dear children and other relatives,
and for an example to others when introduced into the like path of sorrow,
be strengthened to say, thy will be done--yea,

[verse]
____
"`Confess aloud with holy Job, and say
The Lord, who gave, hath right to take away.`"
____

A letter from George Dillwyn to Rebecca Jones mentioning the
decease (in her 35th year) of Sarah Grubb,
(with whom he had been associated in recent religious service on the continent) says,

[.embedded-content-document.letter]
--

"`She closed the relation which she gave to the Quarterly Meeting of Cork,
of our mission to the Continent,
with a declaration of her belief that although we had done little,
The Lord was doing much in the Earth:
concluding with these words '`My day`'s work seems almost accomplished,
and I shall adopt this language of scripture, Return unto thy rest, oh my soul,
for the Lord hath dealt bountifully with thee.`'
The last expressions she was heard to utter (a little
before her exit) were those of her dear Lord,
My peace I leave with you.
Thus fell a valiant in the church militant,
whose endowments and dedication are equalled by few of the present generation,
and to whose memory, I believe, as general a tribute of tears has been paid,
as to any person with whom I was ever acquainted.`"

--

In writing to Christiana Hustler, 4Mo. 29th, 1791,
after referring to the peaceful exit of John Hustler, she thus continues:

[.embedded-content-document.letter]
--

"`I trust your minds are, with mine, fully persuaded, that with him, the end,
being happy, crowned all.
And this must be cause of thanksgiving and praise to our great and gracious helper, who,
I perceive, hath also been with you, and remains to be thy comfort and support,
my ever dear friend.

"`I have from many kind friends received accounts of the last illness and
death of our dear Sarah R. Grubb who also hath left this vale of tears for
an eternal resting place in the abodes of peace and felicity.
May the loss be supplied to the militant church
through the faithfulness of her visible members,
is my fervent prayer!

"`I expect divers friends are preparing to go up to the General Assembly,
which I pray may be a '`feast of holy convocation`'--I hope thou
wilt be strengthened to take thy proper stand there,
and '`do valiantly`'--I am also preparing for a journey to Long island,
where I expect to meet our noble warriors Mary Ridgway and Jane Watson.
Dear Samuel Emlen is now with them at Rah way--and John Pemberton and wife
also talk of getting to the Yearly Meeting to be held next month at Westbury.
Our ancient friend Robert Willis was interred about twelve days ago, and we have,
within a few months, been stripped by death of divers valuable friends,
both in city and country.
Thus we are all passing away, from time to an awful eternity.`"

--

In retrospect of the visit to Long Island, her prospect of which is above alluded to,
she notes, 11th Mo. 15th, "`Thro`' the continuance of the heavenly Shepherd`'s care,
I have been helped in the performance of some religious services on Long Island,
New York, etc. and had the company of our dear Rebecca Wright therein;
also to some meetings in New Jersey, etc.
I felt on my return the incomes of sweet peace,
for which I desire to continue thankful to the great Author of all good.`"
About the same date she says, "`I received a letter from dear Jane Watson from New York,
where she and dear Mary are engaged in the arduous service of cross ploughing the
field over which dear Rebecca Wright and I hastened last summer: i. e. visiting families.`"
In this journey Rebecca Jones attended the half Year`'s
Meeting and most of the meetings on Long Island,
and visited all the families of Friends in the city of New York.
Arriving at her home 6th month, 21st, she notes her attendance of Yearly, Monthly,
Preparative and nine particular meetings,
and having visited eighty families and travelled
three hundred and ten miles--"`in all which,
being mercifully supported, and sensible that I am still a poor weak creature,
my soul humbly worships,
and ascribes praise and thanksgiving to the Lord God and the Lamb,
now and forever worthy--Amen--Amen!`"

In her memoranda respecting New York Yearly Meeting, we note,
that on the 31st of 5th Mo., "`was a very favoured season, and, under a weighty exercise,
Friends we were named to visit the Quarterly Meetings,
and assist there in inspecting the necessities of the poor with respect to Bibles etc.`"
It appears that Rebecca Jones and Jane Watson
went into the men`'s meeting with this concern,
where it was readily agreed to,
and at a later sitting a committee of men was appointed
to join their sisters in this truly christian work.

10th month 14th, she notes--"`I hear that the Pigou, with George and Sarah Dillwyn,
and Samuel Smith on board, is in the river`"--and on the same day, she adds,
"`Soon after penning the above, our dear friends arrived.
They look well every way, being, I trust, sweet and peaceful in their spirits.
We met on the wharf; it was a joyously melting season,
and I waited on them to their respective lodgings.
Friends, generally, rejoiced to see them,
and I am truly thankful to the Father of mercies for this renewed favour,
vouchsafed to them and us.
Blessed be his worthy name now and forever.`"

George Dillwyn, in a letter to Joseph Gurney Bevan, thus refers to their landing,
and to their reception by Rebecca Jones, etc.
"`We landed in the midst of a considerable number of our relatives,
friends and acquaintance, who waited to receive us.
The first we discovered on the wharf, from the quarter deck, when we dropped anchor,
were James Pemberton and Rebecca Jones, just coming down.
Two or three days before, they had heard of the Pigou`'s being in the river;
and Rebecca was prompted by several, the day before we arrived,
to go down to the wharf and look out for us, but she felt no inclination then to comply,
but, (mark the woman!) on this day, dining at James Pemberton`'s,
the cloth was scarcely removed, when she exclaimed, '`Now Phebe,
let`'s get on our cloaks and bonnets,
and set off--we`'ll go from wharf to wharf till we meet them.`'
And a precious meeting it was!--for which the language of humble, silent praise rose,
through much tenderness of spirit, to the gracious Preserver of men,
the Leader forth and reward of his people.`"

This interesting scene is well described by herself in the following letters.

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Mary Bevan.

[.signed-section-context-open]
Philadelphia, 10th month 28th, 1791.

Our dear friends George and Sarah Dillwyn, and S. Smith,
landed in this city last 6th day (the 14th inst.,) about 3 o`'clock, P. M.,
amidst a great number of friends and others, on the wharf.
As it happened,
my friend Phebe Pemberton and self were the only females who knew of
the ship`'s coming to an anchor timely for going down to the wharf.
Thou can conceive better than I can express, how we all felt.
Tears of joy and thankfulness flowed plenteously.
I went with George and Sarah, first to their cousin James Smith`'s,
where was Susan Dillwyn.
We next proceeded to Sarah Dillwyn`'s sister, Margaret Morns`', where they dropped anchor,
and all their connections in the city soon collected.
The scene was sweetly affecting.
Lastly, I introduced them to the chamber of their disconsolate sister Moore,
who was composed on the occasion.
Here we all sat down in solemn silence,
und together were enabled to set up our Ebenezer in our own land,
sensible that`' the Lord had helped us.`'

So, after leaving them all together,
(this I thought right to do) I proceeded to the
house of my old acquaintance and neighbour,
S+++.+++ Smith, where, after a dish of tea, the like experience became ours.
I asked him divers questions,
the first of which (about friends,) was after my
kind friends Joseph Gurney and Mary Bevan,
of whom he gave me a comforting account.
The particular trials on their passage, thou wilt, I have no doubt, have from themselves.
They look particularly well,
and appear to be in possession of the reward for faithfulness.

--

11th month 3rd,
she writes to Esther Tuke,--"`We received our dear friends George and Sarah Dillwyn,
and S. Smith joyfully, on the 14th ultimo.
Taking J. and P. Pemberton with me, I hastened to the wharf,
against which the Pigou anchored,
and we embraced each other amidst a concourse of friends and others, in open daylight,
with tears of thankful rejoicing.

Among all my friends who were at your Yearly Meeting,
not one thought of sending me transcripts of the memorials read there,
concerning my late dear companion Sarah R. Grubb, but that prince of a man,
William Rotch.
They reached my hand in our Yearly Meeting week,
and I thought myself warranted in offering them
for reading to our Women`'s Yearly Meeting.
That meeting appointed a committee to inspect the contents,
(which should always be done if the subject be not specially addressed to
them) who reported their opinion that they might be usefully introduced;
so they were audibly and affectingly read by my Hannah Cathrall, who is clerk,
and had a seasoning tendering effect on the minds of
friends who were desired to "`go and do likewise.`"^
footnote:[On the reading, in this meeting, of the London epistle,
in which mention was made of the decease of Sarah Grubb,
Rebecca Jones stated that she had in possession the memorials alluded to,
and offered them, as mentioned above.]
I may say of a truth, "`She being dead,
yet speaketh;`" and scarce a day passes but I am in secret sweet
converse and communion of soul with her sanctified and exalted spirit.
Her memory will long live in my heart,
and amongst "`the just`" will be blessed to many in different lands,
who were acquainted with her pious, upright example of humble,
unreserved dedication of body, soul and spirit to the service of that God,
whom to obey and follow in all things, was her meat and drink--yea, her all in all,
unto the end.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Christiana Hustler.

[.signed-section-context-open]
11th month 15th, 1791.

Our friends Samuel Smith and George and Sarah Dillwyn, seem peacefully at home,
and are in good health.
George and Sarah stayed but a few days in the city,
and then went to their beloved retreat, Burlington.
Samuel Smith being my near neighbour, we have had divers pleasant interviews,
and much agreeable conversation about thee and thine,
and divers other dear friends in your nation,
and I have the satisfaction to find that he and I harmonize in
sentiment on most subjects that have occurred.
But what dost thou think of our Mary Bevan and Deborah Townsend`'s comparison?
They both, by letter, express their having found a striking similarity of voice,
manner and disposition in Samuel Smith to their friend Rebecca Jones.
At which I greatly wonder--however, it is no disparagement to the latter,
and I hope S. Smith`'s feelings will not be hurt thereby,
for he is a brother beloved of mine.

I have a choice letter from dear Esther Tuke.
She tells me they are compiling for the press our dear Sarah Grubb`'s notes, etc.,
and requests extracts from her letters to me, in making which, I propose, if I am spared,
engaging the evenings of this winter.
Oh, what a loss to the Church, is her removal!
Yet I believe it is in Wisdom and mercy unutterable.`"

--

Rebecca Jones, in compliance with the request conveyed by Esther Tuke,
made copious extracts from the numerous letters of Sarah Grubb to herself,
and to Hannah Cathrall,
(which are now before the compiler) but it seems that they were not
prepared in time to be used in the highly interesting and instructive
account which has long been valued as among those standard works,
without which the library of a Friend would be incomplete.

The following passages from a letter to Martha Routh, bring so vividly to remembrance,
the pleasant, familiar conversational vein of the subject of these memoirs,
that those who knew her may almost fancy her before them.
The "`English hat,`" a large beaver, with its broad brim,
and crown about half an inch in height, is well remembered by the compiler.
Such an appendage to the head of one of our female ministers, would, in this day,
make quite a sensation.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, 11th month 5th, 1791.

[.salutation]
Beloved friend, Martha Routh,

Thy kind letter, by my old friend and near neighbour,
Samuel Smith, has laid me under sufficient obligation,
without the addition of a new English hat.
Why, dear woman, I can never compensate for former marks of thy sisterly attention,
and thou must needs increase the debt!
So thou must look for thy gain from the right quarter,
and then thou wilt have thy reward, with suitable interest.

Leave off complimenting my tongue and hand, I entreat thee;
for (he first never came up to thine, and the latter, through failure of eyesight,
is in danger of forgetting its old cunning, I do assure thee.
And yet, with thanks to Him who is forever worthy, I may say,
that at times my heart is helped in the inditing way--
whether all the matter be good or only insipid,
I must leave--and in it, just now, a sisterly salutation springs, dear Martha to thee.
Having heard that thy worthy aunt, S, T., had entered into her rest,
oh that thou mayest be helped to come up in her footsteps,
and be divinely qualified to turn many to righteousness,
through the efficacy of the heavenly gift which thou hast received,
(let it turn whithersoever the great and all wise Giver shall see meet,) that,
in the evening of thy day, peace and comfort may be thy crown of rejoicing,
and thy glorious arrangement be forever among the stars.

I often feel like a soldier put upon half pay, and not at all fit for great exploits.
And yet, the little bread and water graciously dispensed from Royal bounty,
keep the soul alive in famine,
and cut off the occasion for distrust in that mercy and
goodness which have followed me all the days of my life.
May I but be counted worthy of this provision and succour unto
the end! is all a poor unworthy creature can or dare to ask;
and if these be in boundless mercy granted, I am, and shall be,
with the deprivation of every temporal good, thankfully content.

It comforts me to hear thee express thyself with so much genuine affection,
concerning that beloved disciple, our dear Christiana Hustler.
Her sorrows have oft been concealed under a meek and pleasant countenance,
and I trust the holy staff will be her support, now in her declining years

As to the accounts of your late Yearly Meeting,
except what I felt at the time it was held, I am left by all who have written me, saying,
as thou dost, that there is expectation of my being furnished "`by a more able hand.`"
But where is it?
And yet, thou hast done more than any other, for which I am thy obliged friend.

Thou wilt like to know that Mary Ridgway and Jane Watson are now at New York,
cross-plowing that field, after thy friends, Rebecca Wright and Rebecca Jones.
We visited all the families in that city, last Sixth month, together,
on our return from Long Island, where we had attended that Yearly Meeting,
and most of the meetings;
and we returned home in as hot a spell of weather as I ever remember.
But we were so brisk and lively that we walked about without our staves.

--

After relating an accident to R. Wright, who, she says,
"`after having driven safely so many thousands of miles in Europe and America,
separated from her dear Nathan, made out to overturn herself in a chaise,
near her own home, and lie with her, on horseback`"--Rebecca Jones adds:

[.embedded-content-document.letter]
--

"`In our late partnership journey, thou wast frequently the subject of our conversation,
in that love which many waters cannot quench;
and if thy Master should commission thee to this continent,
whilst these two Rebeccas are in the body,
thou mayest be assured of a couple of affectionate and well wishing Friends,
to hail thee into our field of arduous labour--the
Master of which has dispensed unto us the penny,
and commanded us to "`be content with our wages.`"
My love is to thy beloved husband, who, I desire, may continue to believe,
when the voice which formerly separated unto the Lord, Barnabas and Saul,
is heard commanding the surrender of his second self to the Lord`'s service,
that his reward will also be in proportion to
the acquiescence of his will to the divine call,
wherever it may lead.
With this desire, and with dear love, I conclude, thy poor little affectionate sister,

[.signed-section-signature]
Rebecca Jones.

--

She continued to board with James Goram till the year 1792,
when having concluded to rent a house,
she went to look at one which was to let in Brooke`'s court.
Calling at the adjoining house for the key,
she found it to be occupied by a woman who had
been her next neighbour in Drinker`'s alley,
but had fled with her husband, who was in the British interest, to Canada,
during the revolutionary war.
Their exclamations of surprise and pleasure were mutual,
and this decided Rebecca Jones`'s choice of a residence.

On the decease of William Mathews, his widow communicated to Rebecca Jones,
the following message, which was taken verbatim from his lips.
She accordingly forwarded it to Christiana Hustler,
who had been associated with her and William Mathews, in various journeys,
to be used in her judgment, and especially to be communicated to young Friends,
to whom William Mathews had been "`made more especially
a minister`"--a list of some of whom she furnished.
The message is as follows:

After a time of great weakness, he said--"`I wish one of you, soon after my change,
to write to Rebecca Jones and inform her of it,
and request her to write to my friends in England,
and remember my very dear love to them.
For to some of them I believe this language to be proper--`' In my bonds and
afflictions have I begotten you in the gospel of our Lord Jesus Christ.`'
Several of them, he added,
could testify that he had been made instrumental in turning them from darkness to light,
and from the power of Satan, to serve the living God:--that it was the Lord`'s doings,
and marvellous in his eyes.
He also said that Rebecca Jones had been more with him
than any other fellow-labourer in that land,
and nearly united in the same exercises and afflictions,
and that he trusted their labour had been productive of
the peaceable fruits of righteousness.
That his mind had for several days past been much and remarkably in Europe,
and seemed to pass along through almost all the meetings which he attended when there;
remembering how it was with him in most of them,--
saying that he wanted Rebecca Jones to write,
and communicate to Friends there his affectionate regard,
and that he had intended to write to her himself, but it now seemed too late.`"

To S. Rodman, of Nantucket, she writes, 4th month 1st, 1792:
"`The paper respecting the disuse of West India produce, has made many converts here.
Although I have not yet wholly declined sugar, I do prefer that made from the maple,
and have procured a keg from my friend Henry Drinker,
which answers all the purposes of the other, and is clear of the diabolical trade.

At our spring meeting, dear Samuel Emlen and Sarah Harrison, were set at liberty,
by certificates, to visit England.
May the good hand go with, bear up, and preserve them, through heights and depths,
is my humble prayer.`"

To Joseph Williams she writes a few days subsequently,
coinciding with his views respecting the disuse of West India produce,
and avowing her preference for maple sugar.
John Hoyland, in a letter dated 4th month 17th,
thus intimates the extension in England of a similar feeling.
"`I enclose a newspaper containing the debates upon William
Wilberforce`'s motion for the abolition of the slave trade,
if it be not too black to be read, also a late publication respecting sugar,
supposed to be written by a Friend, upon which I desire thy sentiments.
I don`'t know whether I acknowledged the receipt of the dried peaches
sent to us via Underclifle:--we have had some tarts made of them,
and find they retain their acid better than our apples.
But as Friends generally disuse sugar, pies seldom make their appearance,
and are little in demand.
It seems to be apprehended that those in that country who conceive
themselves interested in the continuance of the slave trade,
will yet have power to prevent an immediate and total abolition.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to S. Hustler

[.signed-section-context-open]
Philadelphia, 6th mo. 9th, 1792.

[.salutation]
My dear S. Hustler,

Thy truly acceptable epistle of the 17th of Second month,
came duly by the ship Grange, and is now before me.
Its contents are all interesting to me,
as my love and friendship to and for your whole family remain undiminished, and will,
I trust, so long as I am capable of recollection,
and with a sense of that mercy and goodness which were so
signally around about the habitation of my endeared companion,
thy worthy mother, who is a sweet and lively epistle, written upon the table of my heart,
which I trust will never be obliterated, whatever we may each of us have to pass through,
of an afflictive nature.
Salute her for me; tell her I was sure from my feelings,
great part of the winter and spring, that she was in a poor way,
and if I was within a few days`' ride of your house, poorly as I have often been myself,
I should have visited, and helped thee to nurse and cherish her.
A widely extended deep is now between us as to the outward!
What a favour it is, that we can in spirit visit and salute each other,
and as I have done this morning, say, "`Be of good cheer,
He that hath called us is faithful--He hath promised to
be with his own to the end of the world!`"

I have frequent conversation with my near neighbour, S. Smith;
that S. S. thou thinks so much resembles poor me, though by the by I don`'t think so,
or else I might be proud.
We often talk about you, and his account of thee and soma others, is what comforts me,
and, in some degree, answers my expectations.
I want to write to B. S.;
she has noticed me more in this line than any one of that house; my love to them all.
I am sorry to learn that dear E., is so declining,
but she having been "`diligent in business,`" whilst able,
will now reap the consolation derived from a sense of having,
with great "`fervency of spirit,
served the Lord;`" which I trust is also thy beloved mother`'s
enriching experience in times of weakness and bodily pain.
May we all have an eye to the blessed recompense of reward!
and not cast away our confidence in the sure arm of divine
support in times of dejection and discouragement,
which are often my attendants, but "`continue stedfast and immovable,
always abounding in the work of the Lord`"--that
when called upon to render up our accounts,
we may stand acquitted in His holy sight, as was the poor woman,
concerning whom her Lord and master said, "`Let her alone,
she hath done what she could.`"

Say for me, to thy brother William, that as the eldest son of the family,
I much desire his steady example may tend to dear John`'s preservation,
and that they together may grow up in their youth,
"`plants of renown,`" to the praise of the great and good husbandman,
who having in a peculiar manner watched over, cared for,
and many ways blessed you in basket and in store,
will most assuredly demand the conspicuous fruits of humility,
gratitude and fear before Him; and which, if happily found with the widow and fatherless,
they may with holy confidence look up in future trials and difficulties,
and availingly cry, Abba Father, for "`in Him the fatherless find mercy.`"

And now in the fresh flowing of that pure spring,
which was often encouragingly witnessed to arise for our mutual strength and consolation,
when we were together, do I salute thee, dear child, desiring the Almighty Father,
friend and helper of His people, may keep and preserve us among His own sheep,
and finally own us as His, when done with time.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Esther Tuke.

[.signed-section-context-open]
Eleventh month 30th, 1792.

"`I believe from some peculiar sensations and late intimations,
that more are preparing for the solemn embassy from this to your land.
Why are you so slow in your remittances?
Surely, in due time, we are to reap from your country.
In the prospect whereof, I desire not to faint,
whether I may be continued to rejoice in the completion or not.

I have a letter saying that Richard Reynolds and Priscilla Gurney,
have openly preached the gospel.
May they prosper in it and live of it, is my fervent desire.

In our particular meeting we have divers new appearances in.
the ministry: and among them a mulatto woman, named Hannah Burrows,
who has sometimes kneeled, and the meeting has risen.
In her appearances, Friends savour the gospel.`"

--

The coloured woman above referred to,
continued to speak occasionally in meetings to the satisfaction of Friends.
A Friend who knew her, and who mentions her peaceful death,
remembers Thomas Scattergood calling to her, in North Meeting, "`Raise thy voice,
Hannah.`"

Fourth month 15th, 1793, in a letter to Christiana Hustler,
she says--"`

[.embedded-content-document.letter]
--

I have a prospect of again moving about in
that line of service which opens as the path of peace;
being likely to set off`' in a few weeks for Long Island and Rhode Island,
and to have Lydia Hoskins, a choice-spirited young minister, for my companion;
also the company of my very near and faithful friends, Samuel Smith and wife.
In the ship '`George,`' by which this is intended to be sent, our dear friends,
George and Sarah Dillwyn, and my very particular friend Elizabeth Drinker,^
footnote:[Elizabeth Drinker died in London, Eighth month 10th, 1794.
She was wife of that honourable elder, Daniel Drinker,
and mother to our late beloved friend, Abigail Barker.]
have taken their passage.
The first two will doubtless have a welcome reception by thee;
and the latter will be found a minister of the Spirit,
to whom I wish that the same kind notice which was shown to me,
when I was on the like errand, may be extended, as also to dear Sarah Harrison.
Perhaps we may not hear so frequently from each other as we have done,
by reason of age and many infirmities, as well as increasing troubles amongst you.
Be that as it may, I deeply sympathize with thee on many accounts; but,
if the Lord be on our side, we need not fear what man can do.
To him,
therefore,--to his blessed guidance and protection--do
I commit and commend thee and thine,
my precious Chrissey, with my own poor soul:
praying that we may be helped so to steer through the troubles of time, as that we may,
of His unmerited mercy, find an everlasting resting place with Him,
when time to us shall be no more.`"

--

The epistle of Philadelphia Yearly Meeting of Women Friends,
to the corresponding body in London, issued Ninth month, 1793,
thus affectionately refers to the Friends mentioned above;
and evinces also the readiness on the part of Friends in this country, to receive,
with cordiality, for the Truth`'s sake, the ministers of Christ,
when sent forth as ambassadors for him.

[.embedded-content-document.letter]
--

"`Your mention of our dear friends, Samuel Emlen, Job Scott,
and Sarah Harrison`'s acceptable service with you, is truly comfortable;
and we desire that they, with dear George Dillwyn and Elizabeth Drinker,
may be sustained and strengthened to finish the work which may be assigned them,
so as to obtain the full reward of peace in the Lord`'s time.
The Friends mentioned in your epistle as likely to embark in Truth`'s service,
for this country, are not yet arrived.
We hope, when so favoured, they will be acceptably received, and aided as necessary,
by such as may be continued, willing to entertain strangers,
and to wash the disciples`' feet.`"

--

The same epistle thus notices the awful scourge which
will be more particularly mentioned in the next chapter.

[.embedded-content-document.letter]
--

"`Our meeting is unusually small by reason of great sickness and contagion
in this city--yet divers friends from different Quarterly Meetings,
having resigned their lives into the Lord`'s hand,
have ventured in--and their countenances, with the sensible help of their spirits,
have been witnessed as balm to our minds.`"

--

Fourth month 23d, 1793.
Our friend was furnished, by Northern District Monthly Meeting,
with the following certificate,
addressed "`To our Friends and Brethren in the governments of New York and New England.`"

[.embedded-content-document.letter]
--

"`Our beloved sister, Rebecca Jones,
having for some time been under a religious engagement of mind to
visit the approaching Yearly Meetings on Long Island and Rhode Island,
also some other meetings in those parts, laid her concern before this meeting, which,
obtaining our approbation and unity,
we hereby certify that she is a Friend well approved amongst us;
exemplary in life and conversation, and her ministry sound and edifying.
We therefore affectionately commend her to the care and
regard of Friends where her lot may be cast,
desiring that her labours may, through the Divine blessing,
prove to the comfort and edification of the church, and her own true peace.
We salute you in gospel fellowship, and remain

[.signed-section-closing]
Your loving friends.`"

[.signed-section-signature]
(Signed by 84 Friends.)

--

Of this visit, in which she was accompanied by Lydia Hoskins, little record being found,
we subjoin the testimony of the church.

The Yearly Meeting held at Westbury, declared, by its endorsement to her certificate,
that "`her gospel labours, both in the line of the ministry and discipline,
have been truly edifying and comfortable to us.`"
And a similar minute of New England Yearly
Meeting says--"`Her company and gospel labours,
both in the line of the ministry and discipline, have been cordially acceptable,
strengthening, and comfortable to us.`"

At the suggestion of Rebecca Jones,
the Women`'s Yearly Meeting held at Westbury in this year made an
essay toward a correspondence with the Women`'s Y. M. of London,
"`which,`" said they in their epistle, "`if it meet your approbation,
we hope and trust will, under the divine blessing,
tend to our mutual comfort and edification.`"

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Newport, Rhode Island, 10th of 6th mo., 1793.

[.salutation]
Dear Friend, H. Drinker,

Through the care and protection of kind Providence,
L+++.+++ Hoskins and myself have been helped thus far in safety on our way.
We arrived here,
after a 40 hours passage,--about twenty in company--in the packet from New York,
which place we left last Fifth day morning,
early--the day on which S. R. Fisher was married to a precious girl named H. Rodman.
The disappointment was great, but the marriage was not suspended on that account.

I expect our friend S. Smith,
will give thee all the needful intelligence about the Yearly Meeting on Long Island.
His company would have been agreeable to me here,
but he was most easy to return from New York.
This I also wished for myself, and sought for a door of escape, which, not being found,
I now humbly trust I am where I ought to be,
and am in pretty good health at the house of our friend Thomas Robinson,
whose daughter Mary is like to become "`a crown`" to John Morton.
They have passed one meeting.

P+++.+++ Yarnall and E. H., are on their way hither by land, and expected this evening.
I don`'t hear of any other strangers coming to the yearly meeting.

I hear that our North Meeting have altered the
hour for Meeting in the afternoon to the 4th,
with which I unite, and should like to hear that it has answered a good purpose.
Please tell me whether any account has reached
you respecting our dear friends in the Pigou,
about whom I have been very thoughtful during the late succession of easterly winds.

As I have not any thing very interesting to communicate--though our
sex are often charged with prolixity,--I shall not trouble thee,
as E. Tuke says,
with "`a lengthy speech now,`" but as I do feel
very sincere esteem and love for thy dear wife,
sister and children, please let them know it.

--
