== Chapter X.

[.chapter-subtitle--blurb]
1794.--1799.

[.chapter-synopsis]
* A young friend joins her family
* Rebecca Jones`'s last letter to Esther Tuke
* N. Waln`'s prospect for England Visit in N. Jersey
* Letter from S. Harrison
* Death and character of Catherine Phillip
* Attends New York Yearly Meeting Letters
* Establishment of West Town School and of Indian Committee
* Letter from William Savery
* Rebecca Jones delivers her message in Monthly Meeting
* Fever of 1797
* Rebecca Jones goes to Edgely
* Death of Thamazin Clifford
* Returns to Brooke`'s Court

An interesting child, who had been with Rebecca Jones, as a daughter,
being removed by death, the bereavement was keenly felt by her; so much so,
that in much disconsolate feeling, not knowing how to think of supplying her place,
she lodged alone in her rented house in Brooke`'s court, for six months.
In the 9th month, 1794, a young Friend (Bernice Chattin) was, as Rebecca Jones,
expresses it, "`providentially afforded unto me.`"
"`I am furnished,`" she notes, "`with another daughter, of a lovely, amiable disposition.
She often so freshly revives my late dear Mary, that the tears flow involuntarily.`"
Thus divinely joined together,
they were associated in sweet and uninterrupted harmony till the marriage of the younger;
calling forth from very many visitors, in religious opportunities and otherwise,
allusions to Naomi and Ruth,
a comparison which was more fully justified when Bernice became a widow, and,
renting the house in Brooke`'s court, adjoining that of Rebecca Jones,
a door was made to communicate between their chambers.
Some years previous to Rebecca Jones`'s removal from time,
some reasons rendering their residence in the court ineligible,
B+++.+++ A. took a house immediately opposite to the North Meeting,
in which they dwelt together till this venerable mother
in Israel was removed to the triumphant church.
This brief notice is given in anticipation of the course of the narrative,
the compiler being unwilling, in a biography of Rebecca Jones,
to omit recording the close union which subsisted for 22 years, and to which,
in the loose manuscripts before him, almost innumerable references are made.
A less interested compiler would have quoted much more freely from their correspondence.

[.embedded-content-document.letter]
--

[.letter-heading]
To Esther Tuke.

[.signed-section-context-open]
Philadelphia, 1st mo. 25th, 1795.

Some sketches of the late awful dispensation to the inhabitants of this city,
and of that share therein which in perfect wisdom was allotted me,
thou hast doubtless had through divers channels.
Let it therefore, my dear friend, suffice to say, that He who is mighty hath, in this,
as well as in former seasons, done for poor, unworthy me, great things.
Under the fresh sense whereof I feelingly acknowledge, "`holy and reverend is his name.`"
Yea, worthy is he to be confided in and trusted to, now and forever more, Amen.

I received some comforting information from your land,
such as I know makes thy heart glad;
because in the present day the Lord hath given the word,
and great is the company of them that publish it--amongst the dear youth especially.
For many of them I also have travailed, according to my small measure;
and I wish this renewed proof of the continued care of the one great and good Shepherd,
may animate his ancient devoted servants,
more fully to commit their work and ways to Him who doeth all things well, and who,
having given some of these to see, as good old Simeon did,
are ready to adopt his language, "`Lord,
now lettest thou thy servant depart in peace,`" etc., they having, like him,
waited for the consolation of Israel.

Our own country hath not yet been cast off in anger,
though closely and heavily punished by the hand of infinite Justice.
Many of my dear contemporaries have been gathered to their everlasting rest, and,
though too few appear to lay these things rightly to heart,
deep instruction has been sealed on the minds of a humble remnant,
and resolutions have been formed to hold fast that which they
have received from the immediate hand of the Father of mercies,
the alone fountain of all light, life and blessedness.
A hopeful succession is also furnished of rightly anointed female ministers in this city,
and several of them are acknowledged by the Church as such.
A niece^
footnote:[Jane Snowdon.]
of dear S. Harrison, gave up, at my request,
to accompany me in my late visit to the families of our large Monthly Meeting,
the sympathy and weight of whose spirit, and the tender,
patient assistance of divers other Friends,
were truly strengthening to my poor bowed down mind.
It is now, to my unspeakable comfort, as well as great admiration, completed;
we having been at about 250 families.
May the praise be given where it is only due, by me, a poor, unprofitable servant.

Our dear friends, Deborah Darby and Rebecca Young, are in this city,
engaged in like manner amongst the families of Pine Street MeSting.
They have general acceptance and good service amongst Friends and others, and are,
in the fulness and authority of the gospel,
often led to "`other sheep which are not of this fold.`"
May their steady example in the service of their great Master,
and their labours under his direction and help,
be productive of lasting benefit to the visited,
and tend to their own establishment in righteousness and peace.
The like ardent desire I feel on account of our dear friends, J. Wigham and Martha Routh.
Our being deprived of dear J. Pemberton`'s help and example, is sensibly felt by many;
but the vacancy which I feel most,
is that made in the circle of my nearest fellow
labourers by the absence of dear Thomas Scattergood,
with and for whom, great has been my sympathy and unity of soul.
His tender frame is so little attended to by himself,
that unless he has a feeling companion, I shall fear that he may, like dear E. Drinker,
never return to us.
But as her meat and drink was to do the Master`'s will,
believing as I do that she now reaps the reward of faithfulness--with dear Job Scott,
who quitted the field a little before her--although I sometimes
lament the loss which the churches have thereby sustained,
I dare not call in question the wisdom of the God of the whole earth,
knowing that he doeth all things right.

Now in that love, which is not subject to change, do I salute my endeared friend,
greatly desiring that we may so steadily trust in our all sufficient Helper, as that,
like Mount Zion, we may never be removed, but that,
when this short fight ol affliction shall terminate, we may,
through his adorable mercy and goodness,
be counted worthy to join the song of his triumphant church, Holy, holy, holy,
is the Lord God and the Lamb, worthy of all glory and praise for ever and ever.
I remain thy poor fellow pilgrim,

[.signed-section-signature]
Rebecca Jones

--

To the above letter was appended the following postscript:

[.embedded-content-document.letter]
--

"`If my beloved Esther Tuke is beyond the reach of this salutation,
I hope for some reply from survivors.
May a double portion of her dedicated disposition, rest on all her family,
saith poor Rebecca Jones.`"

--

The foreboding implied in the postscript, was to Esther Tuke blissfully realized,
she having, before the reception of this letter,
put off the earthly tabernacle in which it had been her chief concern to do the
will of Him with whom she was favoured to partake of "`communion large and high.`"
And ere Rebecca Jones`'s salutation had been wafted across the ocean,
she had doubtless been led, by Him who is in the midst of the throne,
to living fountains of waters,
and had joined with the redeemed of all generations in
the holy anthem of the triumphant Church.

Speaking in a letter to Christiana Hustler, First month 26th, 1795,
of her daughter Sarah Hustler, subsequently an eminent minister of the gospel,
Rebecca Jones says, "`May she suffer the candle to stand in its allotted place,
that so the light of her innocent,
upright and humble example may become happily influential on
the spirits and conduct of the younger children.
I am rejoiced in hearing that she has wisely submitted
to the appointment of your Monthly Meeting,
and the call of the collective body at your last Yearly Meeting; and trust that,
as she offers herself, willingly and devotedly, to the Lord`'s service,
she will be strengthened to do what her hands may find
to do--so will her peace flow as a river,
and her righteousness, (those successive acts of obedience which may be required of her,
follow in succession as the waves of the sea.`"
In the same letters he says,
"`Samuel Emlen`'s son is on the eve of marriage
with Susanna Dillwyn,--they are a hopeful couple.
Reay King is lately married to one of my old scholars, Anne,
only child of William Wilson, a valuable elder of this city--a choice girl:
and the only daughter of my late much loved friend E. Drinker is to be married next week,
agreeably.
Oh, how my feelings have been tried on hearing of the departure of my two dear friends,
Job Scott and Elizabeth Drinker,
and my beloved friends Catherine Phillips and Deborah Townsend:
but they are happily landed on the peaceful shore.
Oh that I may be favoured to join their and thy purified spirits, by and by,
in incessantly celebrating the praise of our ever adorable Helper, Father and Friend,
who lives and reigns, and is forever worthy.`"

Katherine Howell, in her diary, says, First month 27th,
1795--"`Our Monthly Meeting this day, was a season of great favour to some,
whose states were pertinently spoken to.
After the minute was read of Rebecca Jones having
performed the family visit to our meeting,
Deborah Darby arose, like a mother in Israel indeed,
and spoke somewhat after this manner: '`See, Friends, how you have been favoured,
beyond the rich man formerly,
who requested that one might be sent from the dead to warn his relations;
but it was not granted to him.
But you have had one raised up to you again,
therefore I entreat you to gather up the fragments that nothing be lost.`"

Nicholas Waln, having obtained the united concurrence of his friends,
in his prospect of a visit to Ireland and part of England,
Rebecca Jones was solicitous that he should have the comfort of a suitable companion;
and she notes, Fourth month 3rd,
"`I have this evening heard that one of our most upright pillars, David Bacon,
an Elder worthy of double honour, has yielded in sympathy with dear N. Wain,
in order to accompany him over the great deep,
which must be a precious seal to N. W.`'s commission.
What joy will dear S. Harrison and Thomas Scattergood feel,
should they be permitted to meet; D. B. being a father in the Truth to both.
Thomas`' first wife was D. Bacon`'s daughter, one of my scholars.`"

"`1795, Eighth month 15th. Being poorly in health,
and having obtained leave of my friends, my kind friend, Catherine Haines,
offering to take me into the country for the benefit of the air;
we crossed the Delaware about 3 P. M., in company with several Jersey Friends,
and had a pleasant ride to Woodbury, where we staid at the house of John Tatum,
during the Quarterly Meeting there.
Two meetings were held on First day, and that for business on Second day--all large,
and measurably owned with good.
There were also from Philadelphia, N. A. S., E. Foulke, Daniel Drinker, Margaret Elliott, etc.
The first two had acceptable service.
We visited, at different times, Sarah Whitall, Joseph and Hannah Whitall,
J+++.+++ Blackwell and wife, David Cooper, in a low but favourable situation,
S+++.+++ Mickle and John Reeve.

19th. In the afternoon came to Haddonfield;
lodged at John Hopkins,`' and attended their Week day Meeting--an exercising time.
Martha Allinson, and three of her children, met us and came with us to B. Swett`'s,
from whence we had purposed to go that afternoon home with M. Allinson,
(at Cropwell,) but a heavy rain coming on, and a strong wind blowing from the north-east,
we suffered M. A. to depart, and we being both infirm,
were most easy to abide with our kind friends, B. and M. Swett, that night.

21st. It having rained steadily during the night, and continuing wet,
we were easy to give up going to Cropwell Meeting, hoping to get there soon.`"

Next day the 22d, she visited the Friend mentioned in the succeeding note,
and participating with her hostess in true gospel fellowship,
they were enabled to "`Gird up each other for the race divine.`"

At the dinner table, before partaking of the repast,
Rebecca Jones commenced with referring to "`the provision which is now graciously
offered to our acceptance`" and spoke with a weight and solemnity which remained,
through many years of vicissitude,
impressed upon the minds of those who were gathered around the board.

22d. "`Went to Martha Allinson`'s, and after an open time there,
D+++.+++ A. took us to Burlington, where we attended their two meetings on the 23d,
being First day.
We went home with John Cox and lodged.
Next day dined at John Smith`'s, and came in the evening to Burlington.

25th. Concluded to stay till to-morrow, when,
if most easy to go to Buck`'s Quarterly Meeting, we shall have but seven miles to go,
and John Hoskins has agreed to go with us.`"

Her diary, which breaks off abruptly, was probably interrupted by illness.
After attending Bucks and Burlington Quarterly Meetings,
and spending a short time in Bucks county,
she returned to her home with an intermittent fever.

In a letter to Joseph Gurney Bevan, 5th mo.
22d, she says--

"`The affecting accounts of dear John Pemberton`'s departure reached us two weeks ago.
His wife has kept her room ever since, and with many others, is sorrowful indeed.
On his account there is, I trust, no cause for mourning.
He was a brother beloved and honoured by me.
If dear George and Sarah Dillwyn are with you when this comes to hand,
tell them I continue to love them as a sister and that I also
continue in the belief that if their lives are spared a little longer,
they will return to dwell among their own people.`"
In the same letter, referring to business affairs in Philadelphia after the Yellow Fever,
she says--"`The spirit for building, for purchasing and selling estates,
is amazingly great.
Every article in housekeeping is so raised in price
that one might almost fancy oneself in Great Britain,
and be awake too--so that I, with others,
am of the mind-that the present face of things will be changed,
though the time as well as the manner I desire to leave.`"
Expressing a wish to be at New England Yearly Meeting,
"`if it were my proper business,`" she adds--"`at
present I have not much prospect of going from home,
and yet I hardly think I shall be allowed to stay all summer in port.

I am wearing away gradually under a load of complicated trials--some
of which have been more pinching than any preceding:
so that,
did not He who is touched with a feeling of our infirmities
condescend to succour and sustain marvellously,
I should sink below hope and faint in this day of adversity.
May all things which are permitted and dispensed in unerring wisdom,
work together for my increasing fitness to enter into Everlasting rest when
this sore fight of affliction is over--is my fervent prayer.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Extract from a letter from Sarah Harrison to Rebecca Jones

[.signed-section-context-open]
Leeds, 4th mo. 7th, 1796.

'`I do not wish to burden thee with my troubles, for I find thou hast enough of thy own,
and my feelings are awakened, and my sympathy hath been renewed with thee,
in the late fiery trial through which thou hast had to pass,
though I know not from whence those bitter waters spring,
and therefore I am a stranger--that is, from information--to the nature of the case.
But as I was pondering it in my mind this morning,
the language of (he apostle was brought, with some degree of clearness,
to my remembrance, inducing me to take up my pen, poor as I am,
just to remind thee of what he says--`' Think it not
strange concerning the fiery trial which is to try you,
as though some strange thing had happened unto you; but rejoice,
inasmuch as ye are partakers of Christ`'s sufferings;`' and, indeed, it is good for us,
on such occasions,
to remember who it was that suffered so great contradiction from sinners,
even from one who had dipped in the dish with him,
which we may suppose made it harder to bear than the
same treatment from a professed enemy would have been.
For, as said David, '`if it had been an enemy, I could have borne it.`'
And amongst the many perils that Paul met with by land and by sea,
he looked upon them that were brought upon him by false brethren, to be the worst.
Dear friend, if thou hast been tried with any thing similar to what I have hinted at,
and thy soul made sorrowful by any of those with
whom thou hast heretofore taken sweet counsel,
and you have in those days gone up to the house of the Lord in company,
thou art to be felt for, and I do feel for thee as much as my nature is capable of.
And my desire is,
that thou mayst take that ancient advice,`' Fret not thyself because of evil
doers,`' but let such be unto thee as a heathen man and a publican;
though it is reasonable to suppose that the feelings of thy mind on
such mournful occasions will produce the moving language,
'`how is the shield of the mighty vilely cast away!`"

Well, what more shall I say upon an unknown subject, except it be, fear thou not,
for though thousands may fall by thy side, and ten thousand by thy right hand,
none of these things shall come near thee, only thou shalt see them with thine eyes,
and mayest have to go heavily on thy way on their account.
But oh, mayest thou remember that it was to those who sighed, and cried for wrong things,
which prevailed in days of old,
that he who had the writer`'s ink-horn was sent to set his mark upon them.
And with him there is neither variableness nor shadow of turning;
so cast not away thy confidence, but trust in the Lord for ever.
On my own account, I have reverently to acknowledge,
that he that is mighty hath done for me great things;
he hath taken me as from the dung-hill, and set me among princes.
The consideration thereof hath often humbled my mind, and leads to the enquiry,
'`What shall I render unto thee for all thy benefits!`' And persuaded I am
that nothing short of the dedication of my whole heart will be accepted;
and I am very sensible,
that the time is coming wherein I shall stand as
much in need of the prayers of my friends,
as I have at any time since I left home.
And therefore I most sincerely desire to be remembered by thee,
and by all that desire my preservation.

--

In this year died Catherine Phillips (formerly Payton)
whom Rebecca Jones called "`my beloved parent in Christ,
through whom I received the first awakening stroke.`"
The following well condensed sketch of her life and character (taken
from a manuscript copy preserved by Rebecca Jones,) being apparently
not written by a Friend,
and presenting some valuable traits not fully set forth in her printed memoir,
is thought worthy of insertion.

[.embedded-content-document.letter]
--

[.letter-heading]
From the Gentleman`'s Magazine for 1795.

Died, at Redruth, county Cornwall,
at an advanced age, Catherine Phillips, one of the people called Quakers,
relict of the late William Phillips, a gentleman of large concerns in that mining country,
and of great respectability, whom she married late in life.
Her life and talents were too extraordinary not to merit record.
She was a native of Dudley, county Worcester, and sister to the late James Payton,
of that place.
Her natural powers were uncommonly comprehensive; and,
just as she arrived at the prime of life,
she believed it her duty to give up all other
considerations to engage in the Gospel Ministry,
among the Society in which she was born.
Her conceptions of the purity and glory of the Gospel,
and that real sanctification of heart, which it not only teaches,
but furnishes the means of effecting, were deeply engraven on a mind devoted to God,
and filled with love towards mankind.
Thus animated,
she visited the congregations of the Society throughout most parts of England,
and several times those of Ireland;
and with the concurrence necessary by the discipline established amongst them,
she visited the Society in North America,
in company with a young woman of Ireland as extraordinary as herself;
thus foregoing ease and affluence for a very arduous and labourious service.
Many who attended her ministry,
were surprised at finding such powers of unfolding the
Christian doctrine in a woman then in her youth;
and a dignified clergyman, we are told, once said,
"`he wondered where she attained them.`"
A singular testimony to the excellence of her preaching,
is given by a person of great credibility.
A gentleman went to her at Cambridge, and took two youths, then under his care, with him,
on purpose, as he said,
to convince them of the futility of all pretensions to inspiration;
but owned that he left the assembly with very different
impressions from those with which he entered it.
She had very considerable knowledge in medicine and botany,
and published something on planting and beautifying waste grounds,
of which her travels and practical knowledge rendered her a good judge.
Her charity and attention to the poor were extensive;
and she was deeply concerned for the reformation of their morals.

With this view, she drew up an address to the gentlemen of Cornwall,
who were met a few years since on the mining concerns in those parts;
and on the agitation of the public mind since the French Revolution,
she wrote to the miners,
to convince them of their duty and interest in
studying to be quiet and mind their own business.`"
This she knew would be her worthy husband`'s advice, had he been living at such a time,
who had great influence with them.
This paper was thought so salutary,
that a neighbouring magistrate had it printed and dispersed in the country.
She was an ardent well wisher to the governors as well as governed of this realm,
desiring to see that righteousness which exalteth a nation "`so to flourish
as to draw down the divine blessing on this island and its dependencies.`"
For some years before her decease,
she was rendered a perfect cripple by a rheumatic gout;
and during the confinement which this occasioned,
her mental faculties suffered with the body, and rendered her,
like some other great minds, after a series of uncommon exertion,
an object of commiseration.
From these clouds, however, she at times shone forth again,
and wrote with precision on the subjects alluded to;
and also a tract to show why the Society of Friends could not fully
unite with the Methodists in their missions to America and the Indies.
She left also some MS. poems.
During this time she could not distend her fingers so as to write in the usual way.
To the last of her ability, she endeavoured to devote herself to the service of mankind,
and has left an example of exalted virtue,
although in a line unusual to the generality of her sex.
Her uniform, upright conduct in her own community, gained her great esteem;
and her Christian courage to oppose licentiousness among the gay,
covetousness among the rich, and fanaticism among the weak,
rendered her one of the most useful and distinguished members of it.

--

From New York, where she appears to have been attending the Yearly Meeting,
accompanied by Catherine Haines--a minute from her
Monthly Meeting being sent after her--she writes,

[.embedded-content-document.letter]
--

[.letter-heading]
To Henry Drinker

[.signed-section-context-open]
Fifth month 27th, 1796.

"`Tis expected the Yearly Meeting will close to-morrow.
It has been large, and, so far as my weak judgment goes, a solid instructive time;
though by reason of an attack of chill and fever,
I was prevented attending on Third and Fourth days,
since which I have just made out to get to meeting, in C. Haines`'s carriage,
and returned immediately to my chamber at E. Prior`'s,
where I have all necessary attention and care.
Thy`' messages of love have been given to all intended, except H. Barnard,
who is also laid by through indisposition.
She was, however, at meeting this morning, and spread a concern before the meeting,
with which Martha Routh and myself could not fully accord, yet in sympathy with her,
and at her request, we bore her company into the men`'s meeting,
where it was decided against.
I hope she will be relieved thereby.

"`Thy account of the departure of our dear friends,
and that they went out on Seventh day, was gratifying to divers Friends here,
particularly J. Wigham and Martha Routh.
These dear friends, with myself, have a treat in the company of William Rotch, etc.,
who arrived here on Seventh day.
He looks, I think, full as well as before he went to France, etc.,
only that his hair is a little changed.
If my health should be restored by the early part of next week, I hope to turn homewards,
though I may, perhaps, stop a few days at Rahway, etc.`"

--

After referring to the removal by death of some Friends, she continues:

[.embedded-content-document.letter]
--

"`But I consider that it is but a little while that we, who are now moving about,
shall have the opportunity of evincing, to such as are advancing on the stage of life,
that we prefer the welfare of the cause of Truth to our chief joy, and in so doing,
be '`laying up a good foundation against the time to come.`'
Therefore, my humbled spirit craves that I may, in an especial manner, cleave closely,
now in my declining age, to that good Hand which, in early life,
visited and bore up my tabulated soul; which has been with me in every varied scene,
and which is still to me, however unworthy,
the alone Helper--the Physician of value--the unfailing Friend!
May the sense of his unmerited kindness keep me through
the remaining part of my painful pilgrimage,
where only, as I am abundantly convinced, is safety,
even in a state of humble watchfulness and child-like
simplicity--weaned from all creaturely dependence,
and fully resigned to his blessed will in all the
future dispensations of his unerring Providence;
and finally, allow me just an admittance within the gates of that Holy City,
towards which, with longing desire,
the eye of my soul has been turned since the sixteenth year of my age!
Unite with me in desire, my dear friend,
for this! that without seeking '`great things for myself,`' I
may devote myself more faithfully as the evening approaches,
in seeking after an establishment in His favour, which is better than life, and which,
if but happily obtained,
will more than compensate for all that my poor exercised
spirit hath endured for more than forty years:
being the crown that will never fade, but abide for ever and ever.

"`If I have exceeded, tell me so, and believe me to be thy much obliged,
and sincerely affectionate friend,

[.signed-section-signature]
Rebecca Jones

--

Fifth month 30th, in a letter to Bernice Chattin, she mentions,
that although she had suffered with an attack of chill and fever,
she attended all but three or four of the sittings of the Yearly Meeting.
"`We have had,`" she says, "`a large and solid meeting,
and last night a parting meeting with the youth, which was a blessed season,
in which I thought of thee,
with strong desires that thy tender mind may be duly impressed
with a sense of the Lord`'s preserving goodness and fear,
and be kept in a watchful innocent state.
Hereby will my joy be greatly increased.
John Wigham lodges at John King`'s, William Rotch and his daughter Mary, at John Murray`'s,
where are also Martha Routh and her companion L. R.--so we are scattered about.
I hear that R. Cathrall^
footnote:[Sister to Dr. Cathrall, and niece to Hannah Cathrall]
is going fast, so thou seest, my dear, that the youth, as well as the aged,
are called away--that we need all endeavour to be in
readiness to meet the Lord in the way of his coming.
I do not suspect thy being in more danger than other young persons;
but as my soul is deeply concerned for thy preservation,
and as many dear friends have taken most especial tender notice of thee,
and do love thee, and, what is far better, I believe thy heavenly Father loves thee,
and has not been wanting in his secret and blessed intimations to thy own mind,
I do therefore earnestly entreat thee to beg of Him for help and power,
to resist all manner of temptations, and to walk before him in humility,
innocence and holy fear.
Then will he delight to bless thee, and both inwardly and outwardly to prosper thee,
and crown thy tender mind with the incomes of his enriching peace.
Farewell my dear girl--may the Lord keep thee and me near to himself, that,
if we meet again in this world,
it may be with minds suitably impressed with a sense of his goodness, and if,
in his wisdom, he see meet to order it otherwise, oh,
that we may meet in the mansions of rest and peace.
So live in that which will help thee to love thy poor, weak, affectionate friend,

Eleventh month 3rd, 1796.
In a letter to James, son of her beloved Catherine Phillips, she says:
"`I expect thou hast accounts of our great works which are in contemplation,^
footnote:[It was not without reason,
that Rebecca Jones referred to the measures in question as great works,
then in contemplation.
In the autumn of 1795,
the Yearly Meeting of Philadelphia appointed a committee to
endeavour to promote the civilization and improvement of the
Indians residing chiefly in the State of New York.
Funds to defray the expenses were raised by voluntary contribution,
aided by a liberal donation from Friends in England.
A number of young Friends, of both sexes, were engaged to reside for a time,
among the natives in various locations,
and endeavour to instruct them in the arts of civilized life, such as farming,
domestic economy,
and several of the mechanic arts.
{footnote-paragraph-split}
It would exceed the limits of a note,
to given even a concise history of the operations of this committee;
but it may be stated that the appointment is still kept np,
though our valued friend Thomas Wistar is the
only one of the original number now remaining.
The care of the aborigines in various parts of our extended country, has,
since that time, engaged the attention of several other Yearly Meetings,
and the attention of the Philadelphia committee, has been, for a number of Years,
chiefly directed to the settlements on the Alleghany.
Although the progress of those people, in the arts of civilized life,
has not fully answered the anticipation of their friends,
their condition is greatly ameliorated.
Instead of the bark wigwam of that day,
many of them now occupy decent and comfortable houses,
not inferior to those inhabited by their white neighbours;
and instead of the precarious subsistence afforded by the chase,
they generally rely upon the cultivation of the soil,
and deposit the produce of their farms in barns erected by Indian workmen.
The ancient Indian costume has almost entirely vanished, at least among the men;
and the savage practice of cutting the margin of the ear into the form of a ribbon,
which was so prevalent sixty years ago,
has quite disappeared.
{footnote-paragraph-split}
It was at the Yearly Meeting of 1794,
two years prior to the date of this letter,
that the plan of establishing a Boarding school,
under the superintendence of a committee of that meeting, was adopted.
The farm at West Town had been purchased,
and preparations were making for erecting the necessary buildings;
but the school was not opened until the spring of 1799.
The important benefits which that seminary has conferred upon our religious Society,
and the stimulus which it gave to education among Friends,
are too generally known to require particular notice in this place.
{footnote-paragraph-split}
The Admission of black people into society,
to which she alludes,
may seem to imply that a rule to exclude them had previously existed.
That, it is apprehended, was not the case.
But in the autumn of 1796, a question from one of the Quarters,
whether black people might be received into membership,
was submitted to the Yearly Meeting.
The doubt which gave rise to the inquiry,
was probably owing to the paucity of applicants among
the coloured race for admittance into membership.
Upon due deliberation, the Yearly Meeting adopted the just and liberal conclusion,
that "`where Monthly Meetings were united in believing that the
applicants were clearly convinced of our religious principles,
and in a good degree subject to the Divine witness in their own hearts,
manifested by a circumspect life and conduct,
said meetings are at liberty to receive such into membership,
without respect to nation or colour.`"--Ed. Friends`' Review.]--such
as attempting to civilize the inhabitants of the wilderness,
and to establish a Boarding school after the manner of your Ackworth;
build a large meeting house,
(after your example,) to accommodate both sexes at the Yearly Meeting;
admit black people into society fellowship, etc., etc.
Well, my heart wishes well to every great, noble, and virtuous undertaking;
but such is my declining state of health, advanced age, and dimness of sight,
that I have no expectation that these things will be so perfected,
as that I may adopt the language of good old Simeon thereon;
yet am in the faith that success will attend the endeavours of such
as have at heart the promotion of the good cause of Truth therein.`"

It may be briefly noted, that Rebecca Jones was greatly interested, and much consulted,
in planning the building at West Town;
in arranging the rules for the government of the school, etc.
Pewter ware in great varieties, having become very much obsolete, was still stored away,
and nearly useless in many families.
Rebecca Jones interested herself in collecting articles of this kind,
which were sent to her house by wheelbarrow loads; and these utensils,
some in their original form, and others remodeled,
were placed at the service of the institution.

We now extract some passages from a long and interesting letter,
bearing date Twelfth month 30th, 1796, addressed to her from Amsterdam,
by her friend William Savery.

[.embedded-content-document.letter]
--

[.letter-heading]
From William Savery to Rebecca Jones

"`It has been a consolation to my spirit to feel thee
interested as a partner with me in my present engagement,
both before and since I left my dear native city:
yet that feeling always brings with it a sense of my own unworthiness.
I love thee as an elder sister, whose counsels, drawn from long experience,
have often been a comfort to me.
Thy account of thy journey to New York,
and the movements of our brethren and sisters to and fro in the Lord`'s service,
was acceptable, all but that part respecting thy being afflicted with a fever.
Subsequent accounts give me hope that thou art recovered.
Dear Rebecca, thy pen was rightly directed,
when thou wrote that it would be a comfort to me to know that
our holy Shepherd hath not forsaken the flock at North meeting.
They have been long and tenderly endeared to me in bonds of gospel affection.
My spirit often accompanies thee when I apprehend you may be assembled.
The preciously visited young of the flock,
both of that and the other meetings in our beloved city, still lie very near to my heart.
May the good Shepherd of the flock protect and defend them from all
that would hinder their progress in the way of present peace,
and future glorification with him.
Please convey my unfeigned love to as many of them as may be convenient.
It would not comport with the bounds of a letter to particularize.`"^
footnote:[This message was communicated to the womens`' Monthly Meeting by Rebecca Jones,
in a remarkably sweet and heart tendering communication.
She had risen to speak to business,
but her exercise soon extended beyond what was her prospect on rising;
and while the words flowed from her lips like oil,
her persuasive eloquence deeply affected many hearts.
She mentioned the reception of this letter, the place of its date, etc;
the writer thereof being very highly beloved by the congregation.
"`There were giants in those days.`"]

"`With regard to myself, I shall tell, as concisely as I can, how I have fared.
We had a pleasant and agreeable passage of four weeks,
after which thou mayest have heard that I staid about seven weeks in England,
and had several appointed meetings in Liverpool, Birmingham, and London,
which were large.
It appears to be a time of openness to other professors in England.
This was an unexpected service to me.
I humbly hope the cause of truth was not wounded.
In the multitude of my heavenly Father`'s mercies, he gave me as companions to Germany,
my dear friends George and Sarah Dillwyn, David Sands, and our W. Farrer and B. Johnson.
This, thou mayest conceive, my sister, had an animating tendency,
and was quite unlooked for.
I could not have chosen brethren with whom, as partners,
I would venture my little stock more freely.
George told me of thy hint in a letter to him, which, he acknowledged, hit the mark,
as he had this journey on his mind before.
George and Sarah Dillwyn have continued longer at Pyrmont than the rest of us;
I believe rightly so.
David Sands and myself have spent about five weeks there, first and last;
were present at two of their Monthly Meetings,
which are now established in more regular form than heretofore,
and contain about sixty members,
(and several more have applied.) It would do thy
heart good to be a witness of the power of truth,
in the simplicity of these innocent people.
As we stood round the grave of dear John Pemberton, something solemn accompanied,
with a comfortable evidence that he was landed, through many tribulations,
in the arms of everlasting Mercy.

There is a little flock at Minden, one at Hanover, and one near Hertford,
that keep up Meetings in the manner of Friends,
and all over this country where we have been,
there are more or less pious people,--separatists from outward forms.
Some are attached to the mystic writers, (Jacob Boehm, Lady Guion,
etc.,) but appear to be honestly enquiring for a right foundation.
By these we have been received with open arms,
and by the people at large with much civility and respect;
as well the great and officers of the army, etc., as the poor.
David Sands and myself have been led much in one line of service,
and have been nearly united in traveling together about one thousand miles,
having our two companions, and Lewis Secbohm as an interpreter;
for though I have sometimes interpreted for my friends,
as well as delivered my own concern in meetings,
yet I do not find myself perfect enough in the German to refuse an interpreter,
especially such a one as L. S., who has a peculiar talent for it,
and enters into the subject feelingly with us, so that I think he loses nothing.
This may be an encouragement to some of my fellow
labourers who may have a concern to visit this people,
and who are unacquainted with the German.
In several places, the tender people at parting,
expressed a hope that the Lord of the Harvest would send more labourers among them,
and I cannot doubt, that if Friends stand open to the pointings of truth,
their desire will be answered.
Here is a new and very extensive field opened;
the influence of the Priests is decreasing, and the hearts of Princes enlarging,
to allow more liberty of conscience than heretofore,--
although the fruits that have yet appeared in Germany,
are but small, compared with America.
The Prince of Waldeck has been kind to the Friends of Pyrmont in several ways,
and allows them the free exercise of their worship.
The priests, however, still exact some fees, for offices which they do not perform,
as christenings, burials, etc.
We have visited Berlin, the capital of Prussia, and several other cities in that kingdom,
as Magdeburg, Brandenburg, Halberstadt, etc. etc.,
in all of which are many honest enquirers after Truth;
and we had a number of meetings with them, which were generally solid and satisfactory.
At Berlin, in particular, we had seven or eight at our Inn,
where we had four chambers--some of them upwards of two hundred people, many of whom,
though they had never heard of Friends, were nearly united with us in our doctrines,
being taught by the great Teacher of his people.
These are of different ranks in the world, but mostly separated from the public worships.
They appeared like thirsty ground, and received us and our testimony gladly,
parted with us in the most tender affection,
and must long be remembered in near fellowship.
I do not remember at any time to have sat more
humbling and contriting meetings than those:
the praise is the Lord`'s.`"

--

1797+++.+++ In 8th month, the Yellow Fever having again broken out, the inhabitants,
following the instinct of self-preservation, rapidly removed from the city,
and Rebecca Jones`'s small household was left quite alone in "`Brook`'s Court.`"
Although she was preserved from being afraid(with any amazement,`" she
returned an affectionate acceptance to Catharine Howell`'s invitation to
spend the season of the infection at her country seat at Edgely,
on the Schuylkill.
The day previous to her leaving the city,
she fell down the stairs and hurt her leg severely.
This hurt for a time seemed more painful than dangerous,
and although unable to go abroad, she received and enjoyed the society of many visitors,
and wrote many letters.
With the family and guests, and servants, she had religious opportunities,
in which "`the sensible spreading of the holy canopy,`" was witnessed.
In the exciting state of the general mind,
various and conflicting reports of the state of the city were conveyed to her,
but her abode was in the quiet pavilion, and she remained peaceful,
though by no means insensible.

Ninth month 7th, she notes, "`By C. Haines, Sarah Cresson, and Leonard Snowdon,
we had more comfortable accounts of our poor city, yet find that the fever continues.
Oh Lord, be pleased, for thy mercies`' sake,
once more to look down with compassion upon us,
and in thy own way and time deliver and spare thy people,
the workmanship of thy holy hand.
Grant, that now thy judgments are in our land,
the inhabitants may truly learn righteousness!

On First-day, the 10th,
remembering that Catherine Phillips went to meeting with her fractured arm in a sling,
although she was more indisposed, she went to Germantown meeting, which was large,
on account of the funeral of Jonathan Roberts.
After an extensive communication from Nicholas Waln,
Rebecca Jones was engaged in the expression of a lively
desire for the general increase of spiritual health,
and submission to the Lord`'s will.
At the close of the meeting,
she had a select opportunity with the connexions of the deceased at the meeting house,
in which she imparted tender counsel and sympathy.
This effort proved injurious to her health, and a violent ague was followed,
by high fever, and her wounded limb being much inflamed, mortification ensued,
and amputation was for a while anticipated.
Yet, her mind being fixed in dependence,
she recorded on the ensuing day the language of her soul, "`Oh Lord my God,
great and marvellous have been thy dealings with me!
My soul is led, in the depth of abasement and humility,
to bless thy ever adorable goodness and mercy, and renewedly to query,
'`What shall I render!`'`"

Ninth month 23d, she writes to her kind friend and efficient helper, Leonard Snowdon:

[.embedded-content-document.letter]
--

"`I have been much with the little company this day assembled.
May the blessed Shepherd be with you, and crown with his life-giving presence.
I shall esteem it a favour, thy giving me an account of what came before you,
who from the country have ventured in, with any thing that occurs, interesting to a poor,
wounded, and diseased prisoner, who knows not how the present trial may issue.
But I am endeavouring after entire resignation to the Lord`'s will herein.
This family are kind beyond description; divers Friends have been to see me,
and their company, with that of dear William Rotch and Martha Routh and companion,
have several times had a strengthening effect, so that I may adopt the language of David,
'`In the multitude of my thoughts within me, thy comforts delight my soul.`'`"

--

Under the same date she notes: "`In the afternoon dear Tamson Clifford walked here,
(two miles,) and made us an hour`'s visit.
She never appeared so lovely and amiable.
She took a most affectionate leave, and though Christiana Hustler offered her carriage,
she chose to walk, J. Hopkins and E. Howell going with her,
by whose return she sent me a present.
Alas, how frail and how short-sighted we are!
Little did we think it would be a final parting!`"
This lovely young woman had been Rebecca Jones`'s pupil.
She was taken alarmingly ill the next day, with the yellow fever, and in a few days died,
in such a condition that`" they were obliged to send to town for a rough coffin,
which was put on wheels, and brought by two men,
and in the evening was conveyed by them and two black servants, to the city,
for interment.`"
Rebecca Jones felt this circumstance keenly, yet, she says,
my soul rests satisfied that she is centred in the arms of everlasting Mercy.
We sat silent and sorrowful all the evening, in the chamber.`"

The following letter was written to the aged and afflicted mother of the deceased.

[.embedded-content-document.letter]
--

[.letter-heading]
To Anne Clifford.

[.signed-section-context-open]
Edgely, 10th mo. 2nd, 1797.

[.salutation]
My dear friend,

Such are my affectionate sympathetic feelings with
thee and thine in the present humbling and afflictive dispensation,
and such has been the tender solicitude of my soul on account of the dear deceased, who,
(though I always tenderly loved her,) was yet rendered in her last visit here,
more particularly near to me;
and such is my present comforting persuasion that she
has fallen asleep in the arms of everlasting Mercy,
that I cannot forbear manifesting my friendship in this way,
being unfit personally to attempt seeing thee,
which would not be wanting could I even bear the ride:
but the state of my bruised limb will not allow me to leave my chamber.
Mayest thou, my beloved friend,
though bereaved of so lovely and desirable an assistant in thy declining age,
experience the great Healer of breaches near thy drooping mind,
and by the consoling influences of his goodness,
which has followed thee all thy life long, be sustained in the present conflict,
and enabled with his deeply tried servant Job, to bless His ever adorable name,
who hath been pleased (doubtless in unerring wisdom,) to take
away even one of his choicest temporal blessings.
And may all her tender relations look up with submission and dedication of
soul to the one inexhaustible Source of all that is divinely good.
That he may be graciously pleased so to bless
and sanctify this present grievous affliction,
as that they may happily witness it to work for them "`a far move
exceeding and eternal weight of glory,`" is my ardent desire.

[.signed-section-closing]
Thy endeared friend,

[.signed-section-signature]
Rebecca Jones

--

The Yearly Meeting occurring during her imprisonment at Edgely,
her counsel was sought by various friends.
Martha Routh made her several visits,
in one of which they took a solemn and final farewell of each other.

On the 13th of 10th month,
her friends were cheered by seeing her seated by the parlor fire side.
On the 22d, C. Howell notes,
"`Rebecca Jones had a precious opportunity with the whole family collected, this evening.
Addressing the servants particularly, she said,
that though they might think that their advantages were not equal to others,
yet this was not the case,--that they were on a level with the King,
having the same principle placed, for their guide that he had, which,
when a wrong word was spoken, reproved therefor.`"
To a coloured man who had lived in the family more than twenty years,
she spoke encouragingly, and was afterward fervent in supplication.

On the 26th of 10th month, having left the house but twice since she entered it,
she took leave of her kind friends at Edgely, reciting, as she parted, the words of Paul,
"`The Lord give mercy to the house of Onesiphorus, for he hath oft refreshed me,
and was not ashamed of my chain;`" adding,
that whether for the accomplishment of complete sanctification,
their passage should be made rugged or smooth, it would not be long before, if faithful,
they should enter into a peaceful eternity.

Alluding shortly after, (in a letter to Martha Routh,) to the mitigation of her lameness,
she says, with that play upon words,
(pleasantly turning a trite subject into seriousness,) which
characterized her conversational and epistolary style,
"`What cause have I to walk softly, carefully, and humbly, all my days!
I wish I could say,`" she adds,
"`that a desire of this sort was evident in the conduct of the people at large.
But alas, I fear a greater chastisement will be found necessary,
more availingly to teach them righteousness.`"
