== Chapter XIV.

1802--1804.

Arrival of S. Stevenson and M. Jeffries,
and death of the former--Letters--Death of Hannah Price--William Jackson--Retires
to Edgely--Letters to James Allinson--Arrival of George Dillwyn--Returns to Brooks'
Court--Whale--Rebecca Jones and S. Smith in sympathy with Friends in England.

In her pocket almanac for 1802, she notes,--on New Year's day,
as we suppose--"`Forasmuch as the Lord in his infinite
mercy hath granted me a little longer space,
oh that a wise improvement of the present time may ensure to me,
when 'time shall be no longer,' an interest in his favour and mercy forever and ever.`"

She notes the arrival Second month 9th, in Philadelphia,
of Sarah Stephenson and M. Jeffries, and mentions Sarah Stephenson having,
in several meetings, "`good service.`"
"`Third month 8th,
Sarah Stephenson mentioned her concern to visit families in Pine street,
which they began the 9th.`" This Friend was taken sick the next day,
yet on the 11th she went to Germantown, and on the 31st returned to S. R. Fisher's,
and attended Pine street meeting.
"`She was taken ill, says Rebecca Jones, in the middle of the week,
and quietly breathed her last on Second-day, Fourth month 26th,
about seven o'clock P. M. She was interred on Fifth-day,
after a solemn and large meeting at High street.`"

As intimated above, the mortal remains of this virtuous, amiable,
and devoted woman and minister of Christ,
were taken into the meeting house on High street, where,
as we are informed by a Friend who was present,
a number of lively testimonies were borne to her devotedness and Christian graces.
Early in the meeting her bereaved companion, Mary Jeffries, was fervent in supplication.
She commenced with the text, "`As the heavens are high above the earth,
so are thy ways high above our ways;`"--and she implored divine aid,
that she might take with resignation the cup,
though comparable to the wormwood and the gall, saying,
"`thou hast given me to see that it is a sacrifice of thy own preparing,
and that her peace has thereby been sealed with thee.`"
She evinced, by her composure,
her striving to acquiesce in the unerring will--in the
evidence of which the minds of those present were humbled.
Several Friends, says our informant,
expressed their belief that she had come to this land in the ordering of best Wisdom;
and Nicholas Waln said,--"`she was the daughter of consolation;
had a lively ingathering gift,
being a real comforter to those who were thirsting after the living spring,`" etc.
And Hannah, wife of S. R. Fisher, spoke in a beautiful and moving strain, saying,
"`It is the end that crowns all,
and as I was favoured to see the close of this our beloved friend,
I believe it required of me to say, that as she lived the life of the righteous,
so she continued through her sickness, and in her death,
evincing that the sting of death was token away,
whereby she was made to triumph over death, hell, and the grave.
Oh, my beloveds, what encouragement is this to follow her example,
that by living the life of the righteous,
we may be favoured to make an end like unto theirs.`"

The interment took place in the Fourth street grave yard.

To her friend Mary Bevon she writes 5th mo.
1st--"`I by no means wish to take thee in any "`snare`" other than
such as true friendship and good old fashioned love dictates,
I say old fashioned, because thou knowest there is a deal of fancy goods,
and new fashioned stuffs now a days, brought into use,
and some of them of so flimsy a texture,
that they are hardly worth the cost of trimmings and making up--that
when I do meet with what I esteem substantial I am willing to clothe
others and be clothed therewith myself--even with that love which
doth not wax old like a garment--so hold on,
dear friend, in thy epistolary visits to the poor old woman, now in her 63rd year,
because she is cheered and comforted thereby.

I had heard of the removal of thy nephew R. P. B. and did think it would be as
deeply felt by thee and his worthy grandmother as any other of his connexions,
but he has happily escaped those temptations and trials that
in various shapes assail us who remain in the field,
and makes it necessary to put on, and to keep on, the whole armour of light,
in order that through watchfulness and prayer we may be able to stand!
This I do fully believe was the care and concern of thy country woman,
the late dear Sarah Stephenson of whose peaceful
close in the service of her blessed master,
thou wilt hear from others,
but as I was with her at the time and a witness to her
resignation and patience during the conflict,
I am free to inform thee that after her visit at New York to the families of members,
and such as stand disowned, she came to this city in a very infirm state of health,
and having begun a visit to families of Pine-street meeting, she evidently grew weaker.
In the week of our late yearly meeting, she became so much worse,
that hope of recovery was quite lost both by herself and her friends.
She however continued till the 26th ultimo, when she departed without sigh or groan,
divers friends being present.
She was interred the 29th, after a large and favoured meeting held on the occasion,
in which her companion, Mary Jeffries was bowed in supplication, and N. Waln, S. Smith,
M, Swett, etc., appeared in testimony, and W. Severy closed in prayer.
From all I can gather,
I find this dear friend was settled in the belief that
she should lay down her life in America;
and she will be long remembered, even as N. Waln testified of her in the meeting.
"`She was indeed a daughter of consolation, having a sweet, precious, gathering gift.`"
She is now happily released from pain and suffering.
Her dear companion, who faithfully attended on her,
is truly an object of tender sympathy, being now left solitary in a strange land.
But I trust she is under gracious care.
She has endeared herself, by her humility, to friends here.
She has a lively gift in the ministry, and will, I believe,
not go unrewarded by her good Master,
to whose dedicated servant she was sincerely attached in life,
and whom she forsook not in her last moments!`"

I am much of thy sentiment respecting Hannah Barnard's case.
I do hope the right thing will be done and that your women's Yearly
Meeting will be owned by the presence of the great Head of the Church,
which is composed of females as well as males,
who alike have need to move under a sense of their own weakness.
But why let the tormentor Fear in thee predominate?
Perfect love will cast it out.
He that feareth, saith the Apostle, is not made perfect in love.
And thoough; as, William Savery says,
'tis better to be dumb than to offer the sacrifice of fools,--yet even he often
declares that obedience is better than either a dumb or foolish sacrifice.
In short, my dear Mary, 'tis a great lesson, to become a fool;
and such we must be before we are made truly wise.
Take heed therefore to the gift thou hast received.
Do thou let it turn,
and be willing to turn with it--then whatsoever it doeth and whithersover it turneth,
it shall prosper.
See how freely I write to thee.
It is the fruit of that love,
which I felt in first entering thy house in Plow Court--
and in it I salute thee and thy beloved Joseph,
and bid you endearedly farewell, being thy affectionate fellow disciple.
William Jackson,--a man of simplicity, wisdom and sincerity,
has obtained credentials for a visit to your land.`"

Fifth month 8th she notes,--"`Died, Hannah, wife of Philip Price,
of whom it may be said she was among the meek and merciful,
and had marked upon her the blessing pronounced upon the peace makers.
I went with Sarah Harrison and S. Rhoads, to her burial, at Darby, the 10th,
where a solemn meeting was held.
Wm, Savery had the chief service.`"

Rebecca Jones to Joseph William^
footnote:[Parents of Philip Price, once superintendent at Westtown.
H+++.+++ P. was a valued Elder and Mother in Israel.]

Philadelphia Sixth month 9th, 1802.

My clear and worthy friend, Joseph Williams,--However,
"`short and scanty`" in thine own view, thy letter of Fourth month, I do assure thee,
the receipt of it has given me much pleasure;
and though all its contents were not of the most consoling kind,
thy account of your being more calm at present,
affords encouragement to hope that the late storm, in which thou, my brother,
hast been so closely tried, has nearly spent itself.
Be that as it may, I have no sort of doubt, that thou,
with others who have nobly contended for the Faith, as it is in Jesus,
will by the same faith obtain victory, according to that ancient truth,
"`This is your victory, even your Faith!`"

Thou wilt have heard, before this comes to hand,
of the peaceful transition of our late beloved Sarah Stephenson, from this mortal state,
to, we trust, a glorious immortality.
Her chosen companion, M. Jeffries, seeing her way to return to her own land,
and leaving a sweet savour here, will be likely soon to embark,
in company with our dear friend William Jackson.^
footnote:[ William Jackson, whose embarkation for Europe is here mentioned,
was one of the primitive stock of Friends to whom the
character given by our Lord to Nathaniel,
"`behold an Israelite indeed, in whom is no guile,`" might be justly applied.
His ministry was not with the enticing words of man's wisdom,
but remarkable for its weight and solemnity.
Though well acquainted with the doctrines and principles of the Society,
as illustrated by the standard authors among us,
his knowledge of divine things was evidently drawn from
a deeper spring than books or sermons could supply.
To those who had the privilege of an acquaintance with him,
and who could appreciate his worth,
he was a remarkably interesting and instructive companion;
his memory being stored with a large amount of information respecting those
worthy members who constituted the bone and sinew of the Society during a
period a little antecedent to his own.
{footnote-paragraph-split}
During the turmoils of the revolutionary war,
he paid an extensive visit to Friends in some of the Middle and Eastern States,
in which he sometimes appeared to have his life in his hand.
But walking by the faith that led him out,
he was guided safely through all his difficulties and dangers;
and after nearly two years thus employed, returned again to his native place,
in Chester county,
Pennsylvania.
{footnote-paragraph-split}
                After
the restoration of peace he performed a number of visits to
the meetings of Friends in several parts of this continent;
and from the testimonials which were received respecting these labours,
it appears he was enabled to adorn, by his own life and conversation,
the doctrines which he was concerned to preach to others.
{footnote-paragraph-split}
                The voyage to which Rebecca Jones refers,
terminated by his arrival at Liverpool, in the Eighth month, 1809;
and he spent about three years assiduously labouring in the work of the Gospel.
During this time he appears to have attended
nearly all the meetings of Friends in England,
Ireland and Scotland, as well as some parts of Wales, and a number of them several times.
In the brief memorials of this visit, which he left behind him,
and which the writer of this article had the opportunity of inspecting,
we find him patiently traveling from day to day, and from meeting to meeting,
where the members were reduced to a very small and feeble remnant,
seeking out and labouring to strengthen the seeking seed wherever
located.
{footnote-paragraph-split}
                In one of his
notices respecting the attendance of meetings for discipline,
many of which fell in the course of his journey,
he makes the following impressive observations: "`Oh, these meetings for discipline,
were they held and maintained in the wisdom and power of God,
the active members knowing their own wills subjected to His will,
and moving only as he moves them, either to speak or to be silent,
what schools of instruction would they be, both to the youth and those more advanced.
I am now in the fifty-ninth year of my age, and find myself but a learner,
and in need of daily instruction.`"
{footnote-paragraph-split}
He returned to his native land in the Autumn of 1805.
The ancient testimony of the Society, to live within the hounds of our circumstances,
and to avoid engaging in hazardous enterprises,
to the disturbance of our own tranquillity,
and the endangering of the property of others, lay very near to his heart;
often advising his friends, and particularly those who were just setting out in life,
to make their wants few,
and thus avoid the danger of being driven to doubtful or improper
expedients to supply them.
{footnote-paragraph-split}
Retaining his faculties in old age without visible decay,
he performed several short journeys, in the service of Society,
after he had passed his eightieth year; but about two years before his decease,
he found the disorder coming on,
which eventually terminated his pilgrimage here.
{footnote-paragraph-split}
                In the beginning of 1834,
while in the 88th year of his age, he was gathered as a shock of corn fully ripe,
to the place of his rest, weightily adopting, a few days before his removal,
the declaration of the Apostle, "`I have fought a good fight, I have kept the faith,
henceforth there is laid up for me a crown of rejoicing.`"--Ed. Friend's Review.]
When he arrives amongst you, receive him as a brother beloved,
"`if thou count me a partner.`"

I am now confined to my chamber, with rheumatism in one knee, which is much swelled,
and painful.
Since coming up stairs, I have been honoured with the company of dear S. Smith,
who is my frequent visitor, S. Harrison, who looks finely, William Savery,
a strong man in every way, and N. Waln, who is in good health,
and a bright example to the flock.
James Pemberton also sat an hour with me last Seventh-day.
He is near eighty, a firm pillar in the Lord's house, and his faculties,
except his hearing, are, I think, as bright as ever.
Thomas Scattergood and D. Bacon are also in an active, lively state,
and at our late Yearly Meeting in Fourth month, we had the company of R. Wright,
S+++.+++ Talbot and Phebe Speakman, with dear Mehetabel Jenkins, on a visit to these parts.
These were all in the love and life of the gospel,
so that there is yet cause to "`thank God and take courage,`" in believing that our
heavenly Father continues his blessed promise to His humble followers--"`Lo,
I am with you always, even to the end of the world.`"

How fares our old friend Jane Watson now?
I have lately felt so much about her that I have written to her.
Thine to Sarah Stephenson, says, "`M. Ridgway is going into the North of England.`"
What a brave old soldier is she!
If thou corresponds with dear Richard Jordan, present my love to him; also,
to all my acquaintances who have kept their habitations in the truth,
which I sincerely believe is the state of thy dear wife and self.
Accept, therefore, the cordial salutation, and offer it to thy sister, and son Nathaniel,
from thy old and affectionate friend,

Rebecca Jones

[.asterism]
'''

Philadelphia, 7th mo.
8th, 1802.

Dear friend, Mary Jeffries,--As I learn that thou art still detained at New York,
I seem as if I could not remain longer easy without giving
thee a few lines to manifest afresh my sisterly sympathy and
love before thou embarkest for thy native country,
where I do hope and trust, whatever may attend,
thou wilt arrive in safety and with the sheaves of enriching peace in thy bosom.
I am, my dear, sensible that thou hast had thy hidden conflicts amongst us,
and I have no doubt but He who sees in secret hath been
near to sustain and succor under them all.
What a blessed privilege this! that "`all the ways of a man
are before the eyes of the Lord,`" who understandeth every
secret sigh and silent tear of his humble dependent children.
To these He never said "`seek ye my face in vain.'
So that when restored to thy beloved relatives and friends,
thou wilt have to publish the Lord's gracious dealings, with the voice of thanksgiving,
and tell of his wondrous works--"`his wonders which thou hast seen in
the deep!`"--and this I desire thou mayst be encouraged to do,
whenever the word of command is "`Speak to my people that they go forward.`"

My love salutes dear W. Jackson,
a brother in the sufferings and consolations of the Gospel!
He dwells deep, and from thence often draws sweet counsel.
May he be strengthened with holy boldness and magnanimity to
wield the weapons of his warfare against all he may meet with,
that stands opposed to the cross of our Lord Jesus Christ--yea,
against "`Spiritual wickedness in high places.`"--May the
Shepherd of Israel be near you both in your floating enclosure,
"`hold the winds in his fists,`" for your sakes,
and often make you joyful in his House of Prayer,
and then bring into remembrance your infirm poor sister, thy affectionate friend,

Rebecca Jones

In the Eighth month, 1802, a fever broke out in her neighbourhood,
by which she notes that the inhabitants were so much terrified
that "`nearly one third of them removed into the country.`"
On the 10th she accepted the invitation of her "`faithful, invariable friend,`",
the hostess of Edgely, from whose country seat she writes to Sarah Hustler,
Ninth month 15th,--'Whether the people were unnecessarily alarmed,
or by the general removal, under Providence, the progress of the fever was checked,
I cannot tell, but the contagion has not spread as in '93, '97, '98, and '99,
so that there is fresh occasion for grateful,
humble thankfulness to the Father of all our mercies,
which my soul prays may be the clothing of all our spirits.`"
In the same letter she says: "`As thou hast wisely, and I trust, unreservedly,
yielded to the counsel and call of thy heavenly Father, Friend and Helper,
I have no doubt that,
as thou art enabled to persevere in the path of obedience to his holy will,
following the footsteps of thy pious parent, walking by the same rule,
minding the same thing to which she has from her youth evinced that
she has given the preference above every other consideration,
thou wilt also be helped to sing of the Lord's judgments, and of his mercies,
and adopt that ancient acknowledgment of pious David, 'Thou art my God,
I. will praise thee; my father's God, and I will exalt and serve thee.'
 

"`Though I am now in my sixty fourth year, and under many infirmities,
my interest in all that relates to your family is not at all lessened,
nor has my unfeigned love undergone any alteration or diminution,
since the day that my heavenly Master disposed the heart of thy
beloved mother to unite with my exercised spirit in his service.
The remembrance of some of our descendings and ascendings together,
with and for the Seed of Life, is often sweetly and pleasantly my theme,
in my solitary and silent musings, when, in the covenant of love and life,
I can feel her near to my spirit, and sweetly hail her 'highly favoured;' The Lord,
her sure support, being her staff, her salvation,
her evening song of rejoicing and praise.
We hear that George and Sarah Dillwyn are about to return to their native land.
What a treat I shall have thereby!
Also, that David Sands and Richard Jordan have bespoke certificates.
Samuel Smith, Thomas Scattergood, William Savery, N. Waln, S. Harrison,
and the rest known to thee, are well every way.
In love inexpressible, I salute you all,
and am thy cordial friend and sister in the Truth.`"

In a letter to James Allinson, 10th mo.
5th, 1802, referring to the arrival of George and Sarah Dillwyn, she says,

"`I have great joy in the prospect of our looking each
other in the face once more in mutability,
and can now wait with patience, postponing a visit for the present,
as some rest among their tender relatives and numerous friends must be desirable.
May the great Preserver of men, now and forever worthy, be praised!
I expect we shall discover visible marks of age in each other,
and I trust that we shall unitedly set up our Ebenezer together,
on our own dear native shore.
I am quietly at anchor in Liberty Hall,
not having even the pleasing prospect of a quiet return to our poor
city which by accounts is far from safe--new cases occurring,
and my little habitation in the neighbourhood of infection.
I have concluded to stay at Edgely till the inhabitants of our court shall move back.
Thomas Scattergood paid us a pleasant visit.
William Savery is well, and much engaged about the sick and poor in his neighbourhood.
May the Father of mercies be pleased in his own time to grant
us a comfortable meeting in our North Meeting House again,
and the desire of my heart whilst writing is,
that I and all of us may return with spirits clothed upon with humility,
gratitude and thankfulness to the great and blessed Author of all good.

I salute thee, dear James, as a fellow disciple,
and crave thy preservation and perseverance in the cause of Truth and Salvation.`"
Referring a few days later, in a letter to the same friend,
to the arrival of George and Sarah Dillwyn, she says,
"`Oh how pleased I should have been to join their party.
I hope dear Susan Emlen will be revived by the presence of her beloved uncle and aunt,
and that you all,
who are capable of feeling the bond of Christian union and best fellowship strengthened,
will be qualified to acknowledge that the great Head of the Church,
who puts forth his own and goes before them,
is worthy to be trusted in and blessed forever.`"

Rebecca Jones

Writing 11th mo.
1st to Martha Routh, then at N. York, she says:
"`I note with pleasure thy intention of spending
some time this winter in and near our city,
where, as heretofore, I have no doubt thou wilt find an open door,
and be received as an ambassador for Christ.
I do believe, my dear, notwithstanding thou hadst some bitter cups to drink among us,
thy circumspect walking and gospel labours will be long remembered animatingly,
and thy return to this city be truly acceptable
to many more than thou hast been acquainted with,
besides myself and my Bernice Chattin Probably thy tent will be pitched in the old spot,
(Samuel Fisher's) a place in which such poor old creatures as I, can use great freedom,
and from whence the spirit of our dear sister S.
Stephenson took its flight from sorrow and suffering.
I expect thou hast heard of the return of dear George and Sarah Dillwyn,
and Joseph and Beulah Sansom, and also that dear William Jackson and M. Jeffries,
have been favoured with a safe though tedious passage of 38 days to Liverpool,
and that dear Richard Jordan has arrived,
all which calls for our united thankfulness to the great preserver of men.

Our devoted brethren, William Savery and Thomas Scattergood,
with dear Sarah Harrison and divers other fellow labourers,
have staid in the city through all the sickness.
W+++.+++ S. has been much in it, visiting and administering to the poor of all societies,
our own especially.
S+++.+++ Smith and wife, with myself and many others, have been most easy in leaving it,
and have all, I believe, been of more use than poor me,
as I have been kept very much confined to the poor little flock at Germantown,
where the Lord on high has often mercifully
granted the needful supplies of heavenly bread.`"

She returned to her home in Brook's Court 11th mo.
5th,
and notes her thankfulness in finding the city "`once
more filled with its inhabitants in their usual health;
very few, compared with the numbers formerly taken off by this dire disease,
having fallen victims under the present visitation.`"

In a letter written 12th mo.
9th, to Joseph Williams of Dublin,
she thus evinces her continued fervent love to the disciples,
and her constant desire to know how the Master's
work sped in distant parts of the vineyard.

"`I wish to be affectionately remembered to thy family,
and to such of my friends in your city as keep their habitation in the blessed Truth;
and that thou wouldst sometimes give me a few lines
with what information thou mayest judge proper;
for poor and low and old as I am,
I trust the precious cause and testimony are as dear to me as ever,
and therefore I cannot be indifferent to the many
attempts that are being made to lay them waste,
with you, and also in this land.
I salute thee, dear Joseph, in gospel affection,
and trust that thy bow may abide in strength,
and the arms of thy hands be made strong by the hands of the mighty God of Jacob.

"`Our friend Richard Jordan spent an afternoon with me lately; he looks well every way.
So also are all our dear friends who have visited your country.
I hope innocent Joseph Cloud gets on with you safely.
I almost long for David Sands' release.
If thou seest William Jackson, who is a dear brother of mine; present him with my love.
By a letter from dear Mary Jeffries, I find that she arrived safely at home,
and is in the enjoyment of true peace.`"
"`'Tis pleasant,`" she says to the same friend shortly afterward, "`to converse,
even in this way, with fellow travellers,
who are fast sailing towards that better country where all sorrow,
disappointment and pain will forever cease.`"

Early in the spring of 1803,
having suffered greatly from rheumatism and an attack of influenza, she notes,
"`I have never passed such a winter as this has been--yet withal have abundant
proof that now in advanced age I am gently and tenderly dealt with.`"
On the same day she remarks, that if she were free from rheumatism,
she might have something worse to bear.

To Joseph Williams she writes 3rd mo.
7th, 1803, "`I perceive that a portion of sorrow and suffering is permitted,
sufficient to keep alive thy soul's desire after enjoyments pure and unchangeable.
May we, dear friend, maintain the warfare,
and retain holy confidence in the unconquerable Captain of our Salvation,
whose power is not only able to change our water into wine whilst here,
but can graciously cause all things to work together for our good,
both here and for ever.
Our dear George and Sarah Dillwyn have dropped anchor in the
quiet port of their dear Burlington since their return.
We have exchanged some letters, but have not, as yet, met.`"

In the summer of 1803, her steadfast friend,
the hostess of Edgely,--a playmate of her infancy--wrote to Rebecca Jones,
offering her a home during the sickly season; "`on reading which,`" says Rebecca Jones,
"`my heart exclaimed with the apostle, 'who shall separate us from the love of Christ?'
etc. May that peace of mind which has been attendant in all
thy works and labour of love towards the Great Master,
and for the comfort of some of the little ones be increased by
thy late sisterly offer to accommodate even poor,
unworthy me, once more, in the day of trouble.
I am under depression on divers accounts; pray for me when thou canst,
that I may 'approve myself unto God,' in the midst of a crooked and perverse generation,
in this as well as other places, where I desire to be content with my allotment.`"
This invitation was not accepted,
as she decided to take her temporary abode in the neighbourhood of Darby,
whence she writes to K. Howell,
Ninth month 17th--"`To receive from under thy hand an acknowledgment--which
my own heart has often been sensible of on thy account--that 'the
inestimable blessing of divine aid and support' was so richly thy experience,
did, on opening the joint salutation of thyself and dear Elizabeth,
sweetly contrite my spirit: fully believing that,
as 'Mercy and Goodness have followed us all the days of our
lives,' so whilst we prefer a dwelling in the Lord's house,
or service, they will be continued to us Forever And Ever.`"

And to her daughter, Elizabeth Howell,
she writes on the same date--"`Ye are as epistles written on the tablet of my heart, and,
in seasons of unmerited mercy and favour,
ye are--as dear S. R. Grubb said to me in a letter a little before
her exit--'interwoven in my solicitude for heavenly help.'
Keep me in your remembrance.
The restoration of thy health is a fresh proof of the fatherly
care of Him who is justly styled The Lord That Healeth;
and the reward of thy late dedication will, I trust,
stimulate to an increased surrender of soul to the further requirings of Him, who,
'as a father pitieth his children, doth pity those who love and fear him.'
My heart inclines towards the willing in Israel, and though I now am poor and sorrowful,
my trust is in the Lord Almighty, and my mind is stayed upon his eternal arm of power,
who, blessed be his name, hath done great things for me,
and is worthy of the obedient acknowledgment of my whole life.`"

First month 1st, 1S04. "`I was,`" she notes, "`at our North Meeting,
being the beginning of another year, and was enabled to express my thoughts thereon.`"

First month 15th. "`First-day.--Had a good meeting this morning.
The prevalent sense of my mind is,
a want of greater fitness to fill up my measure of duty to my great Lord and Master;
and more sanctification of body, soul and spirit,
to meet him with acceptance both here and forever.`"

"`Search, Lord, and purify my heart,

And make it clean in every part,

And when 'lis clean, Lord keep it so,

For that is more than I can do.`"

"`Third month 17th. After performance of a church visit in the evening,
went to J. Pemberton's to see dear Martha Routh, who reached the city about noon.
Thomas Scattergood came home with me.
Some of our young people went to see a whale which was exhibited up town,
about two-thirds grown, 33 feet in length, and 18 feet in circumference.`"

This whale was seen floundering on the shores of the Delaware,
by two men who were ploughing near Chester.
They loosed their oxen from the plow, and drew the whale beyond the reach of the tide.
The news soon reached Philadelphia.
Thomas Prior purchased it at a price which the men considered liberal,
and brought it up to Kensington, where it was exhibited;
the mouth being kept open by a tackle,
and a high backed arm chair placed within for visitors,
which seat some of our gentle readers will remember having occupied.

Third month 27th,
she mentions "`the passing of five couples`" at the Northern Monthly Meeting;
and some leaving the meeting in an irregular manner, she suitably noticed the disorder,
"`and such as staid quietly were encouraged.`"
Martha Routh gave in a certificate from New Bedford,
and Rebecca Jones accompanied her to the men's meeting,
"`where she had some lively and edifying service.`"
"`Last Second day four weeks,`" she adds,
"`both Samuel Smith and myself were so dipped in
near sympathy with our friends in England,
that we were constrained to mention it to our morning meeting of ministers and elders;
and we are still anxious about them, under a belief that they, with the nation,
are in deep suffering.^
footnote:[I do not discover any allusions from which we
can certainly decide to what circumstance she refers;
or whether there were then any unusual trials to which Friends in England were exposed,
except such as might be apprehended from the condition of public affairs;
but as she speaks of the nation being in suffering,
we may reasonably infer that her sensitive mind, as well as that of Samuel Smith,
was deeply pained with the calamities then impending over the British nation.
After the English and French had passed a number
of years in wasting the strength of each other,
they formed a treaty of peace in 1801.
But this short-lived pacification was broken in 1803,
by the pride and ambition of their rulers.
Napoleon Buonaparte, who held the chief power in France,
had openly declared to the British minister, Whitworth,
that in case hostilities were renewed,
he was determined to make a descent in person on the English coast.
Hostilities were renewed some months before this letter was written,
and numerous armaments were stationed in the ports of the continent,
which lie opposite to the island.
This circumstance naturally excited unusual alarm,
and unavoidably produced much solicitude among Friends,
lest under these trying emergencies their testimony
against war should not be faithfully maintained;
or that considerable suffering might be experienced in
supporting it.Never since the days of William of Normandy,
had the people of England been subjected to the miseries of a hostile invasion,
under a foreign leader.
And the consequences of that invasion were not forgotten in the time of George the Third.
The injury to be apprehended in 1804, from an inundation of foreign invaders,
was incomparably greater than it could be in 1066. For the
property which was liable to be plundered or destroyed,
in the beginning of the ninteenth century, within the limits of a single parish,
was probably greater than could be found in the Island,
when William landed his Norman host on the coast
of Sussex.To a mind like that of Rebecca Jones,
the prospect of having the fields over which she had passed a few
years before with her message of peace on earth and good will to man,
overspread with the desolating legions of France,
and exposed to all the horrors of an invasion,
such as has turned some of the fairest portions of continental Europe into a desert,
must have been painful in the extreme.
Her pious reflection, that the Lord was able to deliver them from all their affliction,
is fully proved by events to have been entirely just.
And it was cause of thankfulness to the great Disposer of events,
that so great a calamity was not permitted to fall on
the English nation.--Editor of Friend's Review.]
But the Lord is able to deliver them out of all their afflictions--may it be so,
saith my poor soul.`"

Third month 28th. Thomas Scattergood came and
gave a more favourable account of William Savery,
who, for some weeks past, appears in declining health, and has had a paralytic affection;
also symptoms of dropsy.
The prospect of losing so valuable a member of our society,
is a close trial to his near friends.`"

"`Fourth month 14th. Seventh day.--The Yearly Meeting of Ministers and Elders,
began at 10 and again at 3; both were large and solid sittings.
15th. Both our meetings were very large--both houses full.
Second day the 16th. The Meeting for Business commenced and ended on the 20th,
about l£ o'clock.
All the meetings were large and much favoured.`"
"`24th. Martha Routh and M. Mifflin attended our Monthly Meeting.
Six couples passed.`"

About this time are noted many visits to the sick,
frequently in association with Martha Routh;
also memoranda of the death of many of her acquaintances;
and of visits received from her friends,
the catalogue of whom presents a noble array of individuals,
whose qualities and Christian graces would have ennobled any age or country.
Whilst, for the sake of brevity, we have, in omitting these,
omitted a very considerable portion of her diaries;
we have been touched in the contemplation of the train of redeemed ones,
who doubtless have "`through faith, obtained the resurrection,
and eternal holy life,`" and been merged in the "`innumerable company`" to
whom we are assured that the subject of these memoirs has also been joined.

Richard Routh and Jesse Kersey being about to embark for England,
Rebecca Jones went with Martha Routh and several
friends to visit the ship on the 30th of Fifth month,
on which day she notes--"`John and Ann Warder, intending for Newport Y. Meeting,
kindly offered me a seat in their carriage, which, for a time, looked pleasant;
but this prospect having clouded over, I informed Ann that I had quite given it up,
at which she was much affected, having been pleased with the idea of my company.`"

