== Chapter XV.

[.chapter-subtitle--blurb]
1804.

[.chapter-synopsis]
* Death of William Savery
* Jacob Beck`'s lines on the occasion
* Letters and notes
* New Year`'s reflections 1805
* Ann Alexander
* Yearly Meeting
* Martha Routh sails for England
* Letter to M. R.
* Dorothy Ripley
* Death of B. Cathrall and wife, and Rachel Collins
* Yellow Fever
* Goes to Darby
* Interesting letter to Mary Bevan
* Returns to the Court

"`Sixth month 19th, 1804.--Third-day.
This morning, before I was up, Ruth Ely sent to let me know that our endeared brother,
William Savery, departed about six o`'clock, very quietly,
though unexpectedly at the time, having rode out the day before,
and seemed rather better.
But in the night the dropsical symptoms increased, and the water rising,
it is believed proved suffocating.
His last words were "`glory to God!`"
His remains were kept till 3 o`'clock on Fourth-day, when,
instead of taking him to the burial ground, he was, at Martha Routh`'s request,
taken to our North Meeting House,
where Martha Routh had a short testimony to his worth as a minister, fellow member,
and fellow citizen, greatly beloved for the work`'s sake.
Elizabeth Foulke appeared in prayer,
and in a very heavy rain his body was taken to our ground, and decently interred there.

[verse]
____
"`While the glad soul borne on some cherub`'s wing,
Attends the throne of her celestial King,
To claim the promised Palm in JESUS`' name,
And join in worship with a seraph`'s flame.`"
____

"`Thus it is, my contemporaries, friends, and acquaintances,
are called hence one after another, and I,
a monument of divine mercy and compassion, am spared a little longer.
May the deep enquiry, __for what end?__
be constantly with me, and may my blessed Lord and Master enable me,
with increasing diligence,
to finish the work he has given me to do;--so as that I also may end in peace,
with the like triumphant song of '`glory to God in the highest,`' is my fervent prayer.

"`Now this 21st of Sixth month, great and heavy rains have fallen for three days past,
without much intermission; also much rain in the past week,
It is feared that the grain will be nearly lost,
as well as the hay.abundance of which has perished.
What a humbling prospect this affords to us poor, short-sighted mortals.
Truly we are nothing, nor can do any thing, in promoting temporal or spiritual good,
without the Lord is pleased to bless the work in and for us.`"

In Front street, opposite the end of Brook`'s court, stood, at the time of which we write,
Peter Brown`'s blacksmith shop, where was employed as foreman, Jacob B., an elderly man,
and a sober minded Methodist, who had lost three daughters in the yellow fever of 1802.
William Savery had in this, as in many other instances, devoted much personal attention,
at the risk of his own life.
A few days after the decease of William Savery,
this man went up the Court to fill his noggin at Rebecca Jones`'s pump, which,
on account of the quality of the water,
was resorted to by persona from many squares distant.
Seeing her seated by her open window, he accosted her.
"`May be you won`'t have any objections to hearing a hymn I`'ve made to
sing over my work;`" adding that it helped his mind to soar,
while his hands were engaged in necessary labour.
He then proceeded to sing his verses with much emotion, which,
with no claim to poetical elegance,
contained a warm expression of regard for the virtues and value of William Savery,
clearly showing that a memorial to the worth of this "`disinterested and faithful
minister of Christ,`" as his venerable biographer has appropriately styled him,
lived in the hearts of others than his own people.
And truly his solicitude to do good to the bodies and souls of men,
was limited by no sectarian boundary.^
footnote:[Although this "`hymn`" (as he styled
it) was certainly not intended to create a smile,
a sample of it may as a curiosity amuse the reader.
`    "`Oh the nineteenth of June Eighteen hundred and four,
     Was a sorrowful day to full many a score
     Of the children of Adam--for on that sad day
     The spirit of Savery did thus soar away
     To the regions of bliss and of endless delight,
     Where Jesus does reign and there is no night--
     For He is the Sun that enlightens the land,
     And Savery the faithful stands at his right hand.`" `]

Seventh month 18th. After noting a recent failure of her health,
she adds,--"`Yet I have mostly attended meetings,
where once S. Starr and Thomas Scattergood were prophetic,
in prospect of some impending calamity, for which, may the Lord prepare us.`"

Having during a brief absence from home, attended meetings, she notes, Tenth month 8th,
"`Martha Routh is still in Jersey, labouring for the good of souls.
Ann Alexander and companion, and Joseph Bowne, reached this city the 29th,
and left it the 6th, for Baltimore Yearly Meeting, expecting to move towards Carolina, etc.
This morning Joseph Bowne, on his return, called at my house.
The mercy of God is indeed inexpressibly great to us poor creatures, and humility,
gratitude and fear, ought to be our clothing,
under the signal display of his kindness in sparing us this summer from the yellow fever,
about which my fellow citizens were greatly
intimidated in the time of its usual approach.
May my soul forever bear in mind the Lord`'s goodness to me, a poor unworthy creature,
in raising me again from the bed of languishing under that sore disease,
in the year 1793.
Just eleven years ago, wanting three days, was I seized therewith.
Oh, it is the renewed anniversary of a very solemn time to me.
Joseph Cloud, who has lately returned from Great Britain,
took a solemn farewell at our meeting yesterday morning,
intending to go to his native home, in North Carolina.`"

[.embedded-content-document.letter]
--

[.letter-heading]
To Martha Allinson.

[.signed-section-context-open]
Philadelphia, 10th mo. 27th, 1804.

[.salutation]
My Dear Friend,

Thy sisterly disposition to oblige a feeling fellow pilgrim,
claims my sincere and grateful acknowledgment.
I am deficient in my returns to thy last two very acceptable epistles,
and hope thou wilt continue to feel love enough in thy heart,
to induce thee to forgive past omissions, and to write freely whenever thou art,
by the great and good Remembrancer, reminded of poor me.
I can assure thee that I do love all my Burlington friends.
I had your last Quarterly meeting in contemplation, but failed in that,
as I have in many other instances, when I came to put things in the right balance.

Please accept the enclosed,--they are to be valued only
on account of their being manufactured by the Friends,
whilst prisoners at York Castle, Great Britain, for their testimony against tithes.

I expect thou hast heard of dear A. Alexander`'s movements,
and that W. C. has family visiting before him, to begin at Pine street.
I have not forgotten any of my old fellow travellers--no not
even those who reside in and near the quiet city of Burlington.
George and Sarah Dillwyn, I and A. Cox, S. and Samuel Emlen, the Hoskinses, the Smiths,
the Morrises etc., etc.

--

"`Eleventh month 1st.--I have endeavoured to look at my friend Martha Routh`'
s proposal for me to join her proposed family visit to our disowned members,
but cannot find that it is my business,
nor that my bodily powers are equal to such an exposure, the ensuing winter.`"

"`7th. Our Quarterly Meeting, held the 3rd and 5th, was large and favoured.
Martha Routh, Martha Allinson, L. Hoskins, C. Cook, etc. etc., attended it.
On Third-day, the 6th, our week day meeting, and a large one for the black people,
which was solemn.
Thomas Scattergood had the service.`"

"`10th. Great depression of both body and mind attended me, insomuch,
that at seasons I was indeed ready to conclude myself
altogether unworthy of the notice even of my dear friends.
But I endeavoured to look up to, and put my trust in my alone Friend, Benefactor,
and Saviour, whose compassion is unfailing, and whose mercies are new every morning.
Blessed be his holy Name--Great is his faithfulness--great his Truth!`"

"`First-day morning, the 11th, got to our meeting,
and felt a renewal of the spirit of prayer, which bowed both mind and body under it.`"

"`Twelfth month 4th. At our Monthly Meeting a solemn quiet prevailed.
Our brethren were engaged about a testimony for our late brother W. Savery,
of which S. Smith gave me a satisfactory account.^
footnote:[For this testimony of Northern District Monthly Meeting,
and for an interesting and instructive biography of William Savery, compiled by,
Jonathan Evans, see [.book-title]#Friends`'Library,# vol. 1.]
On Third-day, the 11th, our meeting was a season of great favour,
through the ministry of J. Simpson and Thomas Scattergood.
Next day, being in company with dear Rebecca Wright,
she and I took sweet counsel together, and her spirit and company were precious to me,
as in former years.`"

"`First month 1st, 1805.--Now opens another year,
and that I am spared to this time is marvellous in my eyes.
O Lord my God, be graciously pleased to look down with an eye of compassion upon me,
now in my declining years, even as thou, in thy adorable goodness and mercy,
didst in the days of my youth, when being but sixteen years of age,
thy gracious visitation of pardoning Love, Grace,
and Salvation plucked my soul as a brand from the burning,
cast thy mantle of forgiveness and mercy over me, and with a powerful voice said unto me,
'`Live.`'
Every part of thy blessed covenant, thou, my heavenly Father,
hast fulfilled--no part thereof hast thou broken.
Thou hast supplied me with all things necessary, so that I have not lacked anything!
I have often broken my covenant with thee; I have repeatedly transgressed,
and thou hast abundantly pardoned.
Continue thy rod and thy staff to the end of my days here, and oh,
For Thy Dear Son`'s Sake, grant my poor soul an admission into everlasting rest,
when it shall please thee to call me hence, is, thou knowest,
my fervent prayer this evening.
Eight O`'clock.`"

"`Second month 2nd. Seventh-day.--Went to our Select Quarterly Meeting with N. Waln,
in his carriage.
John Letchworth was received a minister,
and two elders and a minister from Muncy were accepted.`"

"`11th. Ann Alexander had weighty service at meeting.
I stopped to hear and judge of an epistle from Ann
Alexander to the inhabitants of Charlestown.`"

Rebecca Jones being closely united with her friend Ann Alexander,
notes frequent attendance of meetings with her;
among others she mentions "`large and much favoured meetings`" held by her appointment,
for the inhabitants at large, on the 19th, 20th, and 21st of Third month.
"`Ann Alexander was silent,`" she writes, "`in that at Pine street.
George Dillwyn had been with her and her company to
Westtown school and to some meetings in Chester county,
so he stayed to those three meetings, and had good service there.`"
Fourth month 5th, I went with A. Alexander to the scholars meeting,^
footnote:[Meetings were held for the pupils of Friends`'
schools at the corner of Fourth and Chestnut streets.]
and afterwards to see all the Friends in our almshouses.`"^
footnote:[Some readers may possibly be unaware
that these houses were provided by Friends,
for the comfort and respectable residence of their own poor,
no Friend being allowed to come upon the public for maintenance.]

"`Fifth month 1st. Since the last note our Yearly Meeting has been held,
and though throughout it was a low time,
yet a good degree of weight and solemnity attended, and, I trust,
some strength and encouragement were received by the true burden bearers.
The women`'s meetings were held in the new house built for that purpose,
in Arch street burying ground, and was very large.
It was said by some men Friends who took the account,
that sixteen hundred were accommodated in it.
George Dillwyn and W. C. made us a visit, and were lively in their service.
Charity Cook and Ann Alexander visited the men`'s meeting,
in which the latter had a lively testimony.
I was marvellously supported in sitting so many long meetings,
and for which I desire to be humbly thankful to my ever blessed Helper and sure Friend.
The meeting ended on Seventh-day, about 11 o`'clock, but not as soon as we wished,
and hoped it would.
Yesterday a meeting for other societies was held at the Arch street house,
at C. Cook`'s desire, in which she and W. C. had the service,
and the people were greatly disappointed in not having A. Alexander,
who has great acceptance and place with our own and other societies.
I went with Ann Alexander to visit all the Friends in our alms houses,
and to the three schools in our Northern house,
in which she had something lively to offer.`"

"`Fifth month 5th. A. Alexander had a large meeting for the inhabitants of this city,
in our new house on Arch street, and was greatly favoured therein,
as also at our Quarterly Meeting, which Martha Routh attended in silence.
On the 9th was held the Quarterly Meeting for the black people,
and was the last meeting of the sort, as Friends, upon weighty deliberation,
were united in the belief that the service of them was over,
and they have now several places for worship of their own;
of which they were very judiciously and affectionately informed by Nicholas Waln,
and the meeting ended with solemnity.
At this meeting Ann Alexander was remarkably engaged in testimony.`"

"`8th. Although very poorly, I rose timely for going to John Warder`'s,
from whence Ann Alexander took her departure for the Yearly Meeting at New York,
intending from thence to take her passage to Ireland.
We parted in the love of our heavenly Father,
and my prayers are for her preservation every way, as for my own soul.`"

"`After this I went but little out except to our own meeting,
and in attending to business relative thereto, till the 25th,
when I went to James Pemberton`'s and took an affectionate leave of dear Martha Routh,
who about noon went on board the ship Rose, Capt.
Hathaway, bound for Liverpool.
May divine Mercy be with her,
and protect and carry her in safety and peace to her desired port,
is my fervent prayer.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Martha Routh.

[.signed-section-context-open]
Philadelphia, 5th mo. 29th, 1805.

[.salutation]
My dearly beloved friend and sister,

Feeling my heart this morning
renewedly bound to thee in the precious fellowship of the gospel,
in the afflictions whereof I have also often been thy companion,
I have called for pen and ink, to salute thee on board the Rose.
And perhaps my salutation may soon after thy arrival be put into thy band.

My feelings on parting with thee at James Pemberton`'s last Seventh-day,
amidst such a concourse of thy friends, were indescribable,
fully believing that though we may never more meet in mutability,
our spirits will not be separated by either distance of time or space.
I don`'t dare to say that thou wilt never see America again;
that and all future events I desire to leave to thy blessed Master,
who hath often made a way for thee, even when thou couldst sec no way.
And he will not forsake thee, nor suffer thee to become desolate, "`Because he +++[+++also she]
hath set his love upon me, therefore will I deliver him; I will set him on high,
because he hath known my name; he shall call upon me, and I will answer him,`"etc.
Read the 91st Psalm.
This gracious promise, so replete with Mercy and Goodness,
springs sweetly in my remembrance, as a portion especially designed for thy inheritance,
now, after thy retreat from our labourious field, wherein thou hast not fainted,
nor thy store-house exhausted,
but to the very last thy horn hath been so evidently replenished from the all
bounteous fountain as that no vessel on thy departure was sent empty away.
Well, my dear friend, count it no strange thing if thy faith and patience be again proved.
Thou knowest too well the danger of pleasant things,
to look for or desire them further than in the will of Him who doeth all things well,
and who hath, in the promise alluded to,
given thee the fullest assurance of his care and protection through thy
painful pilgrimage--thy Alpha indeed--and will also reward thy unwearied
endeavours to promote his blessed cause and testimony on earth,
with a peaceful admission among his faithful servants,
when thy tribulations and labours are over--thy ever blessed Omega--thy "`evening song.`"

After meeting on First-day, I took a pensive walk to thy late quarters,
and with J. and P. Pemberton communed about thee.
We concluded that we loved thee quite as well as fellow disciples ought,
so that I came home fully paid for my walk.

I wanted, only I feared interrupting thy exercise, which was to befell,
to desire thee to tell my friends in England,
my dear Christiana Hustler and daughter in particular, also J. and E. Bludwick, J. Thorp,
S+++.+++ Benson and children, Richard Reynolds, Deborah Darby, and her sisters M. and Sarah,
R+++.+++ Young, etc. etc., that I am fast growing old, and my sight being dim,
prevents my saluting them on paper; but that my love continues strong for them,
and for all who love and live near the blessed Truth.

From Friends at New Bedford and elsewhere I have no doubt thou wilt receive many letters;
and mine, if it get not first to hand, may be left awhile, as from a poor old Scribe,
yet no Pharisee,
but thy sincere and unabated friend and sister in the sufferings of the present day.

[.signed-section-closing]
Oh do let me hear soon from thee,

[.signed-section-signature]
Rebecca Jones

--

"`Sixth month 27th, 1805.--Saw a paragraph taken from a York paper,
certifying that Dorothy Ripley is not a member of the Society of Friends.
Received letters from Henry Tuke, D. Darby, R. Y. Byrd, John Waring, Martha Routh,
etc. etc., and visits from Samuel Emlen, George Dillwyn, Richard Hartshorne,
John Hoskins, and several other Friends.
Answered divers English letters.`"

"`Seventh month 8th. Ann Alexander, S. Proctor, and John Warder, Jr.,
sailed the 27th of last month, in the ship Wm. Penn.
Stephen Grellet came yesterday to see me.
He is on a visit to Friends in the compass of this Yearly Meeting.
Heard that Dorothy Ripley is holding meetings about New York, and passes for a Friend,
and that she is coming to this city.
Friends of High street,
last Fifth day removed their week-day meeting to the new house on Arch-street.
16th. Thomas Scattergood took an affectionate leave of our North Meeting.
He is bound in spirit to the boarding school at Westtown.`"

Her friend Benjamin Cathrall being ill, Rebecca Jones made him many visits,
and on the 22d of Seventh month she notes his quiet departure, adding,
"`I always thought him more in religious substance than show.
I believe he was a man of integrity,
and that he has gone to the mansions of the blessed.`"
His widow`'s decease she also records, on the 16th of the ensuing month,
by which event Hannah Cathrall being deprived of her home,
Rebecca Jones`'s sympathies were called into exercise,
until a suitable abode was furnished for her old friend and former partner,
then in declining health, with Hannah, widow of Isaac Cathrall, sr.
"`I hope`" says Rebecca Jones, "`she will be rewarded with peace for so doing.`"
"`My old friend and fellow-labourer, Samuel Smith,`" she says, "`seems declining,
and the prospect of a further stripping to our North Meeting,
feels heavy to my poor weak mind, but it is our business to learn to say in truth,
'`The Lord`'s will be done.`'`"

The yellow fever broke out in the Eighth month, in Southwark,
"`as low down as Christian street,`" and considerable alarm was excited.
Rebecca Jones had however, previously determined, on account of the heat,
to leave the city,
and on the 22d she and her small family went to "`Kingsess farm,`" near Darby.
The fever spread beyond her anticipation, and some of her friends died in it;
also a number of deaths occurred near her residence.
In reference to this, she says,
about two months subsequently,--"`When I reflect on the
awfulness of this and former similar dispensations,
my soul is humbled within me, and a fervent prayer is raised in my soul, that I, for one,
and that all, may so humbly bow under the Lord`'s hand,
which has been so often stretched out in judgment,
as that we may all learn righteousness, and so, through Divine assistance,
order our conversation aright, as to bring honour and glory to the Name of the Most High,
and thereby obtain eternal salvation.
Even so be it, Lord, amen!`"
To S. Smith, near the same date, she remarks,
"`Many of the contemporaries of my youth being by death and otherwise, removed,
I seem stripped and lonely, and feel no inclination to begin a new circle,
so that with regret I shall part with any more of the few who remain,
with whom I have been united in the bond of Christian fellowship,
drinking together at the one inexhaustible fountain of love and life.`"
She notes that New York was at the same time "`largely
and mortally`" affected by the same contagion,
and that Rachel, wife of Isaac Collins, is deceased with it,`" adding,
"`she was an amiable woman, and will be greatly missed.`"

This lovely, accomplished and excellent woman died 9 Mo. 14th,
1805,--and her loss excited general sympathy with her bereaved husband and her
children (13 in number.) A Journal of that day speaks of "`her many virtues,
her sweetness of disposition, suavity of manners,
and uncommonly cultivated and well informed mind,
which shone conspicuously in the best improved society.`"
George Dillwyn, in a letter to Isaac Coliins, senior,
on the subject says--"`I have often noticed,
that such intelligence has been preceded by an uncommon
depression of mind,`"--and describing his heaviness of heart,
which had continued without intermission, until the account was brought to him,
he adds--"`Such intelligence, we might naturally suppose,
was more likely to increase than abate sorrow;
but truly it proved like rolling a stone from a well`'s mouth; a tendering joy arose,
and settled in a quieting,
clear persuasion (which still survives,) that all is
well and forever well with dear Rachel Collins.`"

To Mary, wife of Joseph Gurney Bevan, she writes Ninth month 23d, as follows:

[.embedded-content-document.letter]
--

"`The reading of thy very acceptable and interesting
letter of 26th and 27th of Seventh mo.,
was indeed '`like cold water to a thirsty soul,`'
for notwithstanding thy own account of thyself,
thy jealousies, thy fears,
my own mind was solaced in the belief that thou art deepening
in the ground of living concern for the promoting of the one
blessed cause of Truth and Righteousness,
and the preservation of our fellow disciples in all their united endeavours,
that all may, by keeping in their proper ranks, move safely and wisely,
and the great and blessed Head of his own church be looked to, waited reverently upon,
and obeyed and honoured in and over all, in time and eternity.
A concern like this, not of our own but of the heavenly Father`'s begetting,
if rightly cherished and yielded to, must and will most assuredly,
draw down his peculiar notice and approbation; be promotive of increasing labour,
and eventually crowned with the blessing of soul enriching peace.
So do be encouraged, for now is thy time, to press forward in all things,
in obedience to manifested duty.
And in more important service, such as our large annual assemblies,
fear not to sound the alarm in times of danger,
such as the multiplying of words without knowledge, bringing, as Esther Tuke once said,
'`more stuff than is wanted, or handing bricks when mortar is called for,`' etc,
all which I have often been a pained witness of
and of latter time have had to testify against,
even when, at the same time,
the language of my tongue and pen has been '`arise and build.`'
So that, as that wisdom which is profitable to direct is waited for,
and its qualifying power felt to preside in the church, we shall all grow up together,
an holy temple in the Lord.
I sometimes look mentally at your women`'s Yearly Meeting--
indeed always at the times when you are convened,
and as often I feel united to many of my sisters, both youth and others,
in a lively travail of spirit,
that all things may '`be done decently and in order,`' and that, by each keeping rank,
those in the rear may not, through want of vigilance and dedication in the fore front,
be jostled,
or kept from advancing in that rectitude and valour so
justly and emphatically described in the words,
'`an army with banners.`'

"`Our late Yearly Meeting was held in the new house,
built for the accommodation of women Friends, which is found convenient,
and will be more so when our brethren shall build one for themselves, as contemplated,
on the same lot, in unison with it.
We had no European Friend but A. Alexander, and she a silent witness of our movements.

"`I have transmitted to our dear George Dillwyn, who truly is by me a brother beloved,
in as high a degree as is right to indulge, thy salutation,
and a similar one from A. Alexander,
who supposed she was comforted by his and my mental visits to her whilst on the ocean,
and have just received a pleasant letter from him, in which is the following paragraph:

"`I have for some years past entertained dear Ann Alexander`'s idea,
of substituting mental for epistolary visits;
but alas! it has proved somewhat like the Welchman`'s cow,
which he thought might be trained to live without eating.
As if to convince me that the scheme was too refined for practice on this stage of being,
when this would-be-visiter has been seemingly reduced by abstinence,
almost to a skeleton, something like the present supply has come to hand,
and put me quite out of conceit of the notion.
Thou, too, or I am mistaken, hast more than once thought of compassing the same end.`"
And so he tells me of my declaring myself insolvent, etc.,
and that he supposes I got something handsome by it,
for he observed that not long after I lived away, in as high style as before,
and thus he concludes the subject.
"`In short, I question if we had not as well submit to trudge on in the common track,
and not pretend to be wise above that which is written,
unless we can agree with our younger friends, A. Alexander and M. Bevan,
that they shall continue their paper visits to us and to such as we,
and accept of mental ones in return, till they also reach their grand climacteric.
As to M. B., seeing she has thought fit thus far to tantalize me,
do thou tell her that one of the ways in which '`Self-Love`' may show itself, is,
to excite gratitude and affection by fair promises, and keep the contents to ourselves;
and that if her motive for so doing turns out to be pride,
thou wouldst have her get rid of it out of hand,
that this naughty inmate may no longer hinder me from answering her spouse`'s letter.
So far from George Dillwyn`"

--

In the same letter, under date of Tenth month 15th,
she acknowledges the receipt of some books,

[.embedded-content-document.letter]
--

"`also the piece of which thy Joseph Gurney Bevan is the author.
It is so like his manner that I believe I should have guessed the author,
had his name not been given.
I much desire that this and all his religious endeavours may be blessed to the help
and furtherance of that good work to which you have both put your hands.
I hear that Hannah Barnard has lately published one volume
containing her account of Friends`' proceedings in her case,
and that she is very busy in preparing a second.

"`It seems as if my beloved Christiana Hustler will
hardly be able to visit your metropolis many times more.
But, whether or not,
I do believe she has in great sincerity endeavoured to
advocate the cause of Truth and Righteousness,
and that her reward will be Peace, here and forever.
I have loved her as my own soul.

"`Innocent Ann Christy must be in better health, to undertake such a journey.
Edinbro, though a dark spot when I was there,
I ventured to say that if that old rotten stump could be removed,
I had a hope something green and clever would have room to spring up and grow,
so that I am glad of thy account so far.

"`Is Kendal`'s second volume of Extracts published?
I wish to have it.
Thomas Scattergood, with his wife and daughter, are still at Westtown,
whither he has felt his mind drawn,
and where he has been nearly three months as a teacher,
much to the satisfaction of Friends.^
footnote:[This expression may perhaps lead the readers of the Review to
suppose that Thomas Scattergood was occupied in one or more of the schools,
in the capacity of a teacher.
He was there very acceptably to Friends of that place,
and no doubt to the committee who had the general oversight of the school,
but his labours were devoted principally if not exclusively,
to the religious and moral instruction of the pupils,
and to the encouragement and support of those who were
entrusted with the immediate management of the seminary.
The influence of his example and counsel were probably felt much more,
in all parts of the institution, than it could have been,
if he had been confined to the instruction of the
pupils in any of the schools.--Ed. Friends`' Review]
We, however, expect that he will shortly feel himself released.
What a dear devoted servant is that Deberah Darby.
Nor less so her near friend R. Byrd.
They remind me of a saying of our dear N. Waln,--
'` It is better to wear away than to rust away.`'
H+++.+++ Hull will not be likely soon to visit you,
nor do I hear of any Friend who has so weighty a prospect at present.
I say weighty, for such I found it, and so I hope it will be felt,
especially at such a time as this,
a time in which all the sympathy of feeling minds is and must be called forth,
yet not without hope that All things will work together for good,
to such as love the Lord Jesus, the Prince of Peace, the Saviour of men, in sincerity,
and unfeignedly endeavour and desire that his kingdom may come, and over all be exalted,
and his righteous government and peace never come to an end.

"`Thy concluding sentiment,
that '`it don`'t seem so difficult an attainment to rejoice when Truth is in dominion,
as to suffer with due subjection and patience when that
does not seem apparently the case,`' has done me good,
and is well worth adopting and bearing in remembrance,
through all the ascendings and descendings of such poor pilgrims as myself,
and is also worth its postage from your once favoured isle to this land,
which has undergone changes and suffering beyond what our forefathers ever looked for.

[.signed-section-closing]
"`I am, dear Mary, thy sincere and affectionate friend,

[.signed-section-signature]
Rebecca Jones

--

Tenth month 23d.--"`This day we returned to my habitation, in Brook`'s court, where,
finding that all had, with ourselves, been under Divine protection,
my soul worshipped the God and Father of all my mercies,
and craved to be kept by him unto the end of my pilgrimage.
Eleventh month 2nd and 4th. Our Quarterly Meeting was large and solemn,
David Bacon and S. Smith absent from sickness,
but Friends being generally returned from the country, were rejoiced to see each other.`"
