== Chapter I.

[.chapter-subtitle--blurb]
1739--1762.

[.chapter-synopsis]
* Introductory remarks
* Her own account of her convincement and early life
* Letter from Catherine Payton
* She attends Yearly Meeting through ignorance of its select character
* Is invited to meetings for discipline
* Appears as a minister
* Is acknowledged as such
* Her mother`'s death
* Is joined in the school by Hannah Cathrall
* Makes several visits from home
* Death of Daniel Stanton
* Further particulars of her early history
* Interview with the English Friends.

=== Introductory Remarks.

Truly was it said by Solomon, "`The memory of the just is blessed.`"
And while reverently bearing in mind that "`none is good save One,`" it is admitted
to be both allowable and beneficial to commemorate his goodness by recording the
examples of those who have been clothed upon with his righteousness,
and made partakers with the saints in light.
It is helpful to the pilgrim,
to contemplate the steps of those who have walked with the Redeemer in the way cast up;
not for a servile imitation of particular acts,
but with a prayerful desire to be enabled to walk by the same spirit,
to mind the same rule,
and to adhere to the same principles of eternal truth which they illustrated and adorned.

The papers of our beloved and highly gifted friend Rebecca Jones having been
placed by her sole residuary legatee in the hands of the present Compiler,
were in course of arrangement, with a view to ultimate publication.
During a delay in the compilation, arising from causes not immediately to be obviated,
anecdotes respecting her, with a small portion of her narrative,
found their way to the press, in connection with some inaccuracies.
This, so far at least as the portion is concerned, which was strictly private property,
was regretted,
yet it stimulated the Compiler to furnish to Friends`'
Review (a valuable Journal published in Philadelphia,
and ably edited by Enoch Lewis) copious selections from the materials in his possession.

Long after the compilation had been entered upon,
the caution prefixed to the auto-biographical sketch with which the narrative commences,
continued to operate as a bar to its publicity,
on the mind of the proprietor of these manuscripts,
by whom the memory of Rebecca Jones is most affectionately cherished,
and her wishes and requests regarded almost as a binding law.
This feeling of reluctance, although not removed,
has in some degree given way to the following considerations:
The wishes and views of judicious friends;
a conviction that the request originated in the
writer`'s very humble estimate of herself,
and in more private reasons the force of which has been weakened by Time;
and to the still weightier conviction, that our dear departed friend, was,
in the constrainings of that love in which she
was enabled to labour for the good of souls,
led to pen this testimony to her Divine Master`'s gracious dealings; and that,
however undesirable the prospect might have been to her shrinking and sensitive mind,
it is right at this time to extend the benefits of its perusal
beyond the narrow circle within which it has been known.

The publication above referred to,
of the only part respecting which this scrupulous delicacy was felt,
has assisted in deciding this point;
and it may be remarked that the other journals from which selections will be made,
having been presented by Rebecca Jones to the friend referred to,
without any such restriction,
the responsibility is entirely removed from her of
giving to the public any thing that was prohibited.

The compiler himself,
cherishing the most tender affection and
reverence for the memory of his venerable friend,
trusts that any incompetency or error of judgment on
his part in arranging the materials before him,
may not obscure the light of her example, or derogate from the dignity,
beauty and excellence of a character,
which can hardly be appreciated by those to whom she was not personally known.
He had fondly hoped to throw the task upon a more competent hand,
but it was found impossible, without going through the whole labour of editing the work,
to place the materials intelligibly before a third person;
while motives of propriety and gratitude pressed upon
himself the duty of discharging this debt to her memory.

The size of the volume might have been lessened,
by comprising from the letters the merely narrative
parts and giving them in a condensed form,
but the compiler has desired to present the matter, when practical,
in her words rather than in his own, and it has been moreover his settled conviction,
that these choice and instructive specimens of the epistolary style,
would be both pleasant and profitable to the serious reader.
He has in his possession a rich collection of letters to and from Rebecca Jones,
and while he regrets his inability to obtain many others, of especial value,
which were sent on her decease to the families of her correspondents,
he feels bound to acknowledge his indebtedness to several friends,
in England and elsewhere, for the kind loan of interesting letters.
The extent of her correspondence was truly astonishing, and it would, if collected,
of itself form a larger work than is here presented.

In deviating from the routine of a merely religious work,
in the introduction of some sprightly, but,
we trust never trifling passages and anecdotes,
it has been the object and hope of the compiler,
by adding to its attractiveness to the general reader, to extend its usefulness.
He feels convinced moreover (indeed he has received reiterated
assurance of this) that all minutiae concerning Rebecca Jones
will interest those who vividly remember her.
In hastening to share these interesting relics,
with those of her former friends who may very soon be permitted to follow her,
he is influenced also by the hope that others, in contemplating the course,
and perusing the experiences of this dignified handmaid of the Lord,
may be stimulated to seek in faith of Him by whom alone any can come unto the Father,
ability to walk in the same strait but Heaven-illumined path;
knowing that the principles of Truth which she found to be so precious,
have not been subject to fluctuation, and that the crown of glory, which,
we humbly trust, has been assigned to her, is reserved for all those, in every age,
who love the appearing of our Lord and Saviour Jesus Christ.

=== Autobiographical

It is on my mind to leave a short account of my convincement,
and the Lord`'s gracious dealings with me,
a poor creature, unworthy even of the least of his mercies and of his Truth,
for the perusal of some of my best and most intimate friends,
and I desire that to such only it may be shown,
and that it may not be made any further public.

"`Begin not to say within yourselves, we have Abraham to our Father:
for I say unto you that God is able of these stones to
raise up children unto Abraham.`"--Luke 3:8.

"`Give us help from trouble, for vain is the help of man.`"

I was born in Philadelphia in the 7th month, 8th day, 1739.
My parents`' names were William and Mary Jones.
My father leaving the city when I was an infant,^
footnote:[William Jones was a coaster--was much absent, and died from home.
Rebecca did not remember him.]
the care of my education, and that of my brother, who was nine years older than myself,
devolved on my mother, who, by hard labour, keeping a school, brought us up reputably,
gave us sufficient learning, and educated us in the way of the Church of England.

Before I was twelve years of age,
I often solicited my mother for liberty to go with some of the neighbours`' children,
who were Friends, to their meetings, with which she often complied,
saying that I was but a child,
and not capable of determining in matters of a religious nature, which, indeed,
was really so;
yet I have abundant reason to believe that something of a
Divine nature was then secretly at work in my tender mind,
though I knew not by what name to call it, which, had I given way to it,
would have preserved me, though but a child,
from many things into which I afterwards fell, to the wounding of my poor soul,
and making hard work in the cleansing, purifying day,
that afterwards powerfully overtook me, and from which I could by no means escape.
My mother would frequently say, "`What do you go to meeting for?`"
I being light and airy, would reply,
"`I don`'t know--but I believe they are a good people, and I like their way,
for there is not so much rising up and sitting down among them as at church.`"
And blessed be the God of my life,
who thus gradually and secretly drew my mind towards this people--not only
to go to their meetings--but I loved even the sight of an honest Friend.
Yet I was at times under the influence of another spirit; for,
though I loved this people,
and very early saw a beautiful order and becoming deportment in their meetings,
I could not give up my days to lead such a life of self-denial as the
Divine Instructor in my own breast at times directed me to.
But I loved vanity and folly, and to keep unprofitable company,
by which I was led into many evils,
and quenched the blessed spirit from time to time--yet not wholly,
for oftentimes in the midst of my career, I was favoured with its secret smitings,
and from which it was impossible to flee: and frequently, when in bed, or alone,
my heart was made uneasy for the multitude of my transgressions,
so that I often promised to amend, for I greatly feared to die.
But Alas! though I made covenant,
I soon forgot it and returned to the same things for which I had been reproved,
and thus added sin to rebellion for some time.

Yet I kept close to meetings, both first and week days,
when I could get away without my mother`'s knowledge, though I knew not why I went,
for I liked not their way of preaching, but was always best pleased with silent meetings.

In the year 1754, and in the 16th year of my age,
there came from old England on a religious visit to the churches of Christ in America,
Catherine Payton, in company with Mary Peisley, from Ireland.
I was at several meetings in this city with the aforesaid Friend,
and heard several testimonies which she bore, with which I was much pleased;
but like many others, I only heard,
and sought not to learn the way to salvation in sincerity.
But, forever blessed and praised be the great Minister of all ministers,
and Bishop of souls,
who in his abundant compassion to a poor creature in
the very road that leads to the chambers of death,
was graciously pleased through his handmaid to set my state and condition open before me,
and who enabled her, in one of our first-day evening meetings,
to speak so pertinently to my situation,
in showing the consequences of trifling with Divine conviction,
and proclaiming God`'s love through Christ to all returning sinners,
that I cried out in the bitterness of my heart, "`Lord,
what will you have me do to be saved?`"
And so effectually was my heart reached,
that I was made willing to forsake everything here to obtain peace; yes,
my natural life would not have been too great an offering, if it had been required,
that I might have inherited eternal salvation.

Oh, the many days of sorrow and nights of deep distress that I passed through;
how frequently did I cry out, "`Lord, save me or I perish!`"
I almost despaired of finding mercy, for sin not only appeared exceeding sinful,
but my soul`'s enemy almost persuaded me that my sins were of so deep a dye,
and so often repeated, that I had neglected the day of my visitation, and that,
though I might, like Esau, seek the blessing with tears, I should not obtain it.

But, forever magnified be the kindness and goodness of the Lord my God,
the everlasting Father, he left me not here,
though I was in the situation described by the Prophet.
I was greatly polluted--lay wallowing in the filthiness of the flesh,
without any succour from temporal connections,
and a stranger to the Lord`'s family--"`Not washed at all, nor salted at all,
but cast out as in an open field, void of any enclosure; none eye pitied me,
to do any of these things to me.`"
When the sure Helper passed by, he beheld me in my deplorable situation,
cast his mantle of Divine love over me, and with a most powerful voice said, LIVE--yes,
he said unto me--LIVE.

I was again encouraged by the renewal of divine favour to enter into solemn
covenant with that gracious Being against whom I had so highly rebelled,
and whom I had so justly offended; and fervent were the breathings of my soul,
that I might be enabled to stick close to the
terms made in this the day of my humiliation.

My love to this instrument in the Lord`'s hand was very great; and on a certain time,
being reduced very low in my mind,
under the consideration of my many and deep transgressions,
I took up my pen and opened a little of my condition to her,
though I was afraid to sign my name to it.
I watched an opportunity and slipped it into her hand,
just as she was going into meeting, and in two days after received,
per the hands of one of her friends, the following answer, which,
as it had a blessed effect in encouraging my mind
reverently to confide in the Lord`'s infinite mercy,
I here transcribe at large.
Peradventure it may revive the hope of some afflicted soul.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
"`Philadelphia. 4th mo. 1st, 1755.

[.salutation]
Dear Child,

"`I have carefully read your letter, and,
from a tenderness of spirit which I feel towards you,
conceive much hope that you will do well,
if you keep to that Power which has visited you.
Which, as it has already appeared as a light to convince you of sin, will,
if you will permit it, destroy it in your heart.
Which dispensation being already begun,
is the reason of that anguish of spirit which you feel, which will lessen gradually,
as you are assisted to overcome.

"`And be not too much discouraged, neither at what you have committed against the Lord,
nor at what you may have to suffer for him;
for though your sins may have been as scarlet,
he is able and willing to make your heart as snow,
upon your sincere repentance and humble walking in His fear,
and also to give you strength to do whatsoever he commands you.

"`If you are willing and obedient for the future,
you shall eat the good of the land in the Lord`'s time, and,
as you have already been instructed that '`you shall only
receive consolation as you are fit for it,`' wait patiently,
and let the administration of condemnation be perfected,--so shall
the administration of Light and Peace be more clear and strong:
which will assuredly come upon you,
if you abide faithful to that Power which has visited you.

"`You desired me to explain some portions of scripture to you, which I had to mention,
which I am willing to do as far as the mentioning of them concerns your state:
which I believe was to awake watchfulness and care over your conduct,
that your soul may bring forth the fruits of purity and love to God,
which will be manifested only by your obedience,
and that you may not rest in anything short of the knowledge of His Power,
revealed in your heart as a refiner and teacher,
nor place your happiness in anything short of his salvation.

"`I go out of town tomorrow, and not knowing your name by your letter,
know not how to get to speak to you;
and have therefore committed the care of this to A. Benezet,^
footnote:[This letter was not forwarded to her by Anthony Benezet, but by another friend,
as will be explained in the next chapter.]
who, I believe, will use his utmost endeavours to convey it to you.

"`Farewell; and may the Lord continue to bless you.
I conclude, in much haste, your sympathizing friend,

[.signed-section-signature]
Catherine Payton.

[.postscript]
====

"`P. S. I had rather you keep this to yourself; and be sure,
be careful how you tell your condition to such who have no knowledge of it.`"

====

--

On the receipt and reading of this letter my heart was
melted into great tenderness before the Lord,
and my mind encouraged to trust in his boundless mercy, thus extended to me, a poor,
unworthy creature.
My resolutions were daily strengthened,
in remembering that "`at what time soever the wicked turns from his wickedness,
and does that which is lawful and right, he shall save his soul alive.`"

I now attended meetings constantly, though I suffered some hard things on that account.
I rejoiced when meeting day came; yes,
the evening before meeting day my mind seemed under the preparing power,
for the solemn performance of Divine worship;
of the necessity whereof I was now fully convinced,
as also of my unfitness therefor without the renewal
and daily influence of the blessed Spirit.
The heart-tendering power of Truth in a very singular manner attended,
insomuch that if I was not in the enjoyment thereof, my meeting seemed in vain.
I frequently compared my situation about this
time with that of the children of solid Friends,
many of whom, I perceived, walked widely from their holy profession.
I thought if I had been favoured with privileges like those which many of them enjoyed,
I had not had so much work for repentance.
Oh, that they did but see and rightly understand the manifold
obligations they are under to the Everlasting Father,
and also to their pious parents.
Oh, the unspeakable advantage of an early education in virtue and the fear of the Lord!
Certainly in the great day of decision it will but add to the
weight in the scale against those who pursue lying vanities,
forsake their own mercies, and rebelliously turn their backs on the admonitions,
counsel and instruction of tender, pious, heart-aching parents!
I esteemed myself as a branch broken off from the wild olive,
and grafted into the good olive tree, and was secretly instructed that I stood by faith,
and that the goodness of God would be toward me while I continued in his fear:
otherwise I should be cut off.
I often fervently desired that those who had erred and strayed among the
youth (whom I compared to the natural branches of the good olive tree) might
be grafted in again--"`for God is able to graft them in again.`"
"`Be not high-minded,
but fear,`" was the solemn admonition frequently sounded in the ears of my soul.

It is not in my mind to particularize everything that fell to my lot,
not only from some in near connection with me, but also from my former acquaintance,
to whom I now seemed estranged;
and many were their bitter invectives and hard speeches liberally thrown out against me.
Yet thus far I may say of a truth, greater was that power which had visited me,
and was in a degree in me, than these my enemies that were in and of the world.
To the praise of my gracious Benefactor be it spoken,
the more I suffered in thus turning my back on all those
things which in time past I so greatly delighted in,
the more my strength increased,
and my resolutions were confirmed to serve the Lord the
little time that remained to me in this life,
which I then often thought would not be long.

In the Spring of the year 1756, my aforesaid friend, Catherine Payton,
embarked with her before-named companion, Mary Peisley, Samuel Fothergill,
(who had also performed a religious visit to Friends on this continent,) Samuel Emlen,
of this city, etc., and set sail for Europe.
Soon after their departure I found an indifference towards meetings gradually coming on,
and the enemy of my soul`'s happiness sorely buffeted me.
He suggested to me that my repentance was vain,
(it was not godly) my tears were insincere,
and that I was most certainly under a great delusion.
And the Lord, my only Helper in this night of probation, saw fit in his wisdom,
for the trial of my faith, to hide his face from me.
Thus spoke the deceiver: "`Why are you thus?
surely if you were the visited of God, he would not have left you thus poor,
stripped and helpless.
You are not on the right foundation; for if the Lord had been at all with you,
he would have remained with you forever.`"
Oh the grief and distress of my poor soul!
The Divine presence was withdrawn, and I had no friend on earth to speak to,
nor any to whom I could make my complaint.
Yet I was favoured under all,
with strength to pray that I might be favoured to see
clearly from where this distress and doubting arose.
And, blessed be the God of my life, who, though I thought him far off, was near,
and had only withdrawn as behind the curtain;
he heard and graciously answered in the needful hour.
I resolved if I perished to perish at his feet.
And thus spoke my only friend and alone helper: "`I will thoroughly purge your dross,
and take away all your tin.`"
My soul replied, amen, so be it, blessed Lord!
Here I could feelingly say as did David: "`I know, oh Lord,
that your judgments are right, and that you in faithfulness have afflicted me!`"
Hope revived as a helmet of salvation; I saw my accuser and he fled!
Oh, my soul, forget not you the lovingkindness of your God,
who thus graciously appeared for your help;
not only when the floods of the ungodly made you afraid,
but when in close combat with the Prince of the power of the air,
the Lord`'s arm brought salvation, and his right arm got the victory.

My love again was renewed for the Lord`'s people; and,
although through much difficulty and strong opposition, I attended meetings,
both first and week days,
and should have rejoiced had I been worthy to sit in meetings for discipline,
a privilege not yet granted me;
I frequently went to monthly and quarterly meetings and stayed the first sitting,
but withdrew when Friends entered on business.
I knew I had no right to stay longer--besides,
in one of the yearly meetings for business I was desired to
withdraw by a friend whom I afterwards dearly loved;^
footnote:[During the Yearly Meeting of 1755, Rebecca Jones went to one of the sittings,
not being aware that our order required such meetings
to be select--Finding her accustomed seat occupied,
she went up stairs, but seeing so many plain Friends, she felt uneasy,
and as if she had no business there:
which feeling was increased as she noticed a whispering near the clerk`'s table.
Catharine Kallender, leaving her seat, went up stairs and sat by her;
and seeing Rebecca about to rise, she laid her hand upon her kindly,
and presently they both went out,
when Catharine informed her that those meetings were exclusively for members,
but that she believed the time was not distant
when it would be proper for her to attend them.]
and though I left the meeting under much distress,
(being at that time very low in mind,) yet no hardness got in, blessed be the Lord;
my love rather increased, not only to this mother in Israel, but to the whole flock;
and I admired the care used to keep such meetings quite select:
I saw that it was necessary to do so,
and never after attempted to stay till I was
invited by some who I thought tenderly loved me,
and were authorized to do it.
And here I would mention the observation I made of some of our
youth after I was favoured to sit in meetings for business.

I frequently looked at them with love and tenderness,
but admired to see so little sense appear among
them of the nature and design of such meetings.
I found that many attended through curiosity, and some from other motives:
but very few whose shoulders were preparing for the burden of
exercise that lay weightily on several mothers in the family,
who were far advanced in years,
and in all probability would before long finish their course.
I mourned at the prospect of a succession,
and wished that the spirit of Elijah might rest on Elisha.
At these seasons I often felt a holy zeal to cover my spirit,
and an engagement sometimes attended that the Lord`'s work might go on and prosper.
But, in that weak state, I concluded,
that if the youth would not come up to the help of the Lord,
(I mean children of believing parents,) the cause would drop.
Yet I was sometimes favoured to understand the Lord`'s proclamation, "`I will work,
and who shall hinder it.`"
Very frequently I was seized with an apprehension that,
if I was faithful to the manifestations of Divine grace,
the baptizing influences thereof would be witnessed for the cleansing, purifying,
and preparing my spirit, rightly to engage in the Lord`'s work:
at which my heart trembled within me, and I very much feared I should push, like Uzzah.
And, though in meetings both for worship and discipline,
my duty was often pointed out to me, yet, the fear of marring the Lord`'s work,
a sense of my own weakness, the situation in which I was placed in the world,
the prospect of much suffering awaiting me, but, above all,
a sense of the purity and stability necessary for those who fight the Lord`'s battles,
and a sight of my own state and lonesome condition in the family;
I say all these things mightily humbled me, and reduced me to the brink of the grave.
I went alone--I kept silence--I refrained from my natural food,
and my sleep departed from me.
"`I was stricken of God and afflicted.`"
In this situation I attempted several times to break my mind to some Friends by writing,
and to let them know how it was with me--but was always stopped from doing so; and once,
when I went to the house of an honest-hearted, faithful servant of the Lord,
with an intention to open my case to him,
the ear of my soul was saluted with this prohibition:
"`See you do it not--the work is the Lord`'s.`" My mind was fervent with the Lord,
(than whom none else knew my condition,) that he would be pleased to
favour me with the distinct sight and knowledge of his will,
that I might not be deceived by the enemy of my soul--whom I had
before seen in some of his artful transformations--but that light
might so attend as that I might make no mistake in darkness.

I carried my burden from one month to another, and from meeting to meeting,
until the 7th month 9th, 1758, in an evening meeting, finding no excuse would longer do,
and that faithfulness was required,
after William Prickett had finished a lively testimony,
in which he expressed much sympathy and had great encouragement for
some who were under preparation for the Lord`'s service,
I stood up in great fear and trembling, and expressed a few sentences very brokenly.
I returned home with the promised reward of peace, which I had long sought in vain, but,
now that I had given up to the Lord`'s will, was favoured to obtain it.
This was my first public appearance, and I greatly desired as a sign,
that if I was yet mistaken, I might be visited and advised by some Friends.
But as I met with no opposition from Friends, and as, contrariwise,
some spoke encouragingly to me, I found need to watch myself with a jealous eye,
and was fervent in spirit that I might be preserved in true humility and Divine fear,
the only safe situation for a gospel minister.

And now I found it my place to make a stand
against some things in some of my near relatives,
with which before I had no unity.
And, blessed be God, my best friend, I was helped to overcome both in myself and others,
some inconsistencies which I plainly saw Truth disallowed of.

Hitherto I had met with much opposition in attending meetings;
but the Lord plead my cause, and inclined the heart of my dear mother toward me,
so that she not only gave me liberty in that respect, but was very affectionate,
both to me and to Friends when they came to our house;
and she continued so till her decease.
For which my soul was made humbly thankful,
and it was no small confirmation to me that the Lord was on my side.
"`What shall I render to the Lord for all his
benefits!`" was the honest language of my mind.

In the year 1760,
I had the privilege granted me to sit in the meeting of ministers and elders,
of which I thought myself very unworthy;
and I attended the first meeting of this sort
under strong apprehensions of my own weakness,
and the necessity of labouring after true humility.

In the spring of the year 1761, my dear mother began to decline very fast in her health,
and could scarcely keep about house.
She grew weaker and weaker, insomuch that she needed constant attendance all the summer.
I had a large school on my hands to take care of,
(the only means for our subsistence,) and her to nurse both night and day,
till the 9th month, when she grew so ill that I was obliged to break up the school.
I also was much reduced in my health, and, by such constant exercise,
both of body and mind, received a weakness that I fear I shall never be rid of.

She deceased near the end of the 9th month, 1761.
And here I am free to add that she was a woman of good natural
understanding--of a noble disposition--had many good qualities--lived
a peaceable life among her neighbours--and,
I have good ground to believe,
was under a religious exercise of mind for many months before her decease.
She was favoured with an easy passage, for which during her illness she often prayed,
as a sign of acceptance with the Lord;
and was buried in the burial ground of the Church of England,
(so called,) among whom she always made profession.

In her illness she desired to see Daniel Stanton.
He came, and had a heart-tendering time in supplication, particularly on her account,
(whom he had known from a young woman,) that she might be favoured with patience,
and might obtain mercy with the Lord.
After which she seemed easy, and said he was a servant of the living God.

Now I was in a strait:
for I had often thought that if it should please Providence to remove my mother,
I would think of some other way than keeping school for a livelihood.
But as our Yearly Meeting was coming on, I concluded to leave it till that was over,
and in waiting to know what was best, I seemed easy to continue in the same way,
as being what I was most used to: and a suitable friend offering, made it the easier.
This was Hannah Cathrall, a religious, prudent young woman, who joined me in the business.
I esteemed this a favour from kind Providence,
for I was now grown so weakly that I could not have undertaken it alone,
and she was of an affectionate disposition towards me.
We soon had a large school, and were blessed with a sufficiency to live comfortably.
I had been very little abroad, not only because I was confined by business,
but I was under great discouragement in my own mind,
on account of my weakness both of body and mind.
But whenever my aforesaid companion apprehended I was under any engagement of that sort,
she always encouraged me, and did all in her power to make things as easy as she could,
for which I feel grateful acknowledgments and esteem for her.
In 1762, I went in company with E. Smith of Burlington, and some other friends,
to the General Meeting held at Shrewsbury; and after that, at different times,
with Esther White, Mary Evans, Hannah Harrison, etc., several little turns,
to some Quarterly, Monthly, and particular meetings,
within the compass of our Yearly Meeting.

In 1769, I found a draught of love in my mind towards the Yearly Meeting on Long Island,
and obtained leave of our second day morning meeting of ministers and elders.
I made preparation and was in readiness; but, when the time came,
my mind was so beclouded and distressed that I was glad to give it up.
The cause afterward appeared very plain to me,
and I was made thankful for the secret intelligence afforded from on high.

In 1770, the engagement for that meeting was renewed, and my friend Hannah Foster,
of Evesham, having sent me word that she intended going there, I gave up,
and though much discouraged, being poorly in my health,
and not used to ride on horseback,
yet I was favoured to hold it pretty well as far as Rallway, where my kind friends,
Joseph Shotwell and wife, provided a chair for my accommodation,
and went with us to Flushing.
I was much assisted in this journey, or I could not have held out,
for I was not only indisposed in body, but my mind was very low,
insomuch that I apprehended I should not live to return,
and accordingly settled my outward affairs and
took a very solemn leave of my dear companion,
who was also fearful on my account.
However, the Lord was near--blessed be his name--and made the weak strong.
We were mutually comforted together at that meeting,
and I returned home better every way; for which I bow before the Almighty,
and acknowledge that nothing is impossible with him.
Praised and magnified be his great name, both now and forever!

Soon after my return my mind was bowed very low,
by reason that a beloved friend and father in the truth, Daniel Stanton,
was taken from works to rewards.
He had been eminently favoured in his public appearances for many months before,
insomuch that many Friends were apprehensive of
what he sometimes expressed as his belief,
"`that he had not many days longer to labour among us.`"
This was a great stripping to the church, and a near trial to many individuals,
and the loss was not likely to be soon made up.
Such was the prospect of things among us.
Yet there were still left some honest labourers,
and a remnant clothed with the same spirit of true zeal,
which was the covering of this great and good man, who deceased the 28th of 6th month,
1770, in the 62nd year of his age,
and who had disinterestedly laboured among us upwards
of 40 years--approving himself called of God,
a workman that needed not to be ashamed,
rightly dividing the word to every class in the family.
"`Precious in the sight of the Lord is the death of his saints.`"

[.alt.centered]
==== [Here ends the autobiographical sketch which she probably designed resuming.]

The mother of Rebecca Jones, as has been mentioned in the preceding memoir,
kept a school for small children.
She had subjected herself to many privations,
in order that she might give Rebecca a good education,
being ambitious to make her a teacher of the first standing in Philadelphia.
As this precious young person yielded obedience to the Divine Monitor,
she found herself restricted in various ways,
and restrained from indulging in and teaching to others,
the lighter and merely ornamental branches, as dancing and music,
and ornamental needle-work.

This, being a blight to her mother`'s fond and ambitious prospects,
introduced Rebecca into severe trials and close provings of her faith,
from the treatment which she experienced from her parent,
who now opposed her attending the meetings of Friends.
Her conflict of soul became so great that she did not keep fellowship with any one,
and the Bible to her was a sealed book,
so that she did not dare to resort to it for consolation.

Let no one suppose, however, that she at any time undervalued the sacred volume,
(in the perusal of which she was diligent through life,
and earnest in enforcing the duty upon others,) although at the time of which we write,
instrumental means were withheld; she being,
under the immediate power of the great Teacher of his people, preparing for a service,
the true qualification for which must be directly received
from and renewed by the alone unfailing Source of help.

She went to meeting when she could get away,
although she knew that unkindness awaited her on her return.
On one occasion, coming downstairs with her bonnet and cloak on,
her mother took hold of the latter to detain her.
She untied the string and walked out, leaving her mother in silent astonishment;
but she felt condemnation and could not enjoy her meeting.
Her mother, however, never again attempted to detain her by force.

During this state of things, her brother Daniel, who was nine years her senior,
and who resided in Mount Holly, made them a visit,
and their mother poured out to him her troubles and mortification on Rebecca`'s account,
representing how much money she had spent upon her education, which was now,
in her estimation, all wasted,
and expressing her desponding feelings relative
to their being able to obtain a maintenance.
He enquired whether she was not dutiful and kind to her,
and obedient in everything except what she apprehended
to be connected with her religious duty.
The mother replied that she had never been so kind and dutiful,
and that she was only disobedient in relation to things with
which she professed to be uneasy on religious grounds.
"`Then, mother,`" replied he,
"`let her alone--if it is of herself it will soon come to nought,
but if it is of the Lord, all that you can do will not prevent it.`"^
footnote:[This brother died 10th mo., 1771--aged 40 years.]

It was about this time that she placed in the hands of Catharine Peyton (afterwards
Phillips) the letter to which reference is made in her own narrative,
page 7. It will be noticed that Catharine in her reply
proposes to entrust it to the care of Anthony Benezet.
But, having written her answer, she read Rebecca`'s letter to Daniel Trotter,
who was a near neighbour to Mary Jones,
and had been her fellow passenger in a voyage from the West Indies.
"`I do not know,`" said Daniel, "`who it can be, without it`'s that wild Becky Jones,
who has got to coming to meeting and sits by black Rose.`"
This Rose was a goodly coloured woman, who sat on a bench near the door,
and Rebecca in her humility, occupied the vacant seat beside her.
He was so assured of the correctness of his surmise,
that he undertook to deliver Catharine`'s letter.
One afternoon, at the close of school, Rebecca was sitting with her mother at the door,
and seeing D. Trotter approach, she was much agitated lest he, being a Friend,
should be unkindly treated on her account.
He, however, frankly addressed Mary Jones, and conversed pleasantly about their voyage,
taking no notice of Rebecca, till, as he was going, he shook hands with her,
leaving the letter in her hand.
She kept it for two days before she had any opportunity to read it in private,
and then ripped a seam in her skirt, and concealed the letter in the quilting,
as her pockets, drawers, etc., were frequently searched.

Being selected as bridesmaid by her friend Hannah Zane,
at the time of her nuptials with John Pemberton,
the bride offered to present to her a dress of rich silk,
(then a very costly article,) with which Rebecca Jones
was pleased at the moment--but her mind became uneasy,
and soon settled in the conviction that her safety
consisted in being content with humble things.
During her whole life,
she never wore a silk dress--though she had no disposition to
judge the liberty of others in this respect,
or to fix upon them her individual scruple.
Thus early humbling herself,
she became fit for the exaltation and dignity designed for her by her gracious Master,
and although, during a large portion of her life,
she was treated by "`the household of faith`" with a degree of consideration
and deference which very few could receive without injury,
instead of being thereby purled up and lifted from the foundation,
she seemed to be the more deepened in the conviction that the Lord is everything,
and that she was nothing, and from time to time,
(to use her own expression) to "`center in my old position as an Unprofitable Servant.`"

The English Friends to whom reference has been made, after an absence from the city,
returned to attend the Yearly Meeting; and being at the house of Catharine Kallender,
in Front street, nearly opposite the end of the alley in which Rebecca lived,
they expressed a desire to have her company, and C. Kallender`'s daughter Hannah,
who had been Mary Jones`' pupil,
(and intimate with Rebecca until she withdrew
from all companionship,) was sent to invite her.
Hannah walked backward and forward across the end of the alley,
occasionally beckoning to Rebecca, who sat by the window.

Rebecca Jones at length asked her mother`'s permission to join her young friend,
which was rather ungraciously given.
Hannah then told her that the English Friends wished her to take tea with them.
She was now in a strait, whether to avail herself of the liberty already given,
or to risk a refusal from her mother.
But, feeling best satisfied to act in deference to parental authority,
she asked leave to take tea at their neighbour`'s. Rebecca was emaciated
from the trials and conflicts through which it had been her lot to pass,
being, to quote her own touching description already given,
"`stricken of God and afflicted:`" and her mother, who possibly already began to relent,
gave permission.
She went, but, considering herself unworthy and insignificant,
she felt as though it were intrusive to place herself in the company of such worthies.
She was, however,
well repaid by the comfort and consolation which she derived from those dear friends,
with whom she had not before spoken.
It is not known that she ever related the above circumstances more than once,
when with much feeling, in the latter part of her life,
she communicated them to one who had for many years been to her as a daughter, saying,
that she could not write a full account of her earlier days without
speaking of her mother as a child ought not to speak of a parent.
Many years, however, having now elapsed,
and the reasons for privacy being lessened by time,
it is believed that a condensed statement of these facts,
in connection with some selections from her notes and correspondence,
may tend to the comfort and edification of some sincere minds,
and that in this view they ought not longer to be suppressed.

The difficulty with her parent did not entirely cease, till, in 1760,
the church had acknowledged her gift in the ministry of the Word:
when a committee of two men and two women was appointed to
acquaint her with the conclusion to which her friends had come.
These Friends hesitated about going to Rebecca`'s residence,
and thought of communicating with her by letter:--but solidly considering the subject,
they were most easy to go in person,
and share with her whatever was to be borne on the occasion.
The interview was in the presence of Mary Jones, and, after a time of social conversation,
a season of silence ensued, in which the object of the visit was stated.
After their departure,
her mother said to her--"`Your friends have done all that they
can for you--they have placed you upon the pinnacle;
now take heed to your steps, for if you fall, great indeed will be the fall.`"
From this time they lived harmoniously;
her mother became reconciled to her being a Friend,
and her natural disposition seemed softened.
The school increased, and afforded them a comfortable maintenance; and,
after the decease of her mother,
she entered into the business of teaching more extensively,
in connection with Hannah Cathrall,
the latter attending to the sewing department in a separate room.
