== Chapter II.

[.chapter-subtitle--blurb]
1762--1783.

[.chapter-synopsis]
* Her character as a teacher
* Anecdotes of John Riddle and children
* Rules of the school
* Letters to various persons
* Letter from Elizabeth Smith and sketch of her life
* John Woolman to E. Smith
* House in Drinker`'s Alley
* Anecdote of John Woolman
* Poetry by John Drinker
* Opens her prospect for England.

It might be laid down as an axiom,
that none but a philanthropist is fit for the office of a teacher.
Its responsibilities would be poorly wielded by him who should perform the
task solely as a mode of acquiring the means of subsistence.
Rebecca Jones had remarkable qualifications for imparting knowledge,
for training the youthful mind, developing its powers,
alluring it into the paths of true pleasantness and peace,
and superintending the progress of a "`religious, guarded education.`"
Having, as we have seen in the commencement of her career, made covenant by sacrifice,
she was not likely to be guided in her vocation by mercenary motives; on the contrary,
she performed the service with good will and in singleness of heart,
"`as to the Lord and not to men.`"
She was moreover possessed of a commanding dignity,
and a facility for enforcing salutary discipline,
which enabled her to illustrate the Apostle`'s injunction to Timothy,
"`let no man despise you.`"
Thus she was eminently successful as a preceptor,
obtaining a hold not only upon the affections and respect of her pupils,
but also upon the confidence of their parents;
so that she was often applied to by some of these to
aid them with advice in important movements in life,
in framing their wills, and in various ways.
In such cases, though diffident of her own powers, she was a kind,
ready and wise counsellor.

Among her pupils were the daughters of John Riddle, a Dutch tailor, who,
during the Revolution, worked for the British officers.
Two of them Polly and Rose, having completed their education,^
footnote:[When application was first made for these elder children, the school was full,
but so earnest was the father that he procured desks for them and
brought them to the school room,--and thus obtained admission.
Is not his zeal for the right education of his children worthy of imitation?]
the eldest, who wrote an elegant hand, was his bookkeeper.
When he wished to place his youngest child under her care, she objected,
on account of some scruples relative to the mode of payment.
The exact nature of these scruples, we cannot with absolute certainty explain,
but his funds came from the officers,--and the
following note by the Editor of Friend`'s Review,
will suffice to give the general reader a sufficient insight.
"`It is not easy at the present day to appreciate the
difficulty to which Friends were exposed,
during the revolutionary contest.
No inconsiderable portion of the circulating medium consisted of bills of credit,
issued for the express purpose of meeting the expenses of the war.
The payments of the British officers, were indeed, made in solid coin; but,
under the circumstances of the time,
it is not strange that Rebecca Jones should hesitate, on religious or prudential grounds,
at receiving a pupil whose education was to be paid for out of money sent to
this country to aid in the prosecution of the then existing war.`"

One evening, while Rebecca Jones was enjoying the company of her friend Sarah Wistar,
John Riddle came in to plead his cause,
and strongly depicted the benefits his elder girls had derived.
"`Dere is mine Polly, dat you did learn to write and to cypher.
I did send home General Howe`'s clothes mit de bill,--and when he come to pay it he say,
"`Why Johnny, did you write dis?`"--(holding the bill in his hand.) I say, no,
it is mine Polly`'s writing.
"`Your Polly!`" say he--"`Where did she learn to write so goot?`"
and I say, why she learnt of Becky Jones.
"`Who is Becky Jones!`"--say he--Why don`'t you know Becky Jones the
Quaker Preacher?--I told him she had never gone to any other school, etc.
Thus he went on to show his estimate of the value of her instructions,--and,
being fully informed of Rebecca Jones`'s objections, he said that she might, in payment,
take from his shop any thing that she needed, and give her friends orders upon him.
"`Oh,
you must take mine Sally`"--he continued--"`mine Sally wont give you mooch
trouble--mine Sally is a good gal--she stole her Daddy`'s hearts.`"
Rebecca Jones`'s guest joined in urging his suit, offering to aid in taking out the debt.
Some of the articles thus taken out, are before us as we write.

The child was admitted into the school.
She was so small that her teacher placed a stool
upon the bench to enable her to reach the desk.
She proved to be a very good child.

Before leaving, John took from his ample pocket a blank copy book.
"`I wants you to write mine will in dis.`"
Rebecca sought to excuse herself,
lest some difficulty should result from her ignorance of legal forms and technicalities.
"`Oh,
I don`'t mean what I shall do with mine money--but dat
mine children shall he goot to dere mammy,
and give her every ting dat she want.
I want them to remember when I`'m dead and gone--dat she`'s
been a good mammy to them--You knows how to say it,
petter as I can tell you.`"
Rebecca Jones wrote for him, to his full satisfaction, on a loose paper,
a letter of paternal advice to his children.

This whole family, parents and children, died in the fever of 1793.
Sally, (then a religious-minded young woman,) was the last survivor.
During the illness of the family,
a coloured man went daily as messenger between her and a friend similarly circumstanced,
bearing notes in which they exchanged accounts of the
progress of disease in their respective houses.
These billets sometimes consisted of but a single line,
and sometimes expanded with a highly interesting
interchange of their religious feelings and experience,
and most plaintive references to neighbouring families,
and to their own loved and lost ones, whom they could not bury out of their sight.
Her friend also died in the fever of the same year.

The following rules for the observance of her pupils in school and elsewhere,
were conspicuously placed in Rebecca Jones`'s school room;
and while they may fail to interest some readers who have not been similarly engaged,
they will probably commend themselves to a
sufficient number to warrant their introduction.
The mind of the candid reader will be carried
back to the time in which they were written;
and while it would be unreasonable to expect to see them, in every respect,
such as would now be framed, it will be well, in judging of them,
to reflect what dignified characters were trained under their strict administration.

[.alt.centered]
=== Rules of Conduct for Girls at School.

[.numbered]
__1st.__ Never absent yourselves from school, unless good reasons can be assigned,
to the satisfaction of your mistress.

[.numbered]
__2nd.__ Be always silent at your business, so that your voices shall not be heard,
unless when you are saying your lessons, or speaking to your mistress;
hold no discourse with your schoolmates during the hours of business,
without your mistress`'s permission, unless to ask something relating to your learning,
which must be done in a low voice.

[.numbered]
__3rd.__ Make all your speeches to your mistress with due respect,
observing cheerfully to perform her directions with dispatch, according to your ability.
If a stranger should speak to you, give a modest and ready answer,
standing up and turning your faces towards them respectfully, taking your seats again,
and silently apply to your business.

[.numbered]
__4th.__ Behave yourselves always in a humble, obliging manner to your schoolmates,
never provoking one another, contending or complaining about frivolous matters,
but courteously use the word please, or some soft and obliging expression,
when you ask anything one of the other;
and observe to make some grateful return for any little kindness received,
never returning injuries, but learning to forgive,
showing by an exemplary deportment how all ought to behave.

[.numbered]
__5th.__ Never tell a lie knowingly, nor use the name of God irreverently, or in vain;
mock not the aged, blind, lame, deformed, idiots.
Play not in the streets, or ever for gain; throw no sticks, stones, dirt, snowballs,
or anything at any person; revile none, utter no indecent expression,
and return no affront to any you may meet with,
but according to the best of your knowledge, demean yourselves in a modest, civil,
complaisant manner to all.

[.numbered]
__6th.__ Let your language be the plain language, and spoken with propriety everywhere.

[.numbered]
__7th.__ Be not forward to divulge anything past in school,
nor jeer those who have been corrected, lest it should happen to be your own case.

[.alt.centered]
==== At Home.

[.numbered]
__8th.__ Before you rise from your beds,
observe to offer a mental petition to Divine Providence
for protection from evil and danger the following day,
not omitting at the same time a grateful acknowledgment for the benefit of your rest:
observe also the same reverence at lying down,
returning humble thanks for preservation through the various incidents of the day.

[.numbered]
__9th.__ Observe to use a cheerful and ready compliance to all your parents`' commands,
with becoming resignation to their will--never addressing or
approaching them without honour and respect;
neither be loud in voice or laughter in their company, or before any of your superiors,
nor forward to talk in their presence;
yet always returning ready and modest answers to their questions:
never intrude yourselves upon them when alone, or with company,
if you are necessitated to speak with them, appear with good manners,
and be sure to whisper, and withdraw unless desired to stay.

[.numbered]
__10th.__ Make all your addresses to your brothers
and sisters with humility and good manners,
using the word Please, etc.; and in like manner to the meanest servant,
that your good example may induce them so to behave to you.
If you are necessarily where the servants are, give no ear to their jesting or idle talk,
much less join with them,
but always choose the company of such whose
conversation is most improving in the best things.

[.alt.centered]
==== At Table.

[.numbered]
__11th.__ Be not forward to sit down at table before the rest have taken their places,
especially your elders or superiors; when seated,
be not eager to fall to your victuals like the brute animals,
but first observe a solemn retirement of mind to the Supreme Giver of them.
Be not talkative or offer to carve, or ask for yourselves, but wait till you are served.
Find no fault with your food, or its dressing;
but sit upright and soberly with silent attention,
ready to answer any questions that may be asked of you; having eaten moderately,
rise from table without noise, moving away your seats; withdraw if strangers be present,
unless desired to stay.

[.alt.centered]
==== At Places for Worship.

[.numbered]
__12th.__ When you attend meetings for Divine worship,
observe to be present at the times appointed precisely,
entering the place soberly and without noise in walking or otherwise,
so as not to disturb the meditations of those that are met; when seated,
make no disagreeable scraping or rubbing of your feet against the floor or seat,
nor use any unbecoming gestures or motions with any
part of your bodies to disturb or offend any person,
by biting your nails, pinching your fingers, lolling, stretching, yawning, spitting,
staring about, or by any other means,
but sit attentively and erect in a decent composure of body and mind,
secretly desiring to be favoured by our Heavenly Father with a proper
disposition of mind to offer to him spiritual and acceptable worship,
and to be enabled to practice what good advice you may hear,
giving diligent attention thereto,
that your behaviour may not only be grateful to that Divine Being that made you,
but also well pleasing to your parents and friends; when the meeting breaks up,
rise not in a hurry, nor be impatient to be gone,
but rather think it a favour to be admitted upon such
solemn occasions to sit with your elder Friends,
respectfully noticing them as you pass along, showing no haste to leave their company.

[.asterism]
'''

In the absence of a regular diary of this portion of her life,
it is not easy to supply the deficiency,
but little of her early correspondence being accessible.
The following letter, written at the age of twenty,
evinces that even then she was "`instant in season,`" under the Divine anointing,
in obeying the injunction, given to Peter, "`when you are converted,
strengthen your brethren.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Benjamin Swift, And Samuel Sansom.

[.signed-section-context-open]
Philadelphia, 8th mo. 10th, 1759.

[.salutation]
Respected Friends,

It has been upon my mind ever since
I heard of your intentions for England,
in a great deal of good will, with desires for your welfare every way,
to communicate in a few lines what I think quite necessary to observe.
I have remarked some young men on their return from abroad, seem, as it were,
swallowed up with the prospect of those transient, glaring views,
which many have been presented to their minds relating to visibles:
which disposition I would have you guard against,
and bear in mind that you are of the youth of Philadelphia,
many of whom are greatly beloved by their Maker as well as Friends.
I wish that you may not only gain experience in worldly things,
but that you may know the Stay of youth and the Staff
of old age near your spirit in all company and places,
whereby you may witness experimentally a growth in
grace and in the saving knowledge of God our Saviour,
and may adorn our holy profession by a circumspect, steady conduct,
not only among the faithful, but among whomsoever your lots may be cast;
and may know the Reprover, Refiner, Sanctifier and Comforter,
(which is no other than the Spirit of Christ,) to operate effectually in your hearts,
making you vessels of honour to his praise.
This is the sincere desire of your friend,

[.signed-section-signature]
Rebecca Jones

--

[.embedded-content-document.letter]
--

[.letter-heading]
Elizabeth Smith To Rebecca Jones.

[.signed-section-context-open]
Burlington, 23rd of 4th mo., 1759.

[.salutation]
Dear Friend Rebecca Jones,

As your letter did not seem to require an immediate answer,
I thought best to defer it till a suitable time and opportunity
offered to acquaint you that I received it as a testimony of your
regard and a demonstration of love to the blessed truth,
which I believe you have been favoured in measure to know the
revelation of--even of that Divine arm of everlasting Love and Power
which has been the strength and support of the upright in heart,
through every age of the world;
notwithstanding Infinite Wisdom has seen fit to try and
nearly to prove his faithful children many ways:
sometimes by allowing them to be surrounded with humbling fear
and many deep baptisms on several accounts,
which certainly is in order to wean our affections from
too great dependence on a love to things here below,
and to keep us in a state of continual dependence on
himself--who alone is worthy to be trusted in,
and steadily followed through every dispensation of his Providence.

My friend, I heartily join you in desiring a resigned heart,
being fully convinced that it is not for lack of
sufficient help from Him in whom all power is,
that some of the professors of Christianity stumble, and even fall,
and many turn aside and are offended, because of sufferings.
No, it is undoubtedly for lack of having the will of the creature subjected to
Him whose will is to sanctify and redeem mankind to himself.
And surely they will be blessed with an everlasting blessing,
who are not offended in Him who has given Himself a ransom for all that receive him.
And may you and I be so favoured as to have strength
afforded so to follow on in the path of the just,
as to have the happy experience made our own of its
growing brighter and brighter unto the perfect day,
is the sincere desire of my mind, with which I conclude, Your assured friend,

[.signed-section-signature]
Elizabeth Smith.

--

The writer of the foregoing letter was sister to Samuel Smith the historian--
and between her and Rebecca Jones a close fellowship existed,
until the decease of the former, which occurred in meridian life.
We have already seen that they were banded in religious service in the year 1762.

She died in Burlington, 10th mo.
2nd. 1772, aged about 48 years,
and on her death bed warned Rebecca Jones to be faithful and to place
her trust in him who can safely keep his children by sea and by land.
She was, from a child, of unusual steadiness and composure of deportment and character,
and being early entrusted with the care of her widowed father and his family,
her faithfulness not only won his confidence and love, but was also, it is believed,
attended with the divine blessing.
She was of sympathetic heart, much given to works of charity.
She bore a clear testimony to the value of the Holy Scriptures
and against the fashionable publications of her times.
Early called to the work of the ministry she travelled considerably in Truth`'s service,
and having long apprehended herself bound to cross the Atlantic,
she at length spread her concern before the church and received its sanction--but
was soon seized with the disorder which terminated her earthly pilgrimage,
and introduced her, as we doubt not, and as she expressed when dying,
"`into joy unspeakable and full of glory.`"

During her illness having mentally queried, "`Why am I so afflicted?`"
her spiritual ear was saluted with this answer: "`My beloved Son, who never offended me,
drank of the cup before you.`"--"`And thus,`" said she, in speaking of it,
"`I am helped along with one kind hint after another.`"
In a solemn prayer to the Almighty for his support,
when about to undergo a painful operation,
she reverently closed with the following words: "`You are the God of my life,
who has kept me, and fed me all my life long.
Be now near and support by your presence,
and if it is your will to put an end to my being here, I submit.
Be graciously pleased to give me rest in your mansion,
with your dear Son the lamb immaculate, forever and ever!`"
A distinguished contemporary said of her, "`She lived and died unmarried,
a pattern of modest virtue.`"

There is, we apprehend,
a lesson to be derived from the perusal of the
following singularly characteristic epistle,
which we introduce in the present connection.
It brings to mind the humbling caution,
"`let him that is without sin cast the first stone;`" and it shows us
that those who approach most nearly to the blameless Exampler,
are the most tender in extending admonition, or even rebuke.
Upon few have the limitations of Truth been placed with
greater strictness than upon John Woolman.
Few perhaps, if any, have been more faithfully observant of them than he.
Few have turned inward upon themselves a severer scrutiny,
or have turned upon others a milder and more loving eye.
Unreserved in his dedication to manifested duty,
he was filled with that fervent charity which thinks no evil,
and does not behave itself unseemly.
He walked by that Spirit which James Nayler felt in dying, which,
"`as it bears no evil in itself, so it conceives none in thought to any other.`"
And when, in the Divine illumination with which he was eminently favoured,
it was given him to see that by the example of any,
others were "`in danger of being diverted from close attention to the
light of life,`" instead of passing prompt judgment upon them,
it was his concern in the love of Him by whom his own goings had been established,
to remind such that there were lessons for them and him yet to learn;
remembering that "`Christ of old time taught the people as they were
able to bear it,`"--and having "`regard to the state of their minds.`"
He could thus,
in marking his friend and younger sister`'s indulgence in some
things against which he felt that the Truth must testify,
perceive also that the Lord had in great measure, weaned her mind from all these things;
and he could publicly manifest christian unity,
with "`a reserve`" which he communicated to her alone,
in that perfect love which casts out fear.

To our mind,
this letter touchingly depicts the writer as
faithfully attentive to his Master`'s interests,
and full of kindness also to his fellow servants.

[.embedded-content-document.letter]
--

[.letter-heading]
John Woolman To Elizabeth Smith.

[.salutation]
Beloved Sister,

I have often had a tender feeling with you in your outward afflictions,
and I trust, in some measure, with you in your inward exercises.
I believe our afflictions are often permitted by our
heavenly Father for our more full and perfect refining.

The Truth, my dear sister, has been precious in your sight,
and I trust remains to be to you as precious as ever.
In the pure and undefiled way, that which is not of the Father, but of the world,
is purged out.

Christ of old time taught the people as they were able to bear it, and I believe,
my dear friend, there are lessons for you and me yet to learn.
Friends from the country and in the city, are often at your house,
and when they behold among your furniture some things
which are not agreeable to the purity of Truth,
the minds of some, I believe at times,
are in danger of being diverted from so close an
attention to the Light of life as is necessary for us.

I believe, my dear friend, the Lord has weaned your mind in a great measure,
from all these things, and when I signed your certificate,
expressing you to be exemplary,
I had regard to the state of your mind as it appeared to me;
but many times since I signed it, I felt a desire to open to you a reserve which I then,
and since often felt,
as to the exemplariness of those things among your furniture
which are against the purity of our principles.

[.signed-section-closing]
I trust the Great Friend and Helper is near you, in whose love I remain your friend,

[.signed-section-signature]
John Woolman.

[.signed-section-context-close]
28th day 4th mo., 1772.

[.postscript]
I desired my wife to keep this letter for you when she might see you.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To C. Payton.^
footnote:[Catherine Payton married William Phillips in 1779.
Of course this letter which is without date, was written before that time.
It is in the juvenile hand of Rebecca Jones, and the date, it is supposed, should be 1789.
If so, she was then about 20 years of age.]

[.salutation]
My dear and much esteemed friend, C. Payton,

Feeling the arising of divine help and consolation in my soul,
after a time of deep wading and travail in spirit before the Lord,
I with a grateful sense of the salvation of a gracious God,
and the tender care you expressed for my welfare in your last letter to A. B.,
have set pen to paper just to acquaint you that I am alive, and,
blessed be the God of my life, I feel an increasing love for Truth,
for the further I see and witness of the workings and power of it,
the more I rejoice in Christ Jesus that I have been counted worthy to have a sense of it.
Lord grant, says my soul, that the visitation may be extended to thousands more,
even of them who at present seem dead in sins and trespasses,
(as I was when at first reached,) to the awakening, quickening,
and raising from a state of death and separation from God,
to a state of favour and acceptance with Him.

My dear friend, the love I bear you causes me to use great freedom.
I desire if you find aught to write, you may send it, for in a spiritual relation, I can,
in a feeling sense, call you my beloved parent in Christ,
through whom I received the first awakening stroke.
Oh may I ever bear in mind the mercy and lovingkindness of God to my soul:
for a sense thereof has many times sweetened and made easy
that which to the creaturely part was hard and bitter.

I would not burden you with many words, but draw quickly to a conclusion,
for I trust you can feel (though at a distance in body) the circulation of that
spring of love and life that cements the whole flock and family the world over.
Our youth here seem wonderfully favoured, and many will, I hope,
be made useful in the Lord`'s time,
and qualified to fill up the places of those who have faithfully served Him in their day,
when they shall be called from works to rewards.

Friends here, in general, are in pretty good health.
If you should meet with Joseph White, please to remember my love to him, and tell him,
I heard a few days ago that his family were well, and the young man, Benjamin Hinton,
who had appeared at the Falls Meeting, seems to grow,
and promisingly appears a well concerned minister.

--

In a copy of the epistle from the Yearly Meeting of Women Friends of Philadelphia,
held Ninth month, 1755, to the corresponding body of London, preserved by Rebecca Jones,
we note the following paragraphs, which are interesting in the present connection,
as C. Phillips had been made to her the instrument of much good.
(It is regretted that we have not been able to find their correspondence.)

[.embedded-content-document.letter]
--

"`We have to inform you that this, our annual assembly,
has been large and attended with the continuation of heavenly and merciful regard,
graciously manifested for our help and encouragement,
both immediately and instrumentally;
having been favoured at these opportunities with the company
of our worthy and well esteemed friends from Europe,
Jonah Thomson, Joshua Dixon, Samuel Fothergill, Mary Peisley, and Catherine Payton,
whose solid and edifying labours of love in the gospel of Christ,
we have good grounds to believe, have been made effectual to the awakening of some,
and we trust will be blessed by Him who gives the increase,
to the bringing them into a nearer acquaintance with the one Shepherd of Israel,
under whose teachings they may be favoured to find true rest to their souls.`"

"`The reports from some quarters further signify that a
religious visit to Friends`' families among them,
has lately been performed to good satisfaction,
in which weighty service Friends of this city are now engaged,
and so far as they have proceeded, have met with satisfaction,
having therein been favoured with renewings of strength from the Divine hand,
and also with the acceptable company and solidly helpful labours of
our well beloved friends Mary Peisley and Catherine Payton.`"

--

As she was early associated in religious service with Rachel Wilson,
the following testimony of the same meeting, given in like manner in 1769,
having been preserved by Rebecca Jones, may here be inserted.

We have been favoured with the company of our well esteemed friend Rachel Wilson,
from Europe, whose unwearied labours in the service of the gospel on this continent,
have, we trust, proved effectual, through the divine blessing,
not only to the removing of prejudices,
and making room in the minds of the people for the admission
of those important truths relative to life and salvation,
but have likewise tended to the building up and edifying of the body in love;
that praises may ascend to Him, who is over all worthy forever.

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To M. Rickey

[.signed-section-context-open]
Philadelphia. 1759.

[.salutation]
Respected Friend,

It appears to me plainly,
that the query proposed to you is not applicable,
because they that pretend to no supernatural wisdom make no pretensions to religion,
and so differ little from the animal part of creation;
although a measure of the same grace and good spirit of God is given
to them whereby they may know the mind of heaven concerning them,
if they hinder not its work in their hearts by
allowing the lust of the flesh and of the eye,
and the pride of life, to crowd in and fill up the heart.
But we, who profess to be led and guided by the spirit of Truth,
and are sensible that we have a monitor within
that will not only dictate to us our duties,
but if we ask in faith, nothing doubting,
will also give ability to perform that which it makes known to
be consistent with the will of Providence,--I say,
we, who are making such a profession as this,
are not only "`to expect such guidance,`" but it is our
indispensable duty to seek to him for counsel and direction,
if we expect from him a blessing.
But they who are regardless of their future welfare, who mind only earthly things,
set their affections only on visible objects that are fading and transitory,
they look no further,
and if they accomplish their desires by having a companion to assist in this life,
that they may live comfortably here, they think that they need look no further.
But they who are favoured with a prospect of a future state,
and compare this little span of time here, with that immense ocean of eternity,
are satisfied that their chief interest lies in making preparation for it,
seeing that our time here, when compared with eternity, is but as a drop to a fountain.
But at the same time, my friend, I would remark,
that if we only pretend to be actuated by that grand and noble principle of
Truth,--if we are only satisfying ourselves with a name to Christianity,
and at the same time are destitute of the life and power of religion, we are mocking God,
and deceiving our own poor souls.
And such as these are, I fear,
in a worse state than those who openly rebel and
manifest that they are children of the world,
and so enemies to the Cross; because they are true to their king,
though he be an enemy to the kingdom of love and light.
But these who are in the service of the devil, and yet pretend loyalty to God,
are deceivers in his sight, and he beholds them with derision.
In short, love begets love, and where `'tis from a motive of love that is pure,
and the person`'s expressions agreeing with Truth,
(for out of the abundance of the heart the mouth speaks,) when we see
that they are founded upon the sure immovable foundation,
we need not fear adversity, neither shall we in prosperity be lifted up.

It is religion only that beautifies, and where that is lacking,
(I don`'t mean a name only,) the distinction between a
reprobate and a Christian is also lacking.
I hope with you, that you may with sincerity, seek wisdom and counsel of God, and then,
if it is with sincerity, he will hear and answer your request.
It is my prayer that you may be favoured with
the knowledge of the truth as it is in Jesus,
for I am of the faith that our God will raise up
from among the youth of this generation,
faithful men and true-hearted women that need not be ashamed,
some labouring in a private and some in a public manner,
for the exaltation of the blessed Truth,
if they stifle not that which will burn up all the chaffy part,
and purify the heart thoroughly,
and make them fit vessels to contain the precious treasures of the heavenly gifts.
May we be of this happy number, that we may know the purging power of Truth,
to do away all that which is of an unsanctified, unholy, impure nature,
that being quickened by the life of religion, we may be able to glorify God in our day,
age and generation, and that, whether single or married, living or dying,
we may have the evidence in ourselves that we are his,--is what I earnestly desire.

[.signed-section-signature]
Rebecca Jones

--

An ancient mansion stands No. 8, Drinker`'s alley, Philadelphia.
Its kitchen window, which opens to the westward, afforded, at the time of which we write,
a cheerful prospect of a pleasant garden,
the site of which is now occupied by a smith`'s shop.
On a pane of said window may be read the name of Mary Jones,
and of three others of the same surname, inscribed, probably, with a diamond.
Here dwelt the mother of Rebecca Jones; here Rebecca and her friend, Hannah Cathrall,
succeeded her in her school,
which was continued in this place till the departure of the former for Great Britain.
An intimacy subsisted between Rebecca Jones and John Woolman,
and she sometimes spent the principal part of the summer vacation at his house.
We have lying before us several specimens of his more careful penmanship,
in writing copies performed by him to be imitated by the pupils of his friend,
and which were used in her school, of which he was an occasional visitor.

[verse]
____
"`Knowledge shall be promoted by frequent exercise.`"

"`Happy hours are quickly followed by amazing vexations.`"

"`Just be your thought and every word sincere;`"
"`And know no wish but what the world may hear.`"

"`If you know Christ, you need know little more;`"
"`If not, all`'s lost that you have known before.`"

"`Censure none rashly; Nature`'s apt to halt;`"
"`Look inward; He`'s unborn that has no fault.`"
____

On the night succeeding the Select Quarterly Meeting-day, in the Second month,
probably about the year 1762, a great fall of snow occurred,
which was next morning piled by an eddy half way up the
door and window of our friends in Drinker`'s alley,
who were apprehensive that they might not be able to make
their way through the snow drifts to Quarterly Meeting.
Rebecca Jones opened the door to sweep the snow from the step, and found to her surprise,
the pavement cleared, and a path made down the alley to Front street.
While she was preparing the morning repast, John Woolman entered,
saying that he thought he had earned his breakfast.
Having spent the previous night at Reuben Haines`', in High Street near Fourth,
he arose early, and remembering the lone sisters in their need,
and ever ready for an appropriate labour of love, however humble,
he took with him from his lodgings, a snow shovel,
proceeded (wading through the deep snow from Second street downwards,)
and cleared a path from Rebecca Jones`' to the Bank Meeting,
in Front near Mulberry street.
After breakfast he made a passage to Second street for the benefit of the scholars.

A letter from John Woolman to Rebecca Jones, dated Mount Holly 4th Mo. 20th, 1772,
contains as is supposed, a reference to this visit,
and concludes with commending her "`to Him who is a Father,
a Counsellor and Safe Protector to his family,
through the various difficulties which attend them in this world.`"

"`8th Mo. 20th. 1772.
"`This day our beloved friend Sarah Morris laid her concern to visit friends
in Europe before our Second day morning meeting for its consideration.
She expressed her feeling with much weight and brokenness,
and informed that she had had a distant prospect of that service for many years,
but that since the decease of her dear mother it had
been nearer and now was very weighty upon her.
Friends expressed much sympathy and unity with her;
and next fourth day she intends for Burlington,
there to confer with our dear friend Elizabeth Smith, who is under the like concern.`"

By the following minute of Burlington Quarterly Meeting, held at Chesterfield 5Mo. 25th,
1772,
it is inferred that our friend was at the time of its date
engaged in religious service abroad with a certificate.
"`We were now favoured with the company of our
esteemed friends Rebecca Jones and Joyce Benezet,
to our satisfaction and comfort.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Elizabeth Robinson, (then In England.)

[.signed-section-context-open]
Philadelphia, 6th mo. 25, 1775.

[.salutation]
My beloved Friend,

As you have been so particularly near my spirit today,
I thought this evening, while my dear Hannah is at meeting,
I would stain a little more paper in writing to you.
I wrote you by Capt.
Falconer, the next week after you embarked,
which I hope will be soon received if it has not been already.
And now I may tell you that our dear friend, S. Morris,
is so much relieved (though not well,) that she was at Germantown Meeting last First day,
and this morning at our great house,
in both which she kept her seat and preached the gospel.
My dear Hannah appeared in public ministry this day two weeks,
while I was at Salem attending the Yearly and Quarterly Meetings there.
I took Woodbury, Pilesgrove and Alloways creek in my way.
William Brown, Isaac Andrews, and Grace Fisher, had good service there +++[+++at Salem,]
and poor I, as usual, in such large meetings,
was favoured to keep pretty still all but one day.

We this day visited Samuel Smith and wife.
Since the morning meeting,
Samuel Emlen told me he was much with the dear Friends at London,
and he fixed you at Devonshire House, M. Leaver at the Peel,
and Robert at Gracious Street.
He almost set me a longing to be with you.

I wish I was able to give you a cheering account of matters here, but that I cannot.
Oh for the testimony, how it is trampled upon by many in profession with us!
Last First day morning a Friend, by name Martha Harris,
(whom you must have known,) began at Pine street, then went to G. House,
and lastly at Bank, with the same message to all.
She left her bonnet at the door,
walked up the meeting house through all the upper and lower galleries,
then very gradually through the passages, under them,
and then turned about to the meeting and said with an audible voice--"`Dear Friends,
look to the God of Heaven and of the whole earth,
for he is about to search his camp--this is
truth and no lie,`"--after which she withdrew,
and went home to North Wales, without attending any other meeting.
She appeared to me to be under a very great exercise, and I was not uneasy with it,
though many others were much so.
Neither did I find that her singular appearance did in
the least disturb or unsettle any of the meetings.
I am sure it did not ours.

I am in hopes we are not all mistaken in supposing you now in London.
If not, I am much out in my prospects, thinking you all there the 1st of this month.

Now I think I should be sorry to tire you,
but you know I did not use to be tired of being with you,
and this a little supplies the place of conversation.
Allow me to say, my heart loves you,
and fervently wishes you may be preserved faithful to the end of your days.
I am encouraged in my present state of great weakness and poverty,
in the remembrance of your unreserved dedication to the Master`'s counsel.
Dear friend, have me in your remembrance, for indeed I am a poor, feeble child,
and sometimes doubt ever being otherwise; yet, if I know my own heart,
I wish to be what the gracious, compassionate Father of the family intends,
whatever conflicts and difficulties may attend.

My spirit salutes you in true gospel fellowship, and bids you farewell in the Lord.

[.signed-section-signature]
Rebecca Jones

--

Respecting this friend, Rebecca Jones has left the following brief note:

"`1773, 9th mo.--Robert Walker and Elizabeth Robinson, arrived from Yorkshire;
both faithful labourers in the Lord`'s work, and delivered many warnings in this land.
Sailed from Chester in the 4th month, 1775.`"

Of a visit performed in 1779, within the limits of Baltimore,
and probably also of Virginia Yearly Meeting,
little is known beyond what is contained in the following letter.

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Warner Mifflin.

[.signed-section-context-open]
Philadelphia, 8th mo., 1779.

[.salutation]
Esteemed Friend, Warner Mifflin,

Although I was somewhat disappointed
on the return of my dear companion from your Quarter,
she informing me you had not found time to write to me,
I feel the prevalence of that disposition ever worthy of aspiring after,
"`do as you would be done by,`" and therefore--I may inform you respecting myself,
(R. Chambers, I suppose,
has given you her account,) that after you left us we were poor and quiet some days,
and after attending Fairfax and Goose Creek Preparative Meetings,
and the Monthly Meeting at Fairfax, were in the resignation to go forward, if best,
and in order thereunto, accompanied by Jos.
Janney, Mahlon and his sister Mary, we the next First day got as far as South Fork,
attended that meeting, which was a time of deep exercise,
and went five miles further on our way to John Gibson`'s (his wife Ruth in a poor way,
and glad to see us,) where we lodged.
In the morning, my very enfeebled state, both of body and mind,
together with the deep and singular provings and
exercises I had undergone in this journey,
so discouraged me, that upon Rebecca`'s saying she thought of setting her face homewards,
I at once submitted to her prospect, not daring to proceed on my own concern barely;
and here I think we missed it, for I now believe if we had kept more in patience,
and clave close to the great Master, we might, at least, have returned with as much,
if not a greater share of peace.
As to the propriety of your all leaving us in that wilderness, I leave it;
if you have settled it with your Master, I dare not judge.

Warner, I am a poor, feeble, tottering child,
and am thankful at times that I see myself so; and this sense,
though it does sometimes prevail to the retarding of my own steps, yet is, I believe,
intended in mercy to keep my feet from sliding.
Oh, the necessity of dwelling deep! ever watchful on the
pointings of that hand that does all things well;
for lack of which my own hand has sometimes lifted itself up, and in so doing,
I have not failed to make work for repentance.
I concur in your sense of things in those parts as
expressed in your letter to my Hannah Cathrall;
but must tell you the field of painful labour yet remains open,
and many hands may also lighten the work there, as well as in other places.
We took some meetings on our return, such as Monomy, Bush Creek, Pipe Creek, Monallen,
and Huntington, and left all the rest for another time, or other hands.
I am often encouraged in remembering the apostle`'s declaration,
"`If there be first in you a willing mind,
a man is accepted according to that which he has,
and not according to that which he has not.`"
So that to be entirely willing, or in other words,
unreservedly dedicated to the Lord`'s serving,
is the sure prelude to his blessed favour and acceptance;
this I am labouring according to my little measure for,
and sometimes think I feel pretty near it, when, maybe,
in the instant moment of struggling, the poor unmortified creature shrinks,
draws its neck from the yoke, and its shoulder from the burden,
and then it is all to do over again with renewed exercise and increasing labour.
It may be that this is only my case.
However, I do breathe for strength to follow on,
and if I cannot keep company with the foremost, I hope I may come up in the rear,
so as that I may not be left quite behind.

Give my love to your spouse, and to Daniel and his wife, in which my companion unites,
and also in the expression of care for Daniel and his amiable Deborah,
that they may not only see and approve that which is excellent,
but with heart and hand join in with the tender visitation of love and mercy,
so as they may, by the sanctifying operation of truth,
be made what the Lord would have them be, not serving themselves,
but him who died for them,
and who has bought them with no less a price than his own blood.
Stupendous thought!
Matchless love and mercy! which we can never too much adore,
nor will the greatest returns in our power to make,
be adequate to such infinite lovingkindness.

[.signed-section-signature]
Rebecca Jones

--

[.embedded-content-document.letter]
--

[.letter-heading]
David Sands To Rebecca Jones And Hannah Cathrall.

[.signed-section-context-open]
New Cornwall, 10th of 9th mo. 1781.

[.salutation]
Dear Friends,

We read, as from the lips of our blessed Lord,
that blessed are the poor in spirit.
I have viewed you as a part of this number, who have your way through much poverty,
and at times great tribulation,
in which situation I can at present sympathize with you in some measure,
I having been for some time past in rather a low spot;
having had several poor turns as to my health,
and I think I find myself under more weakness of
body since I left Philadelphia than ever before;
having been much of the time hardly able to sit a long meeting;
and under these trials my mind seems to be stayed on the Lord,
in hope that if it is his will that this earthen tabernacle should be dissolved, I shall,
through the merits and mediation of a Redeemer,
gain an admittance into those joys that are unspeakable and full of glory.
I have had to remember you in much affection and nearness,
and the many useful little hints you occasionally dropped in my hearing,
as also the letters I received from you at the Western Quarter,
and esteem your cares and kindness as the truest tokens of real friendship.

I believe I should have written to you before now if I had been at home;
but I thought at this time,
duty and inclination joined in strengthening my hands to take up the pen and
endeavour to make some small retaliation for the favours and kindness received;
and withal, in hopes of drawing some small bill on one or both of your pens, as I shall,
I believe, always be glad of a line from you whenever freedom and opportunity will admit,
and shall endeavour to make the best remittance I am capable of, which is but small.
I have looked at your situation as a life of care,
and much exercise in your outward employment, as well as in your more public, and,
what if I also say private labours; still I do believe it is by direction of best wisdom,
and in providential care for the help and welfare of Friends in the city,
both parents and children.
Though I believe this favour, like many others, is too lightly thought of by some,
yet I believe there is a remnant preserved in a living sense thereof,
unto whom you are often made very near.
And I have sometimes thought there is abundant cause
for the honest-hearted to be encouraged in hope,
that though Israel be not gathered according to their desire,
yet they are still glorious in the eyes of the Lord,
and their God will be their strength.
But notwithstanding what I have said,
I don`'t mean to confine your labours within the walls of the city;
believing that if I have to accuse you of any neglect of duty,
it is in not being more given up to visit the more remote parts of the family.
And I may say, I have sometimes thought there appeared too many buts and ifs,
and these I have feared were sometimes too much given way to,
to the hindrance of some services that might prove advantageous to yourselves,
and shall I say, to many of the sheep and lambs that the Master has ordered to be fed,
I shall leave you to find or judge by whom.

Thus my dear friends and sisters,
I shall conclude with desire for your prosperity every way,
and remain your truly loving and affectionate friend,

[.signed-section-signature]
David Sands.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Edward Cathrall.

[.signed-section-context-open]
Philadelphia, 7th mo. 25th, 1782.

[.salutation]
Dear Edward,

Since you left your father`'s
house my mind has many times turned towards you,
sincerely desiring that you may not only witness preservation from every temptation
that may present to draw you still further from the path of innocence,
but that by a steady adherence to the quick and
powerful Word in the secret of your own mind,
you may be brought into an acquaintance with a state of true inward stillness,
in which you may be favoured to understand the things that belong to your soul`'s
peace--which is of the greatest consequence both to the aged and to the youth;
especially when we consider that our stay in this world is very uncertain, and that,
after we have done with things below, we must appear before a righteous tribunal,
there to give an account of the deeds done in the body, whether good or evil.
How careful then ought we to be in our steppings through time;
how watchful should be our words and actions!
Retirement of mind is such an excellent situation,
(I have found it so,) that I cannot but recommend it to you.
May you often retire alone, and rather choose to be so,
than in such company as may have a tendency to do you hurt.
Young people who are inexperienced, are often drawn into things highly improper,
if not offensive, in the sight of heaven,
for lack of keeping on their guard in this very spot: whereas,
if they did but love silence,
and to hearken to the monitions of Divine grace in their own hearts,
they would grow up in good liking, yes, in favour with God and man.
My heart prays for your preservation, and that you may,
now in a state of separation from all your tender connections,
be met with by Him who is willing to do them good,
and who is waiting to be gracious to the descendants of
those who have loved and served Him,
as your grand parents did.

Keep this letter to yourself, and read it over leisurely,
it is the language of one of your best friends.

[.signed-section-signature]
Rebecca Jones

--

5th mo., 5th, 1783,
Rebecca Jones notes.--"`I awoke this morning with the following passage:
"`You have not chosen me, but I have chosen you,
that you should go and bring forth fruit, and that your fruit should remain.`"
Oh, my soul, treasure up and improve under the present favour.
"`16th--This day Samuel Emlen opened a concern for visiting England the fifth time.`"
On the 6th of 7th mo., having attended three meetings under great exercise and conflict,
she records a petition to be preserved from murmuring, and helped to redeem Time.
10th mo., 27th, she opened to the 2nd day morning meeting, and 11th mo., 24th,
to her Monthly meeting, the prospect of the important and extensive service,
upon which she was soon to enter; and under the last date, she remarks,
"`Divine help was near,
and our spirits were baptized together under its blessed influence.`"
29th, she notes, "`10 o`'clock--a still, clear sky--an awful shock of an earthquake.`"
