== Chapter IV.

[.chapter-subtitle--blurb]
1784--1785.

[.chapter-synopsis]
* Contrast by Enoch Lewis between the state of our Society in Rebecca Jones`'s day and in our own.
* She attends London Yearly Meeting and enters on her travels northward
* Letter to and from various friends
* Dream respecting John Reynell and its realization
* Family visit at Bradford
* Returns to London
* Requests a meeting with her American fellow-labourers
* Anniversary of her arrival inadvertently kept.

Her memoranda of the time spent in Great Britain and Ireland,
(every day of which is noted,) are, in some particulars, curious and minute,
and doubtless were designed to assist her memory in the
preparation of an auto-biographical memoir,
to which task, though her humility shrunk from it, she at times felt her mind drawn.
They do not, however, assume the form of a regular religious diary,
and afford very little aid to the present compilation.
In a neat and compact form, we find tables of the meetings of that nation,
lists of the ministers, and of all the Friends residing in the different places visited,
with other minutiae.
The deficiency in the diary is in a great measure supplied by her letters,
and would be wholly so could we have access to all that were written.
A mere narrative of her journeyings might be comprised from these,
but to divest it of the portions which are only appropriate to the epistolary style,
would deprive the general reader of much that might prove instructive,
and lessen the interest of these memoirs to the numerous class
of individuals to whom her memory is still fresh.
The compiler moreover is desirous of presenting the subject in her words,
rather than in his own.

We offer no apology for inserting the following interesting observations,
which form part of an editorial in Friends Review,
and which were written in especial reference to this portion of our narrative,
the able and venerable editor being one who well knows the things whereof he writes.

[.embedded-content-document.paper]
--

"`The memorials of Rebecca Jones,
and especially the part which has recently appeared in the Review,
must recall to the memory of such Friends as, like the Editor,
have nearly reached the western verge of life,
the condition of our religious society at the time when
Rebecca Jones`' visit to England was performed.
We find by the narrative before us, that no fewer than five Friends in the ministry,
who were engaged in the love of the gospel to visit the
churches on the other side of the Atlantic,
were passengers in the Commerce.
Of these, four were members of Philadelphia Yearly Meeting, residing in or near this city.
At the same time we find that two Philadelphia Friends were there,
John Pemberton and Nicholas Waln, traveling in religious service in England or Ireland.
Thus it appears that at least six eminent ministers,
all residing within a few miles of Philadelphia,
were then engaged on a mission of love to the British Islands.
Simultaneously with these visits, or shortly afterwards,
a number of European Friends traversed the parts of the
United States where members of the society were located.
This interchange of gospel messengers was then
going on between the people of two nations,
whom their respective governments had, a short time before, placed,
as far as governments could place them, in the attitude of enemies.
The epistolary correspondence which was maintained
between our Yearly Meeting and that of London,
and the mutual visits which were paid by ministers and
others immediately after the revolutionary contest,
may be considered as conclusive evidence that the storms of that
turbulent period had no power to estrange the minds of Friends,
on different sides of the ocean, from each other, or to interrupt the harmony which,
as professors of the same faith, and advocates of the same cause,
they had always maintained.

Whether the same cordiality of religious fellowship is experienced in our day,
is a question which very naturally presents to the reflective mind,
but which we shall not answer, either positively or negatively.
Of one thing we may speak without hesitation.
The reciprocation of gospel messengers has very
visibly declined since the period in question;
and the number of those, on both sides of the Atlantic,
who are clothed with the gifts of apostleship appears greatly reduced.
A comparison of the society at these different periods, forcibly revives the inquiry,
"`Your fathers, where are they, and the prophets, do they live forever?`"
and upon whom has their mantle fallen!
Has our religious society retained its position
in the forefront of civilization and reform,
or has it fallen behind!
These questions we leave to be answered as the judgment
and observation of our readers shall suggest.`"

--

After having attended twenty meetings in London,
(including the Yearly Meeting,) our friend on the 12th of 6th month,
accompanied by Christiana Hustler, T. Corbyn, and Adey Bellamy,
went to Colchester Quarterly Meeting, taking her abode at John Kendall`'s. After this,
and a meeting at Manningtree, the following letter was written at Dykes Alexander`'s,
to her old friend John Pemberton, then in Ireland.

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To John Pemberton.

[.signed-section-context-open]
Needham, in Suffolk, 6th mo. 17th, 1784.

[.salutation]
Esteemed friend,

I was much disappointed, among others,
in not meeting with you at London.
I suppose by the return of Samuel Neale and J. Gough,
you have been furnished with a particular account of the Yearly Meeting, and,
among other things, what is concluded upon respecting the Women`'s Meeting.
I desired S. F. to send you a copy of the minute on that head.
My heart was made thankful in that the women`'s application
carried the weighty evidence of Truth with it,
and that men Friends were made so feelingly sensible thereof,
that they yielded as brethren.

I have no doubt that my arrival in this land is a matter of astonishment to you,
as well as to many more, who do know what a poor feeble creature I am.
But, having resigned my life and all into the Lord`'s hand,
I have witnessed preservation over the mighty deep (our
passage being four weeks from land to land,
without any storm, in an easy ship, with an obliging,
kind Captain,) and was kept quiet in mind during the voyage,
trusting in the Providence of the Almighty, who has been rich in mercy towards me,
an unworthy servant.
Blessed be his great name!

During my stay in London, which was two weeks,
my path was in the way of silent tribulation, and at times very low,
yet content to suffer with the seed, remembering that declaration,
"`Where I am there shall my servant be.`"
And now, having attended the Quarterly Meeting at Colchester,
and proceeding towards Woodbridge and Norwich Quarterlies,
I don`'t see how I may be directed afterwards,
whether to proceed into Yorkshire before the cold weather or not.
I see very little at a time; you know it used to be so with me,
and I am as poor a thing as at any time heretofore when abroad.
But my earnest prayer is that I may be kept in childlike simplicity, and in a humble,
watchful frame of mind; and indeed the little opportunity I have had among Friends here,
has furnished me already with a prospect of the
need of steady circumspection and holy fear,
to step along rightly and safely among the wise and great in this world.
I can say of a truth I am willing to appear as a fool in their eyes;
if but favoured with the great Master`'s presence, it is enough.

You have my true sympathy in your particular allotment,
and a degree of faith springs in my heart, that you will, before long,
see your way out of Ireland, and, I hope,
be fraught with sheaves of solid peace and satisfaction of mind.
And if, in divine direction, we should fall in with each other,
it would be to me truly comfortable.
But I dare not desire anything of that sort, only that,
however little my appearance among the tribes,
and feeble my endeavours towards the promotion of the great cause,
I may be preserved from bringing any sort of blemish thereon--
for it is in my view precious beyond all things.

Patience Brayton and Mehetabel Jenkins have gone towards Yorkshire--N. W. is there,
I left the other Americans at London; Christiana Hustler being my companion,
and Ralph Bainbridge, of Durham, with us.

Your dear spouse has opened her heart and house to my dear Hannah Cathrall, who will,
for a time, abide with her.

My Hannah Cathrall could not yield with perfect resignation and clearness to
a prospect under which she had laboured for some time of accompanying me;
it was too great an indulgence; we were not to be gratified;
and whether she may feel it again revived, I cannot tell;
but of this I am fully convinced, that her desire of soul is to do right, and I trust,
if she sees her way, and is helped along,
she will be of service among Women Friends in this nation,
who are in need of suitable help in the discipline,
and you know she is peculiarly gifted therefor.

I feel the precious unity while I am writing,
and in it can freely subscribe myself your poor little affectionate friend and sister,

[.signed-section-signature]
Rebecca Jones

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Henry Drinker.

[.signed-section-context-open]
Leiston Abbey, about 17 miles N. E of Woodbridge, 6th mo. 23rd, 1784.

Yesterday, after the Quarterly Meeting at Woodbridge, being low, poor and disconsolate,
I received a few lines from my good neighbour, brother and friend, H. D., which,
being the first intelligence from my beloved native land, did revive me.
The removal of that little valiant man, A. Benezet, will be a sensible chasm.
But I remember from where he derived his qualifications,
and that the Divine fountain is inexhaustible.
I feel, as I should do, on the occasion, and for dear Joyce,
who is not far from the same peaceful mansion.
It is truly comfortable to hear that I have a place in the affections of your family.
May they increase in every durable good.
I note your kind desire for my "`growth in faith, strength,
and love which casts out all slavish fear,`" and I add to the necessary train,
humility and childlike simplicity.

My situation while on the voyage and in London, will, I expect,
be imparted in that freedom which subsists between Hannah Cathrall and you.
I left that city on the 12th, having worthy Christiana Hustler my companion.
She has felt for me.
T+++.+++ Corby went with us to Colchester--attended
that Quarterly Meeting--took a few +++[+++Manningtree,
Needham and Ipswich,]
in the way to that at Woodbridge.
That being over, we are now on our way to Norwich Quarterly Meeting;
after which I hope to wait for right direction.
You know I am a little one, and such don`'t see far at a time.
What a favour that it is so!

Dear Henry, don`'t forget your feeble sister.
My heart is earnestly desirous that I may be kept where only true safety is known,
and I have felt very peaceful while sitting and looking like a fool among the great,
wise and good.
Several feeling Friends have been helpful in sympathy.
I have admired at it, as my case has been quietly concealed within;
but the heavenly fellowship enters deeper than words,
and in it I have found comfort and sweetness.

R+++.+++ Valentine had a certificate signed for returning.

On comparing the date of your note with the memorandums made at sea,
I find by my note of the 16th, that your pen was under right direction.
So be encouraged in future to do "`what your hand finds to do.`"
I feel as I approach Norwich, much in the same situation as when drawing near London,
and feel as willing to appear like a fool; so that I may be kept in my place,
is my earnest desire.

Norwich, 7th mo.
1st.--The Quarterly Meeting here, ended yesterday.
Wm, Matthews and E. Gibson, with many others from a distance, attended,
and though in many instances there is abundant cause of lamentation and mourning,
yet the precious visitation of divine love was remarkably extended to the young people,
many of whom were bowed under it.
My heart was secretly comforted and raised in hope,
that some of them will be preserved under it, and be made useful vessels in the family.
Many of the youth here and in London are wide in their
appearance from the ancient standard of plainness;
but there is a tender part in them, so very susceptible, that `'tis beautiful to behold,
and what I have often wished was the case with the gay and
thoughtless among that class in my native city more generally.
Upon the whole, it may be said with thankfulness,
there is yet a solid number in this place, who are,
under the present low state of things, much depressed.
Among whom are particularly, worthy Edward Gurney and sister Mary, etc.

As to future movements,
I rather think my face will in a few days be turned towards Yorkshire.

N+++.+++ Waln, P. Brayton, and Mehetabel Jenkins, are now in Yorkshire.
Thomas Ross and Samuel Emlen are in London,
detained by Thomas`'s indisposition and bad leg, he having hurt it on ship board.
I am afraid it will be tedious, if not worse.^
footnote:[It proved the cause of his death.]
George Dillwyn yet in London.
R+++.+++ W. with a friend from Manchester has gone that way,
and dear John Pemberton is yet in the gloomy confines of Ireland.
I should rejoice in his release therefrom.
Salute me to your household,
and to all other my dear friends who are too numerous to name particularly.
May the Lord be near you, and keep me truly dependent on Him,
is the prayer of your obliged friend and sister.

[.signed-section-signature]
Rebecca Jones

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Hannah Pemberton.

[.signed-section-context-open]
Norwich, 7th mo. 1st.

I have been kept in the patience, and can, of a truth, say,
the Lord has been very gracious to me, a poor, unworthy creature, both by sea and land.
And it is the prayer of my heart, that I may be kept humbly dependent upon Him alone,
without whose renewed aid nothing can be availingly done in
this day of grievous revolt and deep backsliding.
Yet there is a comfortable prospect among the youth here, which will, I trust,
as they keep under the sweet visitation with which they have been favoured,
make some of them honourable, as, in the beginning, our forefathers were.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Rebecca Jones To John Pemberton.

[.signed-section-context-open]
Thorn, the edge of Yorkshire, at N. Dearman`'s, 7th mo. 22nd, 1784.

[.salutation]
Much esteemed friend,

Your truly acceptable salutation of the 28th of last month,
I received at Lynn, the 11th of this,
and at a time that rendered its contents the more valuable,
as my mind was very weak and low.
I am truly thankful that I am yet counted worthy
of a place in your affectionate remembrance,
whose brotherly sympathy I much desire may be continued.

R+++.+++ Valentine with S. Fisher, I expect, sailed on the 10th in the Commerce, Capt.
Truxton, who, I hope, will be as kind to them as he was to us,
for he behaved to us with great courtesy and respect.
I understand N. W. and Mehetabel Jenkins are gone into Scotland.
The latter I expect, intends for Ireland.
I have had no late account from Thomas Ross, whose leg was badly hurt at London.
George Dillwyn and Samuel Emlen were also there.
R Wright is still with Martha Routh, in the midland counties, and Patience Brayton,
I hear, is gone back to London.

I note the account of your situation.
I feel deeply with you under it, and trust in the Lord`'s time you will be released;
still having a hope it will not be long before you are
set at liberty to come into this nation again,
where, if I am favoured to meet you, I shall rejoice.

Hitherto, since I left London,
I have been helped with a little strength from
day to day to step along in the line of duty,
and as you observe respecting yourself--"`trust the good cause has not been
dishonoured,`" and am sincerely desirous that I may be kept truly dependent on the
all sufficient Helper of his people in childlike simplicity and humility.
Great need I find to be watchful,
lest by a conformity to some customs which have crept in among this people,
strength should be given to that part which stands opposed to
the plain self-denying path into which our worthy predecessors
were divinely drawn and enabled to walk.
My mind is often led to admire why so many servants from a
distance should be employed in this part of the vineyard,
and as often I am led to believe `'tis for some good and valuable purpose.
Oh that nothing may be permitted to lay waste the service intended,
but that we may all steadily eye the great Shepherd,
and that he may be graciously pleased to furnish with strength and
wisdom in all our movements to the praise of His worthy name,
and the real benefit of the churches,
is the humble prayer of your truly affectionate friend and sister.

[.signed-section-signature]
Rebecca Jones

[.postscript]
====

26th.^
footnote:[At Thomas Proctor`'s, Selby]
_P+++.+++ S._--Thomas Ross has gone for Bristol in order for Ireland.
S+++.+++ Nottingham is now in London.
I have heard of the death of Thomas Millhouse.
Since writing the above, George Dillwyn and Samuel Emlen are gone for Holland.
I am now at Ackworth much tried, and in poor trim every way;
yet my mind has been for some time and remains so feelingly dipped
into sympathy with you in your present and late particular exercise,
that I have often been on the inquiry,
and am now informed that you have been led in so singular a line,
that must have been deeply trying, I know, to you.^
footnote:[John Pemberton, while on this visit, as well as at some other times,
found his mind engaged in a manner which has not been common of Latter times,
with ministers of our Religious Society.
He was not only engaged in the appointment of meetings where no Friends resided,
and where meetings of Friends had not been previously held,
and in visiting the prisoners confined in the jails;
but he apprehended himself called to walk through the streets of Londonderry,
and preach repentance to the people there.
To this concern he at length gave up, after a long and painful struggle.
It is probable that this singular engagement was one of those
to which Rebecca Jones alluded in the letter before us.
It was much to the credit of the people of Londonderry that no insult
was offered to our Friend while employed in this remarkable mission.
Exercises of a similar kind are several times noted in the early history of the Society;
but the conduct of the populace was often very different from that
which J. Pemberton experienced.--Editor of Friends`' Review]
May the Lord, dear John, be with you, and furnish with best wisdom in all your movements,
(which, I have no doubt, has hitherto been the case,) and, if it be His will,
give you a release in mercy, with the income of solid peace.
My heart again salutes you and bids farewell.

====

[.signed-section-signature]
Rebecca Jones

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Hannah Cathrall.

[.signed-section-context-open]
Undercliff, near Bradford, Yorkshire, 8th mo, 6th, 1784.

Sitting quietly in my chamber this morning thinking about you, Sally,
the eldest daughter of my truly kind friend and fellow helper, Christiana Hustler,
came up with your salutation of the 4th of last month, which, with three others received,
I enter No. 4, and wish you would in future number them,
as I should then know how many are written; and as mine are all numbered,
I wish to know whether all have come to hand.

I find by your last that you are comfortably accommodated at H. P.`'s,
for which I am thankful; but you are still in an exercised path.
May Divine wisdom be your safe director, counsellor and strength.
I have no doubt that as you and I stand resigned in our wills to the Lord,
who has been so rich in mercy towards us, we shall find grace to help in time of need.

I have from time to time given you a particular account of my steppings in this land,
which have been in great weakness and fear,
deeply bowed under a sense of the present state of society,
and of my inequality to the necessary labour of the day:
yet often confirmed in hope that it is the line of duty,
and I am therefore desirous to be kept in a steady trust and dependence on him, who,
as I do believe, has required this sacrifice at my hands,
and whom my spirit feelingly acknowledges to be worthy to be served, loved and obeyed.

I have been this week at John Hustler`'s, resting and refitting,
and his amiable spouse appears willing to bear me company a while longer,
which I esteem a favour.
We have been much united in spirit and labour.
We have now meetings laid out in the west riding of Yorkshire,
in order to be at some of the twelve Monthly Meetings which constitute this
Quarterly Meeting which falls out the beginning of next month,
and after that may perhaps proceed towards New Castle; but I see my way so gradually,
that I hardly dare say where next;
only may tell you that I am desirous of falling in with Monthly and Quarterly Meetings,
which will, I expect, make more riding.
And as to some places, it will be impractical in a chaise;
don`'t know how I shall be able to bear trotting on horseback.
As yet, I am favoured with Christiana Hustler`'s chaise,
which has conveyed us above five hundred miles.

In my last I gave you an account of the Americans as far as I knew,
and have not heard since about them.

My love to your connections is not lessened--tell them so--and persuade dear R. for me,
that she will feel more true satisfaction in conforming
to the blessed witness in her own mind,
than in any gratification that can possibly arise from the indulgence
of a vain and airy appearance in her future arduous movements.
I have the same desire on account of J. He does know better;
but oh this conformity to the spirit and fashions of a degenerate age,
how it does fetter the hearts of the beloved youth!
May their bonds be burst asunder by the Power of Truth,
and they be brought under its humbling operation!
Dear, very dear love to all my friends as if named;
mine to you is not to be conveyed by pen and ink:
feel me therefore in that which has kept and will forever keep us near in Spirit,
as we abide with it, and under its influence.

[.signed-section-signature]
Rebecca Jones

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Hannah Pemberton, (Wife of John Pemberton, then In England.)

[.signed-section-context-open]
Undercliff, 8th mo 6th, 1764.

[.salutation]
Dear Friend,

I expect you will often hear of your precious John Pemberton, who was well,
and fervently engaged in his good Master`'s service.
May he be sustained, for the harvest is truly great, and faithful labourers but few;
and you will also have your reward, if you are as careful in the line of improvement.
And when you are favoured to meet again,
may you be each other`'s joy and comfort in the Lord.
As to this climate, very few days but have borne a fire morning and evening,
and I am at times pinched with cold.
If there happens a moderate day, the people here complain of oppressive heat.

The easy mode of traveling with which I have been favoured, calls for thankfulness.
Love to all your and your husband`'s relations, also to E. Clark, R. Jackson,
Phebe and Oranock, and accept a large share yourself from your loving friend,

[.signed-section-signature]
Rebecca Jones

--

The following letter to a young physician, then prosecuting his studies in England,
and who afterwards became eminent and honourable in his profession,
is not only interesting as reviving his memory,
but may also be serviceable to other travellers in pursuit of knowledge.
Our readers will scarcely need to be informed of the
realization of the desire expressed in the closing sentence.

[.embedded-content-document.letter]
--

[.letter-heading]
To Caspar Wistak, M. D.

[.signed-section-context-open]
Undercliff, 8th mo. 9th, 1784.

As in all probability I may not have an opportunity of seeing you again for some time,
(if at all in England,
or ever,) and feeling an earnest desire of heart for your preservation from the
many dangerous snares so peculiarly awaiting your present exposed situation,
and that you may be so happily conducted in the line of true rectitude,
in your general conduct,
as well as for your better improvement in that which is really valuable,
and suiting the dignity of a candidate for an eternally enriching prize;
I thought that consistently with my duty,
I could not forbear apprising you of the necessity of endeavouring carefully,
in the course of your travels, and especially when among "`men of corrupt minds,
reprobate concerning the faith,`" to maintain the watch,
lest while you are making an improvement in matters relating to your medical knowledge,
the better part in you should receive essential damage,
and which would be prevented by a steady resolution
uniformly to maintain the noble character of a Quaker,
despising the shame, which you in moments of weakness may conclude consequent thereon.
Hereby not only solid satisfaction of mind would be witnessed,
which is more truly desirable than the approbation or applause of the
gay and irreligious part of mankind can possibly furnish,
but even the deserved esteem of the judicious, wise and good.
I consider you as a fellow citizen whom I have known from an infant;
as the son of a pious mother, who, as well as your father,
was anxiously concerned for your welfare, both as a man and a Christian;
and as a youth inexperienced,
and in your present situation much exposed to numberless temptations.

All these considerations, dear Caspar, induce me thus, in much affection,
to intreat you steadily to adhere to the blessed principle of divine grace,
to the monition whereof, I trust you are no stranger.
Allow its restraining influence to have due place in your heart,
and be not ashamed of its tendering effects:
and then instead of falling a prey to that spirit of dissipation and licentiousness
which has captivated and drawn so many from the simplicity of the truth,
you will rise superior to all the attempts of the power of darkness,
and be enabled to resist even the "`appearance of evil.`"
I mean not to suggest from any observations I have made,
that you are more in danger than other young travellers,
nor has any part of your conduct been represented as exceptionable; far otherwise;
I rather hope that there has of later time,
and especially when under difficulties arising from bodily weakness, etc.,
been a desire possessed by you to improve in things of greatest importance;
and am therefore the more concerned on your
account that these good desires may be cherished,
and that, under the conduct of the holy fear of the Lord,
your future steppings may be ordered in His wisdom; that your days here,
whether few or many,
may be spent in such manner as that your life may be truly honourable,
and your close peaceful and happy.

[.signed-section-closing]
Accept this salutation as the fruit of love from your cordial friend,

[.signed-section-signature]
Rebecca Jones

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To James Pemberton.

[.signed-section-context-open]
Ayton, in Yorkshire, 9th mo. 16th, 1784.

[.salutation]
Esteemed Friend,

My sympathy with your beloved brother John is such,
that I have often been on the enquiry respecting him,
as I was greatly disappointed in not seeing him on my first landing,
and knowing your concern must be great on his account,
I seem disposed this evening (though fatigued) to begin some account in this way,
and to let you know that from good information I have
reason to believe he is in the way of his duty,
and greatly owned and supported under the uncommon exercises that have fallen to his lot,
and that he is favoured with a steady, worthy ministering friend, Thomas Cash,
of Cheshire, for a companion.
This Friend went into Ireland the last spring with Isaac Gray, of Hitchin,
who died very suddenly at Tober Head, after which T. C. joined dear John,
and having the like draught among the people at large, they appear suitably yoked.
He still continues in that nation, quietly resigned to the Lord`'s will,
and has great place and acceptance generally.
I have no doubt that he is under best care and direction, and will be helped along,
and released when his service in that nation is over.

And now I may inform you how I have been engaged since my landing in this nation.
I left London 6th mo.
12th, in company with Christiana Hustler, of Yorkshire, who being at the Yearly Meeting,
lodged at Joseph Gurney Bevan`'s, which was also my quarters:
and she having felt her mind engaged on my account, has continued with me ever since,
visiting most of the meetings in Norfolk, Lincolnshire, part of Essex, and Suffolk,
and now in this county, most of which we have gone through,
expecting to be at the Quarterly Meeting in York the last two days in this month,
after which I cannot say, as I see but little at a time,
and continue among the little ones.
My mind seems turned towards the Monthly Meetings,
but they lie so widely that it occasions more riding and industry necessary;
but being accommodated with John Hustler`'s horse and chaise,
and his spouse being an excellent pilot, we have steered in safety thus far,
through hills, moors,
and variety that is to be met with in this
mountainous part of the world called Yorkshire,
and am often bowed in humble thankfulness to the Almighty, who,
blessed be His great name, has been rich in mercy and kindness to me, a poor,
unworthy creature; and my dear friend and true helpmeet, before named,
being wilting to take me under her truly motherly wing,
is not one of the least of the favours for which I have to be thankful.
This is increased by the sense of gospel unity which is felt mutually
in our religious labours as we pass from place to place,
finding the state of things in most places to be exceedingly low,
especially in the Meetings for Discipline among women Friends,
though there is an honest number who are bewailing the present sorrowful declension,
and these are a little comforted in the prospect of some relief;
but alas! unless the Lord is pleased to help, in vain is the help of man.
At times I have felt a secret hope that there is a reviving,
and that the Most High will yet show himself strong in behalf of the
sorrowful few who have indeed hung their harps as upon the willows.
There is a precious visitation of divine love extended to the youth,
and many of them are under the humbling, forming hand, who,
if they abide patiently under the holy fan and fire,
will be made in the Lord`'s time useful and honourable in their generation,
for the rebuilding of the walls of our Zion,
that are in many places so sadly broken down;
and repairing the breaches that are so conspicuous.

Though I feel my own great weakness,
yet am I sustained mercifully in assurance that this sacrifice was
called for at my hands by Him who has an undoubted right to my all,
and who, my soul can say, has been all things to me that I have stood in need of.
And as you know I have not attained to great things,
I may inform you I have nothing in desire more than the exaltation of the pure testimony,
however the creature may be abased, which has frequently been my experience,
being often deeply dipped under a sense of the greatness of the work,
and the feebleness of the instrument engaged therein, insomuch that I have cried out,
"`who is sufficient for these things?`"

My fellow-labourers from America, are, I believe, all well,
and scattered up and down in this nation of Ireland.
N+++.+++ W., by his increase of flesh, looked finely at the Yearly Meeting.
I have not seen him nor any of the others since, except W. M., who is now in Scotland.

Have been twice at Friends`' boarding school at Ackworth, which is a fine institution,
and a blessing to the youth.
Upwards of 300 are now there under the tuition of pious mistresses especially,
(I say mistresses, because my concern was more towards the females;
I hope the masters are, several of them,
religiously engaged,) and proposals are on foot
for another boarding school for girls only,
intended for the accommodation of 40 or 50 girls, to be established at York,
under the particular inspection of Esther Tuke, who is truly a mother in Israel;
and seems to think, though her constitution has had several alarming shocks of late,
that her time will be prolonged till the school is established;
and I am inclined to think it will be of great
use and benefit to the female part of society.
Indeed, in a general way,
Friends here seem more attentive to their daughters`'
education than in some parts of our country.
They are mostly good pen-women, and read with propriety.

I am ready to conclude, from a dream lately had of John Reynell, that he is either gone,
or near going to the house appointed for all living.
I hope the continuance of kind notice and regard
from you and other Friends to my dear partner,
for whom I have felt deeply.
May best wisdom be her counsellor and sure friend.

You may, with my love,
inform S. Waln that her husband is acceptably among Friends here in the way of his duty;
the like, I hope, may be said of all the others.
I hope dear R. V. is by this time arrived, with S. F. and Sarah Grubb,
and should like to hear how they made out with our Captain, who, on our account,
deserves the esteem of our Friends;
Robert has left a good savour on the minds of Friends here.
Oh, I am afraid of none of my fellow servants, but on my own account, I am in great fear,
lest I fail in fulfilling the gracious intention of Him who, in the riches of his mercy,
visited my soul in early life,
and called by his grace into an acquaintance with
himself by the working of His mighty power in my heart,
and changing it, both in desire and affection, so that,
as a brand plucked from the burning, have I been rescued from impending ruin,
and now engaged for the good of others, that they may come, taste,
and see for themselves that the Lord is good.
These considerations are to me very humbling,
and lead fervently to breathe after continued preservation, that I may, indeed,
so run as to obtain,
so fight as to gain the prize which is reserved for the end of this arduous race,
and is often animatingly in my view,
being feelingly convinced that "`of ourselves we can do nothing,`" and I
therefore desire that my dependence may be only on Him who can support,
direct, and help in every time of need.

Yesterday I was at Whitby Meeting--the place where so many friends
were disowned on account of their being concerned in vessels carrying
guns--and I understand that one of them is already reinstated,
and that two others have offered an acknowledgment,
which is before Scarborough Monthly Meeting.
One of the number chose to accompany us to the next meeting at Castleton, and,
as it was his desire, we did not forbid it, having other Friends with us.

I am looking forward to the approaching Yearly Meeting at Philadelphia.
May you be remembered, strengthened and comforted together.

Helmsley, 25th.--I remember this day begins the Yearly Meeting,
and though I believe I am where I ought to be,
yet if I might spend about ten days now with you, it would be truly comfortable.
This is not to be; but my mind is, and will be with you,
and is strongly desirous that the Master of our
assemblies may favour with his blessed presence,
and be your counsellor, wisdom and stability.

[.signed-section-closing]
Farewell, says your tried friend,

[.signed-section-signature]
Rebecca Jones

--

The dream referred to in the preceding letter,
was in substance that Samuel Coates had brought to her from John Reynell,
a plate of soup.
She told her dream to Esther Tuke, and next day a letter arrived from S. C.,
written in his capacity of Executor to J. R.,
enclosing a legacy of 501. "`Dear Rebecca,`" said Esther, "`that is the plate of soup.`"
The removal of this valued friend is thus referred to,
in a letter to Rebecca Jones from Catharine Howell, dated Edgely, 9th mo., 11th 1784.

"`In the death of that worthy elder, John Reynell, our Society has sustained a loss,
and the poor have lost a kind friend,
he having for the last twenty years allotted
one-third of his expenditures for their relief;
and now at the close, he has left one thousand pounds, to be handed them,
in sums of 5£ each.
Also the following legacies, as a token of his regard.`"

James Pemberton, writing to Rebecca Jones the ensuing 2nd mo., says:

[.embedded-content-document.letter]
--

"`Your apprehensions respecting our friend John Reynell, appear to have been right.
At the time you intimate, he was confined to his chamber, if not, just departed.
He was in his sickness favoured with a composed state of mind, without much bodily pain.
John deceased the 3rd of 9th mo., in the morning, and was buried the next day,
leaving a fair character for integrity and stability through life.
His judgment and experience which were valuable, are also missed among us,
particularly in the Southern District Meeting.
You have, doubtless,
been informed of the token he left of his regard to yourself and several others!`"

--

From the residence of William Tuke, at York, she writes,

[.embedded-content-document.letter]
--

[.signed-section-context-open]
9th mo. 29th, 1784, to John Pemberton.

[.salutation]
"`Beloved Friend,

You are so much the companion of my thoughts,
and with so much real sympathy under your varied exercises,
that I believe it will tend to my own relief at least to salute you again by a few lines,
though I have no account whether my last reached you or not.
With my dear friend, Christiana Hustler,
we have visited most of the meetings in Norfolk and Lincolnshire, and have been,
for some time, engaged in this country;
and having felt a draught particularly to the Monthly and Preparative Meetings,
has occasioned more riding and industry, so that we have had little rest.
Being accommodated with J. Hustler`'s chaise, has made it more easy, which,
with many other favours,
is cause of thankfulness to Him who has not failed nor
forsaken in the time of deepest exercise and trial;
for indeed, my dear friend, I may say of a truth, the path allotted me in this land,
is one of tribulation, and my constant breathing is for preservation in the path,
that by no part of my conduct, nor yet through impatience under suffering,
the gracious design of infinite wisdom towards me, a poor, unworthy creature,
may be frustrated, nor any dishonour brought on the blessed and noble cause of Truth.
Truly there is little room for any other than the language of deep bemoaning;
the glory of many in this land has become dimmed and changed.
Oh! how has my heart mourned in remembering that in this part of the world,
where the glorious light of the gospel so eminently broke forth,
and where so many were gathered from shadows and forms,
to the living substance and power of Truth,
under a full persuasion that the Seed Of Life reigned and was in dominion,
there should be such falling away among the descendants of the great and good,
that in most of the places I have visited, there is but little left but the form.
The love of the world, and a conformity to its customs and friendship,
has captivated many of all ranks;
the sense whereof leads me sometimes to believe
that "`the Lord will visit for these things,
and be avenged on such a nation as this.`"
Yet there is an honest and tried number, up and down,
who have a just perception and a clear discerning,
and who are engaged for the restoration of these captives,
that there may be a revival of ancient zeal and simplicity;
and a precious visitation is extended to the rising youth, and those in the middle rank,
many of whom will, I hope,
be brought forward in the Lord`'s time as workmen and
women that will not need to be ashamed;
provided they keep patiently under the holy forming hand of divine power, which,
through adorable mercy, is not yet wholly withdrawn from his heritage.
I did not intend to say so much in this line,
but there are very few to whom I can disclose my present feelings,
except Christiana Hustler, who is a true sympathizing friend,
and is willing to continue a little longer with me.`"

By no means strange was this language of bemoaning,
in reference to the inhabitants of the nation where George Fox and
his associates so nobly testified to the dominion of The Seed,
and to the Power which is over all,
and which must eventually subdue all things unto itself.
In what land, indeed, might not the plaintive query be raised, "`The Fathers,
where are they?`"--in view of the degeneracy of descendants of godly parents,
and of the worldliness of communities,
in the midst of whom the Truth has been preached in its simplicity and purity.
Feelings, such as those above recorded,
will often be experienced by the divinely commissioned messengers of the eternal Word,
and they were, in after years, renewed to Rebecca Jones in various parts of her own land.
In every country, indeed, and in all time,
the children of those who have been conspicuously
employed in the spread of the Redeemer`'s kingdom,
have, in common with all others, abundant need of watchfulness and humility,
and can only become their worthy successors as their
eyes are fixed upon the same unerring Leader,
and, as renouncing self, they take up their cross daily, following him in The Way,
and yielding to the baptism, wherewith he was baptized.
The reader can rejoice, however,
that in respect to many of those for whom our friend was thus exercised,
she lived to see the travail of her soul,
and to be satisfied in the realization of the hope blended with faith,
which she repeatedly expressed.
"`I love Yorkshire,`" she subsequently writes,
"`many Friends in it are near to my very life;`" and she proceeds to declare her belief,
that "`some of the present generation there will be preserved,
and in the right time show themselves to Israel,
equipped with the holy armour on the right hand and on the left.`"

--

Omitting some passages of less general interest,
we now resume her letter to John Pemberton.

[.embedded-content-document.letter]
--

"`I know your situation in Ireland must have been truly in the cross to your nature,
but my mind has been settled in a full persuasion that
you are not following cunningly devised fables,
and often hearing that you are mercifully sustained, is cause of rejoicing to one who,
according to my measure,
have often been engaged for your increase in strength and dedication, as well as my own.
May the lord be near you, your bow and battle axe,
and enable you to finish the work which in His counsel opens to your view,
that your crown may be weighty and eternal.
And oh! may I have a place in your brotherly remembrance,
for you know what a weakling I am;
yet I dare not but acknowledge that the Lord has not been lacking,
nor do I distrust the sufficiency of his power
for the accomplishment of his own purposes;
but weakness and diffidence still attend.

After this Quarterly Meeting is over,
it looks as if we might endeavour for that at New Castle, for the county of Durham,
and some meetings thereabouts.

Our Yearly Meeting is now sitting.
May they be strengthened and comforted together.
I hope dear R. V. is safely arrived,
and I hear Zachariah Dicks and Ann Jessop are coming in
the fall as additional ambassadors to these parts.
Surely something more than common is intended by all these.
John Parrish and James Cresson have laid before their
Monthly Meetings a concern to visit Barbados.
S+++.+++ Hopkins, Thomas Scattergood, and John Haughton, etc.,
have been to the Yearly Meetings eastward.

[.signed-section-closing]
I am with endeared sisterly affection and sympathy, your poor little friend,

[.signed-section-signature]
Rebecca Jones

--

The following instructive epistle may be perused with benefit by parents,
and by all who are engaged in the training of youth:

[.embedded-content-document.letter]
--

[.letter-heading]
To E. Alexander.

[.signed-section-context-open]
Conwood, Northumberland, 10th mo. 19th, 1784.

[.salutation]
Dear friend,

Having you, with your sister Mary,
often in my affectionate remembrance since we parted at Norwich,
and feeling it in a stronger degree this morning, I am willing, by a few lines,
to let you know the continuance of my prospect concerning you,
if by any means I may encourage your steady attention and obedience
to that good hand which has tenderly visited your mind,
and given you to see both the emptiness of all temporal pleasure, and the beauty,
permanency, and excellence of the divine principle of truth; unto which,
let me press your steady and uniform adherence,
"`esteeming the reproaches of Christ greater riches than all the treasures of Egypt.`"
I know that the enemy of all righteousness is endeavouring by
various means to divert the minds of those who are newly
awakened to seek an inheritance in divine favour;
and therefore was the injunction of the great Master so
repeatedly to his disciples--"`Watch and pray,
that you enter not into temptation;`" and for lack of this,
many who were "`beloved of God,
and called to be saints,`" have stumbled on the very threshold of the
"`narrow way,`" and so made no advances in the path of self-denial.
May you therefore be made sensible (after having "`seen and
approved those things which are excellent,`") of the necessity
of yielding obedience to every discovery of the divine will,
and by an increasing dedication of heart thereunto,
be strengthened in your arduous station of a mother,
bringing up your tender offspring under the conduct of holy fear,
and in a suitable contempt of the vanity and folly of this delusive world;
leading them by example in the way of the cross,
and in an appearance consistent with the pure principle of truth which we profess,
endeavouring, as far as your influence extends,
both to advise and restrain them in their tender years,
and to make them acquainted with the nature and effects of divine grace in the heart,
according to that ability with which you may be furnished from time to time.
I am the more anxious on this head,
because I believe that unfaithfulness in many parents of the
present age has not only proved a great loss to their children,
but has been productive of increasing difficulties to
their tender minds in the day of their visitation,
by the open door that has been made for them into the vanity
and foolish customs of the degenerate days in which we live:
so that if you are wise herein,
you will not only be "`wise for yourself,`" and grow "`strong
in faith and good works,`" but wise for them who are not
arrived to an age to be wise on their own account;
and what is of infinitely more value than every other consideration,
have the "`answer of a good conscience`" towards the everlasting Father,
who has visited you with the knowledge of himself,
with gracious intentions to establish you before him forever.
Please communicate the contents to your beloved spouse;
he is equally interested in all the foregoing, and in my sincere desire for his welfare;
also your sister Mary.
May she never lose the precious tendering she was under when we were together.
My dear love is to them, your father and self.
My companion Christiana Hustler, whose company I am still favoured with,
and William Matthews, being present, unite in the salutation.

My aforesaid friend and self have been steadily engaged since we parted with you,
and having taken meetings through most of Norfolk, Lincoln, York, and Durhamshires,
and this county, are about to enter Cumberland,
where to receive a few lines from you and dear M.,
will be truly acceptable to your sincere and well-wishing friend,

[.signed-section-signature]
Rebecca Jones

--

We pass over the detail of attendance of meetings in England and in Scotland,
in which service,
though supplied from day to day with strength sufficient for each emergency,
she was introduced into feelings of weakness.
"`Indeed,`" she says,
"`no one was ever sent abroad who had more need of the prayers of the faithful.`"
In this sense of poverty, she found safety in resorting to the Christian`'s strong tower,
and supplicated that whatever sufferings might be allowed her,
she might be kept from doing any thing that could injure the blessed cause of Truth.

The following letter from her faithful friend, Sarah Grubb, (Sarah R. Grubb,
as she sometimes signed her name by way of necessary
distinction,) develops in an interesting manner her secret
preparation for extensive and weighty religious service.
It may here be remarked, that the letters of Sarah Grubb,
from which it is proposed to make selections,
were not in the possession of the Friends who prepared her journal,
but were so valued by Rebecca Jones,
that she transcribed them in a book now in the compiler`'s possession.
The intrinsic value of these letters, will, it is trusted,
compensate for the space they may occupy.

[.embedded-content-document.letter]
--

[.letter-heading]
Sarah Grubb To Rebecca Jones,

[.signed-section-context-open]
York, 1st mo. 9th, 1785.

About two weeks ago, being in a distressed, tossed situation of mind,
respecting the unsettled prospect of our future residence,
and finding no clear opening of what might prove our lot,
either in this land or in Ireland,
and but little ability to trust and leave the disposal to the Lord,
I seemed ready to sink under the pressure of increasing anxiety,
especially one day as I sat in meeting, when through deep, dark proving,
I got low enough to accept any pointings for peace; my mind was on a sudden calmed,
and a secret language seemed applied to me, "`You shall not settle,
I have other service for you.`"
On which I was deeply humbled;
and then I thought I perceived an opening about the ensuing
Third month to accompany my esteemed friend Rebecca Jones,
to--I know not where.
A degree of sweet peace and serenity mercifully succeeded,
and all that was within me acknowledged, "`good is the Lord.`"
My mind being thus stayed as to my past troubles,
I endeavoured almost continually to obscure the view I had had,
either by making to myself new objects, or reasoning against this,
till I came to the Quarterly Meeting, when it forcible presented itself again,
and urged me to seek a conference with you.

The idea of being instrumental to part companions,
whose union and service have not been small to one another,
was to me so irksome and delicate a point, that I concluded,
that whatever was the consequence, I would conceal my feelings,
not having so much as hinted them to any one but my husband after his return.
But after I got here, the matter still remaining, and considering you as mothers,
and myself a child, in these characters,
I saw nothing to fear (either to you or myself) from this simple communication.
As I believe it possible for very distant services,
to be brought so near us (in order to subject our minds) as that we
may widely mistake the time for the accomplishment of them,
if we run after the vision when it would withdraw and leave us.
And if in this, or other respects, I am erring,
your superior experience and present sense divinely afforded, may, instead of hurting me,
prove of lasting benefit.
Wherefore I leave it.`"

[.signed-section-signature]
Sarah Grubb

--

In a letter addressed to Esther Tuke, Rebecca Jones,
after speaking affectionately of Sarah Grubb, says: "`I have received her loving,
modest and prudent offer to help a poor creature, a little one:
which with yours of a chaise, etc.,
makes me feel very humble that such way should be made for me in the
hearts of those who love the cause of Truth in sincerity.
Indeed, I have admired at it, knowing my little feeble estate,
and thinking that by this time you must know it pretty well.`"
The following, from the same letter,
we quote as bearing upon the present subject:--"`You can not think
how much good you have done me by your several free hints,
especially your reviving the charge '`whom the Lord has joined,
let not man put asunder.`' And as I believe it was the Master`'s will
that Christiana Hustler and Rebecca Jones should be joined so far,
so I am comforted in the belief that nothing of
an inferior nature has attempted to separate.
By this you will understand how kindly we take both your letters to us,
and dear Sarah Grubb`'s. Oh what an unspeakable privilege they enjoy,
whose foundation is on that Rock, against which, as you wisely observe,
'`the gates of hell cannot prevail.`' These are not
disposed to misconstrue the fruits of love and freedom,
but wisely to improve thereby; which is, my dear friend my desire.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Sarah Grubb To Rebecca Jones

[.signed-section-context-open]
Foster, 1st mo. 11th, 1785.

[.salutation]
Beloved Friend,

I am obliged by your favour in so early replying to mine from York,
and particularly for your affectionate freedom contained therein.
The suspense was short and easy.
Feeling but little anxiety how my prospects might terminate,
if my resignation to them and their inherent trials was all that was required,
I gratefully accept the gracious design, and thankfully acknowledge its early completion.
If I was wrong, being conscious of having no end in view,
but the secret approbation of Truth,
I trust that a future impartiality to myself will enable to discover where the error lay.
If I was right, I am contented to rest my cause in that good hand,
which by ways and means inscrutable to us, can effect its own unerring purposes.
In short, when I had read your letter, I considered the lilies,
and remembered the gospel injunction--"`Take no thought
for the morrow,`" which the activity of self,
and the perplexing inquisitiveness of my disposition, often, very often,
prevent my compliance with.
But I humbly crave the continuance of the present covering of my mind on this subject,
and that you may simply proceed in your arduous journey
in the pure openings of Truth upon your own minds,
uninfluenced by any thing inferior thereto.
For did you know to the full the feelings of my heart towards you,
you would be completely convinced, as I trust you are in a good degree,
that was it in my power I should dread to move a finger to bring about too
early a separation of companions united in the holy covenant,
believing the command applicable to these--"`Whom God has joined,
let no man (as man) put asunder.`"

I hope you will be instrumental in supporting the
drooping spirits of our beloved Christiana Hustler,
with whose hidden sorrows my mind has often been led hiddenly and deeply to sympathize.

Various are the ingredients, wisely and evilly, cast into the cup of human life,
and great is our natural antipathy to some of them.
What is tolerable to one, is almost intolerable to another.
So various are likewise our palates for interior food,
and so hard to learn is that capital lesson "`to endure all things,`" and
quietly to depend upon the everlasting arm of power which changes not,
nor forsakes the poorest of the flock who trust in his strength.
Oh the need there is in this day often to repair to the just balance, and when weighed,
steadily to dwell as at the center of the beam,
lest we should be unprofitably tossed up and down by the sleight of men,
and prevented of that quiet habitation divinely appointed for the
refuge and sanctuary of the faithful in their tribulated pilgrimage.

I marvel not, dear friend, from my small experience,
at the often tried situation of your mind.
The Seed, if it be visited in many places, must be sought for in prison houses,
in mangers and deserts,
and sometimes lamented for in a language similar
to Mary`'s--"`They have taken away my Lord,
and I know not where they have laid him.`"
And when the deep exercise and travail of spirit of the
faithful labourers are blessed with a degree of success,
in how abject a state is the pure life found!
What need is there for such as minister to it, to be baptized into its sufferings,
and content therewith as acceptably to clothe its nakedness, relieve its hunger,
and visit its imprisoned state.
Notwithstanding the impoverished situation of these,
their deep self-abasement and fear respecting the uselessness of their services,
yet undoubtedly they are held in everlasting remembrance, and,
in the more triumphant state of the seed, we see even here,
these are admitted to near access through the gracious
invitation--"`Come you blessed of my Father.`"

I remember to have heard that S. Fothergill, in the last journey he took,
was often so exceedingly stripped and tried, particularly after his public appearance,
that the unity or approbation of the least child in the family would have revived him;
and this led him to acknowledge that he was never more
weak and apt to doubt the rectitude of his ministry.
Yet a friend of much religious worth and spiritual discerning, who was often with him,
told me that it was never more pure and baptizing.

But I am grieved with myself for writing thus to an old soldier,
instructed in all the righteousness of both law and gospel.
I had more need get to some Gamaliel and sit at their feet awhile, or,
what would be still better, place myself as Mary did,
that by similar teaching I may be rightly instructed,
and enabled to keep my own standing, which appears to be in slippery places.

I might say much to you respecting the proved situation
frequently portioned as my spiritual meat,
which, though unpleasant to flesh and blood, is, nevertheless,
when the mind is truly humbled, experienced to be substantial food;
and by these things our life is preserved, as, through subjection of soul,
the sanctifying power of Truth is not obstructed.
When there is the least certain evidence that I am at all engaged in the good fight,
and have not forsaken the faith,
I am then encouraged to look with a degree of
confidence to Divine Help for my future steppings;
and, in order to run so as to obtain, to endeavour to run with patience.

We have not yet come to any conclusion respecting our future settlement.
It is indeed by getting deep enough that we can be rightly directed.

[.signed-section-signature]
Sarah Grubb

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Ross To Rebecca Jones

[.signed-section-context-open]
Ballitore, 1st. mo. 25th 1785.

[.salutation]
Dear Rebecca,

You have been of late brought up
in my mind in great nearness of affection,
in that love which distance does not destroy;
so that I find a freedom to visit you with a few lines,
to inform you that I have been favoured to visit
Friends`' meetings generally through this nation,
and have been enabled,
by that good hand which I believe has sent me forth to labour in his vineyard,
to clear myself in warning the rebellious to return;
as also to encourage the youth to give up without reserve,
that so they might come to fill up the seats of those worthies who are removed,
and to be made useful in their day, to the promoting of the great cause on earth.
Dear Rebecca, I think I know you are a woman who travails in the deep,
I travail with you in my measure,
for I think I may let you know that I have been led along in a low way,
and often baptized for the dead,
and yet have been preserved to cast my care upon him that can raise the dead.

Dear Rebecca, you have been as an epistle written in my heart, and,
in a fresh revival of the precious unity which subsisted between us when at home,
I have a hope that if we keep to our first love, we shall come to know an increase,
and that will be more than the increase of corn, wine, or oil.
And now I may let you know that I am as a blank, but cannot see my way out of this nation.
Yet I trust he who has hitherto helped me, in his own time will open the way for me.

Dear Rebecca, you know and I know that unity which spreads over sea and land,
a measure of which I have felt at times, that has brought not only you,
but all my brethren and sisters from America, fresh up in my mind,
with strong desires that we might all be preserved little and low,
and that we might be preserved chaste in our love to him who is the bridegroom of souls.
Then he will take care of us,
that we need not be anxious when we are going from one meeting to another,
what we may have to say, but to keep to our gifts, and look to the Giver;
not to lean to our own understanding, for if we do,
we shall greatly fail instead of bringing honour
to his great name who has called us forth,
we shall bring death on ourselves, and not administer life to the people,
for life answers life, as face answers face in a glass,
and there is nothing that can draw to him, but what proceeds from him.

The province meeting is to be next Seventh day at Castle Dermot,
which I propose to attend, after which I have a view of going to Moate,
where our friend John Pemberton is, to see him:
he has been confined there some weeks with a cancerous wart on his hand,
under the care of a man skillful in such cases.
He is otherwise pretty well in health.
Though he suffered considerable pain, he has been preserved in patience and resignation.
Mehetabel Jenkins has had the small-pox at Samuel Neale`'s in Cork,
and is finely recruited.
I should have wrote before now, only I am such a poor scribe,
but now have an opportunity of writing by a female hand (one who a little like you,
has a ready hand with her pen.) I salute you in near affection,
with desires that you may bear up in your mind,
remembering that he who is the great helper is said to
have been a man of sorrows and acquainted with grief.

My dear love to Rebecca Wright, Patience Brayton, William Matthews, Samuel Emlen,
George Dillwyn and in particular Nicholas Waln, George Dillwyn`'s wife,
and brother`'s family, John Elliot and family, Samuel Emlen, Jr.,
and all other enquiring friends.
Richard Shackleton and family join in the above salutation,
also to your dear companion Christiana Hustler.
Farewell, I remain your brother in tribulation,

[.signed-section-signature]
Thomas Ross.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To John Pemberton.

[.signed-section-context-open]
Appleby, +++[+++Westmoreland,] 2nd mo. 2nd, 1785.

[.salutation]
Beloved friend,

Yesterday,
on my dear companion Christiana Hustler and self coming to Penrith,
(where this day sat their Monthly Meeting,) I received your affectionate letter,
dated the 14th of last month at Moate,
by which we were somewhat relieved from that anxiety and
concern we have felt on account of your diseased hand.
It was cause of rejoicing to my poor mind,
that I am still counted worthy of the near sympathy of
the faithful servants in the heavenly family.
Your situation of mind is truly a desirable one;
for to be "`preserved in a good degree of resignation in hope that divine help and
favour will be continued,`" is a distinguished favour from the Father of mercies.
I have a letter from my Hannah Cathrall,
who mentions your brother James being on the recovery; that Thomas Wharton,
Samuel Rhoads, A. Pemberton`'s son Israel, and Martha Noble,
are released from the troubles of this life; that our other friends are pretty well,
except Samuel Noble, who has had another stroke of the palsy,
by which he is quite speechless, but sensible, and in a sweet frame of mind.
I am rejoiced to hear of dear Mehetabel Jenkins`'s recovery.
She is an innocent, humble handmaid.
I am able still to please you with the tidings
of my dear Christiana Hustler continuing with me,
and hope I shall yet be indulged with her motherly assistance, if in the Lord`'s will.
I expect William Matthews is now in London; he often, while we were together,
expressed his deep sympathy with you, as do many other dear Friends.
Rebecca Wright and companion, got well out of Scotland,
and are under the Master`'s direction and help.
They, with N. Waln, W. Matthews, and myself, were at Leeds Quarterly Meeting,
and mutually comforted in the fresh sense of true unity.
It was a large, favoured meeting.
I rejoice in your account of dear Thomas Ross,
and hope that he will be kept by the power of God unto the end.
Perhaps he may find his mind engaged to bear up your hand, which, if he should, will,
I have no doubt, be acceptable to you.
I had not been able for some time to find out where dear Patience Brayton was,
but I find, by a few lines from George Dillwyn,
(since the date of yours,) that she has gone towards Bristol and Wales.
George Dillwyn and Samuel Emlen,
have been usefully engaged in visiting families in London.
The first seemed low, but in the quiet.

My dear friend may find from my frequent epistles, that you are often in my remembrance,
and however poor and weak I see myself,
yet I am nearly united in spirit to my fellow-labourers,
who are more strongly qualified for useful, lively service in the family.
I would have you give my love to such friends you may fall in with,
who may enquire after the weakest of the flock now abroad on Truth`'s service.
Don`'t forget me, for I am at times so amazed and fearful,
that but for the renewed confirming evidence that did attend my own mind,
and the minds of my dear brethren and sisters, before I left the American shore,
being at times livingly renewed, I should indeed faint by the way.
The greatness of the work,
and the insufficiency of my feeble endeavours towards its furtherance,
are to my mind very humbling and awful; yet I am at times enabled to say,
by a degree of comfortable experience, the Lord is good, and worthy to be feared,
served and obeyed, in his own way, and according to his appointment.

--

[.embedded-content-document.letter]
--

[.letter-heading]
James Pemberton To Rebecca Jones.

[.signed-section-context-open]
Philadelphia, 23rd of 2nd mo., 1785.

[.salutation]
Dear friend,

Notwithstanding my silence,
I may venture to class myself with the foremost
of your friends here for remembrance of you,
believing no day has passed since your departure,
and you unthought of by me with sincere desires, however feeble, for your preservation,
and that fortitude and strength may be your experience in each day`'s service appointed;
and "`lo, I am with you always,`" is an unfailing promise from all-sufficient wisdom,
not intended only for those to whom it was immediately spoken,
but all others of his devoted servants.
It has been an occasion of thankful gladness,
that you are furnished with a companion in whom I am persuaded
you have found the benefit of "`a harmonious labourer for
Truth`'s honour,`" as we have often heard queried.
She was amiable in my view in her youth at Friend Weston`'s,
and being since dignified with a commission from the highest authority,
for publishing the glad tidings of Peace,
I think myself authorized by the precept of an eminent minister,
to hold her in double esteem for the work`'s sake.

I expect your beloved Hannah Cathrall gives you a minute
relation of occurrences among us as they fall out,
so that were I to particularize, it might be a repetition only;
nor can I convey you a comfortable account of the state of
society being advanced for the better since your leaving.
The spirit of the world, in its allurements to trade and commerce,
has captivated too many, to the hindrance of their spiritual progress,
and to the manifest injury of some in their temporal concerns;
yet there remain a number engaged for the general welfare.
Our meetings are greatly increased in number by the removal of many from the country,
without addition to our real best strength.
The evening meetings of First day continue to be often crowded,
and much attended by other professors;
the labour in them rests for the most part upon William Savery, Jr., and Daniel Offley.
Daniel Burns has lately become a citizen in the southern district,
and takes his share with them.
Your Hannah is mostly a silent hearer, yet now and then, chiefly on Fifth days,
gives proof of the validity of her call to the sacred office and improvement therein.

Sarah Harrison, Jas.
Simpson, (from Bucks,) accompanied by I. Zane and M. England,
are now employed in visiting families within our district.

Your account of your visit to Ackworth, is very agreeable.
While that school is maintained on its original intention,
I expect it will prove of great use;
but it too frequently has happened that good institutions have been perverted, which,
I hope, will not be the case in that, and the judicious guard it is placed under,
will be its preservation.

[.signed-section-closing]
With cordial love, your affectionate friend,

[.signed-section-signature]
James Pemberton

--

On the 21st of Second month,
she reached the hospitable abode of J. and Christiana Hustler, Undercliff, near Bradford,
from which she visited the families at Bradford,
which service occupied her till the 20th of the next month.

A letter from Sarah Grubb to Rebecca Jones, dated Third month 18th, contains,
among much that is replete with instruction, the following paragraph, which,
though not necessary to our narrative,
appears so calculated to be of substantial benefit to some readers,
that we fear to omit it.

[.embedded-content-document.letter]
--

"`There is so little in me that is comfortable, much less desirable even to myself,
that I am ready to '`say to corruption, you are my father, to the worm,
you are my mother and sister;`' and were it not for the
breakings in of immortality in the depth of this abasedness,
which (though soon taken up again,) leaves a renewal of strength behind it,
how abject would my state be!
Were there not something which no outward gratification can satisfy,
my husband and my situation in most respects might soon
fix my mind in a sort of earthly paradise,
and center my enjoyments in what the world calls good, and what,
under the blessing which makes truly rich, is really so.
Your kindness and my feelings have urged me to write;
an employment from which I am often led, believing that if it is my lot,
to make a safe progress, I must learn more and more to salute but few by the way.
There is an airy, unconverted mind, very prevalent among the professors of Truth,
and may it not sorrowfully be said among some of the fore rank of the people;
which is naturally seeking to attract us from the Rock of our strength,
and though it is attended with a specious appearance of loving the Truth,
and a readiness to say,
'`blessed is he that comes in the name of the Lord,`' (and
there is something in me that loves to be courteous to these,
rather than abide in the cross,) yet in those humbling
abasing seasons wherein no human consolation can avail,
except what is felt in the deep utterance of united spiritual exercise,
I find not such to be my fellow-helpers in the Lord; and I have clearly discovered,
that to support an unrequired familiarity with them,
is to be in great danger of hurting myself, and if it should be grateful to any such,
will rather strengthen their contentment in their present state,
than turn them from the sandy to the true foundation.

Thus, my dear friend, has a line sometimes opened to the view of my mind,
which being opposite to my natural disposition, brings with it its trials,
a daily call for circumspection, and a daily condemnation for lack of it,
and a willingness to tread, according to my measure,
the suffering path of the great and holy Pattern, who,
though he ate with publicans and sinners when salvation was sent to their houses,
yet in no wise countenanced or approved those who boasted of being Abraham`'s children,
but were under the power of the seducer.

To be sensible of our own infirmities,
and therefore to be chaste to the Bridegroom of souls,
when he is pleased to withdraw the sensible enjoyment of help,
and discoveries of his putting forth, is a desirable situation for the mind to center in,
as it preserves us from joining with those spirits and things,
either in ourselves or others,
which we have once seen to be in the degeneracy from the pure life;
and enables to possess the vessel in sanctification and honour.

--

Rebecca Jones arrived in London the 10th of Fifth month,
taking her abode at Plough Court,
(a locality familiar to the readers of W. Allen`'s life,) and
remained in and near that metropolis till Sixth month 3rd. During
this time she experienced various interests and exercises.
Meanwhile, she had parted with Christiana Hustler, her true yokefellow,
in whose absence she "`felt like a lonely dove without its mate;`" and she says,
in a note to her about this time, "`a living hope springs up just now,
that as you were the first,
so you will be the last companion in this land;`" a hope which,
as will hereafter be seen, was literally realized.

The following note to John Pemberton, written in London some time in this month,
might excite a desire to know something respecting its result,
but we cannot doubt that such a band of disciples,
reverently meeting together in the name of the Lord,
would experience Him to be in the midst of them, realizing his ancient promises.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
6th day morning, nine o`'clock

[.salutation]
Beloved friend,

My mind has been thoughtful this morning on my own account,
and feeling much love and sympathy with my fellow-labourers from our land,
I was willing to propose, if it meet your approbation, with the rest,
that we might all meet at some suitable time and place, and sit down quietly together,
not knowing what may arise for our mutual confirmation and benefit.

[.signed-section-closing]
I am your poor, tried friend,

[.signed-section-signature]
Rebecca Jones

--

Whether there was a connection between the above note,
and the meeting referred to as follows, in a letter to Christiana Hustler,
it is not easy to determine, though it was probably not the case.

[.embedded-content-document.letter]
--

"`My soul salutes you under the precious uniting
sense of the love of our heavenly Father,
which so abundantly flows towards you,
that words would fail me in attempting to convey my feelings.
The salutation which I am now about handing to yourself,
can be done in no other language, if I am honest, than to say, I love you as my own soul.
Remember what I have often reminded you of--
'`Having loved his own, he loved them unto the end,`'
and as he is humbly confided in, and depended upon by these,
he has determined '`none shall be able to pluck them out of His hand.`'

On Seventh day, (Fifth month, 28th,) we all dined at Samuel Hoare`'s, at Newington,
that is to say,
all our little band of seven that came over sea
together,--was it not worthy of thankful commemoration?
Without adverting to the circumstance till we all got there,
we found it was just one year to a day, no about the same hour of the day,
that we landed at Gravesend.
Our hearts were sweetly melted together when I mentioned it;
we were made thankfully to acknowledge that we had '`lacked
nothing`' and we could unitedly set up our Ebenezer.

--

Referring in her diary to this gathering,
she says--"`we had to offer humble thanks for the Lord`'s mercies,
since that time many ways extended.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Sarah Hustler.

[.signed-section-context-open]
London, 5th mo. 20th, 1785.

[.salutation]
Dear Sarah Hustler,

Your dear mother, my precious companion, being gone to meeting,
and I not quite well in my chamber,
having you with the rest of her beloved offspring often in my near remembrance,
it seems as if I may tell you,
if you are willing to be instructed by the divine Monitor within,
which is the only true teacher,
there will be little occasion for any of the Lord`'s servants,
either to be grieved with any thing in or upon you,
or to fear your coming forward answerable to the
merciful intention of infinite goodness towards you;
who having drawn your worthy mother out of the vanities of this world,
called her by His grace, and established her among his humble children,
and engaged her mind on your account;
will bring you also into the same comfortable experience in yourself;
why then should any little matter,
things that your own good sense and better judgment allow to be very little things,
impede your advancement towards an establishment in the Lord`'s favour?
Is there any thing too great or too valuable to be
parted with for the sake of that unshaken peace,
which all these outward things united cannot furnish?
Be obedient, then, my dear; give up everything, however pleasing,
when the divine requisition is,
"`give up,`" that so you may be enabled to step forward in beauty and strength,
when the further call is heard--"`Keep not back.`"

O my heart is and has often been exercised on your account,
and on account of your dear brother William,
lest for lack of an early conformity to divine manifestation,
you should go wider and wider into the paths of defection;
and in so doing render yourselves unworthy of a place in that
succession which will be filled up in the Lord`'s family,
whether they who are first indulged with the heavenly offer are willing or not;
for he has determined that "`his table shall be filled,`" and
many from the highways and hedges are already brought in to
sit down among his faithful children,
delighting in the lifting up of his glorious countenance,
rendering him the acceptable fruits of obedience and love in their season.

And dear children, I am persuaded this is the season, the blessed season,
for you to begin, by bowing under the cross of Christ, conforming to its humbling,
restraining effects and with a noble and righteous firmness,
disdaining to be brought under the power of the foolish
customs and fashions of this degenerate and deluded age;
for if you honour the Lord in heart and conduct,
you will not only rise superior to them all, but, what is infinitely better,
will be honoured by Him, who has promised to do it for such.

And as dear William is more in the way of temptation in various respects,
being often in an exposed situation,
arising from the necessary business in which he is engaged,
I wish him to be on his watch,
and not give way to the subtile whisperings of the adversary,
who may attempt to persuade him, that to keep in a plain, humble appearance, is unmanly,
and that the road to preferment, riches and honour, is pleasant,
and may be safely pursued in the time of youth.
But that by an inward attention to the in-speaking voice of divine wisdom,
he may understand its intelligent indisputable
language--"`By humility and the fear of the Lord,
are riches, honour, and life,`" and wisely prefer it.

Thus, dear children,
is my heart concerned for you--receive it as the fruit of love--
feeling you near as if you were my kinsfolk according to the flesh;
yes more near than some of these; and under this concern I do entreat you,
"`Be wise for yourselves,`" remembering that "`the wise shall inherit true glory,
when shame shall be the promotion of fools;`" hereby
you will be good examples to the younger children,
beloved by those who love what is only lovely, and "`Make glad your father,
and give your mother joy.`"

--

Rebecca Jones having written to Sarah Grubb,
proposing that they should be associated in a visit to Ireland,
Sarah Grubb being at the time from home on religious service,
writes on the 31st of Fifth month, and,
after expressing her apprehension that she should be most easy
to lay the subject before her friends on her return,
adds--

[.embedded-content-document.letter]
--

"`It has ever been a great trial to me to avow a concern to any religious service,
and to act in obedience thereto most humiliating.
I seldom attempt it as long as a stone is left unturned, in endeavouring to put it by,
so that I hope my dear friend will have a little compassion on my doubts and hesitations;
for the more I see myself,
the greater need I find that all my prospects and feelings
should be weighed in the just balance of the sanctuary,
time after time, to prove whether they increase or decrease in pure strength.
I feel near sympathy with you, my beloved friend,
especially in parting with a humble-minded sympathetic companion, whose trial and loss,
will, I trust, with yours, be repaired by the Comforter from the Father.`"

--

Sarah Grubb in allusion to the desolating effects of unfaithfulness
among some among whom her lot was at this time cast,
says--"`May I ever remember, in prospects so distressing,
the instructive conduct of the archangel, who brought no railing accusation,
but wisely left the work to that Hand which can do all things, with or without us.`"
