== Chapter IX.

Yellow Fever of '93--Death and character of Margaret Haines--Letter to her
children--Rebecca Jones is ill with the fever--Thomas Scattergood`'s visits
and notes--Assiduous attentions of Dr. Cathrall--Letters--Family visit.

A Number of our readers will vividly remember the malignant fever which prevailed in,
and almost depopulated Philadelphia, in the summer and autumn of 1793.
For an interesting account of this awful visitation,
we refer the reader to the Memoir of Thomas Scattergood, Friends`' Library, vol.
8,
page 57. To that interesting memoir we also refer for
some letters from Rebecca Jones to Thomas Scattergood,
which we do not think it necessary to transcribe.

Among those to whom this fearful epidemic was made the summons into life,
was Rebecca Jones`'s beloved friend Margaret Haines, an Elder of Market Street Meeting,
the loss of whom was long and extensively felt and mourned.
She was no ordinary woman, being possessed of singular energy and efficiency, able,
as some of her contemporaries said of her, to attend to many things at once,
and her capabilities being both sanctified and fully developed
by the Grace which was not bestowed upon her in vain,
she was eminently useful in her day.
In a quiet unostentatious way, she seemed, almost as if by intuition,
to discover cases of suffering and need;
and knowing no distinction of sect in her expansive benevolence,
she was to all classes an invaluable friend and helper.
Entering, with the sweet insinuations of private sympathy,
into the minute needs of her friends who were less
amply supplied with the good things of this life,
and particularly those who were called to go forth in the service of Truth,
she would provide garments and other things suited to their need,
and make valuable presents with a beautiful delicacy and
privacy which did not wound those who were thus benefited.
In her capacity as a Mother in the Church she was sympathizing, judicious and faithful.
To the diffident she administered appropriate encouragement,
and to those who needed counsel and reproof,
she extended it with a tenderness which precluded offence,
and thus she avoided plucking up the wheat together with the tares.
In her final sickness she was peaceful and trustful, clothed with love to all,
and even amidst her suffering making provision for the poor:
and the language of David may be applied to her, "`Blessed is he that considers the poor;
the Lord shall deliver him in time of trouble.`"
As an evidence of the close union of spirit which subsisted
between Rebecca Jones and this honoured friend,
we subjoin a letter written on the morning of her decease.

To Caspar And Catherine Hainks.

Tenth month 3rd, 1793.
To dear Caspar and Catherine,--I awoke this morning about half past five o`'clock,
under such a solemnity and sweetness of spirit,
that it seemed almost like the end of all conflict,
and which I lay under till near seven;
then I believed all was well over with your dear parent, my truly precious friend.
And as Rebecca Scattergood has just called to let me know that the awful scene is closed,
my feelings now are sweetly joyous on her account; she is blessed forever and ever,
and my sympathy is renewed with you, who feel like my own children.
You will, I trust, be helped now in the needful hour, and if, by my coming down,
I could render you any essential service, I would run all risks.
Don`'t think at all about me; the Lord has helped hitherto,
and I bless his ever worthy name.
My dear love salutes you and dear H. Hastings.
I cannot add, my heart is too full for utterance,
more than that I am your sincerely affectionate and sympathizing friend,

 Rebecca Jones

On the 11th of Tenth month, Rebecca Jones was seized with the yellow fever,
and for two weeks there was little prospect of her recovery.
Her illness continued for nearly two months, and it may not be out of place to note,
as an evidence of the difficulty in obtaining aid in this contagious disease,
that the wages of her nurse was two dollars per diem.
Thomas Scattergood visited her daily, and sometimes frequently during the day;
and from his diary we quote the following passages:

"`Tenth month 23rd, 1793.
Called to see Rebecca Jones, who was seized with great pain,
and could hardly talk to me through extreme suffering,
though the day before she seemed bravely.

"`23rd. Dear Rebecca Jones appeared under much discouragement about getting about again;
but was in a heavenly frame of mind, and glad to see me;
telling me that I felt like bone of her bone.
On my telling her that I had not seen but that she might be
raised up to bear testimony to the Lord`'s goodness and truth,
she replied--'`I am a poor atom, unworthy to be employed in the Lord`'s work.
Dear Thomas, many have fled from the Truth, but the Lord will meet with them.
I have been an exercised woman for thirty years past,
and often grieved to see the pride and forgetfulness of many in our Society;
the multiplying of pleasure carriages, formal visiting, etc.`' And at another time,
when with her, she said, '`there is another dispensation in store for this people,
depend upon it,`'--repeating it more than once--'`if
the people are not humbled by the present.`'`"

"`25th. I called to see dear Rebecca Jones, who lay with her eyes almost closed;
and although I spoke to her and took her by the hand, she answered not,
which was affecting.
After meeting, I went again, and going near to the foot of the bed, she said,
'`Dear Thomas, I saw you,`' alluding to the morning visit, '`but I could not speak;
I am in waiting,
there is nothing to do.`' She lifted up her hands and seemed to wish to say more,
and several times gave us a look of much sweetness and love; and at length,
looking up again, she said, '`Go,
and the Lord go with you.`' Being with her again in the afternoon, she said,
'`Dear Thomas, if the Master renew your commission, and should send you over the water,
mind the time, and do not deal it out to individuals, but spread it before your friends,
and you will find sympathizers; and when you gets there,
remember the poor servants in families--they are too often neglected.
The Lord dealt bountifully with me in that land,
and I have had comfortable seasons with such.`' I asked
her what she had a view of in the morning,
when she looked up at me and said, go, and the Lord go with you.
She replied, '`I could not tell you before J. J., though I love him,
but I alluded to your going over the great waters.
The Lord has, in some instances, entrusted me with his secrets,
and I have not betrayed them.`' After some more conversation,
she appearing inclined to sleep, I left her with much sweetness,
and could say in my heart, that flesh and blood had not revealed these things unto her,
but our heavenly Father, for my confirmation and encouragement.`"^
footnote:[This, as we are informed in the instructive biography of Thomas Scattergood,
was before he had disclosed his prospect to any one.]

This sickness, as it proved, was "`not unto death.`"
About the 1st of Twelfth month, she attended meeting, and, as Thomas Scattergood notes,
"`bore testimony to the goodness and mercy of God.`"^
footnote:[On page 61 of the Memoirs of Thomas Scattergood as
published in "`Friend`'s Library,`" may be seen a weighty
epistle addressed to him by Rebecca Jones bearing date 5th mo.
10th, 1794, with the endorsement--"`To be opened when at sea,
and recurred to in Great Britain and Ireland.`"]

Rebecca Jones was so reduced in this fever, that not only was her life despaired of,
but her decease was currently reported.
There are those who remember her name being officially announced one morning--
supposed Tenth month 25th--among the deaths of the preceding night;
nor is it strange that such should be the case,
as all hope was relinquished the previous evening,
and the nurse was about to remove the pillow, and lower her head,
that her close might be more speedy and more easy, when Dr. Cathrall,
her attending physician, exclaimed, "`No!
No! I can`'t let her die`" He assumed the post and duties of a nurse,
and remained with her all night, dropping into her mouth alternately,
water and diluted wine; and when, in the morning, Dr. Physick--who,
besides being in consultation with Dr. Cathrall,
was greatly attached to Rebecca Jones as his mother`'s friend--called in,
he was amazed to find her not only living, but a little revived.

And now it pleased her Divine Master, having made all her bed in sickness,
and filled her soul with peace and rejoicing in the very valley of the shadow of death,
to prolong her life for his service.
And as in her extremity she magnified the Lord,
so in her renovated health she recognized, in dutiful allegiance,
his perfect right to do with her as it pleased him,
and praising him upon the banks of deliverance, she reverently dedicated unto him,
as a whole burnt offering, the residue of her days.

In a brief account of this epidemic,
after mentioning the death of four thousand of the inhabitants of Philadelphia,
from the latter part of the Seventh month to the second week in the Eleventh month,
Rebecca Jones remarks,
"`But the visitation and awful judgment of the
Most High were singularly mixed with mercy,
in so many instances, that no serious mind can forbear exclaiming,
'`Great and marvellous are your works, Lord God Almighty!
Just and true are all your ways,
you King of Saints!`'`" After recording the names of one hundred and
eighteen of her "`near friends and acquaintances`" who died with this fever,
she adds, "`for many days I had no other prospect but that I should also,
by the same disease, be removed; but the Lord had mercy on me and healed me;
blessed forever be his adorable Name, Mercy, Goodness and Truth.`"

Rebecca Jones To Christiana Hustler.

Philadelphia, 2nd mo.
24th, 1794.
My beloved companion Christiana Hustler, and her dear children, may,
by this salutation of my true love, be informed that I am still on this uncertain stage,
and a monument of divine compassion, goodness and power.
I am weak, and my eye-sight very dim, both rendered so by my long late sickness,
called the yellow fever, from which I was spared,
until the weather grew cooler than it had been during the two months before,
for which I desire to be thankful.
I was not taken down till the 11th of Tenth month last;
and before I was able to go out again, the disease, which had raged with great violence,
was marvellously checked, and the people who left the city through fear,
had mostly returned.
However, it pleased the good Hand which was stretched out over the city,
and permitted upwards of four thousand of its inhabitants, of all ranks, ages, sexes,
conditions, and denominations, among whom were seven of our select members,^
footnote:[Margaret Haines, Huson Longstreth, Daniel Offley, Samuel Lewis, Samuel Taylor,
Charles Williams, etc.
In addition to these, she notes the decease, in the fever of this year,
of the following select members, whose residence, we believe, was not in Philadelphia:
Thomas Lightfoot, Joseph Moore, Owen Jones.]
and many others of my near friends, to be deposited thereby in the silent grave.
Oh, what a humbling season this has been to many!
And how I fear that the people, concluding that the bitterness of death is past, will,
by returning to these things which have drawn down the Lord`'s displeasure upon us,
furnish occasion for another and perhaps yet more heavy judgment, for,
"`verily there is a God who judges in the earth.`"
To return: let it suffice, my dear friend, to say,
that I was confined three weeks to my bed, and to the house near eight weeks;
during which time, and when at the worst, "`my soul did magnify the Lord,
and my spirit rejoiced in God my Saviour,`" in that he condescended to my low estate,
and, by the incomes of his love, sustained me;
granted to me more than I dared to petition for, and was to me All Things.
Blessed now and forever, be his adorable name!
I refer you to my beloved brother Thomas Scattergood,
who is bound in gospel love to visit your land--and probably John Pemberton
may be again with you--for any particular information you may wish to have,
concerning me, as he (i. e. Thomas Scattergood) fearless of danger from infection,
was my frequent daily visitor, and was made near to my best life;
as also respecting the deplorable state of this
once joyous city during the late Visitation,
for I have no language whereby I can convey an adequate idea thereof.
And now, having been raised from the brink of the grave,
I am desirous to stand ready to answer all the requirings of my great Lord and Master,
who has a right to do as he pleases, by, with, through and upon me,
and to whom I desire to be enabled to offer the daily tribute of thanksgiving and praise,
which is his due alone, now and forever more.

Your letters per Deborah Darby, with others from your daughter Sarah and other friends,
arrived while I was confined to my bed, and my doctor, and those about me,
detained them many days, thinking me unfit to peruse them; but when I grew better,
they all proved cordially acceptable to my poor mind.
Present my dear fellow labourers, now in your land, with my sincere love,
and bid them quit themselves like good soldiers: be strong, and stand fast in the faith.
He who has appointed to them this service, will not fail them nor forsake them.
Dear Job Scott is, I hear, happily gathered from further labour and pain.

My love to you, my dear friend, and to all your children, remains unabated.
I should have great joy in hearing that they
were all so listed under the heavenly banner,
as that, by their conduct,
they may evince this to be their resolution--Let others do as they may, as for us,
we will serve the Lord.

Pray for, and pity your poor, weak and affectionate friend,

Rebecca Jones

[.asterism]
'''

Philadelphia, 2nd mo.
11th, 1794.

Dear Friend John Gurney Bevan,--Your last acceptable letter remains unanswered,
but you have doubtless heard what a humbling season has in
infinite wisdom been dispensed to the inhabitants of this city,
and that upwards of four thousand have been through the prevalence of
a malignant fever deposited in the solemn "`house appointed for all
living,`"--that I expect you and other dear friends in your land,
in whose debt I am in the epistolary line, will excuse me.
I am however now disposed to let you know that as a monument
of Divine mercy and compassion I have been raised,
amongst many others, from the brink of the grave!
O, says my soul,
that it may be ascribed to the praise of the holy
Physician! for had not he condescended to interpose,
and by his power check the disorder, "`I had gone down to the grave also,
I should have beheld man no more, etc.`"
I pray that I may never lose the sustaining sense of his majesty as
well as of his mercy! both were at that time marvellously in my view,
and remain unspeakably so;
that I have no words whereby I can convey an adequate idea of
what has been my lot during the progress of the disease,
yes for many weeks before I was taken down,
and after I was brought upon the bed of languishing.
Let it therefore suffice to say, that with respect to myself,
all that I petitioned for and more than I dared to crave was graciously granted:
wherefore, and for the special blessing of a resigned and quiet mind,
I desire to be helped to live and walk humbly, gratefully,
and acceptably the few remaining days of my pilgrimage,
that when the solemn summons is indeed sealed,
I may be counted worthy of a resting place with the many near
friends who are happily gathered from all sickness,
sorrow and pain!
I wish as opportunity offers to let my dear friends who are labouring
amongst you know that I often think of them with affection.

I have just heard of the death of Job Scott, in Ireland, with small pox,
and so sweet a calm succeeded the tidings, that I exclaimed thus:
"`Doubtless he is taken in great wisdom and mercy,
and I have a lively hope he is gathered in peace.`"
Many of his friends here and in his own country, New England,
will be much afflicted with the account.
As I before desired you to impart this letter to
George and Sarah Dillwyn and Samuel Emlen,
I now add that my little handmaid, Mary Brooks,
died about one month before I was taken sick.
She lay but four days, and in that time slept much, and experienced but little pain.
The evening before she was seized, she desired me to explain to her the meaning of Abba,
Father! which when I had done she replied, that is what I thought,
but I wanted to know if I was right.
By her removal I have sustained a loss,
but I am resigned herein to a wise Providence who knew
best when to gather her innocent soul to himself.

I could stain a deal of paper with ink and tears, if my way opened so to do,
but as little is required at my hand in this way, I desire to close this,
and with submission to the will of my heavenly Father, who can repair all losses,
and sanctify all his dispensations to his poor creatures,
I pray to be helped to live without carefulness,
and no longer than I may be of some use in his Church, and amongst this people.

Her princely host and beloved friend, Joseph Gurney Bevan, writing to her from London,
Fourth month 30th, 1794,
thus tenderly and appropriately refers to the
visitation of the previous summer and autumn:

"`I am rather cautious of what I say respecting the
sickness which prevailed last fall in your city,
lest I should speak below the standard of those
minds who have been witnesses of the affliction,
and sharers in it; for in this case it may be eminently said,
'`feeling has no fellow.`' The soul has had an almost
unaccountable knowledge of its own bitterness;
and, for the mercy of preservation and support,
has found a joy with which the stranger cannot intermeddle.
I see no solid ground of comfort at such a time,
but the blessing you mention of a resigned and quiet mind, which,
although it cannot be commanded, is, nevertheless, sometimes afforded; and indeed,
from the very circumstance of being received as a gift,
becomes more precious and consoling than if it could be.`"

Rebecca Jones in writing, after receipt of J. O. B`'s letter,
to Mary Bevan thus refers to the above passage,
"`The remarks in Joseph`'s letter respecting the late sickness and mortality
in this city are such as might be expected from a sensible feeling mind.
They obtained the full consent of my heart,
and have afforded it both comfort and instruction.
Our friend Samuel Emlen and I have conversed about our friends at Plow Court,
and his account confirms the persuasion of my mind,
that the Shepherd of Israel is graciously near to you.
May He be eyed and followed, in all his leadings and directions,
with that submission which becomes the sheep of his pasture, the lambs of his fold.
I rejoice in believing that you are together stepping on in the path of holy
rectitude and increasing dedication to the service of Him who intends,
I verily think, to make you strong for his work, yes,
pillars in his house to go no more out.
I hear,`" she continues, "`that Joseph has quitted business.
Of this I am glad--perhaps it is in the desire I
feel for his increasing usefulness in the family,
and that he may fill up his station therein with that dignity
which can look down upon the world freed from its shackles,
as well as its snares.`"

An impression of duty to visit, in the love of the everlasting gospel,
the families composing the Northern District Monthly Meeting,
pressing weightily upon her mind,
it is thus referred to in a letter to Thomas Scattergood, Fifth month 10th,
1794--"`When you arrive on the British shores, remember me, and pray for me when you can,
for though I have been, through the Lord`'s ever adorable mercy, favoured to see for,
and feel with you, yet now, under the prospect of a family visit, I am ready to sink,
and very much doubt my ability to get through to the honour of my great and good Master,
being a much poorer creature every way than you have any idea of.`"

This concern was weightily spread before and united with, by her friends,
in a monthly meeting capacity, in the Third month, and a minute of Fifth month 27th,
referring to the service as having been entered upon and to the "`propriety
in enlarging the number of those who should be encouraged to afford her
their aid and company,`" thus concludes--"`It is therefore agreed,
to mention to women Friends, for this service, the name of Jane Snowdon,^
footnote:[This Friend was acknowledged as a minister by
Philadelphia Quarterly Meeting in the ensuing Eighth month,
during the course of this family visit.]
and that such of the overseers--both men and women--as
may find themselves at liberty therefor,
should be encouraged to attend thereto.
Such an addition appearing to be agreeable to Rebecca`'s prospect.`"
In a letter to a friend, she thus refers to this engagement--"`I have been favoured,
beyond all expectation,
to visit the families of our Monthly Meeting--about two hundred and fifty in number.
It was almost my summer`'s work,
as my bodily and mental powers were so reduced the autumn and winter previous,
that I went on very gradually; my friends being disposed, in great sympathy and patience,
to take my pace.
Now it is got through, my heart is solaced with the evidence of peace,
and centered in reverent acknowledgment to the great and good Shepherd,
who not only put forth, but went before,
and sustained through those unavoidable baptisms which attended from day to day.
To him be the praise of his own works--I am an unprofitable servant.`"
To another friend she says, respecting this visit, "`I was mercifully helped through it,
and though I began in a very enfeebled state of body, and little and low in mind,
and was obliged to stop in very wet and hot weather, yet our elders, etc.,
who gave up to accompany me, held out in the patience, and,
through the Lord`'s adorable goodness, I was enabled to get through,
to the peace of my own mind, with the sentence of an Unprofitable Servant.`"

[.asterism]
'''

Rebecca Jones To Joseph Williams.

Philadelphia 6th mo., 1794.

Dear Friend, Joseph Williams,--Nothing but the love and esteem I bear you and yours,
and the fear of being thought ungrateful,
could induce one in my present weak state--in
every sense--to set about writing at this time.
Of my late situation, you must have heard; also, how we, in this city, have been visited;
and this, I should have thought, would plead for my not having written to you lately;
but I find by a letter to James Pemberton,
that you are for "`exacting the uttermost farthing,`" so I will send what I have,
and you must forgive me the whole debt.

I hope, that by this time, my beloved brother, Thomas Scattergood,
is arrived on the British shore, and that dear John Pemberton will be there shortly,
as he embarked about the 27th of last month.
May they, with those before separated from us for the gospel`'s sake,
be helped every way to finish the work given them to do, and in the Master`'s time,
be restored to us, with the wages of unshaken peace.
I am, through the Lord`'s goodness, so far restored in my health,
as to be engaged in a family visit here, though I get on but slowly,
not daring to go out much in wet weather; yet trust I am in the way of my duty Godwards,
and pray that the few fleeting days that remain to me,
may be filled up with increasing dedication of heart to the service of Him, who has,
in so marvellous a manner, raised me from the brink of the grave,
and is now and forever worthy to be obeyed in all things.

We are in expectation of shortly seeing Deborah Darby and R. Young;
they are on the return from their journey southward,
where I hear they have laboured faithfully, and where, I have no doubt,
they have had a pretty full share of suffering, both of body and mind.
It is likely, from accounts received,
that dear Martha Routh is on her passage here with William Rotch and family;
but what port in America they intend for, I know not; New England likely,
for William Rotch, belongs there.

I wish you would learn to give without expecting returns from me;
that would be truly noble; and tell me how Robert Grubb, Mary Dudley, S. Shackleton,
and E. Pim come on--how Clonmell school flourishes, with other interesting accounts;
and whether Sarah Grubb`'s works are reprinted, with any addition or alteration thereof.

Believe me to be unchangeably your assured friend and little sister in the Truth,

Rebecca Jones

N+++.+++ B. I omitted, in due place, to mention another ambassador, David Sands,
from the government of New York,
who has obtained certificates to make a religious visit to Friends in Europe.
He is a near friend of mine.
Surely, there is still a precious seed left in these lands,
or so many would not be constrained to visit you.
May their labours be more availing than those of some, who also have done their best.
And may you, my dear friend, be encouraged to hold fast,
and occupy with the precious gift, which you have received;
that so the Lord`'s work may prosper in your hand,
and your evening close with the sweet reward due to faithfulness.

The arrival of the Friends referred to in the above letter is thus noticed
in the Epistle to London from the Women`'s Y. M. of Philadelphia,
(1794,) the draft of which is in Rebecca Jones`'s handwriting.

"`We have had the acceptable company,
and partaken of the Gospel labours of our
endeared friends Deborah Darby and Rebecca Young,
in the several sittings of this meeting,
and are also bound to give thanks to the Father of mercies,
on hearing that our dear friends Samuel Emlen, John Wigham, Martha Routh, etc.,
are safely arrived at Boston in New England--so that the exclamation of the
Royal Psalmist is feelingly adopted by some of our minds,--"`How excellent
is your loving kindness oh Lord!--therefore the children of men put their
trust under the shadow of your wings.`"
Unto whom we desire to render thanks, giving and praise, both now and forever.`"

