== Chapter XI.

[.chapter-subtitle--blurb]
1798--1799.

[.chapter-synopsis]
* Description and character of Rebecca Jones
* She sends for T. Harrison to rescue a captured Negress
* Shipwreck and arrival of Mary Prior
* Stephen Grellet acknowledged as a minister, 1798
* Visits Rahway etc.
* Attends Burlington Quarterly Meeting
* Letters to and from Jane Snowdon
* Goes to Edgely
* Letters to Martha Allinson, etc.
* Change in time of Philadelphia Yearly Meeting.

Rebecca Jones was, in person as in mind, finely majestic.
In her earlier years, and until her embarkation for England, she was slender,
but at her return, and for the rest of her days, she was much increased in size,
and was lame from rheumatism, which was contracted in Ireland by sleeping in damp beds.
Her manner was marked by ease and grace,
and (in honour preferring others to herself) the
gentleness of her Master was conspicuous in her.
Yet there was without assumption on her part, a queenly dignity,
a tout ensemble of nobleness, which drew from all the willing tribute of respect.
"`Here Sits Our Queen Upon Her Throne`" said Thomas Scattergood, playfully,
as he entered her chamber in her declining years.^
footnote:[This visit of Thomas Scattergood was during the week of Yearly Meeting in 1814,
and the last time he was out of his own house.]
"`Ah, Thomas,`" she replied, "`sometimes my palace, sometimes my prison.`"
"`Oh,
it is well that you bowed to the convictions of Truth in your early
days,`" said Samuel Emlen (senior) as they started from her dwelling,
to walk to the Second-day morning meeting in Chestnut street--"`for you
would have been a most powerful instrument in his Satanic Majesty`'s hands.`"
And truly the qualities which through grace enabled her so conspicuously to "`adorn
the doctrine of God our Saviour,`" had they remained unsanctified,
would have rendered her influential for evil,
and "`injurious,`" as was Saul of Tarsus before he yielded to the heavenly vision.

She had a striking and significant way of expressing her thoughts,
which flowed from a mind of great originality and power.
In her ministry she was particularly clear of expletives, or superfluous expressions,
and the solemnity of her manner,
and the genuineness of the gospel message which she eloquently imparted,
impressed the audience with a sense that she was addressing
them under the commission of "`the King immortal,
invisible,`" for whom she was an ambassador.
At such times, an influence accompanying the sound of her voice seemed to fill the house,
and hence an impression was produced which the mere repetition of her words,
(especially to those who did not know her,) would fail to convey.
Her religious communications, in which she was not very frequent,
were remarkably untinctured by what is significantly styled "`creaturely
activity;`" and even the very young were overawed,
their attention was riveted, and their tender minds were enlightened.
So evident was it that the Holy Spirit spoke through her.
When moved, as mouth for the people, to address the throne of Grace,
her petitions were indescribably solemn,
and may be classed with the "`effectual fervent prayers`" of the righteous,
being signally owned by the alone Author of availing prayer.

Nor was her mission confined to the public ministry of the Word.
It was a prominent part thereof,
to carry the consolations of the Gospel to the
abodes of suffering and the chamber of death.
And, being "`wise and endued with knowledge,`" possessed of social
qualities and of personal and mental traits which could not
fail to impress and influence her associates,
she was enabled (by keeping her eye upon the holy
Pattern) to maintain a godly circumspection,
and to "`show forth out of a good conversation her works with meekness of wisdom.`"

Our portrait would be incomplete should we fail to
describe her as being "`in doctrine uncorrupt.`"
Receiving in the fullness of his mission the Son and Sent of the Father,
the Saviour of the world, in whom, while yet in the form of a servant,
dwelt all the fullness of the Godhead bodily, her faith in him was complete and perfect,
and she lived by faith.
Believing with her heart unto righteousness,
and with her mouth making confession unto salvation,
and free from the tendency of narrow minds to "`hold the Truth in parts`" she
brought extraordinary qualifications to her aid in yielding to the heavenly call

[verse]
____
"`Negotiate between God and man
As God`'s ambassador, the grand concerns
Of judgment and of mercy.`"
____

She was eminent for pleading the cause of the poor, and for acting,
as we shall have occasion to notice, as an almoner to the rich;
and to those who were in affliction,
she was an unwearied and tenderly sympathizing friend.
Being prepared,
by her early experience to appreciate the privilege of visiting those
whose goings were established in the way of life and salvation,
she had resolved, that if ever favoured to have a house of her own,
it should be open to all who wished to seek the society of the serious.
To this she adhered.
Her mansion, though small, was freely open to all who desired her society,
or who were in distress of any kind, from mental or physical causes.
She was known to be confidential,
and the afflicted were bold to open freely their situation to this mother in Israel,
as she might, in an extended sense, be called.
Among many instances of the confidence which was freely reposed in her by all classes,
we may briefly narrate the following:

At the corner of Brook`'s Court and Front street, dwelt a wealthy West India family,
who had two female slaves, a mother and daughter.
The mother went out to work,
always paying her master two shillings and sixpence for each day so spent,
and saving the rest,
with the understanding that she might purchase her freedom for one hundred dollars.
When, by her exertions, aided by the generosity of some of her employers,
this sum had been raised,
(being willing to remain in slavery that she might obtain the
blessing of freedom for her beloved child,) she offered to pay
the money for the emancipation of her daughter Maria,
a beautiful girl, with light hair, soft blue eyes, and elegant form,
who would have passed for a white girl; but for her, two hundred dollars were demanded.
This sum in process of time was raised and paid, and Maria considered herself free,
having only her master`'s bare word for it.
She continued in the family, and was employed in needle work,
which she performed with exquisite neatness.
Her master`'s mother being about to return to the West Indies,
Maria made some elegant dresses, with much ornamental work,
for some connections in the islands, and having prepared them,
she was sent to the vessel to pack them carefully away.

She went, with many fears and misgivings, and while she was in the cabin,
the vessel put off from the wharf, and on her returning upon deck she was seized, gagged,
and pinioned.
The weeping mother, in an agony of suspense, dared not breathe her apprehensions;
but being sent to fill the tea-kettle at a pump of soft water, which stood up the court,
near Rebecca Jones`' kitchen, she cast a hurried look to see if she was observed,
and slipped into the house,
where with very little preface she related what
she knew of the situation of her daughter,
and the danger that awaited her.
Rebecca Jones avoided raising her expectations,
but immediately sent our informant to Thomas Harrison,
with a request that he would come to her.
She hastened upon the errand of mercy, found him in his shop,
and eagerly gave him a condensed statement of the case.
"`Yes--yes`" said the philanthropist,--"`tell her I`'ll be there directly.`"
And starting at once, with hasty steps,
he was with Rebecca Jones before the messenger could return.
He instantly proceeded to the house of the master, and opening the door of the parlour,
where the family were at tea, and placing his stalwart figure in the entrance,
with his hands on the door posts, he asked--"`Is J. I. at home?
The person named, being a man of courtly manners,
rose from the table with a courteous bow, and replied, "`That is my name,
sir!`" "`Where`'s Maria ?`" asked Thomas, in an authoritative tone.
"`It`'s none of your business,`" answered J. I., with a greatly altered manner.
"`It is my business, and if you do not tell me,
I`'ll call in the constable to take you to prison,
and keep you there until she is given up.`"
His wife, being alarmed at Thomas Harrison`'s resolute words, called out, "`Oh,
don`'t take my husband to prison--Maria`'s on board the vessel.`"
"`Where is the vessel?`"
"`At Race street wharf,`" she replied, in spite of her husband`'s efforts to silence her,
and also gave him the name of the vessel.
He hastened to the wharf, took a boat,
and was soon attempting to climb the vessel`'s steep sides.
The captain pointed at him a musket, but he, still clambering up, coolly replied,
"`shoot if you dare, you know you`'ll be hanged for it.`"
Reaching the deck, he took the gun from the captain as one having authority,
broke it over the railing, threw it into the river, and hastened to the cabin,
where he found poor Maria gagged,
and the saliva running down her breast--being of course unable to swallow.
The philanthropist took her to his house, kept her till the vessel had sailed, and,
when he had obtained legal papers of manumission,
she was permitted to return to her former master, in the capacity of a servant.^
footnote:[Though Rebecca Jones sought the assistance of Thomas
Harrison as a well known advocate of the enslaved Africans,
and one better qualified than most men of that day to apply
such protection to them as the existing laws could afford,
there is no reason to apprehend that she would approve of the angry
display of authority manifested in the breaking of the gun.
However offensive the conduct of the Captain,
we cannot justify this hasty act.
{footnote-paragraph-split}
It may however be observed,
that if the circumstance occurred near the time to
which the course of the narrative has brought us,
the parties concerned in the attempt at the abduction of the girl,
were acting in direct violation of law.
By the act of 1780, sojourners coming into the State, for a temporary residence,
and bringing slaves with them, could not hold them longer than six months.
This would seem to have been the character of this West Indian master,
and of course Maria was, independently of the purchase, legally free.
If the master came into the Slate after 1780, with a view of a permanent residence,
his slaves became instantly entitled to immediate freedom.
And even if the girl was legally a slave, the attempt to carry her off in that manner,
subjected both master and captain, under the law of 1788,
to a penalty of two hundred dollars.
Thomas Harrison was fully acquainted with the laws which were
designed for the protection of the coloured race,
and was not slow to perceive the power which the
violation of those laws had put into his hands.
Hence the authority assumed at the house of the master, and on the deck of the vessel,
admits of an easy explanation.--Ed. Friends`' Review.]

The following entry in her "`Poor Will`'s Pocket Almanac for the year 1798,`" is
the only metrical attempt by Rebecca Jones which has come to our knowledge.

[verse]
____
And now begins another year!
Lest I should fail I almost fear!
My resolutions now are good;
But, of himself has no man stood.

To you, Oh Lord, my soul does look--
All other help I have forsook,
Therefore on You will I depend,
My sure, my everlasting Friend!

1st Mo. 1st. 1798, 4 o`'clock, P. M.
____

Albeit her character as a wise woman may be best sustained in her prose,
and although we admit the New Year resolutions to be better than the poetry,
we presume that our readers (most of whom are supposed to have tried
their own hand at it,) will pardon a solitary essay at rhyming,
during a life of nearly four score years.

"`Fourth month 25th. Our monthly Meeting.
Mary Prior remarkable in intercession for her own land,
that judgment may be mixed with mercy, and that three capital crimes, the slave trade,
war, and tithes, may be removed.
Also, that her beloved husband and children may be supported through every conflict.
A solemn and heart-tendering season.`"

"`Fifth month 8th. M. Prior in supplication at the Youth`'s meeting for her own land,
for Friends there, for the King, that evil counsellors may be removed from him,
and for her husband and children.
Nicholas Waln, at the close of the meeting, in like manner for our land and rulers, etc.
Truly it was a solemn time.`"

Rebecca Jones in another place notes the arrival of Mary Prior,
on the 14th of Third month, after a passage of thirteen weeks,
having been shipwrecked and taken in by Capt.
Macey.

The ship in which she embarked was a leaky, unseaworthy craft, with a drunken captain.
Mary Prior being the only female on board, a young nobleman,
who to this time had been irreligious and dissipated,
attached himself to her with the tenderness of a son,
and the effect of her religious labours for the
conversion of his soul soon became apparent.
Very early in the voyage a steady use of the pumps was found to be necessary,
to which work our friend stimulated the oft-times discouraged sailors.
When at length it was found that, with all their labours, the water gained upon them,
and the vessel continued gradually to sink, the hands seemed determined,
in utter despair, to relinquish their efforts.
The young man told M. P. that they two should sink together,
and that his only hope was in clinging to her.
She urged the men to continue their pumping for two
hours longer,--and during this interval a sail was seen.
A distress signal was fired, and when they saw the vessel bearing toward them,
they continued to fire guns in rapid succession.

The captain and sailors seemed impressed with the idea that
the presence of our friend had been the safety of them all,
and that while she remained on board they would not sink:
and when the first boat was ready for transferring them to their new floating habitation,
the captain would not allow her to enter it,
insisting that she should remain on board till the last person had left, saying:
"`The ship won`'t sink while she`'s on board.`"
The young man already referred to, took her into his arms, and sprang into the boat.
She saved nothing but what was about her person,
except a parcel which Thomas Scattergood had entrusted to her care for his wife.
Her certificates were in her pocket.

Capt.
Macey`'s vessel was well loaded with oil and codfish,
barely sufficient space being retained for the accommodation of the crew.
With such an addition, the room was insufficient,
and they were obliged to submit to great inconvenience, lying on the cod fish,
and wherever any space could be found.
Every person on board was necessarily placed at once upon short allowance.
This state of things continued for some weeks,
and at length they arrived at Philadelphia, landing at the wharf of Jonathan Willis, who,
having heard of the approach of a vessel consigned to him, went to meet it, and noticed,
as it neared the wharf, a plainly dressed woman on the deck.
Being led ashore, as soon as she set her foot on the wharf she knelt,
and at once the whole crew, by whom she was beloved and venerated,
reverently uncovered their heads.
A stranger, thinking that she had stumbled, took hold of her to raise her;
but the young nobleman repelling the attempt, said--"`Touch her not.`"
She uttered thanksgiving to their Divine Preserver.

James Pemberton had written to invite her to his house,
but Jonathan Willis took her home with him to tea.
Phebe Pemberton soon came in her carriage and took her to her appointed lodgings,
where her comfort was provided for with the greatest tenderness and delicacy.

Rebecca Jones, on being informed that evening of her arrival,
and the attendant circumstances, was greatly affected and overcome,
M+++.+++ Prior being her beloved friend; and she hastened to visit her early the next morning.

On the ensuing Fifth day, M. Prior attended Market Street Meeting.
The young nobleman, her fellow passenger, hearing that she had gone there, followed her.
This was his first attendance at a Friend`'s Meeting.
She was led to elucidate impressively the parable of the Prodigal Son,
and her testimony being sealed upon his mind,
he supposed it to be designed by her especially for himself.
Visiting her in the afternoon, he wept much, and said,--"`Oh! why did you expose me so,
before so many persons--Why could you not have told me all this in private?`"
Of course he was satisfied upon a proper explanation.

Seventh month 16th,
1798.--In a letter to Martha Routh she says:

[.embedded-content-document.letter]
--

"`Your being so
renewedly and quickly commissioned for service in the family,
is animating to me, a poor, feeble soldier.
May your heart endure and your hands be strong, whatever becomes of me,
who am at times in danger of casting away that shield which has covered in many battles.
And yet there is occasion thankfully to rejoice in hope,
that if the dear youth who have of latter time been brought under the holy forming hand,
and have evinced on whose side they are,
if these keep steady in their love and zeal Godward,
that there will be a succession of standard bearers when our heads are laid low.
Of this number, I have a lively prospect concerning H. L. Fisher,^
footnote:[This friend, subsequently Hannah Logan Smith,
is freshly remembered by many of our readers.
Her husband James Smith (who was associated with Leonard Snowdon, Thomas Stewardson,
and Johns Hopkins as executors to Rebecca Jones`' last will,) was one who,
by his christian humility and unblemished integrity,
adorned the doctrine and confirmed the profession of Truth,
and is worthy to be held in remembrance.]
Sally Cresson, Stephen Grellett,
(he is recommended as a minister,) and some others in this city and county,
for the preservation of all whom I am tenderly solicitous.
We are in daily expectation of the return of William Savery and S. Harrison,
who have been absent six years.
The rest don`'t appear to be at liberty.
May the labour bestowed on your land be productive of
that increase of righteousness which,
doubtless, the great Lord of the harvest designs; but as for us,
I fear we are too much in Jeshurun`'s state.`"

--

Early in the Eighth month, 1798, Rebecca Jones and Bernice Chattin left the city,
and pausing at Frankford to visit Nicholas Waln, proceeded to Locust Grove,
the residence of R. Hartshorne.
Having attended Quarterly Meeting at this place,
where Rebecca Jones had much service with many young persons in private opportunities,
they went to the Quarterly meeting at Burlington, where Rebecca Jones notes,
"`I met a kind, open reception.`"

At Burlington she writes, Eighth month 26th, to Jane Snowdon--

[.embedded-content-document.letter]
--

"`The meeting this morning was very large--many of our fellow-citizens are here.
Indeed the town seems crowded, and more came up today.
By these we hear heavy tidings, that T. Paxson, S. Grellet, and others, are taken down,
so that my mind is clothed with sadness on account of those who remain in the city,
and the prayer of my mind is that my beloved friends may be supported
under this great and renewed trial of faith and patience.

"`Oh poor Philadelphia! is the mournful musing of my spirit, by day and by night.
May its mournful inhabitants be instructed by all with which we have met,
in this and former years, and turn to him who smiles,
so as availingly to experience our only place of defense to be the munition of rocks,
where bread may be given us, and our water be sure,
is the petition of your afflicted and affectionate friend and sister.`"

--

Returning to Rahway, she remained till near the time of the Yearly Meeting.
From this place she wrote, 9th mo.
11th, to Leonard Snowdon:

[.embedded-content-document.letter]
--

"`As I sat yesterday in Plainfield Meeting (about five miles from here) my mental
visit to the small exercised remnant in our poor city was sweetly refreshing--yes,
I seemed interwoven with them in sweet supplication to the Lord Almighty,
that he may be pleased, in his unmerited compassion,
to keep you all under his holy protecting wing
till the present sore calamity be overpast;
sustain you above the raging billows, guide you by his counsel,
and finally crown your conflicting minds with unshaken peace.
Perhaps I was brought near in remembrance to some of my dear friends at the same time.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Jane Snowden to Rebecca Jones

[.signed-section-context-open]
Philadelphia, 9th month 28th, 1798.

[.salutation]
My dear friend,

I feel so much weakness and poverty that I scarcely
know how to take hold of my pen to salute you by letter;
nevertheless,
I apprehend I feel at times a degree of that love by
which the disciples of Christ were distinguished;
and, under these impressions of endeared affection,
I thought I would attempt to offer a few lines for your perusal;
though I know not what I shall say,
but hope my pen will speak the language of a heart which has
been of latter times often broken and contrited,
before Him who can preserve from the pestilence that walks in darkness,
and from the destruction that wastes at noon-day.
Was not my harp hung upon the willows,
I would endeavour to speak of his judgments and his mercies too.
This is truly a solemn time.
The Lord, the judge of the whole earth,
is speaking to the inhabitants of this place himself!
Oh, that we may learn righteousness by the things which we have suffered!
If the people should refuse his repeated visitations,
and continue to rebel against the Holy One of Israel,
who could marvel if another vial of the Lord`'s indignation
should be poured forth on the inhabitants of this land.
My soul shrinks at the prospect, and prays for a place of rest in the day of trouble.
When we began to be surprised with the terrors of this
awful visitation of sickness and mortality,
I most ardently desired to be at liberty to leave my habitation;
but such a thick cloud overshadowed, that I could see no way,
either to the right or to the left.
When in this situation,
I often secretly compared myself to a person in confinement under bars, locks, and bolts.
My bonds were too strong to be broken.
So you see, my endeared friend and mother, by what I have written,
and by what you have heard before, that I have been sick and in prison,
having nothing to boast of except my infirmities.
Notwithstanding I felt myself thus bound in a place of deep suffering,
it was far from me to harbour one uncharitable
sentiment in regard to those who left their dwellings;
so distant is such a thought from me, that, in some of the most sorrowful,
humiliating seasons which I have passed through,
I have been thankful in believing that many of my nearest and dearest friends were
permitted to flee from the sufferings which we experienced in our habitations.
I desire not to murmur, and I think I do not feel any disposition of that kind;
neither have we any cause to regret staying here for
the Lord has hitherto dealt very bountifully by us.
Oh that we may be enabled forever to keep our confidence in the Shepherd of Israel,
and in the day of trouble endeavour to take refuge under his Holy Wing,
and then all will be well.

[.signed-section-closing]
Believe me to be, as I am, your truly affectionate friend,

[.signed-section-signature]
Jane Snowden.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Jane Snowdon.

[.signed-section-context-open]
Burlington, 10th month 4th 1798.

[.salutation]
Dearly beloved Jane,

Your precious letter of the 28th
of last month would have been replied to before now,
but wishing to inform you that I had got to Edgely, prevented an earlier answer.
However, this morning I seem disposed to acknowledge it from hence.
The favoured situation of your mind appears almost enviable.
It is what I have been labouring for on my own account, and, according to my measure;
it seems that through the infinite condescension of the Shepherd of Israel,
I have in degree partaken of the like blessed experience; so that I can in truth say,
so far from assuming the seat of judgment respecting
those who have been bound to stay in our poor,
afflicted, and almost forsaken city,
my mind has been so fully yielded in sympathy with you, and other dear friends there,
that the frequent, yes the daily breathings of my sorrowful soul have been,
to the Father of mercies, that you might be surrounded by his all-protecting arm,
and upheld thereby in every renewed baptism, both of body and mind.
So that I rejoice in finding that notwithstanding many and
great have been the provings of your faith and patience,
the shout of a King is evidently in your camp!
May this continue to be your and dear Leonard`'s experience, says my soul.

Our several dear friends, who,
for the sake of supporting the precious testimony of truth
ventured their lives by going to the Yearly Meeting,
are also the objects of my near sympathy and tender solicitude.
Great must have been their conflict to become so resigned; and great also,
I have no doubt, will be their peace, whether in life or death.
We hear often of them who are in the disease.
As to myself I may say that I came from Locust Grove desirous of All-wise direction;
but when the time approached, my soul became exceeding sorrowful,
such a cloud of darkness arose on the prospect that I was obliged to get into the quiet,
and pray to be preserved from tempting the Lord my God, and in the sequel,
as the meeting was adjourned, relief was afforded, and I said in my heart,
good is the word of the Lord, worthy to be trusted in and praised now and forever!

After seventh day please direct to Edgely, where I hope to be in the course of next week,
there to wait until it shall please the Lord to open
the way for my return to my little habitation;
when this is mercifully granted, I trust, my dear friend,
we shall be enabled mutually to set up our "`Ebenezer`" under the renewed
sense of the all-sustaining power and goodness of the Lord Almighty,
to whom be thanksgiving and praise, now and forever.
Amen.

Tell your dear children I love them, and think of them often.

I salute you and dear Leonard in Gospel affection, and remain your tribulated sister,

[.signed-section-signature]
Rebecca Jones

--

As the Yearly Meeting drew near, being still undecided whether to attend it,
she again visited Burlington, making her home with her friend Martha Allinson.

For a day or two both Rebecca Jones and Martha Allinson were under great mental exercise,
desiring right direction whether they should at
this solemn crisis go to the annual assembly,
and not seeing clearly any light upon their movement in the matter;
but when at length Rebecca Jones proposed to go to Philadelphia,
the language distinctly presented, "`Who has required this at your hand?`"
She informed her hostess of her conclusion to remain,
and found that she had arrived at a similar decision.

From Burlington they were taken by James Logan and his nephew John Smith, 10th mo.
10th, to Edgely, there to remain during the violence of the epidemic.
Next day, being the Youth`'s meeting at Germantown, C. Howell notes,
"`Dear Rebecca had good service, dividing the Word with judgment,
and with the authority of Truth.`"
The ensuing first day, a large assembly being convened,
many of whom were not of our Society,
Rebecca Jones was strengthened to speak in the
demonstration of the spirit and with power,
to the edifying of many;
beautifully inviting the youth into that strait and narrow but peaceful way,
in which she had for so many years experienced
the faithfulness of Him who had called her.

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Leonard Snowdon.

[.signed-section-context-open]
Edgely Farm, 10th mo. 12th, 1798.

I wrote a few lines yesterday by Joseph,
and now proceed to fulfil a commission given me just as
I left Burlington by my kind hostess Martha Allinson,
who desired me when I should write to you to present her dear love,
and in like manner did our worthy friends Samuel Emlen and John Hoskins.
The family of the latter are all in tolerable health,
except the young woman who had been nurse to Sarah Scattergood and family.
A letter had just reached Sarah from her dear Thomas,
who appeared to be low both in body and mind, and in bonds in the great Metropolis,
not seeing his way to return with dear William Savery,
yet calls himself "`a poor servant in waiting,`"--and "`desiring that
whether he may or not be permitted to see his dear mother,
wife, and children in mutability, the will of his blessed Master may be done.`"
I thought this seemed like his having some sense of what was to befall his family.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Martha Allinson.

[.signed-section-context-open]
Edgely Farm, 10th mo. 12th, 1798.

[.salutation]
Dear Martha,

I had not time by return of J. S. to give you a line,
but am now seated to inform you that I feel quite
satisfied in leaving Burlington when I did,
as the weather was more favourable then than it has been since,
and the Youth`'s meeting for Abington Quarter was held yesterday at Germantown,
which I attended.
It was a solemn time though held for the greater part in silence.
Dear H. L. Fisher had a few savoury expressions therein.
After it concluded, I found myself surrounded with several of my friends,
(fellow citizens and others,) and I believe we were mutually
glad on seeing each other once more in mutability.
James Cresson, Mary England, Thomas and Samuel Fisher and theirs, R. Buckbee,
Rebecca Archer, etc., etc. were of the number, and appeared well.
Tell our worthy friend Samuel Emlen that there has been much inquiry after his welfare,
and that if he sees his way to Germantown, I believe he will find an open door.
My love to him and his promising children.
And when you see dear John Smith give my love to him and his;
the opportunity I had with him in the ride down is pleasantly in remembrance,
and my desire is renewed on his account, that now having put his hand to the plough,
he may neither look nor draw back, but, in simple childlike obedience,
yield to that blessed hand, which will lead him about and instruct him, and,
oh consoling thought! "`keep as the apple of his eye`"
all his sincerely devoted children,
even when "`the blast of the terrible One may be as a storm against his wall.`"
My love is also to dear John and Ann Cox and theirs, A. Vaux and others in your freedom,
particularly to Land A. Warder, John Hoskins, S. Scattergood, and all their family.
I cannot mention all that arise in view.
A large share of love and gratitude belongs to you and your precious flock,
whose best interest is dear to me.
Salute me to worthy Jane Siddons.
Accounts from our poor city are that though
there is an evident abatement of the disorder,
yet in the last few warm days more new cases have appeared:
but that our friends were all mending.
Tell dear Samuel Emlen that I have just received a letter from +++L______+++ +++R______+++,
who informs me that she has a letter from dear Martha Routh (5th mo.
1st, in London) saying "`the multitude, which is very large,
have been fed with food convenient.
It has been pleasingly affecting to behold so great a number of young girls among them,
who have not only the marks of outward care,
but whose countenances betray them that they are
learning of Christ to be meek and lowly in heart.`"
She also mentions being at Tottenham on 1st day,
and gave an extraordinary account of Sarah Lynes.
Also a religious improvement in many of our young women,
and that there were at the Yearly Meeting,
lesser and greater Prophetesses one hundred and fifty.

I am not furnished with matter for a lengthy letter--hope I retain
the humbling sense of that mercy and kindness which I have so largely
shared from the bounteous hand of our heavenly Father,
and am renewedly desirous that through increasing watchfulness and holy fear,
I may be preserved from swerving from his law,
revealed in my poor soul with greater power, light and certainty,
than in any by-past season.
Wherefore my contrited spirit worships before him,
and humbly craves his blessed assistance,
to enable me and all his dependent children to hold out unto the end.
That so, if faithful unto death,
the crown of eternal life may become our portion forever and ever.
I am, dear Martha, your affectionate friend,

[.signed-section-signature]
Rebecca Jones

--

Martha Allinson, in a letter to Rebecca Jones, Eleventh month, 3rd, 1798, says:

[.embedded-content-document.letter]
--

"`Dear Samuel Emlen has been in to see us this morning,
and on hearing your message of love says,
"`tell her the name of Rebecca Jones has been pleasant to me these forty years.
Tell her that I love her as a co-worker in the fellowship of the gospel,
which I hope will last forever and ever.`"

--

From Edgely she writes to a friend, Eleventh month 3rd:

[.embedded-content-document.letter]
--

"`I do not think I shall get to my lonely dwelling in the city till next week, when,
if I am favoured once more to arrive thereat,
I hope it will be under a suitable sense of the Lord`'s mercy and goodness, which,
having followed me all my life long,
has not withdrawn from me during the late awful visitation;
and with renewed desire to be kept low and humble in his fear
the few remaining days that I may be continued in mutability.

"`Many of our friends in the city, and several who,
in support of the precious cause of Truth, ventured in at the time of the Yearly Meeting,
are removed,--and these having been '`faithful unto death,`' have, I doubt not,
received '`a crown of life.`' But it is not for
us to arraign the wisdom of him whose we are,
and who, most certainly, does all things well.
And therefore it becomes us to submit to all his dispensations,
and pray for strength daily to improve under them, that so,
when the like summons is sent unto us, we also may be found ready, and,
through the adorable mercy of our dear Redeemer,
obtain an admission into the joy of our Lord.

"`Perhaps you may have heard that Sarah Harrison, Charity Cook and Mary Swett,
have gone to Germany and the South of France.
Thomas Scattergood is low in London; other friends there pretty well.
By a letter this day received from Sarah Dillwyn, she and George are well,
and in London.`"

--

It may interest our readers to know that during this absence
from the city the keys of her house were left with two friends,
who were authorized to take therefrom anything
which could minister to the comfort of the sick.
She had a quantity of fine bottled cider,
which was much valued as a medicine for the convalescent, and the friends,
by her direction, would take a bottle and wine-glass and go from house to house,
administering to each patient as was needed.
Rebecca Jones was also diligent in making collections of money and clothing,
which she sent, from time to time, to the city,
to be judiciously expended for the benefit of her suffering fellow-beings.
She had singular penetration in discovering cases of distress,
and delicacy in affording relief.
And although her friends often placed funds in her hands,
without asking how they were to be appropriated,
(confiding in her judgment and fidelity,) she was always careful to let it be understood,
when such was the case, that the money she was bestowing was not her own.

The following incident may serve to exemplify that sympathy in exercise,
free from all confusion which is at times experienced by those disciples who,
having their fellowship with the Father and with the Son,
are perfected in true Christian unity of the Spirit.
At a meeting during the winter of 1798-9,
Rebecca Jones and her tenderly beloved friend Jane Snowdon kneeled simultaneously,
and Rebecca Jones (who did not, till after the meeting,
know of the coincidence) very solemnly gave utterance to the spirit of supplication,
which arose as incense from the hearts of the assembly; and Jane Snowdon,
remaining upon her knees,
felt herself fully relieved by the expression of the
very prayer which had been begotten in her own mind.

Eleventh month 4th, 1798.
Being First-day,
Rebecca Jones had a solemn parting opportunity with a
miscellaneous assembly at Germantown meeting,
impressively recommending the performance of the vows made in the time of distress.
The next day Katherine Howell notes:--"`This morning Johns
Hopkins waited on Rebecca and Bernice to Philadelphia,
they having spent just a month very agreeably with us.
And let me with heartfelt gratitude acknowledge, that my own large family,
(consisting of twenty,) with the circle of my near connections around me,
have been favoured in a peculiar manner, while sickness, distress and death,
have visited the habitations of many in the poor deserted city of Philadelphia;
and the sincere desire of my heart is, that we may walk humbly,
and be enabled to bring forth much good fruit, to the praise of our kind Benefactor, who,
for this, and for every other blessing which we enjoy from his bountiful hand,
is indeed worthy, now and for evermore.`"

"`Our Yearly Meeting,`" Rebecca Jones writes to a transatlantic friend,
"`fell in course in the Ninth month.
Several valuable friends from different quarters ventured in, just to adjourn it.
Of these, ten took the fever, went home and departed--whose loss to the church is great.
The Yearly meeting was adjourned to the 10th of Twelfth month,
when we had the company of dear Mary Prior and Gervase Johnston.
It was large, held the week through, and was, in all its sittings,
the most weighty and solemn assembly that I ever remember to have attended.`"
Of the friends above mentioned, she says: "`They are so clothed with love and meekness,
that all ranks of the people seem united to them;
and truly they have my cordial fellowship and near sympathy,
as beloved fellow disciples and servants of our blessed Master, who will, I humbly hope,
go with them, and be their exceeding great reward.`"
To an English correspondent she writes:
"`The consideration of the time of holding our Yearly Meeting,
which was referred to our last Yearly Meeting, was resumed.
A committee of sixty men and thirty women was appointed,
who all united in reporting that the third week in the Fourth month was most eligible,
and that our general Spring Meeting be discontinued;
which was united with by the meeting.
So that, of course, your epistle will not be answered till that time.`"^
footnote:[The third Second-day in the Fourth month was the time then
agreed upon for the commencement of the Yearly Meeting;
the first, commencing at that time, being held in 1799.
That meeting has regularly convened on the day then fixed, from that time to the present.
The General Spring Meeting to which R. Jones alluded,
was a meeting of Ministers and Elders, which the Friends in those stations,
from all branches of the Yearly Meeting, had held, up to that time,
annually in the Third month.--Ed. Friends`' Review.]

First month 9th, 1799.
Referring to the prospect of more messengers from Great Britain, she says:
"`Surely the great and good Father of his family intends,
by thus sending his servants to and fro, that divine knowledge shall be increased.
So be it, says my soul.
As for me, my dwelling is much among my own people.
This city is a large field, and much labour, exercise,
watchings and fastings fall to the lot of those who are travailing,
for its prosperity in divine things.
Oh, that I could say that we have learned righteousness by all we have undergone!
Then might we hope that the Lord`'s anger would be appeased,
and that his hand may not again in judgment visit us for our iniquities.`"
