== Chapter XII.

[.chapter-subtitle--blurb]
1799.

[.chapter-synopsis]
* Religious visit to New England, accompanied by Jane Snowdon
* Character of Sarah Cresson and R. A. Rutter
* Prophetic warning
* Letters
* Family visits etc.
* Returns
* Goes to Edgely
* Interview with a Welsh convert
* Arrival of S. Harrison and J. Hall
* Incident in North Meeting

On the 31st of Fifth month, 1799, Rebecca Jones and Jane Snowdon,
having been liberated for religious service in New England, left Philadelphia;
and reaching Rahway on the 1st of Sixth month,
they attended meeting there the next morning,
and crossing the North river from Pawles`' Hook, reached New York that evening.
Next afternoon they embarked on board the packet "`Eagle,`" for Newport,
having for fellow passengers, Joseph Whitall, Gervase Johnson, Jonathan Evans,
Ruth Anna Rutter, Sarah Cresson, Richard Mott, Abraham Barker, and many others.
After a passage of forty-nine hours,
they reached the abode of Thomas and Abigail Robinson, at Newport, on the 5th,
"`which,`" she says, "`excited thankfulness in each of our minds.`"
The 6th, being Fifth-day, they attended meeting,
where the service devolved upon Jane Snowdon and Sarah Cresson.
"`It was,`" says our friend, "`a good meeting.`"
"`On the 7th,`" she says, "`Jonathan Evans, with Ruth Anna Rutter, and Sarah Cresson,
went to Conannicut, A. Robinson with them,
to attend some meetings before the Yearly Meeting.
Dear Gervase Johnson and company went to Portsmouth, etc.
I felt most easy to stay here over First-day.
In the evening we had a solemn opportunity in the family,
in which Jane Snowdon appeared in supplication.
Being rainy, I wrote to Christiana Hustler and others.
Seventh-day, the 8th, towards evening, it blew a heavy storm,
which continued through the night.
Oh, how kind is our blessed Master to his poor
servants in that we are not now on our passage.`"

In the letter to Christiana Hustler, she says: "`I have for my companion, Jane Snowdon,
a niece of dear Sarah Harrison, who is, in her gift and manner,
enough like Sarah to be her daughter.
She and her valuable husband, Leonard, are my near neighbours,
and attached to me as to a parent.
They are, in short, as I often say of a faithful friend, a living treasure unto me,
for indeed, my dear, I feel in a very stripped state now in my declining years,
many of my most intimate contemporaries being removed from works to rewards;
and oh! for some who have broken the solemn ties of friendship
in a way still more to be lamented and deplored!
But on this subject I cannot proceed.
The Yearly Meeting at this place is to commence next week, and we have,
with the consent and help of our dear friends at home, got here timely for it.
In the same vessel, came with like prospect, dear Gervase Johnson, an innocent,
humble disciple, much beloved in this land, and Ruth Anna Rutter and Sarah Cresson,
from our Quarterly Meeting.
The former has an excellent gift in the ministry, has had an excellent education,
and in early life indulged much in gaiety, etc., but is now fervent in spirit,
calling others to come, taste, and see for themselves, how good the Lord is.^
footnote:[It may perhaps be acceptable to some of our readers,
to see a brief notice of the worthy Friend of whom Rebecca
Jones bears the above testimony.
{footnote-paragraph-split}
Ruth Anna Rutter was descended from parents of considerable wealth,
and highly respectable character, in the view of the world.
They were not in profession with Friends,
and this daughter received what was no doubt then considered a liberal education,
including the accomplishments of fashionable life.
But at an early period,
her mind became deeply and solemnly impressed with
considerations respecting her future condition.
The gayeties of the world soon lost their attractive influence,
and she became solicitous, above all other considerations,
to seek and to purchase the pearl of great price, the favour of her Redeemer,
whatever it might cost.
Her father, though he felt and manifested a tender attachment to her,
yet not comprehending the nature or depth of her exercises,
made her way for a time more trying than it otherwise would have been.
But the rectitude of her conduct, her filial regard to her parents,
and the steadiness with which she adhered to the course to which she felt herself called,
at length overcame all opposition,
and procured from her parents and connections a degree of love
and respect which could have been obtained in no other way.
Having passed through a series of preparatory baptisms,
she came forth acceptably in the ministry,
about the twenty-second year of her age.
{footnote-paragraph-split}
Among the Friends
who attended the Yearly Meeting during the prevalence of the Yellow Fever,
in 1798, Hannah, the wife of Jacob Lindley, was one.
She was a valuable minister, and in almost all respects, a very superior woman.
Soon after her return from Philadelphia, she was seized with the prevailing epidemic,
and in a few days removed from works to rewards.
About two years after this event,
Jacob Lindley and Ruth Anna Rutter were united in marriage, and she, in consequence,
removed within the limits of the Western Quarterly Meeting,
where she continued to reside during the remainder of her days,
respected and beloved by those who knew her, and were capable of appreciating her worth.
Being, from early life, of a delicate constitution,
she spent the latter portion of her days chiefly at and near home.
While her strength was equal to the exertion,
she continued to attend the meeting to which she belonged,
where her voice was not infrequently, sweetly, though feebly raised,
in advocacy of the cause to which she had dedicated the morning of her day.
In the autumn of 1810, after a decline of several months,
she was quietly released from the pains of mortality,
being in the forty-third year of her age.--Editor of Friend`'s Review.]
Sarah Cresson was for several years under my care,
and I often thought she would be more than a common member,
for she more resembled a Nazarite from her birth, than any other of my scholars.
She is now eminent in gospel service.
They have certificates for more extensive labour than I have any prospect of,
and our coming together is mutually comforting and strengthening.
Besides these, within a few years,
many choice plants have been raised in and near our city, who,
if they keep near the preserving Hand, will be blessed to the Church,
when mine and other heads are laid.

"`I am at times mentally visiting and conversing
with my fellow-labourers now in your land.
They are different in constitution and in their gifts,
but all of them being anointed by the great Head of the church, they will, I trust,
have their own peculiar line of service among you, and, in the Lord`'s time,
return with sheaves of solid peace.
Of these, none are more dear to my best life, than dear mournful Thomas Scattergood,
whose return, if it so please his blessed Master to hasten,
may have a cheering effect on his dear and valuable wife.`"

We pass over the brief and cursory notes in the diary,
respecting the time intervening between their arrival and the Yearly Meeting,
during which our pilgrims were occupied in frequent religious service.
The testimony of the church was given in the following minute,
made on Second-day of the Yearly Meeting--by a subsequent one on Fourth-day,
declaring their "`company and religious services`" to have been acceptable,
and by endorsements upon their certificates.

Minute of N. E. Yearly Meeting.--"`Having had
the acceptable company of our beloved Friends,
Rebecca Jones, Jane Snowdon, and Sarah Cresson, from Philadelphia, and Ruth Anna Rutter,
from Exeter Monthly Meeting, Pennsylvania, at this meeting,
their respective certificates were read, and their gospel labours +++[+++were]
to our comfort and edification.`"

In her diary she notes, "`First-day, Sixth mo.
16th, the Yearly Meeting began, and was continued till Fourth-day, the 19th,
when we had a parting meeting with men and women Friends, wherein I had,
in the fear of the Most High, to proclaim a time, when

[quote.scripture, , Amos 1:2]
____
The Lord shall roar from Zion,
And utter his voice from Jerusalem,
And the habitations of the shepherds shall mourn;
And the top of Carmel shall wither.
____

The very year succeeding this solemn communication,
symptoms of an insubordinate spirit appeared, especially in the Eastern Quarters,
and confined almost exclusively to select members,
so as to induce the appointment of a committee, in the Select Yearly Meeting.^
footnote:[This was probably a verbal appointment.
Committees were appointed by the select Y. M. on
account of difficulties in different Quarters,
in 1804, 1809, 1816.
and 1821, which last was continued, by annual appointments, for years,
and about the same time and in reference to the same difficulties,
a committee was appointed by the general Yearly Meeting.
These appointments (although frequently repeated from the date
last mentioned to the present time) do not appear to have ever
assumed the character of a standing committee.]
In 1801, the defection was still farther developed,
and numbers who had been regarded as "`Shepherds,`" went into manifest ranterism.
This disease was measurably put down, and held in check,
but even to those who only remember the trials with
which Friends of this Yearly Meeting were afflicted,
about the year 1821,
it will not appear strange that Rebecca Jones had to deliver the
solemn warning to which she has thus made a brief reference.
Several Friends, who were, at the time of Rebecca Jones`'s visit, in good standing,
became victims of the fearful storm of ranterism,^
footnote:[In this year a valuable minister (who in venerable age is
still alive in the Truth) being on a visit to New England,
found himself religiously drawn to visit a select member,
and he delivered to him with great plainness of speech,
a close and searching message of warning and rebuke.
The object of his concern, laying his hand upon him in a patronizing manner, replied,
"`Dear young man--be faithful--I desire your encouragement.`"
--His visitor, looking at him with surprise,
said,--"`Surely you have not understood me--I have been endeavouring to convey to you,
that you are one of these wolves in sheep`'s clothing.`"
Unable to bear such plain dealing,
he left the room in a passion--and the character thus given, was,
to the sorrow of his friends, but too clearly illustrated by his subsequent career.]
which carried from the fold even some who had been commissioned to "`feed the sheep.`"
And, although New England Friends were remarkably favoured to
conduct themselves in this trial with meekness of wisdom,
so that the church, as a body, remained "`stedfast, unmovable,`" yet princes,
and honourable and devout men and women, were clothed with lamentation;
and it is vividly remembered,
how signally mourning was brought into "`the habitations of
the shepherds`" on behalf of cherished ones who turned away
from the footsteps of the flock of Christ`'s companions.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Henry Drinker

[.signed-section-context-open]
Nantucket, Seventh mo. 10th, 1799.

[.salutation]
Dear Friend, H. Drinker,

I believe you know how to make large
allowance for such a poor and almost worn out pilgrim,
or else I should make a long apology for omitting till now to acknowledge
the receipt of your friendly communication of the 16th of last month,
which both revived and encouraged my companion, Jane Snowdon, who, you know,
is neither among the forward nor too confident servants.
She has, however, to my comfort, been favoured to relieve, at different times,
her own mind, and to approve herself unto the church,
"`a work-woman that need not be ashamed.`"

You have, I expect, through ours to L. S., heard how we have got along to this island,
where we landed, after a passage of seven hours from Bedford, two weeks ago, minus a day;
and the next Seventh-day, came the other detachment, with Jonathan Evans, namely:
Richard Mott, and his companion A. Underhill, R. Rutter, and S. Cresson;
G+++.+++ Johnson and Joseph Whitall with us.
After attending two Monthly Meetings, and the Quarterly Meeting, etc.,
our young ministers have had two special meetings for the public,
and are all gone to another appointed at 3 o`'clock this afternoon,
about seven miles on the island, among a number of people scattered about there.
Not feeling bound to this meeting, and not being very well, J. S. has left me to write,
at William Brown`'s, and she, with many Friends of the town, has gone to the meeting.
We are all, seven in number, with four of W. Rotch`'s children,
waiting for a fair wind to Bedford,--it is now a-head, and so it seems it will be,
according to the received opinion of Friends here, while anything further is to be done.
So that, perhaps, after this said meeting today,
the work may be ended for which we were sent here.
But I grow so old, and am, as you know, so poor a thing,
that I am afraid to judge even for myself, and more so for others.
Yet the remembrance of the advice of the Apostle, "`You have need of patience,
that after that you have done the will of God,
you might receive the promise,`" keeps me pretty quiet,
and desirous after best direction and help, without which, indeed, "`we can do nothing.`"
I omitted mentioning that G. Johnson and J. Whitall, left us last Fifth-day,
on their journey further eastward,
and that I expect the other Friends will go towards Salem, etc.
As to us two females, we hope, after tarrying a while at Bedford and Newport,
to be at liberty to return home.
But hearing a report, which was current here last evening,
of the yellow fever having broken out again in our poor city, has made us sad.
If it should prove fatal, lamentable indeed will our situation be,
but doubtless there must be a cause therefor,
which I as an individual do most sincerely desire to inquire into, and to be enabled,
for one, to endeavour after its removal, that so the sorrowful effects may cease.
Alas! alas! for our once flourishing city; she that was once great among the nations,
and princess among the provinces!
Is she to become a hissing, a by word, etc.? It is a subject I cannot pursue,
and therefore beg that my poor mind may be stayed under this persuasion,
that the Judge of the whole earth will do all things right.

I have felt, though absent in body, as I ought to do in spirit,
on hearing of the departure of our friend and brother, James Cresson.
We had a sweet opportunity together the second day before I left home,
wherein my persuasion was settled that with him all would be well;
and yet his removal will be a loss to society, as is that of dear Joseph Delaplaine,
to New York.
Your account of West Town school is very acceptable.
I lately wrote to C. Hartshorne, and hope that she, with others there,
will not faint nor grow weary.
If you writes to her or dear Rebecca Archer, please, with my love, tell them so.
I have since received a letter from dear Thomas Scattergood, dated Dover,
Second month 13th. He does not know his wife`'s situation; says nothing about returning;
desires his love to H. Drinker and his, and M. Sandwith.
He mentions a memorable opportunity he has had at Foulkestone,
where were several goodly soldiers, concerning whom he makes this remark: "`Oh,
the sweetness, meekness, and love, that were to be felt in their minds,
though to appearance mighty men!
Great has been the sympathy and love that I have felt for this class of people,
and I should not wonder if they are numbered
among the first fruits of a precious visitation,
approaching towards this favoured island.
The Lord in his love hasten it!`"

Jonathan Evans, R. Rutter, and S. Cresson, unite with me in love to you.
Yours to them was encouraging.
Please offer mine to our friends J. Pemberton, M. Cresson, dear K. Howell,
and others in your freedom.
I note your brotherly hint about "`nooks and corners,`" and hope to profit by it,
but dear Henry, you know we old folks cannot see as in the days of youth,
and therefore it is a comfort that there is a lively
prospect of a succession among the dear youth.
This is indeed rejoicing to my poor mind.
May they be kept down to the immortal Root in themselves,
and preserved as fruit bearing branches in the heavenly vine, is my prayer for them.
Report says our dear Samuel Emlen is coming to New York and Newport.
He will be gladly received there, but if he is long about it we may miss his company.
Our love to him.

And now, feeling the renewal of that love which in earlier life was our encouragement,
and desiring it may now, towards the evening of our day, become our song of rejoicing,
I therein conclude, and remain your sincerely obliged friend and sister in the truth,

[.signed-section-signature]
Rebecca Jones

--

A letter received about this time by Rebecca Jones and J. Snowdon,
contained a message from Samuel Emlen Sr., expressive of his continued gospel fellowship,
and of his trust that their "`experience of the things of God in mercy and salvation,
does in the silence of all flesh often authorize
to hear his own ancient assertion by the Prophet,
You are my witnesses says the Lord, that I am God.
Thus,`" he continued,
"`qualification is derived to publish with the voice of thanksgiving,
and to tell of his own wondrous works, which continue to be not only marvellous,
but unspeakably so, in the eyes of a humblingly baptized remnant, who love him above all,
and sincerely desire that his ever adorable name may be magnified in them, through them,
and upon them, though themselves may be frequently abused even as to dust and ashes.`"

To resume the diary; she proceeds:--"`During the holding of the Yearly meeting,
I had some private religious opportunities, and close labour, and some open service.
So had dear Jane, and Gervasc Johnson, the band of young ministers, etc.`"

On the 20th, they went with William Rotch and other friends, to Bedford.
On the 22nd they had a satisfactory meeting at Long Plains,
and on First-day two labourious meetings at Bedford.
Various meetings are noted,
and the several travellers appear frequently to have diverged in various directions,
and to have occasionally rejoined each other.
"`Dear Jane,`" she notes, "`is in her place, and is helped, from time to time,
in the exercise of her gift, which makes way in the hearts of Friends.
Dear Joseph Whitall has a precious gift, and is much beloved by his friends.`"
Having attended Bedford Monthly meeting, to their comfort,
on the 26th they all went in a packet sloop to Nantucket,
"`where my old friend S. Barney was waiting to see me,
and we mingled tears of thankfulness.`"
Of the Monthly Meeting of Nantucket, and that for the Northern District of Nantucket,
she says: "`both these were seasons of deep exercise and close labour, which, however,
yielded peace to my mind.`"
Rebecca Jones`'s labours on this island were extensive,
and her exercises in the numerous meetings she attended, deep and painful.

"`Seventh month 3rd.--The Quarterly Meeting here ended yesterday.
It was, on the whole, a season of favour, as well as a time of deep exercise throughout;
so that we have fresh occasion to ascribe greatness, with glory,
to our blessed Helper and everlasting Friend.
I don`'t yet see my way for a peaceful escape,
so we must wait in the patience till we can move in the clearness towards Bedford,
and from there take a fresh lookout.
It is no small matter to be brought such a distance from home, and it will be a comfort,
if favoured to get there again, to look back without regret or condemnation.`"

On the 10th, of Seventh month, 1799, they all took packet,
and being driven ashore at Wood`'s Hole, did not reach Bedford till next afternoon.
After several meetings in the vicinity,
she mentioned to her friends on the 13th a weighty
prospect of visiting the families at Bedford,
and received their sympathy and encouragement.
On the 14th, being First-day, she had the afternoon meeting postponed to five o`'clock,
for the more general gathering of the inhabitants:
and next day "`began the arduous task of visiting families in
Bedford,`" accompanied by William Rotch and a female friend.
"`We set out,`" she writes, "`in a low, poor and abused situation of mind,
and were helped through the day by the Father of mercies.`"
They appear to have visited forty-eight families,
and to have been occupied till the 23rd, when, she says,
"`we closed with a sitting with the schools, which were indeed crowning opportunities.
Under the humbling sense of gracious daily help vouchsafed,
our minds were enabled to ascribe the praise to our blessed Shepherd,
who is now and forever worthy.`"

Having completed this service, she was careful not to leave New Bedford prematurely,
"`desiring that the Lord may be pleased to be near us in our return,
even as he condescended to conduct here in safety.`"
She took a solemn leave of Friends at their meeting on Fifth-day the 25th,
"`under the firm belief that if those among them who are mercifully visited,
do not progress in the Christian path,
it will be owing to their not minding the day of small things.`"
That day occurred several "`precious opportunities,`"
and in the evening many young Friends and others,
who convened at the house of her host, William Rotch,
were "`encouraged to dare to stand alone in the most important pursuit.`"
Next morning was a "`uniting melting season`" with many
friends who thronged around her at her lodgings,
and taking leave of them,
our friends proceeded in W. Rotch`'s carriage to T. Robinson`'s at Newport.
At this place she was "`deeply humbled`" in several meetings.
"`Poor Newport!`" she writes, "`yet a small remnant therein claim our sympathy.`"
Although she does not record having entered on a regular family visit,
either here or on Nantucket, yet a memorandum, furnished by a friend,
shows a list of persons visited at each place.

In the evening of Fourth-day, the 31st,
under a prospect of their sailing for home next morning,
several friends visited them at their lodgings,
and being divinely favoured with that influence, which, among Friends,
is significantly called "`a covering,`" Rebecca Jones was engaged in
earnest solicitude that they might "`be prepared to meet,
with suitable resignation, the remaining portion of suffering, which, in divine wisdom,
might be meted out to them,
in order for their increasing sanctification and fitness for an entrance,
when done with time, into the abodes of purity and bliss.`"
Next morning our friends felt most easy to permit the vessel to sail without them,
and again "`had close service`" at meeting.
Next day she notes--"`We were thankful in being with our dear friends at Newport.`"
On Seventh-day, the 3rd of Eighth month, after a parting religious opportunity,
in which J. Snowdon was fervent in prayer,
they embarked with Captain Bliss--but rain coming, the wind shifting,
and the sea becoming very rough, their captain had the candour to propose returning,
after they had, in several hours, progressed but ten miles.

"`Eighth month 4th--First day.--Attended a silent meeting in the morning--
had some service for our blessed Master in the afternoon meeting,
wherein dear Jane was marvellously helped under a mistake of the people,
who rose when she stood up; but, when they became seated, she was strong in the work.
At Samuel Thurston`'s in the evening, a morsel of true bread was handed and broken.
On coming home, we found several young friends,
and I had a word of counsel to administer.`"

"`5th. This being our Quarterly Meeting in Philadelphia,
my mind was much with them there,
and I trust that we may be brought into their remembrance for good.`"

Being still detained by strong head winds,
they attended the Quarterly Meeting at Portsmouth, on the 7th and 8th, which,
Rebecca Jones notes,
"`was large and solemn--in which I was enabled
to be honest in a close and searching testimony,
especially to the young men, a large number of whom where there.`"

On the 9th, attended to the last by many friends,
they went on board "`The Two Sisters,`" where,
having dinner sent them from T. Robinson`'s, they all partook together in love,
after which ensued a renewed and tender leave taking,
and Rebecca Jones finally left the New England shore,
where resided many to whom she was bound in close affection.
On the 14th, they crossed the North river, having the company of Stephen Grellet,
to Rahway, where they met Jonathan Evans, R. A. Rutter, and S. Cresson,
"`and we were,`" Rebecca Jones says, "`mutually glad on seeing each other,
after a separation of several weeks for the work`'s sake.
They proceeded homewards next morning, and we stayed to attend the Quarterly Meeting.
On the 16th came dear S. Smith, R. Wright, etc.--Oh how iron still sharpens iron!
In the select Quarterly Meeting this day, some very painful exercise was experienced;
the result was, that S. Smith had the Select members for Shrewsbury together,
and desired R. Wright, J. Snowdon, and myself, might be present.
He relieved his mind.`"

After attending Quarterly Meeting, and the meetings on First-day,
our friends proceeded homeward, pausing at Brunswick, at R. White`'s near Princeton,
at Bristol, Frankford, etc., and reached Philadelphia,
where great alarm respecting the yellow fever prevailed.
"`I was greatly fatigued,`" she says, "`poor in health,
also in great exercise of mind on coming into our poor city;
yet humbly thankful for Divine help and preservation,
which we had abundantly experienced in this trying journey,
having travelled near one thousand miles, and been from home near three months.
In a sense of the Lord`'s goodness, we had gratefully to acknowledge,
hitherto the Lord has helped us!
Blessed forever be his high and holy name!`"

The fever continuing in Philadelphia, she complied, on the 23rd,
with an invitation to visit her friends at Edgely.
To this salubrious retreat she was followed with
abundant evidences of the love of her friends;
many thronging from the city and vicinity to enjoy the rich treat of her companionship.
Rejoicing with those who rejoiced, and sympathizing with the weepers,
her lively feelings alternated as her suffering friends and
acquaintances were raised from the bed of languishing,
or removal from the mutations of time.

Being much confided in, on account of her wisdom, energy and benevolence,
she was selected by numbers as their almoner,
and about this date we perceive notes of sums lodged in her hands by
fourteen individuals "`for the relief of the worthy poor.`"
From the fund thus created, her own contribution was not withheld.

On the 25th of Eighth month, she mentions a painful season,
in service at Germantown Meeting,
and Catharine Howell notes that it was "`opened by a young man; but Rebecca Jones,
like a skillful workman,
waited till the flocks were gathered before attempting to water them.
She then recommended our being quiet, and minding our own business,
and urged those to whom, at the eleventh hour, a gracious invitation was extended,
to double their diligence.`"

9 Mo. 9th--1799. "`A friend informs me that he
finds that in `'93--in the date of 7th day last,
there were but 18 deaths--but by the returns made last 7th day,
there were 31. So that we cannot yet promise what
progress the disease may make after this time.
Oh, `'tis indeed an awful time!--May we all so bow in this the day of renewed judgment,
as renewedly to experience the joyful return of
the day of mercy and of God`'s salvation.`"

On the afternoon of Ninth month 13th,
she drove into the lawn of her friend Thomas Fisher, near Germantown.
A Welchman, who was engaged in levelling the gravel way,
caught a glimpse of our friend as she alighted, and,
leaning on his spade he stood earnestly gazing at her,
till satisfied at length in his joyous recognition, he threw down his implements,
ran to her, and, taking her by both hands, exclaimed enthusiastically,
"`Yes--`'tis her!-- `'tis her!--`'tis Rebarka Jones!`"
She shook his hand kindly, remarking, "`I do not recollect you.`"
"`Why doesn`'t ya?`"
he replied in surprise--"`You and Sarah Grubb had an
appointed meeting at +++[+++a market town in Wales,
not remembered.]
"`I thought I would go and hear what the Quaker woman could say.
Why, don`'t ya remember me?`"
he continued with increased earnestness--"`Why I sat facing ya,
and you looked at me all the time you were preaching!
And oh! a brave meeting it was!`"

T+++.+++ Fisher, and our informant listened with much interest.
This man was a convert of Rebecca Jones,
and the communication referred to having reached the witness in his breast,
he had supposed himself to be as much the object of her special notice and observation,
as he was of that Divine love which had made her the instrument of good to his soul.
Being thus awakened, he became an attender of Friends`' meetings, and was,
before leaving his own country, received into membership.
He had never seen Rebecca Jones except on the above occasion; but,
after the interview now narrated, she frequently noticed him.

On the 15th, (First day,) T. Fisher took her to Frankford Meeting,
which she notes as "`a large and solemn meeting, many citizens attending.
N+++.+++ Waln much favoured upon the subject of the preparation of wills.`"
On sixth day following, though indisposed, she went through a storm to Germantown Meeting.
"`I sat meeting with pain,`" she says, "`yet I was glad that I was there,
having a word of encouragement to the few who were present.
Ralph Smith departed quietly this morning at his son Benjamin`'s, in a good old age.
He had been lately received a member in our North Meeting; seemed in a happy,
resigned state,
and for near eighteen months was in the belief that he should die about this time,
and had told his children so.
Surely he must have been divinely favoured with such an intimation.
On the evening of this note,
Rebecca Jones and her friends at Edgely were conversing about Ralph Smith,
when some one said that this was the day which R. S. thought that he would not survive.
His presentiment being generally known among his friends.

Her own religious communications are rarely mentioned in her notes,
even when she records those of other labourers;
and we find from other sources that she was often engaged in a remarkable manner,
when from the mention of the occasion in her diary,
we might infer that her part of the work had been in silence.

During her tarriance in the neighbourhood of Germantown,
she made frequent visits of sympathy to the sick and afflicted in which, at times,
she was enabled to communicate to them of those unsearchable riches
which alone could be of avail to them in their extremity.
Her daily entries frequently concluded with,
"`Read the scriptures in the evening;`" and the frame of her mind is
instructively indicated by the following memorandum--"`Lord keep and
preserve us humble and watchful,
is my constant prayer!`"

At Germantown Meeting, Tenth month 6th,
she was led to speak instructively on the happy
state of those who had the Lord for their friend;
who would not forsake them in the time of their trouble,
but would be to them nearer than a brother.
On the 9th she says, "`This day, and the rest of the week,
I was under deep exercise on account of a beloved sister in Ireland.`"
Sixth day, the 11th,
"`Being the anniversary of my being taken with the yellow fever in `'93,
my soul was solemnly humbled before the Lord, for his unmerited mercy under that trial.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Martha Allinson

[.signed-section-context-open]
Edgely Farm, Tenth month 19th, 1799.

[.salutation]
My beloved friend, Martha Allinson,

Many times during my sojourning here,
under the hospitable roof of my dear friend, Catherine Howell,
have I thought of my dear friends at Burlington,
and reflected on the time spent with you and
yours last year on a similar affecting occasion,
with the desire to salute you with a few lines by way
of affectionate enquiry after your welfare,
especially as frequent reports have announced the
indisposition of our valued friend and brother,
Samuel Emlen.
Be assured that my former intentions, as well as the present sensation of love,
are truly sincere.
Please offer the salutation of my sisterly affection to Samuel Emlen and his children,
J+++.+++ Hoskins and his family, J. and A. Cox, and all your precious flock.

My own health, since returning from New England, has been various,
yet thankfulness covers my mind to the great Author of all good,
that I have been thus kindly accommodated and cared for,
and enabled mostly to attend Germantown Meeting.
I have now a hope, that our citizens who have been scattered abroad,
may be permitted to return in safety, and, oh says my soul, that we, myself especially,
may return with fervent and renewed desires,
to walk more humbly in the path of obedience to the law and commandments of Him who
is indeed justly styled "`the dread of nations,`" and "`Prince of Peace;`" that so,
further chastisement for disobedience and ingratitude may not become necessary.

We have cause for thankfulness that our beloved friends Sarah Harrison and John Hall,
have arrived in safety.
They have left Thomas Scattergood behind in the field of deep exercise.

I have made several attempts to visit Westtown School, but as yet have not effected it;
however, I hear that they are all pretty well.
May you and I, dear Martha, through all our trials and conflicts,
be enabled to hold out in faith and patience unto the end,
and finally obtain an admission into that rest which is undisturbed and full of glory,
is the desire of your affectionate friend,

[.signed-section-signature]
Rebecca Jones

--

She returned, 10th Mo. 25th to her home in Brook`'s Court,
which was in those days characterized by neatness and beauty,
and afforded a most desirable residence.
Those who do not remember the character of this Court more than thirty years ago,
would be likely to regard as extravagant the language
of those who describe it as it really was.

The several branches of the family from whom it took its name and who then occupied it,
were on terms of the pleasantest intimacy with Rebecca Jones.
One of these, Lydia Brook, was especially beloved by her,
and is remembered by the Compiler as a lady of extraordinary loveliness.
"`Indeed she is a precious woman,`" said our friend.
One of the few survivors of the Brook family recently visited the Court,--
and as she stood before the house of Rebecca Jones (then in process of
demolition) the dear voice of its illustrious occupant seemed to salute her,
in these lines, which she had taught to her as she stood in infancy beside her knee.

[verse]
____
"`Give first to God the flower of your youth--
Take for your guide the blessed Word of Truth--
Adorn your soul with Grace--prize Wisdom more
Than all the pearls upon the Indian shore.`"
____

There are still many who, who in reference to the subject of our memoir,
can apply the words, "`She being dead yet speaks.`"

Her beloved friends Sarah Harrison and John Hall, having previously arrived from England,
"`the next day,`" she says, "`after I got home, I went down to Thomas Harrison`'s,
where dear Sarah received me with open arms.
Language failed us for a space,
and we silently mingled tears of tender affection to each other,
and of gratitude to the Father of Mercies, in the humbling persuasion,
that during a separation of seven years,
in which time we had been closely and variously tried,
we had been upheld and sustained by the special mercy
and goodness of our holy Head and High Priest,
who now on rejoining, enabled us to set up our Ebenezer.
John Hall, who, on seeing me enter T. Harrison`'s parlour, knew me instantly,
felt like a beloved brother.
He stayed a few weeks in our city, passing his time in our meeting,
mostly in a silent travail; and proceeded on a journey southward,
being accommodated with Stephen Grellet, a steady young minister, for companion.
Dear Sarah Harrison appears in possession of the blessed reward of peace.`"

One First-day morning, in the North Meeting,
a meek spirited and valuable woman Friend arose, and having stood for some minutes,
Rebecca Jones also stood up, and remained for a short time, solemnly silent,
neither of them having observed the other,
until Rebecca Jones commenced a very impressive and weighty discourse,
when the former instantly sat down.
Rebecca Jones knew nothing of the circumstance
till it was mentioned to her in the evening,
when she was much affected, even to tears,
fearing lest she might have crushed or hurt a tender
plant of her heavenly Father`'s own right hand planting.
She immediately put on her cloak and bonnet, and went to see the Friend,
who informed her,
that she (Rebecca Jones) had fully expressed the
exercise which had been upon her own mind,
and that she believed that the surrender of her will, in thus standing upon her feet,
had been accepted.
