== Chapter XIII.

[.chapter-subtitle--blurb]
1799.--1801.

[.chapter-synopsis]
* Death of Samuel Emlen senior, and his presentiment of it
* Notice of Samuel Emlen, junior, and wife
* Gervase Johnson
* Letters
* Stop in her mind against recruiting her shop
* Death of J. Hartley and the intimation thereof afforded to her
* Reflections on the source of such intimations
* Rich Cheese
* Hannah Barnard

On the 14th of Twelfth month, 1799, Samuel Emlen paid Rebecca Jones a visit,
which proved to be their final interview.
Noticing an almanac for the approaching year, he took it up,
and placing it near his eye--being, as is well remembered,
very nearsighted--he said emphatically,--"`Eighteen Hundred!
I have said, I shall not live to see it.`"
She replied,--"`Oh Samuel, don`'t say so!`"
He responded, "`Rebecca--I have said it--remember the agreement which we made years ago,
that the survivor should attend the other`'s funeral.`"
On the following day he was engaged in a First-day meeting in a lively testimony,
and finding himself ill he leaned, in great physical weakness,
on the rail before him and repeated with touching
pathos the following stanza from Addison--

[verse]
____
"`My life, if You preserve my life,
Your sacrifice shall be,
And death, if death should be my doom,
Shall join my soul to thee.`"
____

The meeting broke up--he was taken to a neighbouring house, and, when a little revived,
to his home.
The next third day he assembled with the Church for the last time,
and preached from the text,
"`This is the victory that overcomes the World--even our faith.`"

Soon after this he was confined to the house with indisposition, during which,
with "`tears of holy joy,`" he was enabled to triumph through faith,
and give high praises unto Him whom he had eminently served.
"`The main bent of my mind,`" he fervently exclaimed, "`has been to serve you, oh God,
who are glorious in holiness, fearful in praises.
I have, I am sure,
loved godliness and hated iniquity;--my petitions to
the throne of Grace have been accompanied by faith.
All I want is Heaven!`" he said as his end drew near;
and having repeated part of the Lord`'s prayer, he added,
"`Oh how precious a thing it is to feel the
Spirit itself bearing witness with our spirits,
that we are his!`"
Impressed with the awfulness of the invisible world upon which he was about to enter,
he said to those around him, "`I entreat that nothing be done to me,
except what I may request, that my mind may not be diverted,
that my whole mind may be centered in aspiration to the throne of Grace.`"
On the morning of his last day of probation, about 3 o`'clock,
he asked what was the hour, and being informed he said,
"`The conflict will be over before five.`"
His last, or nearly his last words, after an apparent suspension of life, were,
"`I thought I was gone--Christ Jesus receive my spirit.`"
And thus, at 4 o`'clock on the morning of Twelfth month 30th,
this remarkable man and illustrious ambassador for Christ,
quietly departed to be with him who said, "`Father,
I will that those whom you have given me, be with me where I am,
that they may behold my glory which you have given me.`"

Before day break that morning, Rebecca Jones and her B. C. (Bernice Chattin)
were conversing about Samuel Emlen, and of a singularly pleasant dream^
footnote:[This dream may, without attaching importance to it, interest the reader.
Rebecca Jones`'s young companion, in the illusion of slumber,
thought herself on Market street wharf,
and under the necessity of going to a ship which lay in the channel,
and to which there was no access but by a plank which was tossed about by the waves.
As she clung to the plank, expecting to be washed off and lost, she saw Samuel Emlen,
Senior, coming, clothed in white flowing robes,
with an indescribably beautiful and illustrious appearance.
Passing by her, he stepped lightly along on the water to another ship,
which was under full sail, going down the stream--he ascended the side,
and the ship was immediately out of sight, and she was left struggling.
With this she awoke,
and the messenger arrived while this dream was
the subject of conversation with Rebecca Jones,
both of them being impressed with the belief that he was gone.
As nearly as could be ascertained,
the dream and the decease of Samuel Emlen were simultaneous.]
respecting him, when a loud knock was heard, and the window being opened,
Samuel Emlen`'s Roman Catholic servant, Larry, called out,
"`My blessed master`'s gone to Heaven!`"
He was buried on New Year`'s day, 1800,
his remains being taken to the Market street House,
where Nicholas Waln and another Friend were solemnly engaged in the gospel ministry.
Rebecca Jones, although an invalid, was true to the agreement,
which she had made with her honoured friend.

Fourth month 2nd, 1800, Rebecca Jones notes in her book of business accounts,
"`Memorandum, that having felt a stop in my mind against recruiting my shop,
and having £200 in cash, I placed it on interest.`"

She was on this day engaged in writing an order for goods to the above amount,
to be purchased for her by a sea captain who resided next door to her,
and was about to sail, intending, as was her wont, to accompany the order with the money.
She paused, and laid down the pen, and remarked to our informant,
that she believed she had better not send.
This vessel was wrecked and lost on its return voyage.
The crew were saved.

How affecting is it, and what cause of humble gratitude,
to have evidence that he who said of old,
"`shall I hide from Abraham that thing which I do?`"--
is still a "`Wonderful Counsellor`" to those who,
walking dutifully in faith and simple obedience, have become quick of apprehension,
in recognizing the still small voice.
Truly is the wisdom which comes from above "`profitable unto All Things.`"

By the hands of her beloved friends Samuel Smith and Richard Jordan,
she sent letters to several of her transatlantic friends.
To the latter she gave a general letter of introduction,
and in a letter to Christiana Hustler, Fifth month 23rd, introducing him, she says:

"`In Richard you will meet simplicity, wisdom, and honesty combined.`"
"`They are brethren,`" she adds, "`beloved by me.
That Israelite indeed,^
footnote:[Among the trials which this "`Israelite
indeed`" passed through in this country,
there was one which must have deeply wounded his paternal sensibility.
He had a son, who had emigrated to America, and taken up his residence in Philadelphia.
Some time previous to the arrival of the father,
this son went with some other young men to the Schuylkill, in the vicinity of the city,
to bathe.
Soon after entering into the water and before he had advanced many yards from the shore,
he was seized with the cramp and sank.
All the efforts of his companions to save him, proved unavailing,
and several days elapsed before the body was recovered.
The father, ignorant of these circumstances,
came to this city expecting to meet this long absent son: and,
if my recollection is to be relied on,
he went to the place of his residence immediately upon landing.
There, instead of embracing the object of his paternal affection,
he met with the sorrowful tidings of his sudden removal--Editor of Friends`' Review.]
Gervase Johnson, who returns with them,
leaves us under the impression of love and unity in our minds.
May the Shepherd of Israel go with them, strengthen them in their labours,
and bless their endeavours to the churches.`"
"`You would feel for us when the tidings reached you of the
happy translation of our dear brother and father in the church,
Samuel Emlen, whose company is missed by none more than by myself,
as he often visited my little habitation, and as often confirmed Solomon`'s assertion,
"`as iron sharpens iron,`" etc.
Being confined with a hurt during his illness,
I did not see him after the 14th of Twelfth month, when he, being poorly,
told me that he should not live till New Year`'s day.
And according to his prospect he was interred on the first day of 1800.
His son Samuel and his precious wife, who reside near Burlington are a very valuable,
steady couple.`"

+++[+++It is a coincidence perhaps worthy of being mentioned
in this connection that this Samuel Emlen,
Jr., who was a valued and beloved Elder in the church,
and a man of remarkable watchfulness,
had in the latter weeks of his life a presentiment that
he should not live to see the approaching new year.
He died in great peace in Burlington N. J. 12th mo.
29th, 1837.
The day previous he was visited by the venerable and patriarchal John Cox,
who in a solemn address to his dying kinsman repeated the text
"`I am the Resurrection and the life--whosoever believes in me,
though he were dead yet shall he live,--and whosoever lives and believes in me,
shall never die,`"--connecting with it the passage in Revelation,
"`Blessed and holy is he who has part in the first resurrection,
on such the second death has no power.`"--These passages lived
with Samuel Emlen during his few remaining hours,
and to the very last, even when the full power of utterance had failed him,
he made repeated efforts to quote them.

His wife Susanna Emlen (daughter of William Dillwyn) to whose singular
loveliness and purity of character repeated reference has already been made,
died in Burlington 11 mo.
24th, 1819.

A valued minister who knew her well,
writing soon after the event thus commemorates her worth.
"`The writer has only to regret the inadequacy of her pen to portray a character which,
while strictly faithful to Truth, should
not be regarded by those who were strangers to this
inestimable woman as the language of panegyric.
Possessed of all mild and endearing virtues; gentle, benevolent,
good,--she was the delight of her friends and a treasure of
inestimable worth to her husband and relatives.
The spotless purity of her mind, and the sweetness of her whole character,
appeared so entirely without alloy,
that she seemed like an inhabitant of a more blessed sphere,
"`Let down in cloudy throne to do the world some good.`"
And a bright and beautiful example has she been to all who have witnessed
her patience and resignation under the most severe and protracted suffering.
She had a very solid judgment united to great delicacy of
taste--her disposition was remarkably kind and tender,
she was serious while cheerful and social,
and her lovely countenance beamed with soft intelligence.

But--she has gone--and her death is the withdrawing of a most radiant and beautiful
orb that gladdened and enlightened the circle of her family and friends,
yet the triumphant hope of glory through the blessed Redeemer is felt over all.`"+++]+++

[.small-break]
'''

To her valued friend and kind Dublin host, Joseph Williams, she writes, Fifth mo.
24th, 1800:

[.embedded-content-document.letter]
--

"`As you are like to be favoured with another visit from our beloved brother,
Samuel Smith, who, with his worthy and valuable companion,
my dear friend, Richard Jordan,
I have no doubt will be cordially received and acknowledged, as they are,
as true gospel ministers, by you and all others who love the Lord Jesus in sincerity,
and your sweet spirited friend, Gervase Johnson, whose innocent,
watchful example will be long remembered by many in the land;
I am desirous to accompany them with a few lines, to inform you that I am still,
to my own admiration, in the land of the living,
and feel the continuance of that same precious influence,
which so nearly united our spirits when I was a sojourner with you,
your beloved wife and dear children.
To all of them I desire to be affectionately remembered, and wish, most sincerely,
their preservation in every wise and valuable pursuit.

"`Samuel Smith, you know--and he being qualified,
can give you all needful information about your friends in these parts;
also particulars concerning the latter end of our dear friend, Samuel Emlen,
whose company is not missed more by any than by myself;
but as his blessed Master saw fit to call his faithful servant home,
submission to His holy will becomes his family everywhere; therefore, I desire to say,
Amen!
You will also be able to understand how our dear
S+++.+++ Harrison has been tried since her return;
she, however, is in the enjoyment of the reward promised to faithfulness,
which appears to be also the strengthening experience of dear S. Talbot.
She, Rebecca Wright, and Ann Jessop, were at our late Yearly Meeting,
which was a solemn season.
The remembrance of the four awful visitations which this city has experienced,
and the approach of another summer, must, to every serious mind, have a humbling effect.
O,
that the people had truly learned righteousness by the judgments
permitted to us! then might we hope to be spared another year.^
footnote:[It may be interesting to some of our
readers to be informed that the yellow fever,
to which Rebecca Jones so frequently and feelingly alludes,
and which made such awful ravages in this city in the years 1793, `'97, `'98, and `'99,
visited it again, to a considerable extent, in 1803.
From that time to the present, though isolated cases have occurred,
it has not assumed an epidemic character.
It can be no disavowal of our dependence on Divine protection, to remark,
that as far as natural causes have contributed to this exemption from epidemic disease,
the introduction of good water, in abundance, from the river Schuylkill,
must be considered as one of the most efficient.
Besides contributing to the cleanliness of the city,
it has greatly diminished the consumption of fermented liquors;
and experience has sufficiently proved that alcoholic drinks, of every description,
render the human body more susceptible of disease,
and more insensible to the action of medicine,
than it is when such liquids are totally avoided.
Total abstinence has been found one of the best preventatives of cholera.
So true it is, that whatever contributes to good morals, is, in general,
promotive also of health.
The blessing of Providence always rests on the course that is right.
--Editor Friends`' Review.]
But there is reason to fear, that long neglected and repeated mercy,
being so little laid to heart, further chastisement awaits us,
the inhabitants of this highly favoured city.
Your trials have been of a different kind, and some of them, I have no doubt,
have been magnified to us.
I hope, however, all is not as has been represented; but be that as it may,
"`the foundation of God stands sure, having this seal,
the Lord knows them that are his.`"
My sympathy, however, is great with you and dear Mary Ridgway;
my love is to her and her companion, Jane Watson.
In your freedom--though I suspect it will be a painful
task--I should like to know the true state of things,
that more than enough might not be in circulation.

Our dear N. Waln is poorly; William Savery, a strong man,
and David Bacon remains an upright pillar--sound and steady;
perhaps you have heard of the decease of dear Patience Brayton;
but Mehetabel Jenkins is alive and in the truth.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Martha Routh.

[.signed-section-context-open]
Philadelphia, 5th mo. 26th, 1800.

[.salutation]
My beloved Martha Routh,

Your last, of Seventh month 13th, 1799, is now before me.
I had, before its receipt, concluded that,
as so many of mine to different friends in your land had been lost,
it would be best for me to lay my pen, where my honour had for some time been, namely,
in the dust.
But now, our mutual dear friend, Samuel Smith, with Richard Jordan,
being about to embark on a gospel errand to Ireland, and some parts of your nation,
feeling a fresh salutation flow towards you, I am disposed to make the present attempt.

I need not say much about Samuel Emlen`'s close, which was in great sweetness and peace,
as dear S. Smith can give you intelligence of this or other circumstances.
Suffice it therefore to know, that our young ministers are, many of them,
growing in strength and beauty, particularly Sarah Cresson, H. Fisher, H. L. Fisher,
and Rebecca Archer.
Our Jacob Lindley is to declare his intentions of
marriage next Fourth day with our Ruth Anna Rutter.
A like report we have of dear Rebecca Young.
May they all be favoured with the conducting hand of best wisdom.

I suppose your annual solemnity is near a close.
My mind has been so much with you, that I do hope it has been a festive time,
even if the cup of suffering has also been handed.
Ours was truly so.
We had the company and large services of several strangers--especially Nathan Hunt,
Ann Jessop, Daniel Haviland, and Daniel Dean, besides Richard Jordan, etc.
Your dear R. Wright was here, and seemed of her better sort.

We are in full expectation that our absent brother, Thomas Scattergood,
will be at liberty, after your yearly Meeting, to return, and, if I am in the body,
I shall rejoice at seeing him.

I somehow was not capable of feeling sorrow,
in hearing of the happy translation of M. Haworth;
so many are the dangers that beset us poor creatures on every hand,
that I have learned to adopt in sincerity,
on every such removal from this militant state,
this exclamation--"`Blessed are the dead,`" etc.
We have affecting accounts from your sister kingdom.
We have enough everywhere to convince us of the necessity of
"`taking heed lest we fall,`" so that I sometimes tremble on my own account.
My old friend, Hannah Cathrall, is in an innocent childlike state of mind,
but so lame in her feet, from a paralytic affection,
that it is with difficulty she gets from one room to another.
Have me, dear Martha, in remembrance for good, for I have many infirmities,
both of flesh and spirit, to struggle with,
and I need the prayers of my friends more than ever.
Do sometimes let me hear from you,
and all about my dear friends in England--a spot pleasant to my thoughts;
yet the good land, which is not very far off, being sometimes so animatingly in view,
my soul is enabled to look beyond the things which are seen, and to crave that the Lord,
in his infinite mercy, may, at the last, conduct my poor soul thereinto,
even in the lowest station.
Farewell, my endeared sister, for so you are to your poor

[.signed-section-signature]
Rebecca Jones

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Martha Routh.

[.signed-section-context-open]
Philadelphia, 11th mo. 6th, 1800.

[.salutation]
My dear Friend,

Your tender greeting of Seventh month last, came duly to hand;
the contents whereof awakened all that is within me capable of
feeling with you in the depth of many sorrows,
and with Friends in your land who are concerned to support those
testimonies of divine origin which were given to our forefathers,
and are renewed to us in the present day.
Yours and other similar accounts respecting the
sorrowful affair which so exercised your Yearly Meeting,
explains what was before in circulation here.

What can be done, short of the Lord`'s doing,
to bring the party to see and escape the subtle work of the enemy, I know not.
I sincerely pray that she may be restored to the path of sound judgment,
and so remove the occasion of offense; or I fear the weak of the flock will be staggered,
and scattered into the wilderness thereby.
But the living Foundation will stand sure!
Happy and safe are they whose building is thereon!
Against these, we are told, "`the gates of hell shall not prevail.`"
How different are the sensations of my mind on reading your account,
and your settled opinion respecting some of the younger class among you,
whose solid deportment drew forth sympathy and encouragement from their elder sisters.
And it appears from what you say about meeting with our dear S. Smith and Richard Jordan,
M+++.+++ Stacey and Sarah Lynes, at your Quarterly Meeting,
that it was similar to what the apostle experienced at _Appii Forum_, when he "`thanked God,
and took courage.`"
I remember to have seen Sarah Lynes at Clerkenwell school, and that my landlord,
Joseph Gurney Bevan,
told me he "`did believe she would make something clever if she lived.`"
I don`'t wonder at your solicitude for her preservation.
My spirit unites with yours therein, that she may be kept by the power of God,
by the armour of Righteousness on the right hand and on the left, from every snare,
and in every hour of trial and temptation that may assail her.
I was pleased to find that she had so steady and valuable a friend as M. Stacey with her.

Our choice plants, Hannah, wife of S. R. Fisher, Hannah L, daughter of Thomas Fisher,
Sally Cresson, etc., thrive and bring forth pleasant fruit, as do many more,
in city and country.
So that if you should be again divinely commissioned, and sent to visit this land,
you will have some joy, amidst many sorrows that will inevitably be your portion.

Our dear S. Harrison is able to get to meetings, and among her friends;
and our dear Thomas Scattergood feels near as ever to the living among us.
He gave us, last Second-day, being our Quarterly Meeting,
a lively but affecting account of his exercises;
after which our Meeting`'s Memorial concerning dear Samuel Emlen, was read,
and being lively and very descriptive, had a remarkable reach on the meeting,
so that we broke up in tears.
Samuel Emlen`'s daughter has been married to Dr. Physick,
of an unexceptionable character, as a man and as a physician,
yet not a member of our Society.
What shall we say to such things as these,
but that all must purchase Truth for themselves,
if they really come into the possession of it.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Joseph Williams.

[.signed-section-context-open]
Philadelphia, 11th mo. 6th, 1800.

[.salutation]
Dear friend, Joseph Williams,

Your truly welcome epistle of Eighth month last,
I have now before me, and, fully resolved to keep fast hold of my end of the chain,
as our Indians say, sit down in order to reply to your sundry intelligence;
some part of which has clothed my mind with great sadness.
The particulars as related by you, have more fully explained the matter,
which had reached us before yours came to hand.
It is rapidly spreading as from Dan to Beersheba.
I am not equal to any advice in this afflicting case;
but hope best wisdom may direct whatever is done;
and that the party may have an ear to hear "`what the spirit says unto the churches.`"
And seeing what poor, fallible creatures we are,
oh that we may watch and pray continually to be
preserved on the one true and living foundation,
"`against which the gates of hell shall not prevail.`"

I am, however, truly sorry it is become so public, fearing,
lest some of the weak of the flock may be staggered, if not wholly driven away thereby.

Your situation, before this happened, was to be lamented; and you my dear friend,
with all the faithful,
who are endeavouring to "`hold fast the profession of our
faith without wavering,`" have had a bitter cup to drink.
But may it be remembered, that greater is He that is in and with his people,
than he that is in and of the world!
By this time, I hope, some of you will have to say,
in the arrival and help of dear S. Smith and Richard Jordan,
"`God that comforts those that are cast down, comforted us by the coming of Titus.`"
My love to them, if they are yet in your land, and to dear G. Johnson;
say I look towards him in the same love by which we were united at Newport, Nantucket, etc.
He may have heard that his young companion, Ebenezer Cresson,
died suddenly not long since, in consequence of a hurt on his foot,
which brought on a lock-jaw, and took him away in his innocence.

Dear Samuel Emlen`'s company and services are greatly missed,
but he had finished his work, and is, I doubt not, translated to a better inheritance.
A sweet memorial of him was read at our late Quarterly Meeting,
and a still sweeter one lives in many of our hearts.
At the same meeting, dear Thomas Scattergood gave us an account of his trials,
sufferings, and baptisms, which was very affecting to the meeting in general.
We rejoice in his release from the field of service,
and that he is evidently alive in Truth.
Phebe Speakman also looks fine and easy in spirit.
Oh, what a mercy, that the poor servants are so preserved through what is allotted them,
and favoured to return with sheaves of peace!

We of this city have abundant cause to be humbly thankful to the Father of mercies,
in that he has been pleased to spare us this year a visitation from that dire disease,
the yellow fever, yet it has prevailed at Baltimore, Norfolk, and Providence.

We have several promising young ministers in this city.
My prayer for them is, that the Lord keep them humble, little, and low.

I wish my love handed to your dear wife, etc.
Ah, what changes, divisions, and multiplications in families,
have taken place in a few years! and what
remains to pass through is wisely hidden from us.
I think this scrawl will convince you, that I am old, and almost worn out,
for all you pleasantly say about old maidens.

As to my present circumstances take the following.
I live in a neat dwelling in Brook`'s Court, near North meeting; keep a little shop;
have a precious child in my B. C. +++[+++Bernice Chattin]. I
can walk about better than for several years past;
have a tolerable share of health; am favoured with the company of my dear friends,
and what is still more to be prized,
feel my heart at times lifted up in gratitude and thankfulness to the Author of all good,
for his innumerable favours and mercies vouchsafed in an abundant manner, to me,
a poor unworthy creature.

Let us pray for one another, that we may be kept steadfast and immovable unto the end,
and finally obtain an admission into that city, "`none of whose inhabitants can say,
I am sick!`"

[.signed-section-closing]
I am, dear Joseph, with love unfeigned, your sister in the unchangeable Truth,

[.signed-section-signature]
Rebecca Jones

--

The skepticism which prevailed in Ireland occasioned her much concern; the more so,
as it ensnared some, of whom she had hoped better things.
"`I have learned,`" she notes, Tenth month 3rd,
"`that Truth has so far prevailed over Error, and light over darkness,
that opposition to its known principles is on the decline.
This must inevitably be the case, because,
'`the Lamb and his followers will have the victory.`'`"

Under the same date, she says,

"`I have a letter from Richard Jordan, written after the last Yearly Meeting in London.
He appeared to be low and lonely, having in prospect a visit to the continent, and,
as yet, no companion.
I hope he is by this time favoured with a yokefellow,
and have no doubt but his blessed Master will supply all his needs.
He is a near and dear brother in the Gospel.`"

On the 11th of Ninth month, 1801, died her kind and faithful friend James Hartley.
Early one evening, during his illness,
Rebecca Jones sent to him by a neighbour a sympathetic message.
While sitting at her supper, at 9 o`'clock that night,
she laid down her knife and fork and sat with great solemnity,
which feeling was shared by her companion, our informant.
After a little while, she said, "`The conflict is over, James is gone.`"
About an hour afterwards the same neighbour called,
with information that he had deceased precisely
at the time of Rebecca Jones`'s impression.

Whatever may be thought of intimations thus afforded to individuals
at the moment when a near friend is disrobed of mortality,
the fact of such, and of kindred phenomena, is placed, by reiterated occurrence,
entirely beyond dispute, at least to those who believe the testimony.
There are those among our readers who can refer
to cases within their own personal knowledge.
Several instances of this spiritual communion will be found in these memoirs,
and more might have been inserted.
We think it expedient to place on record well authenticated cases of the kind,
not to encourage superstition, but as an aid to the believer,
in furnishing evidence that the Divine Spirit does at times
communicate to the human mind a knowledge of things which
could not be perceived by the natural faculties.
We see no reason for seeking to refer these spiritual
phenomena to any other source than "`the testimony of Jesus,
which is the Spirit of Prophecy.`"

To Christiana Hustler she writes, Third month 12th:
"`It was like marrow to my bones to hear, by a late letter from Henry Tuke,
that you are '`strong in the best life.`' It must be a great
comfort that your dear children are settled so near to you,
and that precious Sarah is continued a prop to your declining years.
Salute each of them and theirs for me,
and convey to them my fervent desire that they may become valiant for the cause of Truth,
through an unreserved obedience to all its dictates,
in smaller as well as in greater matters; seeing that the work of Righteousness is Peace,
and the effects thereof quietness and assurance forever!
Your approaching Yearly Meeting will be interesting--
one subject in particular painfully so.
May best counsel be waited for and obtained!
Dear Richard Jordan, being left to serve alone in Ireland, calls forth my tender sympathy.
My love to him and to Samuel Smith, Charity Cook, M. Swett, David Sands,
Elizabeth Coggeshall, and George and Sarah Dillwyn.
Tell S. Smith his wife is accompanying John
Parrish in a family visit to our North Meeting.

"`It is probable that some of our friends may clear out at your approaching solemnity,
whose return will be pleasant to their friends here.
May their peace be sealed sure.
Dear Thomas Scattergood is a precious addition to our meeting.
Our dear Sarah Harrison often mentions you with heartfelt affection,
and in a late conversation we were both so revived,
that we concluded that if by going 100 miles we could gain an interview with you,
we should not hesitate an hour about the undertaking.
We are as nearly united in gospel fellowship as ever.`"

Referring in this letter to the approaching Yearly Meeting of Philadelphia, she says:
"`I suppose you will look sometimes towards us, as I shall towards you,
if continued in mutability.
And this being one of the blessed privileges
enjoyed by the children of the heavenly kingdom,
let us prize it, be comforted in it, and give to our great and holy Head,
who presides over his own church everywhere, the glory which is now and forever his due.

"`My Bernice,`" she adds,
"`continues an affectionate precious companion in my solitary moments,
as well as a most tender nurse under indisposition.
I number her among my comforts in the journey
through and near the end of this vale of sorrow.

"`May the Shepherd of Israel protect, defend, and save you by his own immediate power,
in every time of trial and distress,
is the present breathing desire of your sincerely affectionate friend,
old fellow traveller, and sister in the Unchangeable Truth.`"

Fifth month 4th, she received from John Lury, of Bristol,
a present of "`a very rich cheese,`" in which was a tin box,
containing twenty guineas in gold,
being the amount of a legacy left to Rebecca Jones by a deceased friend.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, 10th month 26th, 1801.

[.salutation]
Dearly beloved friend, S. Stephenson,

I have often thought of writing to you since
your arrival in our land with your dear companion M. Jeffries,
but being in expectation of seeing you before this time in our city,
I have put the motion by until now--and having, in a dream last night, been with you,
and embraced you and M. Jeffries in the arms of
undissembled Christian and Gospel fellowship,
I have at length taken up my pen in near and dear unity,
to offer the written salutation thereof to your acceptance.
For, though by increased years since I was a sojourner in your land,
I witness an increase of bodily infirmities, which, for the last two years,
have kept me much in our city; I do, nevertheless,
rejoice in the continued qualification to bid good speed to
all the dignified servants in our heavenly Father`'s family,
and crave that the arms of their hands may indeed be
made strong through the Power of the God of Jacob.
That so, in this day of deep revolt,
and time of Satan`'s triumph over such who have been numbered
among the stars--Israel may not be given over to reproach,
nor Jerusalem become a hissing and a desolation.

I hear that you are given up to the service of visiting families--a work in which you,
dear Sarah, have had long and large experience.
May it be blessed to the visited in that city,
where dear R. Wright and myself were a few years ago engaged in like manner,
from house to house.
While sitting by my own fireside, I can accompany you mentally,
and share a part of your exercises therein, according to my small measure,
trusting that mouth and wisdom, with every requisite supply will be granted,
and the Divine name exalted, which is now and forever worthy.
You are so often enquired after by friends here,
that many seem already acquainted with you,
and believe that notwithstanding things are as they are among us,
you will find Fathers and Mothers, Brethren and Sisters, in the heavenly Relation;
unto which I know you wisely give preference.
I have no late letters from Europe, but, as I cannot hold out as usual,
in the epistolary way, I must endeavour to be content under the ancient assertion,
"`He that sows sparingly, shall reap sparingly.`"

[.signed-section-closing]
In Gospel affection, I remain your poor, but sincerely well wishing sister,

[.signed-section-signature]
Rebecca Jones

--

To Christiana Hustler and daughter, she writes Eleventh mo.
27th:

[.embedded-content-document.letter]
--

"`My faithful, dear friend Catharine Howell`'s choice daughter, Elizabeth,
about the age of S. Hustler, has several times, lately,
lifted up her voice in public meetings, and is a precious plant.
May all who have submitted to become fools for Christ`'s sake in this way,
follow his leadings faithfully, and serve him with their whole hearts,
is the fervent petition of my heart.`"

[verse]
____
'`So shall they grow to glad parental care,
And shine as warriors in defence of Truth.`'
____

"`Of Hannah Barnard`'s^
footnote:[In several of the preceding letters,
allusion is made to the trials experienced by Friends, particularly in Ireland,
about this time,
but the name of Hannah Barnard has not been heretofore mentioned in connection with them,
yet there can be no reasonable doubt that she was a prominent agent
in the production of the difficulties and exercises to which Rebecca
Jones frequently alludes.
{footnote-paragraph-split}
Hannah Barnard,
who resided in the State of New York, was an acknowledged minister in our Society,
possessed of talents considerably above the ordinary level,
with a force of imagination and power of language which were
quite attractive to her youthful and inexperienced hearers.
Yet some of the more discerning and considerate class regarded her, as one,
to use a hackneyed but expressive phrase, who was carrying more sail than ballast.
When she opened to her friends at home,
her prospect of paying a religious visit to the meetings in England and Ireland,
it is understood that considerable hesitation appeared,
but she was eventually liberated by the proper meetings,
and proceeded to Europe in pursuit of her prospect.
Whether she had, previously to her embarkation,
embraced opinions incompatible with those acknowledged and maintained by the Society,
or whether she gradually fell into them while on her journey;
she at length gave such evidence of the unsoundness of her principles,
that Friends in Ireland judged it needful that
she should discontinue her ministerial labours,
and return home.
{footnote-paragraph-split}
From this
judgment she appealed to the Yearly Meeting of London,
where the subject underwent a careful examination.
Her popular and plausible eloquence had attached a party to her,
but after a patient investigation,
the Yearly Meeting bore its testimony against the doctrines which she had
espoused.
{footnote-paragraph-split}
She at length returned to her native land,
and a complaint being laid before the Monthly Meeting to which she belonged,
she was disowned.
From this judgment she appealed to the Quarterly and Yearly Meetings,
by which the testimony was confirmed.--Editor Friend`'s Review.
{footnote-paragraph-split}
Rebecca Jones received from Richard Jordan a
curious and interesting letter respecting Hannah Barnard,
which the compiler has not been able to find among her papers.
Writing in allegorical style,
so as to be intelligible only to those who knew something of the case,
he describes the arrival of a ship from America laden with contraband wares.
A few parcels he says were cautiously opened in England, but,
there being no demand for them, she set sail for Ireland, etc.
The allegory was ingeniously pursued.
W+++.+++ J. A.]
return little has been said, so that I hope she continues quietly at home.
Richard and Martha Routh are on their way to New Bedford.
My Bernice Chattin is a solid, precious companion,
and as near to me as though she were my own daughter.
Dear Samuel Smith, William Savery, and Thomas Scattergood, are my frequent visitors,
and brethren beloved.

"`Could we but have a few hours personal interview, how pleasant would it be!
But as this cannot be, let it suffice that we often mentally visit each other,
and endeavour to live and walk in that holy fellowship,
which stands '`with the Father and with his Son,
Christ Jesus,`' in whom all the families of the earth are blessed; and let us trust that,
of his adorable mercy, we shall, when this short fight of affliction is over,
be united in his heavenly kingdom, never more to part.

"`My old companion, Hannah Cathrall, who lives about five miles off, at Frankford,
is on a visit to her friends in this city, and though very lame,
seems renewed in best life.
She spoke a few words in our meeting last Third day, and will, I verily believe,
land in peace at last.
What a mercy!`"

--
