== Chapter XVI.

[.chapter-subtitle--blurb]
1805--1813.

[.chapter-synopsis]
* Letter to Mary Jeffries
* Marriage of James and Bernice Allinson
* Letters to them
* Eclipse and note by E. Lewis respecting it
* Death of Hannah Cathrall
* Painful circumstances
* Letters
* Goes to New York
* Returns
* Death of John Teas
* Yearly Meeting
* Death of K. Howell, James Simpson, Christiana Hustler and James Allinson
* Letter to S. Hustler
* Death of R. Wright
* Mentions Susanna Home

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Mary Jeffries.

[.signed-section-context-open]
Philadelphia, 3rd mo. 1st, 1805.

[.salutation]
Dear Mary Jeffries,

Increasing infirmities, with old age coming fast upon me,
have prevented my seasonable returns to many other epistles from your land besides yours,
so that I am thereby deprived of those frequent little "`brooks by the way,`" which
for many years have been very refreshing and strengthening to my poor mind;
the secret past conflicts whereof, as also the exercises of the present time,
are known only to Him whose "`eyes behold, and whose eyelids try the children of men.`"
I have, however, abundant cause for humble thankfulness that the best life is, I trust,
still preserved, so that I can say in sincerity, "`I love the brethren;`" and this is,
at times, my only joyous experience.
Well, dear Mary, you are comfortably among your own people, where,
if enough attentive to divine counsel, you will not sink into a state of inactivity;
remember, the time of youth is the fittest time for action,
and when the query is proposed in the secret of your mind, "`whom shall we send,
and who will go for us?`"
may the dedicated reply of your heart be, "`Here am I, Lord, send me.`"
So will your experience in the strength of salvation be increased,
and your day`'s work be going on with the day; and finally, as our late dear friend,
William Savery, has done,
close your season of labour with "`glory to God,`" and lay down your head in peace.

By some late account from you,
it is probable your dear father has joined his spirit to many
who are already members of the church triumphant.
"`Blessed are the dead who die in the Lord,`" etc.,
is often the language of my waiting spirit on hearing such tidings,
because the "`living who are yet alive,`" are so liable to the
assaults and buffetings of that Power which continues to wage
war against "`Michael and his angels;`" but the Lamb and his
followers shall have the victory! and "`this is our victory,
even our faith.`"

My Bernice Chattin has lately lost her dear mother at Cape May, who left eight children;
and having expressed a desire that I might take her daughter Elizabeth,^
footnote:[This young friend grew up under Rebecca Jones`'s care,
and remained her constant and affectionate companion to her close.]
she is added to my family, and is number 3;
but I fear my being able to do justice by her,
only that her sister B. is very capable to instruct and educate her.

To hear of my friends in your land is always gratifying,
and very much so is any account of my ever dear friend Christiana Hustler and hers.
She, like myself, is bending towards our original dust, and on her account,
I have no doubt but when called home,
she will be found in a state of readiness to enter the Bridegroom`'s chamber,
and "`forever solace in his love.`"
And oh, says my soul,
that I may also be counted worthy of an admittance
thereinto when my short span of time shall terminate.

--

"`New Year`'s day, 1806.
At home, and favoured with a peaceful mind.
Lord, grant that I may be so sensible of the multiplied
mercies which you have bountifully heaped upon me,
that I may walk in fear and reverence before you all the days of my life,
and finally die in your favour and acceptance.

Last evening, paid us a family visit.
He was dipped in sympathy with my aged and infirm state,
and imparted sweet counsel to my dear B.,
telling her that he fully believed that a singular blessing awaited her.
In the close of the opportunity my soul secretly exclaimed;
He has crowned and closed the year with his goodness!

"`First month, 5th. My old friend, Hannah Cathrall,
had yesterday another stroke of palsy,
which deprived her of the use of her left arm and hand.
I spent this afternoon with her.
She was sensible, and in a broken, contrite state of mind.
In the evening I got to a large meeting at High street, which was a quiet, low time.

"`12th, First day.
Our meeting this morning was a precious season;
dear S. Smith ministered in great weakness.
Thomas Scattergood had also good service.
Prostration of body and soul was my portion therein.
In the afternoon I stayed with Hannah Cathrall, who grows more weak.
May the Lord be pleased to make her more easy, both here and forever!

"`17th. H. Drinker brought me $22, for eleven poor widows.`"

In her diary, under date of the 22nd, she notes a visit from James Allinson,
who opened to her his views respecting a matrimonial connection with Bernice Chattin.
For this the mind of Rebecca Jones was already prepared,
under a conviction that these young Friends were by their
heavenly Parent designed and fitted for each other,
and she says, "`I let him know that I could have no other objection,
than the prospect of parting with her now in my declining years;
that if they sought for best counsel, and obtained it,
so as that they might be united in the Lord`'s fear, I should not dare to oppose it.`"
The further memoranda of Rebecca Jones on this subject,
touchingly illustrate the closeness of the union which
subsisted between this mother and her child,
our aged friend disinterestedly and nobly taking part against herself,
and overcoming Bernice`'s dutiful reluctance to leave
her venerable parent in her declining years.

It is however due from the compiler to say that the insertion of this
and other references to his beloved parent is contrary to her request,
and without her consent.
He cannot join in her humble estimate of herself,
nor can he wholly disconnect her history from that of one to whom she was so endeared,
and to whose comfort she was so essential--and in his decision on this delicate point,
he has been influenced by the counsel of judicious friends.

"`Fourth month, 26th. Our Yearly Meeting is just ended.
By an attack of erysipelas,
I have been prevented from getting out (save once) in the last two weeks.
This, with the prospect of my beloved child being likely,
in a few weeks after her marriage, to remove to New York, has been deeply trying;
but He who furnished this innocent plant to me in a time of great need,
is able still to supply all my needs.
On him, therefore, I desire to depend, and humbly crave, for her and for myself,
that we may be continued, as we have for many years been,
the objects of his divine compassion and care through time,
and land safe in a happy eternity.
Amen, says my soul.
Many friends have called to see me,
with whom I have sweet fellowship--particularly dear Martha Allinson and her children.

"`29th. At our Monthly Meeting James and Bernice declared their
intentions in a very solemn and becoming manner.
Thomas Scattergood came into our meeting with James,
and language of encouragement was handed through John Parrish and others.
Also, in the evening, at my house, Thomas Scattergood had a sweet testimony.
It was a day of favour.

"`Sixth month 3rd. Were married at our North Meeting, James Allinson and Bernice Chattin.
They were solid and weighty in their deportment, and a favoured meeting it was,
in which Thomas Scattergood was engaged in testimony and supplication.`"

Her letters to her "`children,`" as she called them, were now numerous,
and much more frequent than to other correspondents,
and were fraught with tenderest maternal feelings.
From these we shall extract sparingly.
Sixth month 16th,
in a letter to them she says:--"`In our meeting today I
had silently to worship the God of my life,
to commit and commend you into the arms of His goodness and mercy,
(which have followed me all my life long,) and to bless and
praise his great and excellent name on your account and my own.
May the Lord condescend to bless you in your new habitation, that thereby it may be,
indeed, like the house of Obed-edom, where his ark found a resting place.
I have been looking today at the eclipse, which led me to exclaim with the Psalmist,
"`In wisdom have you made them all.`"^
footnote:[The circumstance of looking at an eclipse may appear like a very common affair.
But the eclipse on the 16th of Sixth month 1806, was a very unusual one.
It was one in which, as seen at Philadelphia,
more than eleven-twelfths of the sun`'s surface was covered;
and though the day was unclouded, everything seemed to assume a somber appearance.
It occurred at a season of the year when the earth was
nearly at its greatest distance from the sun,
when, of course, the apparent diameter of that luminary was near its minimum;
at the same time the moon was not far from the point in its orbit nearest the earth,
when its apparent diameter was consequently near its maximum.
In some of the Northern States the eclipse was total,
the sun being there for a time entirely obscured.
This is a phenomenon which few persons have the opportunity of witnessing.
Dr. Halley asserts that he could not find that a total eclipse
had been visible at London between the years 1140 and 1715.
Within the last sixty years, two eclipses have been visible at Philadelphia,
in which the central parts of the sun were obscured,
leaving merely a luminous ring around the darkened portion of the sun.
At the time of a total eclipse of the sun,
the planets and some of the brightest fixed stars have
come into view.--Editor friends`' Review.]

Dear Thomas Scattergood has again gone to spend some time at Westtown School,
so that our poor North Meeting must endeavour to be content with more silence.
And yet we often have favoured seasons, and sometimes life is raised through the gospel.
May you, with your sister M., experience the force of the ancient assertion,
'`Two are better than one,
and a threefold cord is not easily broken.`' May that gracious God, who has been with,
fed and supported me all my life long, take the government and direction;
and may your wills be so brought into subjection to his blessed will,
as that he may mercifully condescend to hear you when you call upon him,
and answer all your requests when, in innocence and uprightness, you intercede with him.
It is a comfort to me that dear Margaret remains,
that you may take sweet counsel together, going up to the house of God in company.
I want Bernice to remember that she has called me by the endearing epithet of mother;
and come at a suitable time to see me and others whom she has left behind,
who know how to value and love intrinsic worth.
I feel as nearly for your present and everlasting
welfare as it is possible for a mother to feel.
I think of you when sitting at my meals--in my lonely evening hours--in the night season,
on my bed--and when assembled with the northern flock.
May the certificate about to be forwarded bind you more
closely to the living members of your meeting,
and settle you down as a squared and polished stone in that
building of which Christ Jesus is the chief corner stone,
'`in whom`' (says the Apostle) '`all the building fitly framed, etc.,
grows up together a holy temple in the Lord.`'

"`Seventh month 15th. In a letter to Bernice Allinson,
Rebecca Jones says:--"`Dear Samuel Smith spent an hour with me yesterday.
I mourn in looking at him, so emaciated, so reduced, and so old in appearance,
that you would hardly know him; yet full of love and sweetness.
I cannot help hoping that he may yet be restored to labour and service among us.`"

Eleventh month 5th,
she writes to Bernice Allinson:

[.embedded-content-document.letter]
--

"`Our Quarterly Meeting was uncommonly large;
the service in both meetings was close and sharp, both from male and female,
against detraction and spreading of evil reports.
We had dear Rebecca Wright`'s company.`"
And Twelfth month 3rd, she writes to her--"`Our old and afflicted friend,
Hannah Cathrall, has had a more general stroke of palsy, and now lies almost lifeless.
Her speech has almost failed, so that but little has been understood,
and for the last two days and nights she only breathes.
They wet her lips, but she does not swallow.
For the first eight days she knew us all,
and was full of love and sweetness,--often called for me, and begged me not to leave her;
and told me her mind was quite easy.
Now that her speech has failed, she fixes her eyes on me with great affection.
I do fully believe she will center in eternal rest and peace.
Many friends have manifested their love by going to see her.
S+++.+++ Smith, R. Price, etc., spoke comfortably to her last First day.
Oh, I do look at you with love and sweetness, and often remember the saying,
"`two are better than one,`" etc.
May the God of all grace and consolation be with us, now we are separated;
even as he has many times when you and I have sat by the light of the same
lamp and has tendered our hearts by the shedding abroad of his love,
by which we have been united in desire to fear, love and serve him forever and ever.

P+++.+++ S.--I open my letter (Sixth day, the 5th,) to mention that dear Hannah Cathrall,
after laying 72 hours in an easy sleep, quite motionless,
quietly breathed her last about 9 o`'clock this morning.

[.signed-section-closing]
I am your unchangeably affectionate mother,

[.signed-section-signature]
Rebecca Jones

--

In her diary after recording the illness and death of her "`old friend and former
companion Hannah Cathrall,`" with the particulars given in the above letter,
she adds--"`She was interred 12th mo.
7th, many friends attending.
She died aged 70 years, and near six months,
and from the sense which was afforded to my mind I do
believe has gone to rest and peace with her Maker.
Blessed be his great Name, for his mercies they endure forever.`"

On the 22nd,
after referring to two circumstances which had
deeply afflicted her in common with all Friends,
and respecting one of which she says,
"`the thing that I had for many weeks feared came upon me like
an armed man,`"--she adds--"`These cases have raised the
necessary prayer for myself and others;--oh Lord,
in mercy look down upon us--spare your people, and give not your heritage to reproach:
lest the uncircumcised triumph, and the Philistine nature say, where now is their God.
I got to meeting in a state of great weakness yesterday morning,
where solemnity attended, though all our harps were on the willows hung.
Mine still is, and will long remain there, for unless the Lord keep us, none other can.
Thomas Scattergood had a sweet time in supplication to
the God and Father of our Lord Jesus Christ,
for preservation through time, and for divine aid to journey on in fear and trembling,
etc. etc. I went pensively down to J. Pemberton`'s, and stayed there the rest of the day,
communing about what had happened in Israel, and we were very sad.
I also called on dear S. Smith.`"

"`1st mo.
1st., 1807.
Dr. Physick has buried his only son; which is to them a severe trial--but I say,
happy is it for those dear lambs who are taken
in their innocence from those fiery trials,
which some even in advanced age are unable to sustain
unaided by the power of our Almighty Helper.`"

Catherine Hartshorne in a letter to Rebecca Jones, dated 1st mo.
9th, says,
"`I have been often much instructed in remembering some conversation in our parlour,
between you and my beloved mother.
You said that you had a little precious stone of faith in your
girdle--which encouraged a belief that you would be cared for.
This I fully believe, and it has proved strengthening to me many times,
in a hope that I may also be thus favoured.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones to Mary Allinson

[.signed-section-context-open]
Philadelphia, 1st. Mo. 23rd. 1807.

[.salutation]
My dear friend, Mary Allinson;

I have such confidence in your friendship that though more
than a month has elapsed since the receipt of your short kind address,
I trust when you take in the several events that have occurred,
and one more afflicting and awful than I believe ever happened in our society before;^
footnote:[The circumstances to which she here alludes, excited at the time,
an unprecedented sensation in Philadelphia and its vicinity;
and were well calculated to impress the admonition:
"`Let him that thinks he stands beware lest he fall.`"
But the particulars having passed away from the
memories of most of the present generation,
need not be exposed to those who are to come.--Ed. Friends`' Review.]
you will readily excuse your poor old friend whose harp has been ever since "`hung
upon the willows,`" and the garment of mourning and unutterable sorrow and
astonishment has completely covered my spirit by day and by night.
So that though I have also deeply and tenderly sympathized with you,
I have not been able to do more.
But as by this time the melancholy tidings may have reached England,
my mind seems somewhat relieved, especially when I remember the assertion in Holy Writ:
"`Mercy rejoices against Judgment`"--and that "`secret things belong only to God,`"
who is the Supreme judge of all--and there I wish to leave the scene,--and hope so
to apply the instruction which it conveys as to remember that "`he who thinks he
stands has need to take heed lest he fall.`"

Your dear mother has had a tedious illness,
and very trying I know it must have been--but
she has been sustained by the Great Physician.
In sisterly affection salute her for me.
Her feeling sympathy I have shared in past seasons,
and have enjoyed her sympathy under the late heavy and afflictive stroke.
 
My poor afflicted old companion Hannah Cathrall as I expect you have heard,
has bid adieu to mutability, after a long series of weakness and pain.
I was much with her the last two weeks of her time,
and from the calm and easy state both of body and mind in which she breathed her last,
have a comfortable hope that "`her warfare was accomplished`"
etc.--and that her evening closed in peace.

Our dear friend S. Cresson is in a low spot, but will, I fully believe,
in the Lord`'s time,
experience the Sun of Righteousness to arise with healing in his wings.`"
The like comfortable hope I have for dear +++_______+++ who
is so low that she refuses to be comforted.
Tell your worthy Mother that in just now looking towards her,
I can adopt the benediction of one formerly,
"`Blessed are you among women`"--because I feel
that she is under the Great Shepherd`'s care,
who slumbers not by day nor sleeps by night,
and will eventually cause the dispensations of his Providence to work
together for her good and the good of her beloved children.

--

In her diary, 2 mo.
4th 1807,--still dwelling on the anguish noted the 22nd of 12th month,
she says--"`My mind from the two foregoing sorrowful circumstances, is so sunk,
that silence and sorrowing seem so fastened thereon,
that unless the Lord most high (whose voice I have often experienced to be
mightier than all the noise of the boisterous waves of the billows of
affliction that have passed over my head) is pleased in mercy to relieve,
help, and succor, I shall indeed sink in these deep waters,
where there is no standing--but with his blessed arm underneath there is hope.
My dear S. Cresson, who has always been, in my view, a precious plant,
being also in a low dejected state of mind, is an addition of grief to my sorrow;
and thus I exclaim, "`Woe is me.`"
Yet on the same day she writes to her whom she addressed as
her daughter a cheering letter fraught with consolation,
in which,
after commemorating the preserving power of him who sits with the solitary in families,
she says, "`Blessed be his Name,
in that he still vouchsafes to be near me now in my old age and under many infirmities,
or I should fail before him.
And when I consider my great unworthiness I cannot but exclaim,
Lord what am I that you should be mindful of me a poor creature--dust
and ashes before you!`"--"`Dear S. Cresson`" she adds,
"`is a little revived, and took part in our Quarterly Meeting on 2nd day.
Our North Meeting have lately raised by collection $800 in consideration of the
severity of the season upon the poor (not members of our Society) in our district;
with which, in wood, warm bed clothes, etc., they have relieved many worthy characters,
who could not make their needs known.
Thomas Scattergood^
footnote:[It is a pleasing circumstance to find Thomas Scattergood,
after spending a number of years during the prime of his life,
in traveling through Europe and America, proclaiming the glad tidings of the gospel,
now in his declining years engaged in relieving the
physical needs of that worthy class of sufferers,
of whom numbers are unquestionably furnished by every age and country,
who being duly conscious of the duty of providing for themselves,
as long as they have the power without pressing upon the charities of the world,
are struggling with difficulties known only to themselves and to the all penetrating eye.
If the spirit by which Thomas Scattergood was actuated, both in his gospel labours,
and in his works of charity, was more generally prevalent,
there can be no doubt that many acts of unostentatious benevolence,
would be extended towards those who are on the verge of need,
but whose modesty impels them rather to suffer than to make their necessities known.
Charity is much more worthily bestowed on such retiring characters,
than upon those who shamelessly flaunt their needs in
the face of day.--Editor of Friends`' Review.]
was at the head of the committee of distribution--John Teas
also took an active part--and I hope the blessing of some who
were ready to perish is felt by them as a sweet reward.
It was very seasonably and judiciously done.`"

Referring, 4 mo.
12th, to the considerable diminution of her circle of acquaintance by many recent deaths,
she notes the confirmation of the Truth that,
"`One generation passes and another generation comes,`" yet she says,
"`this consolation remains--the Word of the Lord abides forever, and He,
our blessed Creator, in his inscrutable wisdom, does all things rightly and well.`"

"`5 mo.
14th, Having the offer of going to New York, in company with Richard Jordan, etc.,
and having been for some time inclined to visit my dear
children J. and Bernice Allinson who are settled in that city,
I consented.
We spent a night at Robert White`'s and another at Richard Hartshorne`'s,
and were joyfully received in New York on the 17th. The
Yearly Meeting began the 22nd and held till the 29th:
in which I had some service.
I felt near unity with many dear friends, and also with some precious young plants,
whose spirits had a sweetening effect on my poor mind.`"

To Christiana Hustler, she writes from New York, 6 mo.
4th,

[.embedded-content-document.letter]
--

"`I have been in this city about three weeks,
on a visit to my daughter who was married to a choice young friend a year ago.
Oh you know not what a painful thing it was when the time of separation came;
but their union was so marked with concurrent evidences of its rectitude,
that I dared not to lift up a finger against it.
May the Lord, my gracious Helper, bless her every way!
Whenever your Sarah is thus taken from you, why then you will realize my feelings.
The Yearly Meeting, held here last week, was a time of favour.
I have had an opportunity of visiting our friend
Elizabeth Coggeshall in her own habitation,
where she has just arrived after an arduous journey through our Continent,
which engaged her for more than a year, and which noble sacrifice,
in leaving her husband and three dear children,^
footnote:[The youngest of these children,
was only about nine months old when their dedicated mother
commenced her mission of love to Friends and others.
Being in her company, when on her return, bat some time before she reached home,
I heard her say she had not seen her own dear family for eighteen months.
What a sacrifice in compliance with religious duty!--Editor of Friends`' Review.]
she yesterday at the Monthly Meeting declared had yielded to
her mind the rich reward of sweet peace and consolation.
David Sands, with his wife Clemency, were in attendance.
He is, as usual, a living example of dedication,
in fervent labour in the work of the ministry--but his voice more weak,
and utterance less clear than formerly.
He called often to see me and to chat about friends in your land:--among others,
about you and yours.
Richard Jordan, who had been at our Yearly Meeting and now belongs to this,
was my fellow passenger in the carriage in which I came here.
He is a brother beloved.`"

--

Enumerating some symptoms of failing health, she adds--

[.embedded-content-document.letter]
--

"`...so that I conclude that the journey, the painful journey, cannot be far from its end.
O says my poor soul, that with it, all my pains and sorrows may also end.
Pray for me, dear Chrissy,
that my faith and patience may not fail--for verily both are closely tried.
I am glad to hear though you are failing in flesh,
your exertive faculties and general health are, considering your years,
not much impaired--and, what is preferable to all these,
that you are alive in our blessed Master`'s service, and dedicated thereto.
May Grace, Mercy and Peace from God the Father, be with us, and abound,
through Jesus Christ our Lord forever and ever,
is the prayer of your poor and almost worn out fellow traveller,

[.signed-section-signature]
Rebecca Jones

--

"`N. York 5th mo.
31st--1807. The Yearly Meeting here concluded 6th day at noon.
Upon the whole it was a solid time throughout,
though some instances of weakness were felt.
Richard Jordan, David Sands, etc., had large communications in the public meetings.
I hope I had a little share.`"

"`I stayed,`" she notes, "`with James and Bernice Allinson till the 15th of 6th mo.,
when I went with Thomas Eddy in his carriage to his house at Elizabeth Town,
where my kind friends R. and C. Hartshorne came for me.
After pausing two days with them, and making some visits at Rahway,
R+++.+++ H. took me to R. Whites.
Reached Burlington 6th day noon, and stayed there over 1st day.
On arriving at my habitation in Brook`'s Court, and finding it and all therein safe,
I had abundant cause (as often before) to be thankful
and to bless the Name of the Shepherd of Israel,
whose mercies endure forever.`"

7th mo.
26th. "`I have been twice at meeting this day,
and much comforted under the lively and consoling ministry of dear Thomas Scattergood.`"

9th mo.
2nd. "`We have had a general visit of what is called influenza--so
that very few in the city or country have escaped,
though few cases have proved mortal.
Some aged persons have died with it.
It has been a serious matter, and I esteem it no less than a gentle shaking of the rod,
from the same fatherly Hand who has often visited our poor city,
both in mercy and in judgment.
Oh that the inhabitants may now learn Righteousness.`"

[.embedded-content-document.letter]
--

[.letter-heading]
To Mary Allinson.

[.signed-section-context-open]
Philadelphia, 2nd mo. 1808.

[.salutation]
Dear Mary,

Your sisterly communication of 14th of this month is very acceptable,
though to hear of your dear Mother`'s continued
indisposition calls forth my renewed sympathy,
but we may hope that as warm weather advances, like Thomas Ellwood`'s Winter Tree,
she "`will bud again and shoot.`"
I have been mostly kept at home this winter by the succession of damp weather,
which was always unfriendly to my constitution,
but particularly so since the painful debilitated state of my limbs,
which are not sufficiently restored to be trusted any great length from Brook`'s court.
Yet I am, I hope,
humbly thankful that I have been mostly free from those rheumatic affections,
and a desire is mostly cherished,
that I may receive the present dispensation from our merciful Father,
with due submission, and become more worthy of His blessed care and protection,
who has done for and to me great things, and who knows best how to deal with me,
a poor creature, for my good, both here and forever.
I am sorry to hear that my dear fellow pilgrims George and
Sarah Dillwyn are suffering under bodily infirmities.
I feel them often near to my best life,
and rejoice in believing that the ancient of days will not leave them.

By a late letter from M. R.----I learn that my venerable friend Sarah
Barney of Nantucket has closed her well spent life.
She took sisterly notice of me, a poor stripling, half a century ago,
and has been inflexible in her friendship ever since.
I have loved her spirit, and her great example, and wish to follow it.

See what a long letter I have written under perplexities,
and by lamp light--so excuse all that it lacks.
I have nothing better at command just now--not even a promise to mend in future,
so let your dear mother and sisters share in this and in the salutation of dear love,
from a poor old fellow soldier,

[.signed-section-signature]
Rebecca Jones

--

Having been engaged in deep travail and exercise in Burlington Meeting,
as she entered the door of her friend Martha Allinson an engaging child,
(Rebecca Jones`'s namesake) came running to the door to meet her.
Rebecca Jones took her in her arms, and pressing her to her bosom,
repeated the following lines with a charm of voice and manner which impressed the
minds of those present far more than the narration can interest our readers.

[verse]
____
`'Tis this--`'tis Innocence your bosom cheers--
This calms your troubles, this dispels your fears--
This spreads o`'er all its beautifying rays,
Makes every object, every plaything please.
This, while less things a guilty breast can awe,
Gives music to a key and beauty to a straw.
____

In the first month of the year 1809,
died her valued friend John Teas--an upright man--a
self sacrificing Philanthropist--and a sincere Friend.
In the Yellow Fever, during successive years,
he performed those painful and hazardous services to humanity which
are likely to be owned as done unto Him by the great Example,
who "`went about doing good.`"
On various occasions he aided Rebecca Jones in carrying out her schemes of benevolence.
Although the state of her health at the time scarcely warranted the effort,
she went to the funeral, and was largely drawn forth in testimony, opening with the text,
"`Speak you comfortably to Jerusalem, and cry unto her,
that her warfare is accomplished,`" etc.--
directing the discourse principally to his widow,
and affecting most of the company to tears.

In a letter to William Rotch, 4th mo.
22nd, 1811,
after noting a confinement to her house from indisposition for near six months, she says,
"`and yet, to the praise of our ever adorable Helper,
who has hitherto sustained and upheld; I am at times enabled to set up my Ebenezer.
Our Yearly Meeting ended on 7th day last.
I have been enabled to attend all the sittings except four,
and may say it was throughout a solemn and very large meeting.
We had the company of dear Susanna Horne,
and of Ann Jessop from Carolina--and several from neighbouring Yearly Meetings.
The two named are going to that of New York.
Among those who were able to attend you will be pleased to hear of George Dillwyn,
S+++.+++ Smith, Benj.
White, Thomas Scattergood, John Hoskins (now in his 84th year) Rebecca Wright,
Leonard and Jane Snowdon, Sally Cresson, Ann Mifflin, etc.,
who nobly showed themselves alive in the best cause.
Also Jacob Lindley, who has buried his wife Ruth Anna.
M+++.+++ Pleasants was out generally, and bears up admirably.
My dear friend Catharine Howell, in her 74th year, after a long illness,
was a few months since released from all sorrow and pain.
Sarah Harrison is yet with us, struggling under infirmities and manifold trials,
yet often favoured to tell of the Lord`'s goodness.
James Simpson, near three weeks ago, after a short illness,
made a peaceful and happy close; fully resigned, and quite sensible,
telling those around him, "`I am going.`"
Lying down with his clothes on, and requesting to be turned on the other side,
he said,--"`it is done,`"--and ceased breathing.
His remains were interred at Frankford amidst a large company of Friends and others.
I could not but desire, "`Let me die the death of the righteous,`" etc.

Thomas Scattergood mentioned at our Monthly Meeting yesterday his prospect
of attending the Yearly Meetings at New York and Rhode Island.
Susanna Horne and Mary Allinson are bound the same way,
having Caleb Shreeve (a valuable friend of our meeting) for their charioteer.
How I should rejoice to spend a little time among you at N.
Bedford--but as that is not to be expected by me again,
you must let me love you, as I do sincerely,
and ask for the consolation of continued remembrance in your seasons of favour.`"

"`I have received an account,`" she notes,
"`of the peaceful and happy close of my truly dear friend,
and companion in gospel labours in England, Christiana Hustler; who,
after a long illness, in the 80th year of her age,
died at her country seat at Underclifle, Yorkshire, the 27th of 6th mo.
1811. And on the 14th of 8th mo.
dear James Allinson died at his mother`'s house in Burlington, aged 33 years,
leaving a precious wife and three children to lament
their irreparable loss--whom may the Lord sustain!`"

No notes or letters bearing date in 1812 have been found.
It appears that she attended at least a portion of the Yearly Meeting in the 4th month,
and participated in its exercises, although in a very enfeebled state.
We are informed that in one of its sittings she was eminently favoured,
drawing a comparison between the state of the Church Militant and
that of the Church Triumphant--expressing her belief that it was
designed that there should be a traveling towards a nearer
approximation to the latter while in this militant state.

[.embedded-content-document.letter]
--

[.letter-heading]

Rebecca Jones to Sarah Hustler.

[.signed-section-context-open]
Philadelphia, the 1st day of the year, 1813.

[.salutation]
My endeared friend and sister Sarah Hustler:

I have been so long your debtor that I hardly know how to begin the excuse which is
necessary for omitting to answer your letter of the 23rd of 8th month last,
and one from dear Martha Routh,
both announcing the peaceful and favoured end of your honourable and precious mother,
my truly near and dear companion, which deeply afflicted me,
being at the time weak and low both in body and mind.
Yet after nature was a little relieved,
my soul craved that I might also die the death of the righteous,
and my latter end be as sweet and as happy as hers.
Yes, my dear, I well know some of her hidden conflicts,
and that her soul`'s enemy sorely and frequently assailed her.
But even then, her head was covered in the day of battle, and for a helmet,
the hope of salvation was her and my secret rejoicing.
Oh her love to the blessed cause, and to poor me, was wonderful,
surpassing all temporal enjoyment;--yes,
we were knit as Jonathan and David--and now that a final separation has taken place,
and she happily removed from "`the noise of all
archers,`" where death is swallowed up in life,
and hope in everlasting enjoyment, my soul worships in reverent thankfulness, and craves,
for myself and for you and your dear brother, that walking humbly by the same rule,
and minding the same thing,
we may approve ourselves as followers together
of the same Lord who has led captivity captive,
and given the like precious gifts, even to the rebellious.

My spirit, while my pen is in motion, salutes you.
I am truly glad to hear of your dedication to the service of the Most High,
and I wish you safely and wisely to move in faithfulness to every divine requisition,
now in the time acceptable, that when reduced, as I at present am,
(being nearly helpless and mostly confined to my chamber) you may
look back with humble confidence to the voice of blessed acquittal,
"`Let her alone, she has done what she could,`"--which is sometimes, in boundless mercy,
vouchsafed even to me.

I am now in my 74th year, and so stiff and enfeebled, that I get out but seldom,
and only to our North Meeting, with the help of an arm and my staff;
yet in the humbling dealings of my blessed Master with me,
I am provided with the comfort of my dear Bernice Allinson,
who you may remember married a precious young man about 7 years ago.
They were happy in each other.
They settled in New York, but after some years removed to this city.
He has by his death left her a widow indeed.
Finding my powers giving way,
this dear child has taken a neat house adjoining the one I live in,
and a door communicating between our chambers, she has become my care-taker.

You may`'st have heard of the sudden and peaceful end of our dear friend
Rebecca Wright (in her 75th year,) who after attending our Yearly Meeting,
got home, and in a few days we received an invitation to her burial.
She was an ornament and great example in society.
In the last month, Phebe, wife of our honourable friend James Pemberton,
departed this life.
And dear Sarah Harrison, after struggling with much bodily weakness, and heavy,
very heavy trials of various kinds, was happily removed a few weeks since.
These, with the peaceful close of dear John Pemberton`'s widow,
and the death of several young and promising plants about the same time,
together with my debility and varied exercises, have sunk me so low,
that I was not able to get to see any of them or their families; but remained,
a silent and secret mourner, in my own chamber,
where I now sit thus conversing with you.

12th. I can give you the pleasing information of
dear Susanna Horne`'s safe return from a long,
trying journey to the westward--having had, throughout, for her steady companion,
Mary Allinson of Burlington, a friend in the station of an Elder,
and to whom S. Horne seems as nearly united as I was to my beloved Christiana Hustler.
Susanna and Mary, with Thomas Scattergood (with whom they quarter,) Samuel Emlen, etc.,
spent last sixth day with me in my chamber,
and this day started on a visit to Bucks Quarter.
They look bravely, but I told S. Horne that her work not being done here,
I don`'t yet see any opening for her return to her native land.
Her services and example are truly satisfactory to us all,
I hear that dear Stephen Grellet is in like manner beloved amongst you;
and by a letter to his valuable wife he was at and in the neighbourhood of Undercliffe;
so you must have been gratified, and I also am in hearing of it,
for he is a brother beloved by me for the Work`'s sake.
If you have opportunity, present him with the expression of my love.

To dear Martha Routh and to dear A. Alexander I
wish you to give the perusal of this letter,
which must serve them as a proof of my sincere and undiminished love,
and that I retain my wish to hear often from them; for indeed,
nothing but ability of sight is lacking, to them and yourself, often.
To will is present, but how to perform I find not.

14th. I was so dim when I wrote the above,
that I almost despaired ever finishing this letter;
but I am not easy without making another attempt.
If I fail finally, I hope my dear B. will send it to you.
Dear Samuel Smith sends his love.
He, by a late division of our large Monthly Meeting,
is likely to become a member of the Monthly Meeting of Philadelphia,
which is painful to us both,
as we have always been fellow helpers together in the Meeting
for the Northern district for upwards of three score years,
and are still in the unbroken bonds of the Gospel.
And though all the three meetings have been much stripped of valuable members,
the multitude that do attend,
(and a large number of other professors) especially on first day mornings,
have induced Friends of the Middle Meeting to build another house to the westward,
which is nearly finished.
And materials are collecting for one to the northward.
So that like London, we shall abound in houses, whether they are all filled or not.

Although it is a low time in general, yet,
in acknowledgment of the goodness and mercy of the blessed Shepherd of Israel, I may say,
that a hopeful succession of true burden bearers is coming forward,
and a living hope is raised that the standard of
Truth and Righteousness will be supported,
and the day approaching spoken of by the prophet, when many shall run to and fro,
and knowledge in divine things be increased.
So be it, says my soul.

Dear George and Sarah Dillwyn still reside at Burlington.
George is especially strong in the exercise of his gift, and as skilful a workman as ever.

20th. By a letter from S. Horne,
she expects to finish her visit in Bucks Quarter so as to be in this city next week,
when I apprehend she, with Thomas Scattergood,
will mention their prospect of a visit to the families of Pine street Monthly Meeting.
In which case they will then have visited all the families in this city,
and very acceptably, as indeed their gospel labours have been,
here and elsewhere in our land.
Our friends M. Swelt, Charity Cook, Ann Jessup, Benjamin White, Henry Hull,
William Jackson, Richard Jordan, and Mehetabel Jenkins, who have laboured amongst you,
are all living, though some are growing infirm,
and especially dear Nicholas Waln and Phebe Speakman,
who are evidently breaking down--but none more so than your sincerely attached and
aged sister in the fellowship of the Gospel of peace and salvation.

[.signed-section-signature]
Rebecca Jones

--
