== Chapter XVII.

[.chapter-subtitle--blurb]
1813--1817.

[.chapter-synopsis]
* Typhus Fever
* Prayer
* Green Street Meeting
* Attends Twelfth Street Meeting
* Is at North Meeting for the last time
* Death of Thomas Scattergood and message to Susanna Home
* Letter to Sarah Hustler
* Intimation respecting S. Home`'s arrival in England
* Warning to a Minister
* Her last letter to S. Hustler
* Bernice Allinson`'s account of Rebecca Jones`'s death
* Reflections by Enoch Lewis
* John Cox
* Passages from her Will, and Concluding Remarks

In the early part of the year 1813 she was prostrated by a typhus fever;
and although she was raised, contrary to the expectations of her friends,
from this protracted illness, she never fully recovered from the effects of it.
During the most critical stage of this fever her utterance was
almost wholly in prayer or religious testimony,
or exhortation.
A valued friend who called at the adjoining house to enquire concerning her health,
hearing her thus engaged, paused at the front door, and said in speaking of it,
that the strains were so angelic that he thought
them the prelude of approaching dissolution.
But few of her expressions have been preserved.
On one occasion she said to those who were in her apartment:--

"`Oh draw near to the mountain of the Lord, to the house of the God of Jacob.
He is good and worthy to lean upon--he is rich in mercy.`"
And afterwards, addressing herself to the Father of mercies,
she spoke at intervals as follows:

"`We are sensible of increasing weakness and debility.
Grant that your Spirit may be near!
May your invisible Power preserve your people and your children!
Oh, enlarge our hearts--our souls!
I have been much exercised in mind for several days past that your
servants and handmaidens may have no dependence but on your mercy.
Oh be pleased to be near in these times of trial.
Make their wilderness to blossom as the rose, and to flourish as your garden of Eden.
Keep the few in this place in your fear.
Bring down the lofty seals of man.
Say to the North, give up; to the South, come forth,
that judgment may be brought unto truth--for you can make a little one a great one,
and a small one a strong one.
None ever trusted in the Lord in vain.
You will never leave or forsake your people, if they do not first leave you.
Raise them, Oh you God of Power, raise them as from the very stones of the street,
to praise your great and excellent name where there will be no more sliding,
and bring them to the general assembly and church of
the first born whose names are written in Heaven.

"`All glory be to you Oh God, and the dear Son of your love, the Lamb immaculate;
not only now, but forever and forever more, Amen.`"

During the last five years of her life she was very much confined to her house,
and for three years mostly to her chamber,
which was often a scene both of interest and instruction to the many who resorted there,
as well as to those whose privilege it was daily to share her society,
and to minister to her needs:
yet during this time she was a few times out of her own house, and twice at meeting.

When the establishment of a monthly meeting in the Northern Liberties was decided upon,
and a new division of districts was also to join many of the valuable
members of the North Meeting to the one held in Arch street,
a friend came to Rebecca Jones`'s chamber,
and with tears poured out her troubled feelings on the occasion,
expressing a fear that there would be only a poor handful left,
hardly sufficient for the maintenance of a Monthly Meeting.
Rebecca Jones leaned back in her easy chair, and sat silent awhile,
with an expression of holy serenity upon her countenance, which is described as angelic.
At length she said,
that she had been recurring to the time when North Meeting was established,
and she believed that a vine was planted which would not be destroyed;
but that although the branches might die down to the ground,
the root would be kept alive, and sprout and flourish again.

She had not been able to see the propriety of the establishment of Green street meeting,
and more than once said that she felt no inclination to attend it.
Toward the Western District, however, she felt an attraction,
the house on Twelfth street having also been recently built.
A friend having a desire that she should make an effort to attend the two new meetings,
especially Green street, offered the use of her carriage.
Early the next First day morning she sent word
that she would like to go to the Western meeting.
The husband of the friend referred to, came with his carriage,
and when they had entered the vehicle, Bernice Allinson,
(her constant companion) informed him that they wished to go to the Western meeting.
He replied, "`I understand--my wife told me.`"
As he continued driving to the northward,
he made a similar reply to repeated intimations,
and at length stopped before the gate of the Green street house,
having been so impressed with the belief that this was their destination,
that he could scarcely admit a different idea when Rebecca Jones,
who had sat with her eyes closed, said, "`I`'ve nothing to do with Green street.
I wish to go to the Western meeting.`"
They arrived late,
and it was with considerable difficulty that she was got into the meeting house,
and Samuel W. Fisher stepping across the house, took her arm,
and helped to convey her to the head of the meeting.
There were then present, Sarah Matthews, supported by pillows, and Samuel Smith.
The former was never at meeting again; Samuel Smith and Rebecca Jones only once,
which was, with each, at North Meeting.
Samuel Smith spoke very sweetly, and as much at length as was usual with him.
Sarah Matthews, unable to rise from her seat,
was favoured to communicate a lively and instructive testimony; and Rebecca Jones,
(also keeping her seat--unable,
through debility to kneel,) appeared in very solemn supplication.
The next, and last lime of Rebecca Jones`'s being at meeting, was on a First day morning,
at the house on Keys`' Alley, where, upon her bended knee,
she raised in a memorable manner, the voice of praise and thanksgiving,
ending (as was not unusual with her,) with these words, "`To you,
and to the dear Son of your love, be glory and honour, now and forever more.`"
And it is worthy of note, that in her addresses to the throne of Grace,
she seemed never unmindful of the Saviour`'s gracious words:
"`Whatsoever you shall ask the Father in my name, he will give it you.
Hitherto you have asked nothing in my name; ask and you shall receive.`"
"`At that day you shall ask in my name.`"

It will be remembered that the decease of Thomas Scattergood took place in the year 1814,
after the erection, and before the opening of the Green street house,
and that there was an undue anxiety among some,
as to the meeting to which he should be attached.
The following is an extract from a letter which was written at Rebecca Jones`'s request,
to Susanna Horne, (who was Thomas Scattergood`'s child in the Truth,
and afterwards his intimate associate in the work of the Gospel) and
which being read to Rebecca Jones previous to its being sent,
received her sanction.

"`During his illness,
as our dear Rebecca Jones was ruminating upon the
apprehended departure from this earthly tabernacle,
of her beloved friend Thomas Scattergood,
the passage of Scripture came before her which speaks of Michael the Arch-angel, who,
contending with Satan, and disputing about the dead body of Moses, which had been,
through Divine interference, taken away, brought against him no railing accusation,
but said, "`The Lord rebuke you!`"
The application in her mind seemed thus.
Considerations relative to the division of North meeting
having somewhat agitated the minds of many friends,
and Thomas Scattergood being situated near the probable
line between it and the newly established meeting,
there was considerable anxiety as to the meeting to which he should belong:
and that therefore, his Master was about to remove the cause of disputation, by assuming,
in a manner awfully striking, the right of decision Himself:
whereby rebuke was administered by the all-wise Controller of events,
to that spirit which actuates to an undue reliance on human aid.
She also mentioned that since his close took place, this passage had been,
in reference to the deceased,
illustrated in her view in a manner in which it had not been before:
'`They that be wise shall shine as the brightness of the firmament,
and they that turn many to righteousness,
as the stars forever and ever.`' The application of which was,
that as the brightness of the firmament, though always perceptible,
is at some times more luminous than at others,
so his company while in the body had been to her
always more or less cheering and encouraging.
The fixed stars being placed farther from our sight,
yet shining with a continual and undiminished brightness,
conveyed to her a lively representation of that unalterable and
perfect state of happiness in which he was now immutably placed.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Sarah Hustler.

[.signed-section-context-open]
Philadelphia, 3rd mo. 8th, 1813.

[.salutation]
My Dearly Beloved Sarah,

Through the tender mercy of "`the
Lord who heals,`" I am continued in this probationary state,
and have received your kind long letter by our dear friend Stephen Grellet, who has,
in good health and in peace of mind, arrived among us,
and has made me several visits in my chamber, with his amiable wife.
He has given me a particular account of my friends,
and of you in a precious feeling manner, which has been like marrow to my bones,
wherefore I thought I would tell you so.
Bernice also (who with her three dear lambs are a great comfort to me
in my old age) begging me to write to you once more,
thinking you will excuse all defects.

Oh how I have loved your dear parents and my
ever dear friends John and Christiana Hustler,
who, being delivered from pain etc., on earth, are joyfully united,
in the realms of bliss, forever and ever;
and have left two children to represent them here, in person and pursuits,
I trust to the comfort of many who have their parents in fresh remembrance.
Be encouraged,
my dear Sally--you have put your hand to the plow,--don`'t
look back--but look unto Him who has called you,
and will be with you, even unto the end of the world.
Your dear brother will be a co-worker with you, and will partake of the reward.
Tell him so with my love, which I desire also to your sister Jane.

I suppose you have heard how we are reduced in number since I last wrote you.
Since then dear N. Waln has gone.
Our North Meeting has divided--two new houses are built.
Dear S. Smith remains a living monument of divine love and life.
Salute dear Martha Routh, A. Alexander, William Tuke,
J+++.+++ and E. Hoyland and my other acquaintances as they fall in your way.
Give my love to E. Coggeshall, and tell her to do all that her hand finds to do.
My love to dear S. Hornt--her friends at Burlington are well.
You can hardly tell how we miss our dear Thomas Scattergood--but all is well with him.

I must be short.
You know I used to write a long letter, but now let it suffice to say,
I am patiently waiting till my change comes, and this may be my last.
In best love I remain your very affectionate and nearly united friend,

[.signed-section-signature]
Rebecca Jones

--

While confined by her infirmities to the house,
it was her practice to have the Bible placed upon a table
beside her during the absence of the family at meeting.
It frequently however remained un-opened,
her mind being gathered with the assembled Church,
reverently waiting upon the Father of spirits.

In the house which she occupied for the last two years of her life,
her window was opposite the women`'s gate of the North Meeting--thus
when the doors were open she could from her seat in her chamber
recognize many individuals in meeting.
Her faithful and beloved Leonard Snowdon,
was in the regular practice of visiting her on first day evenings,
and giving her an account, so far as he had been able to gather it,
of the different meetings on that day and during the week;
she having this evidence that she had passed from death unto life,
that her love to the brethren, though she could no longer mingle in their assemblies,
was strong,--as was also her interest in all that
concerned the cause of the ever blessed Truth.
He being with her upon a first day evening after
the departure for England of Susanna Horne,^
footnote:[No transatlantic friend, probably,
within the memory of those now upon the stage,
has travelled in this land with more general acceptance than
this dear friend,--(now Susanna Bigg.) Her ministry was sound,
practical and persuasive, and her private walk very exemplary.
She arrived in 1810, and remained on our Continent nearly three years, during which time,
accompanied by Mary Allinson, she visited most of the meetings,
and very many of the families of Friends in America.
She returned to England in 1813,
leaving a sweet memorial in the hearts of her fellow disciples.
A large proportion of those who knew and appreciated her,
have entered before her into the fruition of
that rest which remains for the people of God.]
on her return from a religious visit to this country, she observed to Leonard,
"`In my silent meditation this morning I had a view of
Susanna Horne in a meeting in her own land.`"
A remarkable coincidence may be mentioned here, not merely from its interesting nature,
but as showing the union of spirit which is sometimes permitted to disciples,
and as illustrative and confirmatory of the doctrine of the immediate
communication of the Divine Spirit with His creatures,
of which her life had afforded many illustrations.
George Dillwyn, in a meeting at Burlington the same morning, after a lively testimony,
and near the close of the meeting, again rose,
and said that he "`felt more than a liberty to inform his friends that he believed
our beloved friend Susanna Horne was now safely landed on her native shore.`"
The constant companion of Susanna Horne in her visits
in this land was present at the latter meeting,
and next morning letters between her and Bernice Allinson passed each other on the river,
giving accounts of the two remarkable incidents.
When the letter was read to George Dillwyn,
which gave information of the view afforded to Rebecca Jones he said,
"`It is not the first time that our thoughts have flowed in the same channel.`"

S+++.+++ Horne arrived in Liverpool, 8th Mo. 5th, 1813,
after an unusually short passage.--The first confirmation of the impressions above
mentioned was from a young man immediately on his arrival from that port.
Though not in the practice of attending the meetings of Friends,
he had in this land listened with interest to the ministry of
S+++.+++ H. He had been to England and being about to return,
having been detained from his voyage by contrary winds, he went to Liverpool,
where seeing some friends going to meeting he followed them and there he saw
and heard S. H. On his reaching Philadelphia he gave the information of her
arrival before the reception of letters which came in the same ship.

It was near this time that she received a visit from a minister whose
subsequent declension gave cause of mourning to his friends.
He was on his feet to depart when she began to address him.
He resumed his seat, and listened to a heart tendering communication,
in the course of which she laid before him, with striking distinctness,
two prospects of his future career and condition,
dependent upon his watchful faithfulness or the reverse.
And so awful was the picture which she presented,
of the consequences which would attend him if disobedient to the Divine Monitor,
that he wept audibly, and a friend who was present,
and who retains a vivid remembrance of the scene, was also greatly affected.
A regard to individual character forbids us to raise the veil
from the affecting realization of her worst forebodings.

[.embedded-content-document.letter]
--

[.letter-heading]
Rebecca Jones To Sarah Hustler.

[.signed-section-context-open]
Philadelphia 4th mo. 20th, 1816.

[.salutation]
My dear friend S. Hustler,

I ought to have made a more quick answer
to your very acceptable lines by our dear Stephen Grellet,
but I can hardly persuade myself that you can read such a scrawl, and I can do no better.
You may know by this that I love you for your own and your dear Mother`'s sake,
wishing you to know that I am still in the body,
a miracle to myself and a wonder to my friends.
I am quite lame, from many falls and hurts on my limbs,
and though it is our Yearly Meeting I am sitting alone in my room, and have you,
in fresh love brought into view.
And, praying for help for myself,
I have felt your and dear John`'s best welfare interwoven in my solicitude.
May that God who gave your mother as an helpmeet to me in your land,
be near to me in this, and crown my poor soul at last with peace, is all my desire.

Our Yearly Meeting has been thus far favoured,
and will conclude tomorrow;--but E. Coggeshall did not get here.
I hear she is peacefully at home.
Our S. Grellet is also at home, preparing to go on another errand,
and will I hope be mercifully preserved, even among the West India Islands.
He is a tender brother of mine, and has a precious wife.
You will have heard of the short illness and blessed close of dear Thomas Scattergood.
He was near to my best life, and is only gone a little before poor me,
and rests now from his arduous labours.
A stripping day has come over us in this land,
and many lively Ministers have gone from works to rewards;
so that part of the vineyard is solitary.
But a lively hope is raised,
that a succession is preparing to receive the garment of Elijah,
and bear tidings of good things, as in days of old.
Great and marvellous are his works, can my soul say, just and true are all his ways.
For even my present bodily affliction, will, I trust, work for my further refinement,
and the joy of the Lord be my strength in the final giving up of my accounts.

Let Martha Routh and A. Alexander know that I love them in the covenant of love and life,
and long to hear from them.

Our dear Samuel Smith is weak, and gets very little out,
but is evidently owned as a sheep of the favoured fold, who is waiting for the summons,
"`Come you blessed of my Father.`"
Don`'t forget your old friend--and let me hear from you once more.
I am nearly blind, near seventy seven years of age,
and your sincere friend and sister in the bonds of the gospel,

[.signed-section-signature]
Rebecca Jones

--

As increasing and certain tokens were given of the approaching dissolution of "`the
earthly house,`"--the union between "`Naomi and Ruth`" was beautiful to behold.
In one sense indeed,
their relative position was changed--for the child had become the tender and
watchful guardian of one who had been "`a succourer of many and of her also.`"--The
compiler well remembers on an occasion of his Mother`'s illness,
the distress and anxiety of Rebecca Jones, as she queried what would become of her,
should her B. be taken first--to which the invalid replied,
that she had "`faith to believe that it would not be permitted.`"
He also freshly remembers being summoned by Rebecca
Jones to partake with her of her last meal,
and the sweetness of her countenance when

[verse]
____
"`We knew that the hour was drawing nigh
To fulfil every fearful token--
When the silver cord should loosen its tie,
And the golden bowl be broken.`"
____

The following brief notes relative to her last illness and closing scene,
are from the pen of her beloved Bernice Allinson and were
written shortly after the solemn event which they record.

"`3rd mo.
30th, 1817.
After the morning meeting, Mary Smith,
(widow of Samuel) called to see my dear Rebecca Jones,
who seemed better than for a long time before.
They had long been united in the bonds of the Gospel,
and were on this occasion remarkably engaged in
encouraging each other to hold out a little longer;
Rebecca Jones saying,
"`If we were but permitted to join his purified spirit (alluding to
dear S. Smith) it will be enough.`"
In the afternoon several others called;--she was very pleasant, and enjoyed their company.
One friend remarked, that she had not seen her so much like herself for several years.

That night she was taken with a complaint in her bowels, attended with great pain.
She had a very restless night,
but in the morning slept until near eleven o`'clock when she took her breakfast, and,
being dressed for the last time,
seemed pretty comfortable till about three o`'clock P. M. when the complaint returned.
In less than two hours her strength was so gone that
she could not stand when raised upon her feet.
My sister and myself both stayed in her room that night.
After being up many times, and enduring great pain,
she was seized with a severe spasm which threatened immediate suffocation,
from which she was relieved by throwing from her stomach a considerable quantity of bile.
Her voice which had for a long time been quite impaired by repeated paralytic affections,
was for several hours quite gone.
Towards day she fell into a gentle sleep and awoke refreshed,
her voice being nearly as intelligible as for some months past.
About eleven o`'clock she desired to get up and sit in her easy chair, saying,
"`It is meeting day,
and it is likely some friends will call in.`"--The
restlessness attendant on her disease had so increased,
that one of us was constantly employed in changing her position.

The mental powers in some degree yielded to the
infirmities of the body which for years had been great;
yet on religious subjects her faculties had always continued clear and bright,
so that her counsel on important occasions was still sought and valued.

About the eighth of the 4th month, the disease assumed a new aspect.
The fore part of each night was most trying,
she being favoured to sleep a little in the morning.
Early in the night of the 9th,
she seemed in as great anguish of body and mind as could be endured,
which continued to be the case for several hours.
My mind had often been permitted to partake of her mingled cup,--but
the wormwood and the gall seemed all that was now offered.
My spirit having, during this night of suffering, been enabled more than ever before,
to enter into feeling with her tried tossed mind,--was permitted after the dear
sufferer had experienced some refreshment from sleep toward the morning of the 10th,
to partake with her in the enjoyment of Divine good.
She spoke of the solemn prospect of the final change being near,
and in a most impressive manner, said, "`Not by works of righteousness which I have done,
but according to His Mercy he saves us, by the washings of regeneration,
and the renewing of the Holy Ghost!
After having done all, we are but unprofitable servants!`"
After this she was not able to express much.
Repeated paralytic affections occasioned a difficulty of utterance and of swallowing.
During the last few hours, she made many efforts to speak but was unable.
It was extremely trying to behold one,
on whose tongue so long had dwelt the law of kindness, now, on the confines of Time,
vainly endeavouring to communicate the feelings that pervaded her mind,
which appeared to be unclouded.
About 11 o`'clock Elizabeth Foulke came to see her,
and after sitting awhile in silence said that her mind had
that morning been brought into deep sympathy with her,
and that now she was enabled to rejoice in the full assurance
that the tossed mind was nearing the port of eternal rest;
that death had no sting and the grave no victory.
Dear Rebecca Jones raised her clasped hands but could not articulate.
Elizabeth Foulke descended the stairs, and was about departing,
when the nurse announced a visible change in her countenance.
On my bending over her, she put her arms around me.
I gently raised her--she made another great but unavailing effort to speak,--
drew several hard breaths--then breathed gently for a few minutes--and,
in the last effort of Nature, closed her mouth and eyes,
and a sweet smile played over her noble countenance which was indeed beautiful in death.

--The immediate language of my mind was,
"`Well done good and faithful servant--enter you into the joy of your Lord.`"
She was interred in Friends`' ground on Mulberry street,
on the morning of the Select Yearly Meeting.
Mary Nafftel, (from England) then on a religious visit to friends in this country,
attended the funeral and bore a lively testimony to her
devoted labours both in this land and in Great Britain,
in promoting the spread of the everlasting gospel--saying that on hearing of
her departure the language that saluted her mind was "`Well done good and
faithful servant--enter you into the joy of your Lord!`"
George Dillwyn was also one of those who spoke at the funeral.
The Select members went from the grave into the meeting house,
with minds solemnized in the recollection that one who had for more
than fifty years stood as one of the Pillars in the Church militant,
was now removed to the church triumphant in Heaven.
There had not been any left, since the decease a few years previous of James Pemberton,
who was a member of that meeting at the time when she was introduced.`"

[.offset]
+++[+++In introducing the following remarks by Enoch Lewis,
the Compiler takes occasion to acknowledge his grateful sense
of the value of the notes (by which this volume is enriched,)
which have been furnished by him as Editor of Friends`' Review.
The notes by E. L. are indicated by his editorial signature.]

Although Rebecca Jones had passed the period which was
formerly considered as the utmost limit of human life,
yet the removal of such a pillar of the church, even at this mature age,
was naturally and justly productive of solemn reflections.
What changes had occurred, both in the world at large and in our religious society,
during the time embraced by her memory!
When she reached the period of womanhood, a monarch, who was a native of Germany,
held the dominion of Great Britain and a considerable portion of North America.
She had heard the appalling rumours of Indian massacre on the
frontiers of the peaceful province in which she was born,
and there witnessed the bitter fruits of the injustice
dispensed by her countrymen to the natives of the forest.
She had seen the American people rise up in opposition to the metropolitan power,
and the city of her birth occupied by a hostile force.
Thus the land selected by the benevolent Penn, as the seat of a holy experiment,
where a government might be established on christian principles,
as a model to succeeding generations, was rendered, by the vices and follies of man,
a scene of sanguinary conflicts.
She had heard from beyond the Atlantic, the rumours of wars and commotions;
the throne of the Capets overturned;
the nominal master of thirty millions of people led to the block;
a military democracy erected on the ruins of the monarchy;
that democracy itself subverted and an imperial government erected in its stead;
the European continent, throughout its length and breadth,
inundated with contending armies;
and the man before whom the greatest potentate had trembled,
consigned as a captive to a rocky island in the southern Atlantic.
These events might well suggest the reflection how
transient and evanescent is the greatness of a world,
which thus passes away.
How delusive the hope of those who make the flesh their confidence,
and trust their prospect of happiness upon any thing which the world can afford.

In her own religious society, numerous and important changes had arisen.
Those with whom she engaged in religious service in the morning of her day,
and with whom she often took sweet counsel, were nearly all numbered with the dead.
Of her first companions in the meeting of Ministers and Elders, not one was left.
What solemnly melancholy,
yet hardly painful considerations must she often have experienced,
when near the close of her course, she reviewed the exercises,
and the companions of her early days.
As the faithful and valuable labourers of that time to
whom she was accustomed to look for advice and support,
in her varied trials, rose up in vivid remembrance, the recollection was still at hand,
that their voices would be heard no more;
yet no doubt these recollections were often attended by the consoling assurance,
that they were resting from their labours, and that their works would still follow them.
