== Conclusion

The consideration of her latter end, having been present with her through life,
she was careful to keep a Will in readiness,
and her last will and testament bears date about a year before
her decease.--"`Considering`"--she says in the preamble,
"`the uncertainty of Time, and that many are suddenly called from here,
I do think it commendable and necessary not only to endeavour with the
assistance of Divine Grace to be inwardly prepared for so awful a change,
but also to settle my outward effects, with which the Lord has been pleased to bless me,
as I would they should be.`"

In this document, after leaving various legacies,
among which is one to her friends Ann Warder and Anne Stewardson,
in trust for poor friends of North Meeting,
she constitutes Bernice Allinson her sole residuary legatee,
and she concludes in these words:

[.embedded-content-document.letter]
--

"`In confirmation hereof after acknowledging with gratitude and in
humility of soul the tender and infinite mercy of the Lord Almighty,
which has in numberless instances been signally vouchsafed and
displayed for my redemption from sin and the wages due thereunto,
and his preservations and deliverances by sea and by land; hoping,
through the merits of my blessed Saviour and Redeemer Jesus Christ,
to be admitted into his holy kingdom when I shall put off this earthly tabernacle;
and in peace and unity with his Church under every name,

[.signed-section-signature]
Rebecca Jones.

[.signed-section-context-close]
Signed sealed etc., the 9th of the 3rd month 1816.`"

--

It would be unjust in her Biographer to omit
transcribing the following passage from the said will.

[.embedded-content-document.letter]
--

"`I give to George Dillwyn, Samuel Emlen, and John Cox of Burlington,
and Leonard Snowdon and Thomas Stewardson of this city, in trust,
all my books and papers of every kind to be carefully inspected,
(and if there be any thing therein that may be of disadvantage to any person alive
or deceased that they may be destroyed;) together with all my Diaries and Journals,
etc.,
and it is my further request that no written testimony or
account may be issued concerning me,--I having often been
pained under the reading of such marks of distinction.`"

--

A portion of the manuscripts thus entrusted to the wise and excellent men above named,
had, previous to her decease,
been presented by Rebecca Jones to Bernice Allinson without restriction.
The memoir of her convincement given at the commencement of this volume,
was retained in their possession, until John Cox, being the sole survivor,^
footnote:[Language would fail the Compiler in attempting to portray the character,
or express the worth of this true Israelite,
illustrious Friend and patriarchal christian Gentleman.
The following extract from a letter,
published as an obituary shortly after his removal from the militant state,
will not be thought, by any one, to be over-wrought.
Those who knew the Sage of Oxmead will scarcely expect ever to "`look
upon his like again,`"--or to meet with any memorial of his worth
which shall equal their own exalted but just estimate.
He died at his delightful abode Oxmead, Burlington, N. J. 4th Mo. 5th, 1847,
in the 94th year of his age.
W+++.+++ J. A.
{footnote-paragraph-split}
"`By the Intelligencer of the 10th of this month,
I learn that my dear friend John Cox is released from
the cares and sufferings of this probationary state.
It is now more than fifty years since I was introduced into his society;
since which I have often been in his company,
both in the social circle and in the house of worship; and I can truly say,
that I never had the pleasure of knowing a man who combined in his character,
more perfectly, the Gentleman and the Christian.
In social interaction with his friends he was affable and
cheerful--sometimes even sprightly--yet always dignified;
never for a moment forgetting the importance of the station to
which he was called as an ambassador for Christ,
nor indulging in any thing inconsistent with that station.
His ministry was exceedingly interesting; his language clear, chaste, and elegant,
but without the least mark of affectation.
In prayer he was very weighty,
appearing to be deeply impressed with the awfulness of public supplication,
in which he not only manifested a deep reverence for the Divine Majesty,
but made his hearers participate in the same feeling.
I shall never forget my sense of his ministry; even, when I was a youth,
how my mind was absorbed in deep and solemn attention,
and made to feel the Divine power and authority, with which at such times he was clothed.
It may truly be said of his ministry,
that it was '`in the demonstration of the Spirit and of power.`' He
was gathered to his everlasting rest in a full age,
like as a shock of corn comes in his season,`' and his memory
will long remain as a sweet odour with his survivors.`"]
delivered it to Bernice Allinson declaring it to be her property.

It will be seen that it found its way to the
press without the consent of Bernice Allinson,
notwithstanding the caution prefixed--a transcript having been
taken by some one to whom it had been loaned.

It will be a question with some, how far the publication of her biography,
in violation of her request, is to be justified.--With others, the query will arise,
how far it was within her province to withhold, from those who personally knew her not,
and from posterity, the lustre of her example.
It is not to be doubted that her humility (which was the means of her
preservation) inspired this request--but let it be remembered that although
she had "`often been pained under the reading of such marks of distinction,`"
when she felt that the creature was thereby unduly exalted,--yet none could
place a higher value than she did upon memorials of the blessed dead,
who had died in the Lord.
Witness her introduction to the Womens`' Yearly Meeting,
of the memorials issued in England respecting Sarah R. Grubb;
and abundant confirmation is before us as we write,
of the pains which she took to collect and to preserve productions of the kind.
Having surrendered herself, body, soul and spirit,
that she might do the work of an evangelist and win souls to Christ,
her modest shrinking from publicity, and from human applause,
however binding it might be felt to be, by her executors and the trustees of her papers,
could not be expected forever to operate upon those who might successively
become possessed of them;--and the question appeared to be,
whether a compilation should be made by those whose
knowledge and interest are of a personal character,
and who have an ownership in her memory,
or whether the work should be left for a future collector of materials,
to whom much that has now been gathered must of necessity be inaccessible, and by whom,
probably other portions, of merely private interest, might have been inserted.

In short,--she was, as we doubt not, influenced by a sense of duty,
to commit to writing much that is worthy to be preserved.
With all her sensitiveness on this subject,
(although she has been known to take them in her hands for the
purpose,) she had not been permitted to burn these papers--
being submitted to some of the wisest men in the Society,
they did not venture to destroy them--preserved (though widely scattered,
and without a view to their compilation) for more than thirty years,
they have been placed by their proper owner in the hands of the present Compiler.
It has been believed to be right to arrange them in a
permanent form for the satisfaction and benefit of others;
and if this judgment be erroneous, it has been an honest error,
and it is sincerely desired that it may be over-ruled for good.
